#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012, 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

cat /etc/motd

sudo service tor restart

sudo service tor status

true $?

true "Feel free to close this window."

sleep 86400

