#!/bin/sh

#set -x
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log
