#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

WHONIX_BUILD_PARSED="1"
VMNAME="internalrun"

source pre
source variables

prepare-build-machine() {
   trap "error_handler_general" ERR INT TERM

   ## If whonix_build is run with --fast1 switch.
   if [ "$WHONIX_BUILD_FAST1" = "1" ]; then
      echo "${bold}${cyan}INFO: run with --fast1 switch, skipping $0. ${reset}"
      exit 0
   fi

   ## Check if user "$USERNAME" already exist.
   ret="0"
   id "$USERNAME" || { ret="$?" ; true; };
   if [ ! "$ret" = 0 ]; then
      true 'INFO: Creating user "$USERNAME" with password "changeme", because some things have to be run as "$USERNAME".'
      ## setting password of user "user" to changeme
      ##
      ## How this password was created:
      ## sudo apt-get install whois
      ## mkpasswd
      ## changeme
      ## Resulted in: aTayYxVyw5kDo
      useradd --password aTayYxVyw5kDo --user-group --create-home --shell /bin/bash "$USERNAME"
   else
      true "${cyan}INFO: Not creating user \"$USERNAME\" with password \"changeme\", because it already exists.${reset}"
   fi
   
   ## Add user to sudo group.
   addgroup "$USERNAME" sudo   

   ## Fix permissions, just in case.
   ## Not sure if it's still useful for anything.
   #chown --recursive "$USERNAME":"$USERNAME" /home/"$USERNAME"   

   if [ ! "$WHONIX_BUILD_UPGRADE_BUILD_MACHINE" = "0" ]; then
      ## Always keep old configuration file. Do not prompt to install new config files.
      echo '
         Dpkg::Options {
            "--force-confold";
         }
      ' > /etc/apt/apt.conf.d/90whonix-build-confold
   fi
   
   ## Using an apt cache to speed up downloading
   ## If you want to build multiple times (for debugging etc.),
   ## it makes sense to install a local apt proxy on your build machine.
   ## That safes download time and traffic.
   ##
   ## Minor: If you build Whonix on Whonix, apt-cacher-ng will go through Tor's TransPort.
   ##
   ## Thanks to source:
   ##    https://linuxexpresso.wordpress.com/2011/02/13/howto-apt-cacher-ng-on-ubuntu/
   ## It would be possible to download without an apt-cacher...
   ## But why? If you do not want to use it, comment out the following line and
   ## change the mirror settings in grml configuration file.
   
   ## Check if apt-cacher-ng is installed.
   dpkg --status apt-cacher-ng 1>/dev/null 2>/dev/null || { ret="$?" ; true; };
   
   if [ ! "$ret" = "0" ]; then
      ## Update package lists and install apt-cacher-ng.
      apt-get update 
      apt-get install --yes apt-cacher-ng
   fi

   ## Restart apt-cacher-ng.
   ## Should not be required, but it was for me.
   service apt-cacher-ng restart
   
   ## Check status of apt-cacher-ng.
   service apt-cacher-ng status

   ## Enable apt-cacher-ng proxy.
   export http_proxy="http://127.0.0.1:3142"

   if [ ! "$WHONIX_BUILD_UPGRADE_BUILD_MACHINE" = "0" ]; then
      ## Update package lists and upgrade.
      apt-get update
      apt-get --yes dist-upgrade
   fi
   
   ## Check if config-package-dev with debhelper support is installed.
   ## (Build Dependency for Whonix Build Script for creating .deb packages.)
   if [ ! -d /usr/share/doc/config-package-dev/examples/debhelper/ ]; then   
      ## Temporarily adding debian testing (jessi) repository, because we need config-package-dev with debhelper support,
      ## which is unfortunately only available since debian jessi.
      local TEMP=/etc/apt/sources.list.d/whonixtestingtemp.list
      echo "deb http://ftp.us.debian.org/debian testing main" > "$TEMP"

      ## Update package lists and install config-package-dev from debian testing (jessi).
      apt-get update \
                   -o Dir::Etc::sourcelist="$TEMP" \
                   -o Dir::Etc::sourceparts="-" \
                   -o APT::Get::List-Cleanup="0"

      apt-get -t testing install config-package-dev
   
      ## Removing temporary debian testing (jessi) repository.
      rm --force "$TEMP"
   
      ## Update package lists again to get ride of debian testing (jessi) repository.
      apt-get update \
         --no-download \
         --list-cleanup
   fi

   ###############################################   
   ## Build Dependencies for Whonix Build Script #
   ###############################################
   ## - required for sudo -u user
   ##      sudo
   ## - required for creating man pages
   ##      ruby-ronn
   ## - required for build step "verify files"
   ##      diffutils
   ## - required for creating .deb packages
   ##      debhelper
   ## - required for debug-steps/copy-into-img
   ##      rsync
   ## - required for some dialog based upstream (Debian) postinst scripts
   ##      dialog
   ## - faster creation of local OpenPGP APT repository signing key
   ##   and better entropy during build
   ##      haveged
   ## - required for creating .deb packages, debchange (dch)
   ##      devscripts
   ## - required for creating an upstream tarball (git archive) and for
   ##   creating a version number (git describe)
   ##      git
   ## - required for creating (local) APT repository
   ##      reprepro
   ## - required to silence dpkg-gencontrol:
   ##   warning: File::FcntlLock not available; using flock which is not NFS-safe
   ##   http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=677865
   ##       libfile-fcntllock-perl   
   apt-get install --yes \
      sudo \
      ruby-ronn \
      diffutils \
      debhelper \
      rsync \
      dialog \
      haveged \
      devscripts \
      git \
      reprepro \
      libfile-fcntllock-perl
  
   if [ "$BARE_METAL" = "1" ]; then
      ###########################################
      ## Build Dependency for Bare Metal Builds #
      ###########################################
      true
   else
      ##################################################################
      ## Build Dependencies for creating Virtual Machine Images (.img) #
      ##################################################################
      ## - for grml-debootstrap
      ##      grml-debootstrap kpartx mksh parted qemu-utils
      ## - for creating Virtual Box VM images
      ##      virtualbox   
      apt-get install --yes \
         qemu-utils \
         grml-debootstrap \
         parted \
         kpartx \
         mksh
         
      #######################################################################
      ## Build Dependencies for creating Virtual Box Images (.vdi and .ova) #
      #######################################################################         
      apt-get install --yes \
         virtualbox
   fi

   ##Should there ever be a problem with apt-cacher-ng (package verification failure) (rare cases), use this.
   #sudo apt-get update
   #sudo apt-get autoremove
   #sudo apt-get dist-upgrade
   #sudo apt-get clean
   #sudo apt-get autoclean
   
   ## Disable apt-cacher-ng proxy.
   export unset http_proxy
   
   rm --force /etc/apt/apt.conf.d/90whonix-build-confold
} 

true "${bold}INFO: Currently running script: $0${reset}"
prepare-build-machine

