#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

## TODO
#VMNAME="internalrun"

source pre
source colors
source variables

cd "$MYDIR"
cd ..

cowbuilder_setup() {
   if cowbuilder_setup_do ; then
      true "$FUNCNAME: success"
   else
      true "$FUNCNAME: try again"
      cowbuilder_setup_do
   fi
}

cowbuilder_setup_do() {
   true "${bold}${green}INFO${reset}: Setting up cowbuilder..."

   whonix_build_sources_list_primary_contents="$(cat "$whonix_build_sources_list_primary")"
   export whonix_build_sources_list_primary_contents

   if [ "$whonix_build_unsafe_io" = "true" ]; then
      eatmydata_maybe_install="eatmydata"
   fi

   if ! test -f /etc/hostname ; then
      ## mmdebstrap requires /etc/hostname to exist.
      touch /etc/hostname
   fi

   if [ "$whonix_build_unsafe_io" = "true" ]; then
      if mount | grep /var/cache/pbuilder | grep tmpfs ; then
         true "INFO: /var/cache/pbuilder already tmpfs."
      else
         mount -t tmpfs -o size=2G none /var/cache/pbuilder
      fi
   fi

   ## Debugging.
   cat "$whonix_build_pbuilder_config_file"

   for whonix_build_multiarch_package_item in $make_cross_build_platform_list ; do
      export whonix_build_multiarch_package_item

      ## TODO: change that folder
      cow_folder="/var/cache/pbuilder/cow.cow_${whonix_build_multiarch_package_item}"
      base_folder="/var/cache/pbuilder/base.cow_${whonix_build_multiarch_package_item}"

      if [ -d "$base_folder" ]; then
         "$WHONIX_SOURCE_HELP_STEPS_FOLDER/umount_kill.sh" "$base_folder/"
         rm --recursive --force "$base_folder"
      fi

      local cowbuilder_exit_code
      cowbuilder_exit_code=0

      ## '--mirror "$whonix_build_apt_sources_mirror"' should be only cosmetic,
      ## because of pbuilder-debootstrap-command-filter and hooks.
      ##
      ## Duplicate --extrapackages to prevent removal by pbuilder.
      $COWBUILDER_PREFIX \
      SOURCE_DATE_EPOCH="$SOURCE_DATE_EPOCH" \
         cowbuilder \
            --host-arch "$host_architecture" \
            --architecture "$whonix_build_multiarch_package_item" \
            --configfile "$whonix_build_pbuilder_config_file" \
            --create \
            --basepath "$base_folder" \
            --buildplace "$cow_folder" \
            --distribution "$whonix_build_apt_stable_release" \
            --mirror "$whonix_build_apt_sources_mirror" \
            --debootstrap "$WHONIX_SOURCE_HELP_STEPS_FOLDER/pbuilder-debootstrap-command-filter" \
            --hookdir "$WHONIX_SOURCE_HELP_STEPS_FOLDER/pbuilder-hooks" \
            --extrapackages "sudo devscripts debhelper strip-nondeterminism fakeroot apt-transport-tor python eatmydata aptitude cowdancer" \
            || { cowbuilder_exit_code="$?" ; true; };

      if [ -d "$base_folder" ]; then
         "$WHONIX_SOURCE_HELP_STEPS_FOLDER/umount_kill.sh" "$base_folder/"
      fi

      if [ ! "$cowbuilder_exit_code" = "0" ]; then
         return "$cowbuilder_exit_code"
      fi

      ## help-steps/pbuilder-hooks/G10sources_list_restore.bsh should have restored it already.
      ## `pbuilder` component `/usr/lib/pbuilder/pbuilder-createbuildenv`
      ## unfortunately runs function `installaptlines` after `${DEBOOTSTRAP}`,
      ## which uses a different sources list. This pbuilder hook script restores
      ## Whonix build APT sources list.
      true "Sanity test. Security critical. Comparing Whonix build sources list with chroot sources list."
      diff "$whonix_build_sources_list_primary" "$base_folder/etc/apt/sources.list"

      cp "$whonix_build_sources_list_primary" "$base_folder/etc/apt/sources.list"
      mkdir -p "$base_folder/$(dirname $apt_get_update_wrapper_bin_path_full)"
      cp "$apt_get_update_wrapper_source_path_full" "$base_folder/$apt_get_update_wrapper_bin_path_full"
      cp "$apt_get_update_sanity_test__source_path_full" "$base_folder/$apt_get_update_sanity_test_bin_path_full"
      mkdir -p "$base_folder/home/$user_name"
      cp "$whonix_build_pbuilder_config_file" "$base_folder/home/$user_name/pbuilder_config_file"

      mkdir -p "$base_folder/home/$user_name"
      if [ "$base_folder/home/$user_name/genmkfile" = "/home/$user_name/genmkfile" ]; then
         error "Bug! base_folder variable is probably empty!"
      else
         rm -r -f "$base_folder/home/$user_name/genmkfile"
      fi
      cp -r "$WHONIX_SOURCE_FOLDER/packages/genmkfile" "$base_folder/home/$user_name/genmkfile"
      chown --recursive $user_name:$user_name "$base_folder/home/$user_name"

      cowbuilder_exit_code=0
      $COWBUILDER_PREFIX \
      SOURCE_DATE_EPOCH="$SOURCE_DATE_EPOCH" \
         cowbuilder \
            --host-arch "$host_architecture" \
            --architecture "$whonix_build_multiarch_package_item" \
            --configfile "$whonix_build_pbuilder_config_file" \
            --execute "$whonix_build_pbuilder_chroot_script" \
            --basepath "$base_folder" \
            --buildplace "$cow_folder" \
            --save-after-login \
            || { cowbuilder_exit_code="$?" ; true; };

      if [ -d "$base_folder" ]; then
         "$WHONIX_SOURCE_HELP_STEPS_FOLDER/umount_kill.sh" "$base_folder/"
      fi

      if [ ! "$cowbuilder_exit_code" = "0" ]; then
         return "$cowbuilder_exit_code"
      fi
   done

   true "${bold}${green}INFO${reset}: cowbuilder setup done."
}

main() {
   if [ "$build_remote_derivative_pkgs" = "true" ]; then
      true "${cyan}INFO: build_remote_derivative_pkgs is set to $build_remote_derivative_pkgs, skipping cowbuilder setup.${reset}"
      return 0
   fi
   root_check "$@"
   cowbuilder_setup "$@"
}

main "$@"
