#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

root_check

export-libvirt-xml() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   sudo -u "$user_name" mkdir --parents "$WHONIX_BINARY"

   sudo -u "$user_name" cp "$libvirt_source_kvm_file" "$libvirt_target_kvm_file"
   sudo -u "$user_name" cp "$libvirt_source_qemu_newer_archs_file" "$libvirt_target_qemu_newer_archs_file"

   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      sudo -u "$user_name" cp "$libvirt_source_network_file" "$libvirt_target_network_file"
   fi
}

if [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
   true "${bold}${under}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
   export-libvirt-xml
   benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}${under}INFO: End of: $BASH_SOURCE ${1+"$@"} | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
else
   true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_QCOW2 is not set to 'true'.${reset}"
fi
