#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

export-libvirt-xml() {
   sudo $SUDO_OPTS mkdir --parents "$binary_build_folder_dist"

   sudo $SUDO_OPTS cp "$libvirt_source_kvm_file" "$libvirt_target_kvm_file"

   if [ "$dist_build_type_long" = "kicksecure" ]; then
      true
   else
      sudo $SUDO_OPTS cp "$libvirt_source_network_file_external" "$libvirt_target_network_file_external"
      sudo $SUDO_OPTS cp "$libvirt_source_network_file_internal" "$libvirt_target_network_file_internal"
   fi
}

main() {
   root_check
   if [ "$dist_build_type_long" = "whonix-host" ]; then
      ## There is no such file:
      ## /home/user/Whonix/packages/libvirt-dist/usr/share/libvirt-dist/xml/Whonix-Host.xml
      true "${green}INFO: Skipping $BASH_SOURCE, because dist_build_type_long is '$dist_build_type_long'.${reset}"
   elif [ "$dist_build_raw" = "true" ]; then
      ## Required for Linux libvirt KVM raw image builds.
      ## Interest to maintain arm64 Linux libvirt KVM raw images has been
      ## indicated by HulaHoop until qcow2 image builds are fixed.
      ## XXX: Superfluous for non-libvirt raw image builds.
      export-libvirt-xml "$@"
   elif [ "$dist_build_qcow2" = "true" ]; then
      export-libvirt-xml "$@"
   else
      true "${green}INFO: Skipping $BASH_SOURCE, because dist_build_qcow2 is not set to 'true'.${reset}"
   fi
}

main "$@"
