#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

export-libvirt-xml() {
   trap "error_handler_general" ERR

   if [ ! "$whonix_build_script_create_qcow2" = "1" ]; then
      true "${green}INFO: Skipping $BASH_SOURCE, because whonix_build_script_create_qcow2 is not set to 1.${reset}"
      return 0
   fi

   sudo -u "$user_name" mkdir --parents "$WHONIX_BINARY"

   sudo -u "$user_name" cp "$libvirt_source_kvm_file" "$libvirt_target_kvm_file"
   sudo -u "$user_name" cp "$libvirt_source_qemu_newer_archs_file" "$libvirt_target_qemu_newer_archs_file"

   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      sudo -u "$user_name" cp "$libvirt_source_network_file" "$libvirt_target_network_file"
   fi
}

if [ "$ANON_BUILD_INSTALL_TO_ROOT" = "1" ]; then
   true "${green}INFO: Skipping $BASH_SOURCE, because ANON_BUILD_INSTALL_TO_ROOT is set to 1.${reset}"
else
   true "${bold}${under}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
   export-libvirt-xml
   benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}${under}INFO: End of: $BASH_SOURCE ${1+"$@"} No error detected. (benchmark: $benchmark_took_time)${reset}"
fi
