#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

install-meta-packages() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   ## If whonix_build is run with --fast2 switch.
   if [ "$WHONIX_BUILD_FAST2" = "1" ]; then
      echo "${bold}${cyan}INFO: run with --fast2 switch, skipping $0. ${reset}"
      exit 0
   fi   
   
   if [ ! -f "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done ]; then
      error "${red}${bold}$0 ERROR: "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done does not exist. Most likely build-steps.d/1200_create-debian-packages has not been run yet.${reset}"
   fi

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-img
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/prevent-daemons-from-starting
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/chroot-img

   sync

   ## Just for testing.
   $CHROOT update-grub -v
   $CHROOT sync
   sync
   
   ## backup exiting /etc/apt/sources.list, might be useful for bare metal users
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/apt/sources.list "$CHROOT_FOLDER"/etc/apt/sources.list.backup
   
   ## We have to manually fix /etc/apt/sources.list, because the list which comes with
   ## grml-debootstrap is incomplete (does not complain debian security repository) and points to 127.0.0.1.
   cp "$WHONIX_SOURCE_FOLDER/whonix_shared/etc/apt/sources.list.whonix" "$CHROOT_FOLDER/etc/apt/sources.list"
   
   cp "$WHONIX_SOURCE_FOLDER/whonix_shared/etc/apt/preferences.d/"* "$CHROOT_FOLDER/etc/apt/preferences.d/"

   cp "$WHONIX_SOURCE_FOLDER/whonix_shared/etc/apt/apt.conf.d/"* "$CHROOT_FOLDER/etc/apt/apt.conf.d/"
   
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/create-local-temp-apt-repo

   ## Debugging.
   $CHROOT apt-key finger

   ## Enable apt-cacher-ng.
   export http_proxy="http://127.0.0.1:3142"

   sync
   
   mkdir --parents "$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER"
   cp "$WHONIX_SOURCES_LIST_BUILD_SOURCE" "$WHONIX_SOURCES_LIST_BUILD_FULL"
   
   sync

   ## Info.
   ls -la "$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER"
   cat "$WHONIX_SOURCES_LIST_TEMP_BUILD_FULL"
   cat "$WHONIX_SOURCES_LIST_BUILD_FULL"

   ## Reading apt repository containing snapshot.debian.org and repository containing Whonix's packages.
   $CHROOT apt-get update \
                   -o Dir::Etc::sourcelist="$EMPTY_DIR" \
                   -o Dir::Etc::sourceparts="$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER"

   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-packages-dependencies
   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-packages-recommended

   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-desktop
   
   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-desktop-kde

   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-kde-accessibility   
      
   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then 
      $CHROOT apt-get --yes --no-install-recommends install whonix-gateway-packages-dependencies
      $CHROOT apt-get --yes --no-install-recommends install whonix-gateway-packages-recommended
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      $CHROOT apt-get --yes --no-install-recommends install whonix-workstation-packages-dependencies
      $CHROOT apt-get --yes --no-install-recommends install whonix-workstation-packages-recommended
      
      $CHROOT apt-get --yes --no-install-recommends install whonix-workstation-default-applications
   else
      bug "${red}${bold}ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!${reset}"
   fi
   
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/remove-local-temp-apt-repo
   
   ## Forget about apt repository containing snapshot.debian.org and repository containing Whonix's packages.
   $CHROOT apt-get update \
              --no-download \
              --list-cleanup
   
   $CHROOT sync
   sync
   
   ## Disable apt-cacher-ng.
   unset http_proxy   

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-img
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting   
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-img

   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
install-meta-packages
