#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

install-meta-packages() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   ## If whonix_build is run with --fast2 switch.
   if [ "$WHONIX_BUILD_FAST2" = "1" ]; then
      echo "${bold}${cyan}INFO: run with --fast2 switch, skipping $0. ${reset}"
      exit 0
   fi   
   
   if [ ! -f "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done ]; then
      error "${red}${bold}$0 ERROR: "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done does not exist. Most likely build-steps.d/1200_create-debian-packages has not been run yet.${reset}"
   fi

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-img
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/prevent-daemons-from-starting
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/chroot-img

   sync

   ## Just for testing.
   $CHROOT update-grub -v
   $CHROOT sync
   sync
   
   ## backup exiting /etc/apt/sources.list, might be useful for bare metal users
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/apt/sources.list "$CHROOT_FOLDER"/etc/apt/sources.list.backup
   
   ## We have to manually fix /etc/apt/sources.list, because the list which comes with
   ## grml-debootstrap is incomplete (does not complain debian security repository) and points to 127.0.0.1.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_shared/etc/apt/sources.list.whonix "$CHROOT_FOLDER"/etc/apt/sources.list
   
   ## Since "$WHONIX_SOURCE_FOLDER"/whonix_shared/etc/apt/sources.list.whonix includes both, stable and testing repositories,
   ## we have to apply our apt pinning configuration as well. Otherwise Whonix would be based on Testing, not Stable.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_shared/etc/apt/preferences.d/* "$CHROOT_FOLDER"/etc/apt/preferences.d/
   
   ## Enable apt-cacher-ng.
   export http_proxy="http://127.0.0.1:3142"

   mkdir --parents "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"
   mkdir --parents "$CHROOT_FOLDER"/"$EMPTY_DIR"
   mount --bind "$WHONIX_APT_REPOSITORY_FOLDER" "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"
   
   cp "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/pubring.gpg "$CHROOT_FOLDER"/etc/apt/trusted.gpg.d/whonix-temporary-local-apt-repository.gpg
  
   echo "deb file:"$DEB_INSTALL_FOLDER"/ local main" > "$WHONIX_SOURCES_LIST_TEMP_BUILD_FULL"
   
   sync
   
   ## Need to update package lists at least once.
   $CHROOT apt-get update
   
   $CHROOT apt-get update \
                   -o Dir::Etc::sourcelist="$WHONIX_SOURCES_LIST_TEMP_BUILD_BASE" \
                   -o Dir::Etc::sourceparts="$EMPTY_DIR" \
                   -o APT::Get::List-Cleanup="0"

   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-packages-dependencies
   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-packages-recommended

   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-desktop
   
   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-desktop-kde

   $CHROOT apt-get --yes --no-install-recommends install whonix-shared-kde-accessibility   
      
   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then 
      $CHROOT apt-get --yes --no-install-recommends install whonix-gateway-packages-dependencies
      $CHROOT apt-get --yes --no-install-recommends install whonix-gateway-packages-recommended
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      $CHROOT apt-get --yes --no-install-recommends install whonix-workstation-packages-dependencies
      $CHROOT apt-get --yes --no-install-recommends install whonix-workstation-packages-recommended
      
      $CHROOT apt-get --yes --no-install-recommends install whonix-workstation-default-applications
   else
      bug "${red}${bold}ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!${reset}"
   fi
   
   rm --force "$WHONIX_SOURCES_LIST_TEMP_BUILD_FULL"
   
   $CHROOT apt-get update \
              --no-download \
              --list-cleanup
   
   $CHROOT sync
   sync
   
   ## Disable apt-cacher-ng.
   export unset http_proxy   

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-img
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting   
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-img

   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
install-meta-packages

 
