#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "Currently running script: $0 ${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

backup-img-after-meta-package-install() {
   trap "error_handler_general" ERR INT TERM

   ## If whonix_build is run with --fast2 switch.
   if [ "$WHONIX_BUILD_FAST2" = "1" ]; then
      echo "${bold}${cyan}INFO: run with --fast2 switch, skipping $0. ${reset}"
      exit 0
   fi

   cp "$WHONIX_BINARY"/"$VMNAME".img "$WHONIX_BINARY"/"$VMNAME"-backup-after-meta-package-install.img
   chown --recursive "$user_name:$user_name" "$WHONIX_BINARY"/
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping $0, because BARE_METAL is set to 1.${reset}"
else
   true "${bold}${under}INFO: Currently running script: $0 ${1+"$@"}${reset}"
   backup-img-after-meta-package-install
   benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}${under}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
fi
