#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

run-chroot-scripts() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-img   
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/prevent-daemons-from-starting   
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/chroot-img

   sync

   ## Just for testing.
   $CHROOT update-grub -v
   $CHROOT sync
   sync

   ## We need to copy the pre chroot scripts manually into the image,
   ## because the *-common packages are not yet installed at this point.
   
   ## Delete eventually already existing folder to support re-running the script.
   rm --recursive --force "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/
   
   mkdir --parents "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/
   
   cp \
     "$WHONIX_SOURCE_FOLDER"/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/* \
     "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/
     
   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then   
      cp \
        "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/share/whonix/chroot-scripts-pre.d/* \
        "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/ 
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then   
      cp \
        "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/share/whonix/chroot-scripts-pre.d/* \
        "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/
   else
      bug "${red}${bold}ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!${reset}"
   fi
   
   ## Check which chroot scripts we got.
   $CHROOT run-parts --verbose --test "/var/lib/whonix/initial-chroot-scripts-pre.d"

   ## Run the chroot scripts.
   ## (Which got copied into the image by copyinto.)
   $CHROOT run-parts --verbose --exit-on-error "/var/lib/whonix/initial-chroot-scripts-pre.d"

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-img   
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting    
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-img

   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
run-chroot-scripts

