#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

run-chroot-scripts-post-d() {
   errorhandlersetup "errorhandlerunchrootunpreventunmount" ERR INT TERM

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-raw

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/prevent-daemons-from-starting

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/chroot-raw

   sync

   ## Sanity tests.
   $CHROOT dir
   $CHROOT mount
   $CHROOT sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/create-local-temp-apt-repo

   sync

   if [ -d "$CHROOT_FOLDER/usr/libexec/initializer-dist/chroot-scripts-post.d" ]; then
      ## Check which chroot scripts we got.
      $CHROOT run-parts --verbose --test "/usr/libexec/initializer-dist/chroot-scripts-post.d/"

      ## Run the chroot scripts.
      $CHROOT run-parts --verbose --exit-on-error "/usr/libexec/initializer-dist/chroot-scripts-post.d/"

      sync
   else
      true "${green}${bold}INFO: Folder /usr/libexec/initializer-dist/chroot-scripts-post.d does not exist in chroot.}
Not running any chroot scripts.${reset}"
   fi

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/remove-local-temp-apt-repo

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-raw

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-raw

   sync
}

main() {
   if [ "$WHONIX_BUILD_FAST2" = "2" ]; then
      echo "${bold}${cyan}INFO: run with '--fast 2' switch, skipping $BASH_SOURCE. ${reset}"
      exit 0
   fi

   root_check
   if [ "$WHONIX_BUILD_TYPE" = "gateway" ]; then
      run-chroot-scripts-post-d
   elif [ "$WHONIX_BUILD_TYPE" = "workstation" ]; then
      run-chroot-scripts-post-d
   elif [ "$WHONIX_BUILD_TYPE" = "custom-workstation" ]; then
      true "${cyan}INFO: Skipping running chroot-post.d scripts for $VMNAME.${reset}"
   elif [ "$WHONIX_BUILD_TYPE" = "whonix-host" ]; then
      run-chroot-scripts-post-d
   elif [ "$WHONIX_BUILD_TYPE" = "kicksecure" ]; then
      run-chroot-scripts-post-d
   else
      error "ERROR: Invalid WHONIX_BUILD_FLAVOR $WHONIX_BUILD_FLAVOR. Please report this bug!"
   fi
}

main "$@"
