#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

zerofree_raw() {
   ## Used by "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-raw and "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-raw.
   export kpartx_only=true

   source "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-raw
   ## provides: dev_mapper_device
   mount_raw

   zerofree -v "$dev_mapper_device"

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-raw
}


main() {
   root_check
   zerofree_raw
}

main "$@"
