#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "Currently running script: $0 ${1+"$@"}"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

cleanup() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-img

   sync

   ## Get rid of /dev folder inside the vm image. This is only required for
   ## verifiable builds. Otherwise this could be skipped. For example,
   ## "sudo sha512sum /dev/xconsole" or "sudo sha512sum /dev/initctl" would
   ## run forever. The /dev folder gets recreated by the kernel upon first
   ## boot.
   rm --recursive --force "$CHROOT_FOLDER/dev"

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-img

   sync
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping $0, because BARE_METAL is set to 1.${reset}"
else
   true "${bold}${under}INFO: Currently running script: $0 ${1+"$@"}${reset}"
   cleanup
   benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}${under}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
fi
