#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

convert_raw-to_qcow2() {
   error_handler_setup "error_handler_general" ERR INT TERM

   if [ ! "$whonix_build_script_create_qcow2" = "1" ]; then
      true "${green}INFO: Skipping $BASH_SOURCE, because whonix_build_script_create_qcow2 is not set to 1.${reset}"
      return 0
   fi

   mkdir --parents "$WHONIX_BINARY/"
   chown --recursive "$user_name:$user_name" "$WHONIX_BINARY/"

   ## Debugging.
   sudo -u "$user_name" \
      qemu-img \
         info \
            "$binary_image_raw"

   ## Create qcow2 image form raw image.
   ## VMSIZE defaults to 100G as per help-steps/variables.
   sudo -u "$user_name" \
      qemu-img \
         convert \
            -p \
            -O qcow2 \
            -S "$VMSIZE" \
            -o cluster_size=2M \
            -o preallocation=metadata \
            "$binary_image_raw" \
            "$binary_image_qcow2"

   ## Debugging.
   sudo -u "$user_name" \
      qemu-img \
         info \
            "$binary_image_qcow2"
}

if [ "$ANON_BUILD_INSTALL_TO_ROOT" = "1" ]; then
   true "${green}INFO: Skipping $BASH_SOURCE, because ANON_BUILD_INSTALL_TO_ROOT is set to 1.${reset}"
else
   true "${bold}${under}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
   convert_raw-to_qcow2
   benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}${under}INFO: End of: $BASH_SOURCE ${1+"$@"} $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
fi
