#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

convert_raw_to_qcow2() {
   if [ ! "$WHONIX_BUILD_QCOW2" = "true" ]; then
      true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_QCOW2 is not set to true.${reset}"
      return 0
   fi

   sudo $SUDO_OPTS mkdir --parents "$WHONIX_BINARY/"

   ## Debugging.
   sudo $SUDO_OPTS \
      qemu-img \
         info \
            "$binary_image_raw"

   ## Create qcow2 image form raw image.
   ## VMSIZE defaults to 100G as per help-steps/variables.
   sudo $SUDO_OPTS \
      qemu-img \
         convert \
            -p \
            -O qcow2 \
            -o cluster_size=2M \
            -o preallocation=metadata \
            "$binary_image_raw" \
            "$binary_image_qcow2"

   ## Debugging.
   sudo $SUDO_OPTS \
      qemu-img \
         info \
            "$binary_image_qcow2"
}

main() {
   root_check
   if [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
      convert_raw_to_qcow2
   else
      true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_QCOW2 is not set to 'true'.${reset}"
   fi
}

main "$@"
