#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

convert_img-to_vdi() {
   trap "error_handler_general" ERR INT TERM

   sudo -u "$user_name" \
      mkdir --parents "$HOMEVAR/VirtualBox VMs/$VMNAME"

   sudo -u "$user_name" \
      VBoxManage convertfromraw "$WHONIX_BINARY/$VMNAME.img" "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping $0, because BARE_METAL is set to 1.${reset}"
else
   true "${bold}INFO: Currently running script: $0${reset}"
   convert_img-to_vdi
   true "${bold}INFO: End of: $0 No error detected.${reset}"
fi
