#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

root_check

convert_raw-to_vdi() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   sudo -u "$user_name" \
      mkdir --parents "$HOMEVAR/VirtualBox VMs/$VMNAME"

   ## Debugging.
   sudo -u "$user_name" \
      qemu-img \
         info \
            "$binary_image_raw"

   sudo -u "$user_name" \
      VBoxManage convertfromraw "$binary_image_raw" "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   ## Debugging.
   sudo -u "$user_name" \
      qemu-img \
         info \
            "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"
}

if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
   true "${bold}${under}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
   convert_raw-to_vdi
   benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}${under}INFO: End of: $BASH_SOURCE ${1+"$@"} | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
else
   true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_VIRTUALBOX is not set to 'true'.${reset}"
fi
