#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

convert_raw_to_vdi() {
   sudo $SUDO_OPTS \
      mkdir --parents "$HOMEVAR/VirtualBox VMs/$VMNAME"

   ## Debugging.
   sudo $SUDO_OPTS \
      qemu-img \
         info \
            "$binary_image_raw"

   sudo $SUDO_OPTS \
      VBoxManage convertfromraw "$binary_image_raw" "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   ## Debugging.
   sudo $SUDO_OPTS \
      qemu-img \
         info \
            "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   sudo $SUDO_OPTS \
      VBoxManage modifymedium --compact "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   ## Debugging.
   sudo $SUDO_OPTS \
      qemu-img \
         info \
            "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"
}

main() {
   root_check
   if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
      convert_raw_to_vdi
   else
      true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_VIRTUALBOX is not set to 'true'.${reset}"
   fi
}

main "$@"
