#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

general_setup() {
   trap "error_handler_general" ERR INT TERM

   ## Create a new VM. Name: $VMNAME
   sudo -u "$USERNAME" VBoxManage createvm --name "$VMNAME" --register

   ## Debian
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --ostype Debian

   ## Add SATA Controller.
   sudo -u "$USERNAME" VBoxManage storagectl "$VMNAME" --add sata --name "$VMNAME"

   ## HDD gets added in specific_setup.

   ## Only 4 sata ports instead of 30. Speeds up booting.
   sudo -u "$USERNAME" VBoxManage storagectl "$VMNAME" --name "$VMNAME" --sataportcount 4

   ## Add CD-ROM
   sudo -u "$USERNAME" VBoxManage storageattach "$VMNAME" --storagectl "$VMNAME" --type dvddrive --port 1 --medium emptydrive

   ## RAM
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --memory $VMRAM

   ## Enable PAE.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --pae on

   ## Hide hosts CPU info. This does not have a GUI option.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --synthcpu on

   ## REVIEW
   ## ACPI boots up the VM boot process. It has not been reviewed if this is good or bad for security.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --acpi on

   ## REVIEW
   ## ACPI boots up the VM boot process. It has not been reviewed if this is good or bad for security.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --ioapic on

   ## Set system clock of VM to UTC.
   ## When Virtual Box starts it looks up date and time of the host, i.e. "JAN 15 2012 00:00:00"
   ## and sets the VM clock to that date and time. The following option translates the date
   ## and time to UTC, thus hiding the hosts timezone from the guest.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --rtcuseutc on

   ## Deactivate time synchronization between host and VMs.
   ## This is documented in Whonix Design on TimeSync page
   ## Thanks to
   ## http://www.braingia.org/webnotes/2011/06/22/disable-time-sync-with-virtualbox/
   sudo -u "$USERNAME" VBoxManage setextradata "$VMNAME" "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled" "1"

   ## Disable clipboard sharing. Only matters if guest additions are installed which is recommended against.
   ## Just in case.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --clipboard disabled
}



gateway_specific() {
   trap "error_handler_general" ERR INT TERM

   ## Attach the HDD.
   sudo -u "$USERNAME" VBoxManage storageattach "$VMNAME" --storagectl "$VMNAME" --type hdd --port 0 --medium "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   ## Leave Adapter 1 as NAT.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --nic1 nat

   ## REVIEW
   ## NAT adapter also gets fixed MAC shared among all Whonix users.
   ## Use cases:
   ## - Whonix-Workstation can see it.
   ## - See Whonix Security page about Whonix in public networks / MAC address
   ## - In case the Gateway gets broken, this one can not be used as identifier.
   ##   Gets interesting in future with multiple gateways.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --macaddress1 002682475ce1

   ## Prevents leaking DNS info from the host into the guest.
   ## Also useful in other cases.
   ## https://www.virtualbox.org/manual/ch09.html#nat-adv-dns
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --natdnsproxy1 on

   ## Prevents leaking DNS info from the host into the guest.
   ## Also useful in other cases.
   ## https://www.virtualbox.org/manual/ch09.html#nat_host_resolver_proxy
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --natdnshostresolver1 on

   ## Do not pass the domain name for network name resolution to the VM.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --natdnspassdomain1 off

   ## Enable Adapter 2, set to "Internal Network".
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --nic2 intnet

   ## Change the internal network to "Whonix", IMPORTANT!
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --intnet2 "Whonix"

   ## Enter following MAC address: 0013029cf191
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --macaddress2 0013029cf191
}



workstation_specific() {
   trap "error_handler_general" ERR INT TERM

   ## Attach the HDD.
   sudo -u "$USERNAME" VBoxManage storageattach "$VMNAME" --storagectl "$VMNAME" --type hdd --port 0 --medium "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   ## 128 MB Video RAM.
   ## Settings->Display->Video Memory->128 MB.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --vram 128

   ## Add Adapter 1 (will be eth0), an internal network, IMPORTANT!
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --nic1 intnet

   ## Remove the virtual network cable. Same reason like gateway_specific.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --cableconnected1 on

   ## Change the internal network to "Whonix", IMPORTANT!
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --intnet1 "Whonix"

   ## Enter following MAC address: 0021004d8f08
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --macaddress1 0021004d8f08

   ## Enable audio controller ac97.
   ## sb16 should be obsolete.
   ## ac97 is hopefully better supported than intel hda.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --audiocontroller ac97

   ## Host audio driver can be oss, alsa or pulse.
   ## Unfortunately, no auto detection available.
   ## Depends on host driver.
   ## Ubuntu host uses pulse audio.
   sudo -u "$USERNAME" VBoxManage modifyvm "$VMNAME" --audio pulse
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping $0, because BARE_METAL is set to 1.${reset}"
else
   true "${bold}INFO: Currently running script: $0${reset}"

   general_setup

   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      gateway_specific
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      workstation_specific
   else
      bug "ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!"
   fi
fi

