#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

export-vbox-vm() {
   trap "error_handler_general" ERR INT TERM

   if [ "$VMNAME" = "Whonix-Gateway" ]; then
      local TEXT="
##############
## SNAPSHOT ##
##############

It is important to take a snapshot right after importing is complete. You can restore the original snapshot whenever you need a clean state.

##############
## LOW RAM? ##
##############

If your computer has 2GB or less RAM, set the RAM for Whonix-Gateway to 128MB to automatically boot into a command-line environment. The Gateway will work normally, and you can configure it via the command-line. If you need a graphical environment, temporarily increase RAM to 512MB to boot to a desktop.

#####################
## SECURITY ADVICE ##
#####################

Whonix with its default settings may provide better protection than Tor alone. You can make it even more secure. It is recommended to read this page:
https://www.whonix.org/wiki/Pre_Install_Advice

################
## DISCLAIMER ##
################

There is no magic pill for anonymity. The more you learn about Whonix, Tor, and threats to your privacy, the safer you can become.

Whonix is produced independently of, and carries no guarantee from The Tor Project.

Whonix is experimental software. Do not rely on it for strong anonymity.
"
   elif [ "$VMNAME" = "Whonix-Workstation" ]; then
      local TEXT="
# For internet access, Whonix-Workstation requires that Whonix-Gateway be running. #

##############
## SNAPSHOT ##
##############

It is important to take a snapshot right after importing is complete. You can restore the original snapshot whenever you need a clean state.

##############
## LOW RAM? ##
##############

If your computer has less than 2GB RAM, you can lower the RAM for Whonix-Workstation to 512MB. Performance will suffer, but an advanced user can install a lighter desktop environment. Setting RAM to less than 512MB will boot to a command-line environment.

#####################
## SECURITY ADVICE ##
#####################

Whonix with its default settings may provide better protection than Tor alone. You can make it even more secure. It is recommended to read this page:
https://www.whonix.org/wiki/Pre_Install_Advice

################
## DISCLAIMER ##
################

There is no magic pill for anonymity. The more you learn about Whonix, Tor, and threats to your privacy, the safer you can become.

Whonix is produced independently of, and carries no guarantee from The Tor Project.

Whonix is experimental software. Do not rely on it for strong anonymity.
"
   else
      local MSG="${bold}${red}$0 ERROR: VMNAME is neither Whonix-Gateway nor Whonix-Workstation. Please report this bug! ${reset}"
      echo "$MSG"
      bug "$MSG"
   fi

   ## Not yet using: --producturl

   sudo -u "$USERNAME" \
      VBoxManage export "$VMNAME" \
         --manifest \
         --vsys "0" \
         --product "$VMNAME" \
         --vendor "Whonix" \
         --vendorurl "https://www.whonix.org" \
         --eula "$TEXT" \
         --version "$WHONIX_BUILD_WHONIX_VERSION_NEW" \
         --output "$WHONIX_BINARY"/"$VMNAME"-"$WHONIX_BUILD_WHONIX_VERSION_NEW".ova
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping $0, because BARE_METAL is set to 1.${reset}"
else
   true "${bold}INFO: Currently running script: $0${reset}"
   export-vbox-vm
fi
