#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

general_setup() {
   ## Create a new VM. Name: $VMNAME
   sudo $SUDO_OPTS VBoxManage createvm --name "$VMNAME" --register

   if ! echo "$BUILD_TARGET_ARCH" | grep "64" ; then
      sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --ostype Debian
   else
      sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --ostype Debian_64
   fi

   ## Add SAS Controller for hdd.
   ## Not using SATA for hdd:
   ## - https://github.com/Whonix/Whonix/issues/274
   ## - https://www.virtualbox.org/ticket/10031
   sudo $SUDO_OPTS VBoxManage storagectl "$VMNAME" --add sas --name "$VMNAME-sas"

   ## HDD gets added in the gateway / workstation specific functions below.

   ## Add SATA Controller for DVD.
   sudo $SUDO_OPTS VBoxManage storagectl "$VMNAME" --add sata --name "$VMNAME-sata"

   ## Only 4 sata ports instead of 30. Speeds up booting.
   sudo $SUDO_OPTS VBoxManage storagectl "$VMNAME" --name "$VMNAME-sata" --portcount 4

   ## Attach the HDD.
   sudo $SUDO_OPTS VBoxManage storageattach "$VMNAME" --storagectl "$VMNAME-sas" --type hdd --port 0 --medium "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   ## Add DVD.
   sudo $SUDO_OPTS VBoxManage storageattach "$VMNAME" --storagectl "$VMNAME-sata" --type dvddrive --port 1 --medium emptydrive

   ## RAM
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --memory "$VMRAM"

   ## Settings->Display->Video Memory
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --vram "$VRAM"

   ## Enable PAE.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --pae on

   ## 4 virtual CPU cores by default.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --cpus 4

   ## Restrict Boot devices
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --boot4 none
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --boot3 none
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --boot2 none
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --boot1 disk

   ## Hide hosts CPU info. This does not have a GUI option.
   ## Was removed from VirtualBox.
   ## https://phabricator.whonix.org/T408
   #sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --synthcpu on

   ## REVIEW
   ## ACPI speeds up the VM boot process. It has not been reviewed if this is good or bad for security.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --acpi on

   ## REVIEW
   ## It has not been reviewed if this is good or bad for security.
   ##
   ## VirtualBox documentation can be found on:
   ## https://www.virtualbox.org/manual/ch03.html
   ##
   ## Quote VirtualBox documentation:
   ## "[...] Enabling the I/O APIC is required for 64-bit guest operating
   ## systems, especially Windows Vista; it is also required if you want to use
   ## more than one virtual CPU in a virtual machine. [...]"
   ## Conclusion: it is better to leave it enabled to avoid support requests by
   ## users who wish to use more than one virtual CPU, who install an amd64
   ## kernel or create their own Custom-Whonix-Workstation.
   ##
   ## Quote VirtualBox documentation:
   ## "[...] Advanced Configuration and Power Interface (ACPI) which VirtualBox
   ## presents to the guest operating system by default. ACPI is the current
   ## industry standard to allow operating systems to recognize hardware,
   ## configure motherboards and other devices and manage power. As all modern
   ## PCs contain this feature and Windows and Linux have been supporting it
   ## for years, it is also enabled by default in VirtualBox. [...]"
   ## Conclusion: The linux kernel is better tested with I/O APIC enabled
   ## rather than I/O APIC disabled.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --ioapic on

   ## Set system clock of VM to UTC.
   ## When VirtualBox starts it looks up date and time of the host, i.e. "JAN 15 2012 00:00:00"
   ## and sets the VM clock to that date and time. The following option translates the date
   ## and time to UTC, thus hiding the hosts timezone from the guest.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --rtcuseutc on

   ## Deactivate time synchronization between host and VMs.
   ## This is documented in Whonix Design on TimeSync page
   ## Thanks to
   ## http://www.braingia.org/webnotes/2011/06/22/disable-time-sync-with-virtualbox/
   sudo $SUDO_OPTS VBoxManage setextradata "$VMNAME" "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled" "1"

   ## Clipboard sharing.
   ## https://www.whonix.org/wiki/VirtualBox_Guest_Additions#Clipboard_Sharing
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --clipboard bidirectional

   ## Drag'n'Drop
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --draganddrop hosttoguest

   ## Disable microphones.
   ## https://www.whonix.org/wiki/Hardware_Threat_Minimization#Microphones
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --audioin off

   ## Quote https://www.virtualbox.org/manual/ch03.html
   ## > "VMSVGA: Use this graphics controller to emulate a VMware SVGA graphics device."
   ## > "This is the default graphics controller for Linux guests."
   ##
   ## Has better desktop resolution in CLI (virtual terminal) mode.
   ##
   ## Broken for some users.
   ## https://forums.whonix.org/t/black-screen-on-15-0-0-6-6-and-15-0-0-7-1/8554
   #sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --graphicscontroller vmsvga
}

spectre_meltdown_defenses() {
   ## This code is currently not in use! Reasons:
   ## https://www.whonix.org/wiki/Spectre_Meltdown#VirtualBox

   ## https://www.virtualbox.org/manual/ch08.html
   ## > "--ibpb-on-vm-[enter|exit] on|off: Enables flushing of the indirect branch prediction buffers on every VM enter or exit respectively. This could be enabled by users overly worried about possible spectre attacks by the VM. Please note that these options may have sever impact on performance."
   ##
   ## There is a mistake in VirtualBox manual saying 'enter' which does not work. It's 'entry'.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --ibpb-on-vm-entry on
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --ibpb-on-vm-exit on

   ## https://www.virtualbox.org/manual/ch08.html
   ## > "--l1d-flush-on-vm-enter on|off: Enables flushing of the level 1 data cache on VM enter. See Section 13.4.1, “CVE-2018-3646”."
   ##
   ## There is a mistake in VirtualBox manual saying 'enter' which does not work. It's 'entry'.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --l1d-flush-on-vm-entry on

   ## https://www.virtualbox.org/manual/ch08.html
   ## > "--l1d-flush-on-sched on|off: Enables flushing of the level 1 data cache on scheduling EMT for guest execution. See Section 13.4.1, “[https://www.virtualbox.org/manual/ch13.html#sec-rec-cve-2018-3646 CVE-2018-3646]”."
   ## https://www.virtualbox.org/manual/ch13.html#sec-rec-cve-2018-3646
   ## > "For users not concerned by this security issue, the default mitigation can be disabled using
   ##    VBoxManage modifyvm "$VMNAME" --l1d-flush-on-sched off"
   ## Since we want to enable the security feature we set '--l1d-flush-on-sched on'.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --l1d-flush-on-sched on

   ## https://www.virtualbox.org/manual/ch08.html
   ## > "--spec-ctrl on|off: This setting enables/disables exposing speculation control interfaces to the guest, provided they are available on the host. Depending on the host CPU and workload, enabling speculation control may significantly reduce performance."
   ## According to https://www.virtualbox.org/ticket/17987 '--spec-ctrl' should be set to 'on'.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --spec-ctrl on

   ## https://www.virtualbox.org/manual/ch08.html
   ## > "--nestedpaging on|off: If hardware virtualization is enabled, this additional setting enables or disables the use of the nested paging feature in the processor of your host system; see Section 10.7, “Nested paging and VPIDs” and Section 13.4.1, “CVE-2018-3646”."
   ## https://www.virtualbox.org/manual/ch13.html#sec-rec-cve-2018-3646
   ## > "13.4.1. CVE-2018-3646"
   ##
   ## > "This security issue affects a range of Intel CPUs with nested paging. AMD CPUs are expected not to be impacted (pending direct confirmation by AMD). Also the issue does not affect VMs running with hardware virtualization disabled or with nested paging disabled."
   ##
   ## > "For more information about nested paging, see Section 10.7, “Nested paging and VPIDs”."
   ##
   ## > "Mitigation options:"
   ## > "13.4.1.1. Disable nested paging"
   ##
   ## > "By disabling nested paging (EPT), the VMM will construct page tables shadowing the ones in the guest. It is no possible for the guest to insert anything fishy into the page tables, since the VMM carefully validates each entry before shadowing it."
   ##
   ## > "As a side effect of disabling nested paging, several CPU features will not be made available to the guest. Among these features are AVX, AVX2, XSAVE, AESNI, and POPCNT. Not all guests may be able to cope with dropping these features after installation. Also, for some guests, especially in SMP configurations, there could be stability issues arising from disabling nested paging. Finally, some workloads may experience a performance degradation."
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --nestedpaging off
}

hardware_obfuscation() {
   # This code is no longer in use!
   # remove attempts to hide CPU information from VM in VirtualBox
   # https://phabricator.whonix.org/T881
   # It could be enabled through an optional build option if there is interest.

   # Thanks to dumbmouse contributing this!
   # https://phabricator.whonix.org/T408#11595

   # Clear existing (not necessary for initial install)
   sudo $SUDO_OPTS vboxmanage modifyvm "$VMNAME" --cpuidremoveall

   # GenuineIntel
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/00000000/ebx 0x756e6547
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/00000000/ecx 0x6c65746e
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/00000000/edx 0x49656e69
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000000/ebx 0x756e6547
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000000/ecx 0x6c65746e
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000000/edx 0x49656e69

   # Model/Family/Stepping
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/00000001/eax 0x00000f43
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000001/eax 0x00000f43

   # Pentium model name
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000002/eax 0x20202020
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000002/ebx 0x20202020
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000002/ecx 0x20202020
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000002/edx 0x6e492020
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000003/eax 0x286c6574
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000003/ebx 0x50202952
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000003/ecx 0x69746e65
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000003/edx 0x52286d75
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000004/eax 0x20342029
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000004/ebx 0x20555043
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000004/ecx 0x30302e33
   sudo $SUDO_OPTS vboxmanage setextradata "$VMNAME" VBoxInternal/CPUM/HostCPUID/80000004/edx 0x007a4847
}

whonix-gateway_specific() {
   ## Disable Audio
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --audio none

   ## Leave Adapter 1 as NAT.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --nic1 nat

   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --cableconnected1 on

   ## Enable Adapter 2, set to "Internal Network".
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --nic2 intnet

   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --cableconnected2 on

   ## Change the internal network to "Whonix", IMPORTANT!
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --intnet2 "Whonix"
}

whonix-workstation_specific() {
   ## Add Adapter 1, an internal network, IMPORTANT!
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --nic1 intnet

   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --cableconnected1 on

   ## Change the internal network to "Whonix", IMPORTANT!
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --intnet1 "Whonix"
}

whonix-custom-workstation_specific() {
   whonix-workstation_specific

   sudo $SUDO_OPTS VBoxManage setextradata "$VMNAME" "GUI/FirstRun" "yes"
}

debian_specific() {
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --nic1 nat

   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --cableconnected1 on
}

audio_enable() {
   ## Enable audio controller ac97.
   ## sb16 should be obsolete.
   ## ac97 is hopefully better supported than intel hda.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --audiocontroller ac97

   ## Host audio driver can be oss, alsa or pulse.
   ## Unfortunately, no auto detection available.
   ## Depends on host driver.
   ## Ubuntu host uses pulse audio.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --audio pulse

   ## Activate audio output.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --audioout on
}

dns_specific() {
   ## https://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working

   ## Prevents leaking DNS info from the host into the guest.
   ## Also useful in other cases.
   ## https://www.virtualbox.org/manual/ch09.html#nat-adv-dns
   ##
   ## '--natdnsproxy1 on' might cause issues:
   ## https://forums.virtualbox.org/viewtopic.php?f=6&t=94671&p=457620#p457620
   ##
   ## Probably not both required 'natdnsproxy1 on' and 'natdnshostresolver1 on'.
   ##
   ## Both enabled at the same time causes an error in VirtualBox VM log:
   ## 00:00:00.933430 NAT: Host Resolver conflicts with DNS proxy, the last one was forcely ignored
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --natdnsproxy1 off

   ## Prevents leaking DNS info from the host into the guest.
   ## Also useful in other cases.
   ## https://www.virtualbox.org/manual/ch09.html#nat_host_resolver_proxy
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --natdnshostresolver1 on

   ## Do not pass the domain name for network name resolution to the VM.
   sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --natdnspassdomain1 off
}

main() {
   if [ ! "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
      true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_VIRTUALBOX is not set to 'true'.${reset}"
      return 0
   fi

   root_check
   general_setup

   ## Possibly not worth it due to huge performance penalty and unclear security benefits. Despite:
   ##
   ##     host microcode upgrade
   ##     host kernel upgrade
   ##     VM kernel upgrade
   ##     spectre-meltdown-checker on the host showing "not vulnerable"
   ##     latest VirtualBox version
   ##     all spectre/meltdown related VirtualBox settings tuned for better security as documented below
   ##
   ## VirtualBox is likely still vulnerable to spectre/meltdown. For reference see VirtualBox bug report / forum discussion.
   ## https://www.whonix.org/wiki/Spectre_Meltdown#VirtualBox
   ## https://www.virtualbox.org/ticket/17987
   ## https://forums.virtualbox.org/viewtopic.php?f=7&t=89395
   ## https://forums.whonix.org/t/whonix-vulerable-due-to-missing-processor-microcode-packages/5739/22
   #spectre_meltdown_defenses

   if [ "$WHONIX_BUILD_TYPE" = "gateway" ]; then
      whonix-gateway_specific
      dns_specific
   elif [ "$WHONIX_BUILD_TYPE" = "workstation" ]; then
      whonix-workstation_specific
      audio_enable
   elif [ "$WHONIX_BUILD_TYPE" = "custom-workstation" ]; then
      whonix-custom-workstation_specific
      audio_enable
   elif [ "$WHONIX_BUILD_TYPE" = "whonix-host" ]; then
      debian_specific
      dns_specific
      audio_enable
   elif [ "$WHONIX_BUILD_TYPE" = "kicksecure" ]; then
      debian_specific
      dns_specific
      audio_enable
   else
      error "ERROR: Invalid WHONIX_BUILD_FLAVOR $WHONIX_BUILD_FLAVOR. Please report this bug!"
   fi

   sync
}

main "$@"
