#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

export-vbox-vm() {
   trap "error_handler_general" ERR INT TERM

   if [ "$VMNAME" = "Whonix-Gateway" ]; then
      local TEXT="
########################
## HOSTS WITH LOW RAM ##
########################

If your host computer has 2GB RAM or less, set the virtual machine's RAM for Whonix-Gateway to 128MB to automatically boot into a command-line environment. The Gateway will work normally, and you can configure it via the command-line. If you need a graphical environment, temporarily increase RAM to 512MB to boot to a desktop.

Boot environment based on RAM can be configured in /etc/whonix.d/

########################
## PRE INSTALL ADVICE ##
########################

Whonix with its default settings may provide better protection than Tor alone. You can make it even more secure. It is recommended to read and apply Whonix Pre Install Advice:
https://www.whonix.org/wiki/Pre_Install_Advice

################
## DISCLAIMER ##
################

There is no magic pill for anonymity. The more you learn about Whonix, Tor, and threats to your privacy, the safer you can become.

Whonix is produced independently of, and carries no guarantee from, The Tor Project.

Whonix is experimental software. Do not rely on it for strong anonymity.
"
   elif [ "$VMNAME" = "Whonix-Workstation" ]; then
      local TEXT="
# For internet access, Whonix-Workstation requires that Whonix-Gateway be running. #

########################
## HOSTS WITH LOW RAM ##
########################

If your host computer has less than 2GB of RAM, you can lower the RAM for Whonix-Workstation to 512MB. Performance will suffer, but an advanced user can install a lighter desktop environment or use a Custom-Whonix-Workstation. Setting RAM to less than 512MB will boot to a command-line environment.

Boot environment based on RAM can be configured in /etc/whonix.d/

########################
## PRE INSTALL ADVICE ##
########################

Whonix with its default settings may provide better protection than Tor alone. You can make it even more secure. It is recommended to read and apply Whonix Pre Install Advice:
https://www.whonix.org/wiki/Pre_Install_Advice

################
## DISCLAIMER ##
################

There is no magic pill for anonymity. The more you learn about Whonix, Tor, and threats your privacy, the safer you can become.

Whonix is produced independently of, and carries no guarantee from, The Tor Project.

Whonix is experimental software. Do not rely on it for strong anonymity.
"
   else
      local MSG="${bold}${red}$0 ERROR: VMNAME is neither Whonix-Gateway nor Whonix-Workstation. Please report this bug! ${reset}"
      echo "$MSG"
      bug "$MSG"
   fi

   ## Not yet using: --producturl

   sudo -u "$USERNAME" \
      VBoxManage export "$VMNAME" \
         --manifest \
         --vsys "0" \
         --product "$VMNAME" \
         --vendor "Whonix" \
         --vendorurl "https://www.whonix.org" \
         --eula "$TEXT" \
         --version "$WHONIX_BUILD_WHONIX_VERSION_NEW" \
         --output "$WHONIX_BINARY"/"$VMNAME"-"$WHONIX_BUILD_WHONIX_VERSION_NEW".ova
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping $0, because BARE_METAL is set to 1.${reset}"
else
   true "${bold}INFO: Currently running script: $0${reset}"
   export-vbox-vm
fi
