#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

msg_graphical_gateway_low_ram="\
########################
## GATEWAY - LOW RAM? ##
########################

If your computer has 2GB or less RAM, set the RAM for Whonix-Gateway to 256MB to automatically boot into a command-line environment. The Gateway will work normally, and you can configure it via the command-line. If you need a graphical environment, temporarily increase RAM to 512MB to boot to a desktop."

msg_whonix_security_advice="\
#####################
## SECURITY ADVICE ##
#####################

Whonix with its default settings may provide better protection than Tor alone. You can make it even more secure. It is recommended to read our documentation:
https://www.whonix.org/wiki/Documentation"

msg_whonix_disclaimer="\
################
## DISCLAIMER ##
################

There is no magic pill for anonymity. The more you learn about Whonix, Tor, and threats to your privacy, the safer you can become.

Whonix is produced independently from the Tor (R) anonymity software and carries no guarantee from The Tor Project about quality, suitability or anything else.

Whonix is a derivative of and not affiliated with Debian. Debian is a registered trademark owned by Software in the Public Interest, Inc.

Whonix is experimental software. Do not rely on it for strong anonymity."

msg_whonix_workstation_requires_whonix_gateway="\
# For internet access, Whonix-Workstation requires that Whonix-Gateway be running. #"

msg_whonix_workstation_low_ram="\
##########################
## WORKSTATION LOW RAM? ##
##########################

If your computer has less than 2GB RAM, you can lower the RAM for Whonix-Workstation to 512MB. Performance will suffer, but an advanced user can install a lighter desktop environment. Setting RAM to less than 512MB will boot to a command-line environment."

create-vm-text() {
   if [ "$WHONIX_BUILD_FLAVOR" = "whonix-gateway-cli" ]; then
      local TEXT="\
$msg_whonix_security_advice

$msg_whonix_disclaimer"
   elif [ "$WHONIX_BUILD_FLAVOR" = "whonix-workstation-cli" ]; then
      local TEXT="\
$msg_whonix_workstation_requires_whonix_gateway

$msg_whonix_security_advice

$msg_whonix_disclaimer"
   elif [ "$WHONIX_BUILD_TYPE" = "gateway" ]; then
      local TEXT="\
$msg_graphical_gateway_low_ram

$msg_whonix_security_advice

$msg_whonix_disclaimer"
   elif [ "$WHONIX_BUILD_TYPE" = "workstation" ]; then
      local TEXT="\
$msg_whonix_workstation_requires_whonix_gateway

$msg_whonix_workstation_low_ram

$msg_whonix_security_advice

$msg_whonix_disclaimer"
   elif [ "$WHONIX_BUILD_TYPE" = "custom-workstation" ]; then
      local TEXT="\
$msg_whonix_workstation_requires_whonix_gateway

$msg_whonix_security_advice

$msg_whonix_disclaimer"
   elif [ "$WHONIX_BUILD_TYPE" = "whonix-host" ]; then
      local TEXT="TODO"
   elif [ "$WHONIX_BUILD_TYPE" = "kicksecure" ]; then
      local TEXT="TODO"
   else
      local MSG="${bold}${red}$BASH_SOURCE ERROR: VMNAME is neither Whonix-Gateway nor Whonix-Workstation. Please report this bug! ${reset}"
      error "$MSG"
   fi

   echo "$TEXT" | sudo $SUDO_OPTS tee "$binary_image_text" >/dev/null
}

main() {
   root_check
   if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
      create-vm-text
   else
      true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_VIRTUALBOX is not set to 'true'.${reset}"
   fi
}

true "${bold}${under}INFO: Currently running script: $0 "$@"${reset}"
main "$@"
