#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

export-vbox-vm() {
   if [ "$WHONIX_BUILD_FLAVOR" = "whonix-gateway" ]; then
      local TEXT="\
########################
## GATEWAY - LOW RAM? ##
########################

If your computer has 2GB or less RAM, set the RAM for Whonix-Gateway to 128MB to automatically boot into a command-line environment. The Gateway will work normally, and you can configure it via the command-line. If you need a graphical environment, temporarily increase RAM to 512MB to boot to a desktop.

#####################
## SECURITY ADVICE ##
#####################

Whonix with its default settings may provide better protection than Tor alone. You can make it even more secure. It is recommended to read this page:
https://www.whonix.org/wiki/Pre_Install_Advice

################
## DISCLAIMER ##
################

There is no magic pill for anonymity. The more you learn about Whonix, Tor, and threats to your privacy, the safer you can become.

Whonix is produced independently of, and carries no guarantee from The Tor Project.

Whonix is experimental software. Do not rely on it for strong anonymity.
"
   elif [ "$WHONIX_BUILD_FLAVOR" = "whonix-workstation" ]; then
      local TEXT="\
# For internet access, Whonix-Workstation requires that Whonix-Gateway be running. #

##########################
## WORKSTATION LOW RAM? ##
##########################

If your computer has less than 2GB RAM, you can lower the RAM for Whonix-Workstation to 512MB. Performance will suffer, but an advanced user can install a lighter desktop environment. Setting RAM to less than 512MB will boot to a command-line environment.

#####################
## SECURITY ADVICE ##
#####################

Whonix with its default settings may provide better protection than Tor alone. You can make it even more secure. It is recommended to read this page:
https://www.whonix.org/wiki/Pre_Install_Advice

################
## DISCLAIMER ##
################

There is no magic pill for anonymity. The more you learn about Whonix, Tor, and threats to your privacy, the safer you can become.

Whonix is produced independently of, and carries no guarantee from The Tor Project.

Whonix is experimental software. Do not rely on it for strong anonymity.
"
   elif [ "$WHONIX_BUILD_FLAVOR" = "whonix-custom-workstation" ]; then
      local TEXT="\
# For internet access, Whonix-Custom-Workstation requires that Whonix-Gateway be running. #

#####################
## SECURITY ADVICE ##
#####################

Whonix with its default settings may provide better protection than Tor alone. You can make it even more secure. It is recommended to read this page:
https://www.whonix.org/wiki/Pre_Install_Advice

################
## DISCLAIMER ##
################

There is no magic pill for anonymity. The more you learn about Whonix, Tor, and threats to your privacy, the safer you can become.

Whonix is produced independently of, and carries no guarantee from The Tor Project.

Whonix is experimental software. Do not rely on it for strong anonymity.
"
   else
      local MSG="${bold}${red}$BASH_SOURCE ERROR: VMNAME is neither Whonix-Gateway nor Whonix-Workstation. Please report this bug! ${reset}"
      error "$MSG"
   fi

   ## Not yet using: --producturl

   ## --vsys needs to precede --eula.
   sudo $SUDO_OPTS \
      VBoxManage \
         export "$VMNAME" \
         --vsys "0" \
         --eula "$TEXT" \
         --manifest \
         --product "$VMNAME" \
         --vendor "Whonix" \
         --vendorurl "https://www.whonix.org" \
         --version "$anon_dist_build_version" \
         --output "$binary_image_ova"

   ## Only important for redistribution.
   ## VirtualBox creates $binary_image_ova with u+r only, which is problematic
   ## with respect to rsync.
   chmod ugo+r "$binary_image_ova"

   sync

   ## Sanity test.
   ## A different --vmname is required, because $VMNAME does already exist
   ## in the list of imported VirtualBox machines.
   sudo $SUDO_OPTS \
      VBoxManage \
         import "$binary_image_ova" \
         --vsys "0" \
         --eula accept \
         --vmname "$VMNAME-$anon_dist_build_version" \
         --dry-run
}

main() {
   root_check
   if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
      export-vbox-vm
   else
      true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_VIRTUALBOX is not set to 'true'.${reset}"
   fi
}

true "${bold}${under}INFO: Currently running script: $0 "$@"${reset}"
main "$@"
