#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

create-ova-report() {
   trap "error_handler_general" ERR INT TERM

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER/analyze_image" \
      --ova "$WHONIX_BINARY/$VMNAME-$whonix_build_whonix_version_new.ova" \
      --report "$WHONIX_BINARY/$VMNAME-$whonix_build_whonix_version_new.report" \
      --tempfolder "$WHONIX_BINARY/$VMNAME-${whonix_build_whonix_version_new}_report_tempfolder"
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping $0, because BARE_METAL is set to 1.${reset}"
else
   true "${bold}INFO: Currently running script: $0${reset}"
   create-ova-report
   true "${bold}INFO: End of: $0 No error detected.${reset}"
fi
