#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

convert_raw_to_vdi() {
   $SUDO_TO_VBOX_TEMP mkdir --parents "$HOMEVAR_VBOX_TEMP/VirtualBox VMs/$VMNAME"

   ## Debugging.
   ## Execute as user "user" (actually, default user that has run derivative-maker), because inside "user"'s home folder.
   qemu-img \
      info \
         "$binary_image_raw_file"

   ## Can be safely deleted because stored under dedicated, temporary user account.
   ## Must be deleted for this step to be idempotent. Otherwise "VBoxManage convertfromraw" would fail.
   $SUDO_TO_VBOX_TEMP rm -f "$HOMEVAR_VBOX_TEMP/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   $SUDO_TO_VBOX_TEMP VBoxManage convertfromraw "$binary_image_raw_file" "$HOMEVAR_VBOX_TEMP/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   ## Debugging.
   $SUDO_TO_VBOX_TEMP qemu-img info "$HOMEVAR_VBOX_TEMP/VirtualBox VMs/$VMNAME/$VMNAME.vdi"

   if [ "$dist_build_fast1" = "1" ]; then
      echo "${bold}${cyan}INFO: run with '--fast 1' switch, skipping compacting vdi. ${reset}"
      exit 0
   else
      $SUDO_TO_VBOX_TEMP VBoxManage modifymedium --compact "$HOMEVAR_VBOX_TEMP/VirtualBox VMs/$VMNAME/$VMNAME.vdi"
   fi

   ## Debugging.
   $SUDO_TO_VBOX_TEMP qemu-img info "$HOMEVAR_VBOX_TEMP/VirtualBox VMs/$VMNAME/$VMNAME.vdi"
}

main() {
   if [ "$dist_build_virtualbox" = "true" ]; then
      convert_raw_to_vdi
   else
      true "${green}INFO: Skipping $BASH_SOURCE, because dist_build_virtualbox is not set to 'true'.${reset}"
   fi
}

main "$@"
