#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## Copyright (C) 2021 Gavin Pacini
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

export_utm_packages() {
   ## create folder structure for UTM
   ## move image file
   ## copy configs
   utmfolder="${dist_binary_build_folder}/${VMNAME}.utm"
   mkdir --parents "${utmfolder}/Images"
   $SUDO_TO_ROOT chown "$user_name:$user_name" "$binary_image_raw"
   ## copy instead of move the raw image
   ## disadvantage:
   ## - requires more disk space
   ## advantage:
   ## - makes this step idempotent, easier to test and debug
   ## - can CI test dm-prepare-release
   cp "$binary_image_raw" "${utmfolder}/Images/${VMNAME}.raw"
   cp "$source_utm_file" "${utmfolder}/config.plist"

   tar -zcvSf "${dist_binary_build_folder}/${VMNAME}.utm.tar.gz" "$utmfolder"
}

main() {
   if [ "$dist_build_utm" = "true" ]; then
      export_utm_packages
   else
      true "${green}INFO: Skipping $BASH_SOURCE, because not using --target utm.${reset}"
   fi
}

main "$@"
