#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

prepare-release(){
   if [ ! "$dist_build_redistributable" = "true" ]; then
      return 0
   fi

   dm-prepare-release "$@"

   true
}

main() {
   prepare-release "$@"
}

main "$@"
