#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

cd "$MYDIR"
cd ..

create-windows-installer() {
   pushd ~/virtualbox-windows-installer-binary

   for file_name in ./VirtualBox-*.exe ; do
      break
   done
   test -r "$file_name"
   FILE_VBOX_INST_EXE=$(realpath "$file_name")
   test -r "$FILE_VBOX_INST_EXE"

   "${dist_developer_meta_files_folder}/usr/bin/dm-virtualbox-installer-exe-verify-windows"
   popd

   ## environment variables read by Whonix-Installer build.sh
   FILE_LICENSE="$source_code_folder_dist/packages/kicksecure/kicksecure-base-files/usr/share/kicksecure/KICKSECURE_BINARY_LICENSE_AGREEMENT"
   FILE_WHONIX_OVA="$binary_image_ova"
   FILE_WHONIX_STARTER_MSI="$source_code_folder_dist/windows/Whonix-Starter/WhonixStarterInstaller.msi"
   #FILE_VBOX_INST_EXE="$FILE_VBOX_INST_EXE"
   FILE_INSTALLER_BINARY_WITH_APPENDED_OVA="$binary_image_windows_installer_exe"
   export FILE_LICENSE FILE_WHONIX_OVA FILE_WHONIX_STARTER_MSI FILE_VBOX_INST_EXE FILE_INSTALLER_BINARY_WITH_APPENDED_OVA

   ## TODO: refactor variable name
   VERSION_FULL=$(basename "$binary_image_ova")
   export VERSION_FULL

   cd windows

   cd Whonix-Starter
   ./build_on_linux_for_win64

   cd ..

   cd Whonix-Installer
   ./build.sh

   true
}

main() {
   if [ ! "$dist_build_windows_installer" = "true" ]; then
      true "${bold}${cyan}INFO: Not run with '--target windows' switch, skipping $BASH_SOURCE.${reset}"
      exit 0
   fi

   if [ "$dist_build_type_long" = "workstation" ]; then
      create-windows-installer
      return 0
   fi

   true "${bold}${cyan}INFO: dist_build_type_long is not workstation, skipping $BASH_SOURCE.${reset}"
}

main "$@"
