#!/bin/bash
PID="`pidof firefox`"

if [ "$PID" = "" ]; then
   echo "Starting TorBrowser"
   ~/tor-browser_en-US/start-tor-browser &
else
   echo "TBB is already running"
fi



while [ "$PID" = "" ]
do
   PID="`pidof firefox`"
   sleep 3
done

echo "Opening aos Readme"

~/tor-browser_en-US/App/Firefox/firefox --profile Data/profile -new-tab https://trac.torproject.org/projects/tor/wiki/doc/TorBOX/Readme

