#!/bin/bash
# Safe as /home/user/aos/aos_modifyiso

# See LICENSE in root of aos source for copyright, license and authors.

script_help() {
echo "
# aos_modifyiso available commands:
#
# -create
#  creates preseed.iso
#
# -delete
#  unmounts and deletes ISO and build folder
#
# -help
#  shows this help
"
}



# Enable debugging.
set -x

# Exit if there is an error
set -e

USERNAME="user"

# Thanks to
# http://askubuntu.com/questions/122505/how-do-i-create-completely-unattended-install-for-ubuntu



##############################################################################################
# error_handler
##############################################################################################
error_handler() {
echo "
#!!! ERROR in aos_ModifyISO !!!#
#!!! ERROR in aos_ModifyISO !!!#
#!!! ERROR in aos_ModifyISO !!!#
"

echo "aos_modifyiso: unmounting iso..."
unmount_iso
echo "aos_modifyiso: Done."

touch /home/$USERNAME/aos_binary/AOS_BUILD_FAILED
exit 1
}



root_check() {
######################################################
# Checking script environment
######################################################
# Check if we are root
  if [ "$(id -u)" != "0" ]; then
       echo "ERROR: This must be run as root (sudo)!"
       exit 1
  else
       echo "INFO: Script running as root."
  fi
}



##############################################################################################
# mount_and_copy_iso
##############################################################################################

mount_and_copy_iso() {
   trap "error_handler" ERR INT TERM

   mkdir -p /home/$USERNAME/aos_binary/original_iso
   # Ubuntu:
   mount -o loop /home/$USERNAME/aos_binary/ubuntu-12.04-server-i386.iso /home/$USERNAME/aos_binary/original_iso
   # Debian:
   #mount -o loop /home/$USERNAME/aos_binary/debian-6.0.5-i386-CD-1.iso /home/$USERNAME/aos_binary/original_iso
   mkdir -p /home/$USERNAME/aos_binary/modified_iso
   cp -rT /home/$USERNAME/aos_binary/original_iso /home/$USERNAME/aos_binary/modified_iso
}



##############################################################################################
# unmount_iso
##############################################################################################

unmount_iso() {
   umount /home/user/aos_binary/original_iso
   rm -r /home/user/aos_binary/original_iso
}



##############################################################################################
# modify_iso_general
##############################################################################################

modify_iso_general() {
trap "error_handler" ERR INT TERM

# Please, if you make changes to this file, document your changes.
# Preseeding is not the most bugfree or easy thing.
# Changes my break it.
# If you make changes, please test if they are working!

# lang
echo en > /home/$USERNAME/aos_binary/modified_iso/isolinux/lang

# isolinux.cfg
cp /home/$USERNAME/aos/isolinux.cfg /home/$USERNAME/aos_binary/modified_iso/isolinux/isolinux.cfg

# ks.cfg
#
# Create kickstart configuration file.
# Due to bugs in Ubuntu preseed we have to combine kickstart with preseed.
# Bugs such as choosing the language does not work with preseed alone.
cp /home/$USERNAME/aos/ks.cfg /home/$USERNAME/aos_binary/modified_iso/ks.cfg

# preseed.cfg
cp /home/$USERNAME/aos/preseed.cfg /home/$USERNAME/aos_binary/modified_iso/preseed.cfg
}



##############################################################################################
# rebuild_iso
##############################################################################################

rebuild_iso() {
trap "error_handler" ERR INT TERM

mkisofs -D -r -V "ATTENDLESS_UBUNTU" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o /home/$USERNAME/aos_binary/$ISO_NAME /home/$USERNAME/aos_binary/modified_iso/
}



################################################################ 
# -create                                                      #
################################################################ 
if [[ "$1" = "-create" ]]; then
   root_check
   mount_and_copy_iso
   unmount_iso
   modify_iso_general
   ISO_NAME="preseed.iso"
   rebuild_iso
   echo "BUILD INFO: Done, if success, next stept should be sudo ./aos_createvm -tg-pre"
   exit 0
fi



################################################################ 
# -delete                                                      #
################################################################ 
if [[ "$1" = "-delete" ]]; then
   root_check
   unmount_iso
   rm -r /home/$USERNAME/aos_binary/modified_iso
   rm /home/$USERNAME/aos_binary/preseed.iso
   echo "Done."
   exit 0
fi



################################################################ 
# -help                                                        #
################################################################ 
if [[ "$1" = "-help" ]]; then
   script_help
   exit 0
fi



################################################################ 
# no option chosen                                             #
################################################################ 
echo "No option choosen. Use -help for help."
touch /home/$USERNAME/aos_binary/AOS_BUILD_FAILED
exit 1
