#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"

source ./help-steps/pre
source ./help-steps/colors
source ./help-steps/variables

if [ "$dist_build_virtualbox" = "true" ]; then
   cleaned_up="true"
   ./help-steps/delete-vbox-vm "$@"
fi

if [ "$dist_build_qcow2" = "true" ]; then
   cleaned_up="true"
   ./help-steps/delete-qcow "$@"
fi

if [ "$dist_build_utm" = "true" ]; then
   cleaned_up="true"
   ./help-steps/delete-utm "$@"
fi
