#!/bin/bash
# internally used by whonix_createvm

set -x



copy_gateway_pre() {
   #########################
   # Whonix-Gateway Copy Pre  #
   #########################

   # Copy interfaces into VM.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/etc/network/interfaces "$CHROOT_FOLDER"/etc/network/interfaces

   # UGLY WORKAROUND:
   echo '#!/bin/bash

        echo "whonix_firewall not active during build (whonix_internal_install_script)."
        exit 0
   ' > "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall

   # Copy VM script into VM image and make it executable.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/local/bin/whonix_internal_install_script "$CHROOT_FOLDER"/usr/local/bin/
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix_internal_install_script

   # apt.conf currently empty and not used for anything.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/share/whonix/apt.conf "$CHROOT_FOLDER"/usr/share/whonix/apt.conf

   # Copy arm wrapper script to start arm into VM.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/local/bin/arm "$CHROOT_FOLDER"/usr/local/bin/arm
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/arm

   # Copy Whonix helpfile into VM.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/local/bin/whonix "$CHROOT_FOLDER"/usr/local/bin/whonix
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix

   # Create folder for vidalia.
   mkdir -p "$CHROOT_FOLDER"/home/user/.vidalia
   chown user "$CHROOT_FOLDER"/home/user/.vidalia

   # Copy Whonix-Gateway leaktest script into VM and make it executable.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/local/bin/leaktest "$CHROOT_FOLDER"/usr/local/bin/leaktest
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/leaktest

   # Just a marker that it is an whonix_gateway. Used by whonixcheck script.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/share/whonix/whonix_gateway "$CHROOT_FOLDER"/usr/share/whonix/whonix_gateway

   # Setup Vidalia to use Cookie Authentication.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/home/user/.vidalia/vidalia.conf "$CHROOT_FOLDER"/home/user/.vidalia/vidalia.conf
   chown user "$CHROOT_FOLDER"/home/user/.vidalia/vidalia.conf
}

append_gateway_pre() {
   ##########################
   # Whonix-Gateway Append Pre #
   ##########################

   # appendto_sources.list
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/etc/apt/sources.list
   done < "$WHONIX_SOURCE_FOLDER"/whonix_gateway/etc/apt/appendto_sources.list

   # Append Whonix help/welcome message to .bashrc.
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/home/user/.bashrc
   done < "$WHONIX_SOURCE_FOLDER"/whonix_gateway/home/user/appendto_.bashrc

   # Append to sysctl.conf.
   # IPv6 off, Forwarding off, fs.file-max to 100000, vm.swappiness to 0.
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/etc/sysctl.conf
   done < "$WHONIX_SOURCE_FOLDER"/whonix_gateway/etc/appendto_sysctl.conf
}

copy_gateway_post() {
   #########################
   # Whonix-Gateway Copy Post #
   #########################

   # No need to restore torrc. Will be replaced.

   # Backup torrc inside VM before replacing it with Whonix version.
   cp -n "$CHROOT_FOLDER"/etc/tor/torrc "$CHROOT_FOLDER"/etc/tor/torrc.backup

   # Copy Whonix firewall script into VM.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/local/bin/whonix_firewall "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall

   # Copy Whonix torrc into VM.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/etc/tor/torrc "$CHROOT_FOLDER"/etc/tor/torrc

   # Autologin, copy tty1.conf into VM.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/etc/init/tty1.conf "$CHROOT_FOLDER"/etc/init/tty1.conf

   # Delete /etc/resolv.conf to work around some strange bug
   # "Operation not supported While reading flags on" while
   # trying to set -i on /etc/resolv.conf.
   # Override trap function, if /etc/resolv.conf does not
   # exist or is write protected (+i).
   rm "$CHROOT_FOLDER"/etc/resolv.conf || true

   # Remove write protection from resolv.conf.
   # Override trap function, if /etc/resolv.conf does not exist.
   chattr -i "$CHROOT_FOLDER"/etc/resolv.conf || true

   # Delete file to keep care of potential leaks.
   # Override trap function, if /etc/resolv.conf does not exist.
   rm "$CHROOT_FOLDER"/etc/resolv.conf || true

   # Set nameserver to localhost.
   # iptables redirects any of Whonix-Gateways DNS requests to DNS_PORT_WHONIXG
   # Do not override trap function, this step is essential.
   # resolv.conf
   cp "$WHONIX_SOURCE_FOLDER"/whonix_gateway/etc/resolv.conf "$CHROOT_FOLDER"/etc/resolv.conf

   # Add write protection to resolv.conf to prevent DNS leaks by getting
   # edited by DHCP.
   # Do not override trap function, this step is essential.
   chattr +i "$CHROOT_FOLDER"/etc/resolv.conf 
}