#!/bin/bash
# internally used by whonix_createvm

set -x

copy_workstation_pre() {
   #############################
   # Whonix-Workstation Copy Pre  #
   #############################

   # UGLY WORKAROUND:
   echo '#!/bin/bash

        echo "whonix_firewall not active during build (whonix_internal_install_script)."
        exit 0
   ' > "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall

   # Copy VM script into VM image and make it executable.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/whonix_internal_install_script "$CHROOT_FOLDER"/usr/local/bin/
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix_internal_install_script

   # /usr/local/bin/hiddenserver-install
   # TODO: Needs documentation, revision, gui, menu integration.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/hiddenserver-install "$CHROOT_FOLDER"/usr/local/bin/hiddenserver-install
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/hiddenserver-install

   # Copy the torbrowser update script.
   # TODO: Needs documentation.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/torbrowser "$CHROOT_FOLDER"/usr/local/bin/torbrowser
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/torbrowser

      #########
      # xchat #
      #########

   # Prepare /usr/share/whonix/xchat2 folder.
   mkdir -p "$CHROOT_FOLDER"/usr/share/whonix/
   chown user "$CHROOT_FOLDER"/usr/share/whonix/
   mkdir -p "$CHROOT_FOLDER"/usr/share/whonix/xchat2
   chown user "$CHROOT_FOLDER"/usr/share/whonix/xchat2

   # Copy xchat configuration files.
   cp -r "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/share/whonix/xchat2 "$CHROOT_FOLDER"/usr/share/whonix/

   # /usr/local/bin/xchat-reset
   # TODO: Needs documentation, warning, gui, menu integration.
   cp -r "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/xchat-reset "$CHROOT_FOLDER"/usr/local/bin/xchat-reset
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/xchat-reset

      ############
      # leaktest #
      ############

   # Create the leaktest folder.
   mkdir -p "$CHROOT_FOLDER"/usr/share/whonix/leaktest

   # /usr/share/whonix/leaktest/simple_ping.py
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/share/whonix/leaktest/simple_ping.py \
"$CHROOT_FOLDER"/usr/share/whonix/leaktest/simple_ping.py

   # /usr/share/whonix/leaktest/exhaustive_ip_send.py
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/share/whonix/leaktest/exhaustive_ip_send.py \
"$CHROOT_FOLDER"/usr/share/whonix/leaktest/exhaustive_ip_send.py

   # /usr/share/whonix/leaktest/tcp_test.py
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/share/whonix/leaktest/tcp_test.py \
"$CHROOT_FOLDER"/usr/share/whonix/leaktest/tcp_test.py

   # /usr/share/whonix/leaktest/udp_test.py
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/share/whonix/leaktest/udp_test.py \
"$CHROOT_FOLDER"/usr/share/whonix/leaktest/udp_test.py

   # /usr/local/bin/leaktest
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/leaktest \
"$CHROOT_FOLDER"/usr/local/bin/leaktest
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/leaktest

   # Just a marker that it is an whonix_workstation. Used by whonixcheck script.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/share/whonix/whonix_workstation "$CHROOT_FOLDER"/usr/share/whonix/whonix_workstation
}

append_workstation_pre() {
   ###############################
   # Whonix-Workstation Append Pre  #
   ###############################

   # /etc/sysctl.conf
   # IPv6 off, Forwarding off, fs.file-max to 100000, vm.swappiness to 0
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/etc/sysctl.conf
   done < "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/appendto_sysctl.conf
}

copy_workstation_post() {
   ##################################
   # Whonix-Workstation Copy Post      #
   ##################################

   # /etc/network/interfaces
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/network/interfaces "$CHROOT_FOLDER"/etc/network/interfaces

   # Delete /etc/resolv.conf if it exists.
   chattr -i "$CHROOT_FOLDER"/etc/resolv.conf || true
   rm "$CHROOT_FOLDER"/etc/resolv.conf || true

   # /etc/resolv.conf
   # We do not need chattr +i for Whonix-W resolv.conf, because
   # dhcp is never used and resolvconf was uninstalled.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/resolv.conf "$CHROOT_FOLDER"/etc/resolv.conf

   # firewall script
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/whonix_firewall "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall

   # /etc/cron.daily/whonixcheck
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/cron.daily/whonixcheck "$CHROOT_FOLDER"/etc/cron.daily/whonixcheck
   chmod +x "$CHROOT_FOLDER"/etc/cron.daily/whonixcheck

   # Enable sub pixel rendering.
   cp -n "$CHROOT_FOLDER"/etc/fonts/conf.avail/10-sub-pixel-rgb.conf "$CHROOT_FOLDER"/etc/fonts/conf.d/

   # Ensure folder exist.
   mkdir -p "$CHROOT_FOLDER"/etc/init/

   # Prepare dirs.
   mkdir -p "$CHROOT_FOLDER"/home/user/.config/
   chown user "$CHROOT_FOLDER"/home/user/.config/
   mkdir -p "$CHROOT_FOLDER"/home/user/.config/openbox
   chown user "$CHROOT_FOLDER"/home/user/.config/openbox
   mkdir -p "$CHROOT_FOLDER"/home/user/.config/tint2
   chown user "$CHROOT_FOLDER"/home/user/.config/tint2
   mkdir -p "$CHROOT_FOLDER"/home/user/.config/libfm
   chown user "$CHROOT_FOLDER"/home/user/.config/libfm
   mkdir -p "$CHROOT_FOLDER"/home/user/.config/autostart
   chown user "$CHROOT_FOLDER"/home/user/.config/autostart
   mkdir -p "$CHROOT_FOLDER"/home/user/.config/gtk-3.0
   chown user "$CHROOT_FOLDER"/home/user/.config/gtk-3.0

   # Create backup of menu.xml.
   # cp -n "$CHROOT_FOLDER"/home/user/.config/openbox/menu.xml \
#"$CHROOT_FOLDER"/home/user/.config/openbox/menu.xml.backup || true
   # chown user "$CHROOT_FOLDER"/home/user/.config/openbox/menu.xml.backup || true

   # .config/openbox/menu.xml
   # cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/.config/openbox/menu.xml \
#"$CHROOT_FOLDER"/home/user/.config/openbox/menu.xml
   # chown user "$CHROOT_FOLDER"/home/user/.config/openbox/menu.xml

   # .config/openbox/menu.xml_howto
   # cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/.config/openbox/menu.xml_howto \
#"$CHROOT_FOLDER"/home/user/.config/openbox/menu.xml_howto
   # chown user "$CHROOT_FOLDER"/home/user/.config/openbox/menu.xml_howto

   # Copy default files to home.
   # Tint2 example file is Ubuntu specific.
   #cp "$CHROOT_FOLDER"/usr/share/doc/tint2/examples/icon_and_text_1.tint2rc \
#"$CHROOT_FOLDER"/home/user/.config/tint2/tint2rc
   #chown user "$CHROOT_FOLDER"/home/user/.config/tint2/tint2rc

   #cp "$CHROOT_FOLDER"/etc/xdg/openbox/rc.xml "$CHROOT_FOLDER"/home/user/.config/openbox/
   #chown user "$CHROOT_FOLDER"/home/user/.config/openbox/

   # .config/libfm/libfm.conf
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/.config/libfm/libfm.conf \
"$CHROOT_FOLDER"/home/user/.config/libfm/libfm.conf
   chown user "$CHROOT_FOLDER"/home/user/.config/libfm/libfm.conf

   # .config/autostart/whonixcheck.desktop
   # ~/.config/autostart is a freedesktop.org standard and should work cross desktop.
   # Create whonixcheck autostart.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/.config/autostart/whonixcheck.desktop \
"$CHROOT_FOLDER"/home/user/.config/autostart/whonixcheck.desktop
   chown user "$CHROOT_FOLDER"/home/user/.config/autostart/whonixcheck.desktop

   # .config/gtk-3.0/settings.ini
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/.config/gtk-3.0/settings.ini \
"$CHROOT_FOLDER"/home/user/.config/gtk-3.0/settings.ini
   chown user "$CHROOT_FOLDER"/home/user/.config/gtk-3.0/settings.ini
}

append_workstation_post() {
   ###############################
   # Whonix-Workstation Append Post #
   ###############################

      ###########
      # Restore #
      ###########

   cp "$CHROOT_FOLDER"/home/user/.gtkrc-2.0.backup "$CHROOT_FOLDER"/home/user/.gtkrc-2.0 || true
   cp "$CHROOT_FOLDER"/home/user/.profile.backup "$CHROOT_FOLDER"/home/user/.profile || true
   cp "$CHROOT_FOLDER"/home/user/.xinitrc.backup "$CHROOT_FOLDER"/home/user/.xinitrc || true
   cp "$CHROOT_FOLDER"/home/user/.gnupg/gpg.conf.backup "$CHROOT_FOLDER"/home/user/.gnupg/gpg.conf || true

      ##########
      # Backup #
      ##########

   # Create backup of gpg.conf.
   # Do not override. This is important.
   cp -n "$CHROOT_FOLDER"/home/user/.gnupg/gpg.conf "$CHROOT_FOLDER"/home/user/.gnupg/gpg.conf.backup
   chown user "$CHROOT_FOLDER"/home/user/.gnupg/gpg.conf.backup

   # Create backup of .gtkrc-2.0.
   cp -n "$CHROOT_FOLDER"/home/user/.gtkrc-2.0 "$CHROOT_FOLDER"/home/user/.gtkrc-2.0.backup || true
   chown user "$CHROOT_FOLDER"/home/user/.gtkrc-2.0.backup || true

   # Create backup of .profile.
   cp -n "$CHROOT_FOLDER"/home/user/.profile "$CHROOT_FOLDER"/home/user/.profile.backup || true
   chown user "$CHROOT_FOLDER"/home/user/.profile.backup || true

   # Create backup of .xinitrc.
   cp -n "$CHROOT_FOLDER"/home/user/.xinitrc "$CHROOT_FOLDER"/home/user/.xinitrc.backup || true
   chown user "$CHROOT_FOLDER"/home/user/.xinitrc.backup || true

      ##########
      # Append #
      ##########

   # gpg.conf
   # Must be post because gpg.conf has not been created by gpg
   # before gpg has not been run at least once.
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/home/user/.gnupg/gpg.conf
   done < "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/.gnupg/appendto_gpg.conf
   chown user "$CHROOT_FOLDER"/home/user/.gnupg/gpg.conf

   # .gtkrc-2.0
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/home/user/.gtkrc-2.0
   done < "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/appento_.gtkrc-2.0
   chown user "$CHROOT_FOLDER"/home/user/.gtkrc-2.0

   # .profile
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/home/user/.profile
   done < "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/appendto_.profile
   chown user "$CHROOT_FOLDER"/home/user/.profile

   # .xinitrc
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/home/user/.xinitrc
   done < "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/appendto_.xinitrc
   chown user "$CHROOT_FOLDER"/home/user/.xinitrc

   # .bashrc
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/home/user/.bashrc
   done < "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/appendto_.bashrc
}