#!/bin/bash
# internally used by whonix_createvm

set -x

copy_workstation_pre() {
   ############
   ## restore #
   ############

   cp "$CHROOT_FOLDER"/whonix_workstation/etc/polipo/config.backup "$CHROOT_FOLDER"/whonix_workstation/etc/polipo/config || true

   ###########
   ## backup #
   ###########

   cp -n "$CHROOT_FOLDER"/whonix_workstation/etc/polipo/config "$CHROOT_FOLDER"/whonix_workstation/etc/polipo/config.backup

   ###############################
   # Whonix-Workstation Copy Pre #
   ###############################

   # Copy VM script into VM image and make it executable.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/whonix_internal_install_script \
"$CHROOT_FOLDER"/usr/local/share/whonix/whonix_internal_install_script
   chmod +x "$CHROOT_FOLDER"/usr/local/share/whonix/whonix_internal_install_script

   # Copy Whonix helpfile into VM.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/whonix "$CHROOT_FOLDER"/usr/local/bin/whonix
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix

   # /usr/local/bin/hiddenserver-install
   # TODO DOC
   # TODO Needs documentation, revision, gui, menu integration.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/hiddenserver-install "$CHROOT_FOLDER"/usr/local/bin/hiddenserver-install
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/hiddenserver-install

   # Copy the torbrowser update script.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/torbrowser "$CHROOT_FOLDER"/usr/local/bin/torbrowser
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/torbrowser

   # Just a marker that it is an whonix_workstation. Used by whonixcheck script.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/whonix_workstation "$CHROOT_FOLDER"/usr/local/share/whonix/whonix_workstation

   # /etc/network/interfaces
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/network/interfaces "$CHROOT_FOLDER"/etc/network/interfaces

   # firewall script
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/whonix_firewall "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/whonix_firewall

   # cron for user user_crontab
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/user_crontab "$CHROOT_FOLDER"/usr/local/share/whonix/

   # polipo
   mkdir -p "$CHROOT_FOLDER"/whonix_workstation/etc/
   mkdir -p "$CHROOT_FOLDER"/whonix_workstation/etc/polipo/
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/polipo/config "$CHROOT_FOLDER"/etc/polipo/

   # polipo rss config
   mkdir -p "$CHROOT_FOLDER"/usr/local/share/whonix
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/config_rss "$CHROOT_FOLDER"/usr/local/share/whonix/

   # wpolipo whonix polipo wrapper for multiple http listen ports and multiple socks parent proxies
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/init.d/wpolipo "$CHROOT_FOLDER"/etc/init.d/wpolipo
   chmod +x "$CHROOT_FOLDER"/etc/init.d/wpolipo

   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/wpolipo-control "$CHROOT_FOLDER"/usr/local/share/whonix/wpolipo-control
   chmod +x "$CHROOT_FOLDER"/usr/local/share/whonix/wpolipo-control

      ########
      # skel #
      ########

   cp -r "$WHONIX_SOURCE_FOLDER"/etc/skel/ "$CHROOT_FOLDER"/etc/skel/

      ###########
      # desktop #
      ###########

   mkdir -p "$CHROOT_FOLDER"/home/
   # no chown...
   mkdir -p "$CHROOT_FOLDER"/home/user/
   chown user "$CHROOT_FOLDER"/home/user/
   mkdir -p "$CHROOT_FOLDER"/home/user/.local/
   chown user "$CHROOT_FOLDER"/home/user/.local/
   mkdir -p "$CHROOT_FOLDER"/home/user/.local/share/
   chown user "$CHROOT_FOLDER"/home/user/.local/share/

   # Prepare dirs.
   mkdir -p "$CHROOT_FOLDER"/home/
   # no chown...
   mkdir -p "$CHROOT_FOLDER"/home/user/
   chown user "$CHROOT_FOLDER"/home/user/
   mkdir -p "$CHROOT_FOLDER"/home/user/.config/
   chown user "$CHROOT_FOLDER"/home/user/.config/
   mkdir -p "$CHROOT_FOLDER"/home/user/.config/autostart
   chown user "$CHROOT_FOLDER"/home/user/.config/autostart

   # .config/autostart/whonixcheck.desktop
   # ~/.config/autostart is a freedesktop.org standard and should work cross desktop.
   # Create whonixcheck autostart.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/home/user/.config/autostart/whonixcheck.desktop \
"$CHROOT_FOLDER"/home/user/.config/autostart/whonixcheck.desktop
   chown user "$CHROOT_FOLDER"/home/user/.config/autostart/whonixcheck.desktop

      #########
      # xchat #
      #########

   # Prepare /usr/local/share/whonix/xchat2 folder.
   mkdir -p "$CHROOT_FOLDER"/usr/local/share/whonix/
   chown user "$CHROOT_FOLDER"/usr/local/share/whonix/
   mkdir -p "$CHROOT_FOLDER"/usr/local/share/whonix/xchat2
   chown user "$CHROOT_FOLDER"/usr/local/share/whonix/xchat2

   # Copy xchat configuration files.
   cp -r "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/xchat2 "$CHROOT_FOLDER"/usr/local/share/whonix/

   # /usr/local/bin/xchat-reset
   # TODO: Needs documentation, warning, gui, menu integration.
   cp -r "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/xchat-reset "$CHROOT_FOLDER"/usr/local/bin/xchat-reset
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/xchat-reset

      ############
      # leaktest #
      ############

   # Create the leaktest folder.
   mkdir -p "$CHROOT_FOLDER"/usr/local/share/whonix/leaktest

   # /usr/local/share/whonix/leaktest/simple_ping.py
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/leaktest/simple_ping.py \
"$CHROOT_FOLDER"/usr/local/share/whonix/leaktest/simple_ping.py

   # /usr/local/share/whonix/leaktest/exhaustive_ip_send.py
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/leaktest/exhaustive_ip_send.py \
"$CHROOT_FOLDER"/usr/local/share/whonix/leaktest/exhaustive_ip_send.py

   # /usr/local/share/whonix/leaktest/tcp_test.py
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/leaktest/tcp_test.py \
"$CHROOT_FOLDER"/usr/local/share/whonix/leaktest/tcp_test.py

   # /usr/local/share/whonix/leaktest/udp_test.py
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/share/whonix/leaktest/udp_test.py \
"$CHROOT_FOLDER"/usr/local/share/whonix/leaktest/udp_test.py

   # /usr/local/bin/leaktest
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/local/bin/leaktest \
"$CHROOT_FOLDER"/usr/local/bin/leaktest
   chmod +x "$CHROOT_FOLDER"/usr/local/bin/leaktest
}

append_workstation_pre() {
   ##################################
   # Whonix-Workstation Append Pre  #
   ##################################

   # /etc/sysctl.conf
   # IPv6 off, Forwarding off, fs.file-max to 100000, vm.swappiness to 0
   while read LINE; do
      echo $LINE >> "$CHROOT_FOLDER"/etc/sysctl.conf
   done < "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/appendto_sysctl.conf
}

copy_workstation_post() {
   ################################
   # Whonix-Workstation Copy Post #
   ################################

      ####################
      # /etc/resolv.conf #
      ####################

   # Delete /etc/resolv.conf if it exists.
   chattr -i "$CHROOT_FOLDER"/etc/resolv.conf || true
   rm "$CHROOT_FOLDER"/etc/resolv.conf || true

   # /etc/resolv.conf
   # We do not need chattr +i for Whonix-W resolv.conf, because
   # dhcp is never used and resolvconf was uninstalled.
   cp "$WHONIX_SOURCE_FOLDER"/whonix_workstation/etc/resolv.conf "$CHROOT_FOLDER"/etc/resolv.conf
}

append_workstation_post() {
   ##################################
   # Whonix-Workstation Append Post #
   ##################################

   # Not used at the moment.
   true
}