#!/bin/bash
# internally used by whonix_createvm

set -x

copy_backup_shared() {
   trap "error_handler_int_whonix_image" ERR INT TERM

   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/sudoers "$CHROOT_FOLDER"/etc/sudoers.backup
   chmod --recursive 0440 "$CHROOT_FOLDER"/etc/sudoers.backup
   chown --recursive root:root "$CHROOT_FOLDER"/etc/sudoers.backup

   ## Better no backup of localtime.
   #cp --no-clobber "$CHROOT_FOLDER"/etc/localtime "$CHROOT_FOLDER"/etc/localtime.backup

   ## Better no backup of dbusmachineid.

   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/rc.local "$CHROOT_FOLDER"/etc/rc.local.backup
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/apt/sources.list "$CHROOT_FOLDER"/etc/apt/sources.list.backup
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/default/grub "$CHROOT_FOLDER"/etc/default/grub.backup
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/network/interfaces "$CHROOT_FOLDER"/etc/network/interfaces.backup
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/hosts "$CHROOT_FOLDER"/etc/hosts.backup || true

   touch "$CHROOT_FOLDER"/etc/motd
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/motd "$CHROOT_FOLDER"/etc/motd.backup || true

   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/issue "$CHROOT_FOLDER"/etc/issue.backup || true

   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/inittab "$CHROOT_FOLDER"/etc/inittab.backup || true
}



copy_into_shared() {
   trap "error_handler_int_whonix_image" ERR INT TERM

   ## Delete old swapfile, only in case the script has run before. (Debugging only.)
   rm "$CHROOT_FOLDER"/swapfile1 || true

   ## /etc/motd
   ## rm to get ride of the symlink, in case there is any.
   ## http://wiki.debian.org/motd
   rm "$CHROOT_FOLDER"/etc/motd || true

   ## delete default symlink to "$CHROOT_FOLDER"/etc/dpkg/origins/debian
   rm "$CHROOT_FOLDER"/etc/dpkg/origins/default || true

   ## copy skel to user home
   cp --recursive --preserve "$CHROOT_FOLDER"/etc/skel/. "$CHROOT_FOLDER"/home/user

   ## Ensure timezone is UTC.
   cp --recursive --preserve "$CHROOT_FOLDER"/usr/share/zoneinfo/UTC "$CHROOT_FOLDER"/etc/localtime

   ## Copy
   rsync --verbose --perms --recursive --checksum "$WHONIX_SOURCE_FOLDER"/whonix_shared/ "$CHROOT_FOLDER"/

   ## /etc/dpkg/origins/default
   ## symlink is created by whonix_internal_install_script

   ## Permissions for /home/user get fixed by int_copy_gateway or int_copy_workstation.
}
