version = 0
commit_goodlist = []

[authorization."Patrick Schleizer <adrelanos@whonix.org>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 916B 8D99 C38E AF5E 8ADC  7A2A 8D66 066A 2EEA CCDA
Comment: Patrick Schleizer <adrelanos@kicksecure.com>
Comment: Patrick Schleizer <adrelanos@riseup.net>
Comment: Patrick Schleizer <adrelanos@whonix.org>

xsFNBFLYY+gBEACb5AqqsBuxzGlqSQZoua/CI/kr9YOagD9G8I+aBXoTUqyTSafy
JvamqxcV1mti0QKhyQsw43f340R9lGvdGTm7JhsESuHwbkAPxa6hOdjvNy//5NkK
N+wWUm6PGiAmLmgxYp69PHMUzSkKeMIlOxEINFlvnkAsB945Zm1mEZcWiSIQEpgd
crfi8B0CKw/9hzHoQZpvc9Jt9ZeWlZOQR/vowz0Mb5vGT9IwMVoVjmdDJF4K/Nuo
cj9PrBOfzS1UBtgaornkddCVYvOSr2YWu1baKtyf2JkLx1uCSU34kvyy8/11e3Rh
xmskoqvT/P7ChCHRxQTKNN4Zz/iB/OjlXWOA1e1E46NvIfxezMtz7smbV2WPk799
mXjqpZJWJirJWZAB6B4GDm1vc0K1qvWMKrdNHPu02To96KgYW8iHH0Vn+0jgz7ag
7ocLvgFxOZwDUc8qkWxPZBOUFClv1epW1UIGCsZ/OmHfpm6qTjUgLA6pijUEEYBs
i7gzKKg6wvt6UK19FYrtBk93H0rQN8eS48U5e45JGmvLVgb523uN+OOkkKuJIGOP
ue60lE4euUuKOSgGQKZPL8bAnz3YdpRVPacPzgYnMhns4m1fQFkhpmMAYN6YYl3P
Bs1PeuD70KXG3tKCX7IafPWFaVWyjzZo3qk+N4PXtZCp8YqPQyWS+LMA7QARAQAB
zSxQYXRyaWNrIFNjaGxlaXplciA8YWRyZWxhbm9zQGtpY2tzZWN1cmUuY29tPsLB
jgQTAQoAOAIbAwULCQgHAwUVCgkICwUWAgMBAAIeAQIXgBYhBJFrjZnDjq9eitx6
Ko1mBmou6szaBQJpeg30AAoJEI1mBmou6szazvkP/iEvsRhJL1j3PwsGL18x22qf
HPLhBUIN3/TN4O/6SBXDJfczq4ejUKdRRG2Pxyhfk8WQWm/QQv4WgCeHrhHbWwtf
kNpxknz5rLxND7albhj4hezzYz3j+MZlcF2Xah+5OizORhSyneiXXmynJ60e/hVv
VtvlLUdTr8Wd8xjdk+Mrobwb+lkrSjKlRRlIT7Z2tjWQH5R+BBY27imF7pW/bRzh
7tS/raXupRA7h0HhoTazdrKGOTNxuQrukhquEeVktVPiogyQPy2RGwJM5eAArf5P
ZiDtk8isCC4fmp+WrqDjNitdTCKtpAq0Ykgsnu1RFNMhVs4sJrIW1CsMtiUY/QD7
uYRl/My/IzZGuB5I8zt7+qStoCrPG4TxsuaJjXuvIz2o9JQPmnGTFxe9yt+XRjmU
LVmmViRMIXEVqTD/PcNP6rFJBtCpmYpLbcfaLHZawCVHVvWBuTdUV/y/CLgu6rdr
YWYxjH1wGWfDzK1MZQ9mmAw8T7ji8GCxxO06j1Aj/MPvqXgebgn2x+W/MPqC8fVI
j14LqKHxp/jcjAeLD3gLRkxF6W4YZVkKqNLRpODLbBkB2QOiorrvnjbtxulApKz0
RZO3fiCVFWx5E+X79wUSzMi6PFXhwIYBaQ+cHn9I+Bt+gqtGtNMmQESFizwclvfF
5zCb+zuK4xU8Fi63YTgfwsGUBBMBCgA+AhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4B
AheAFiEEkWuNmcOOr16K3HoqjWYGai7qzNoFAmi9NNwFCSEsBfQACgkQjWYGai7q
zNoTHA//XA17vxw5pYBiVocwTFPq4X3HTc01o2DcU6DqkmVj1h6cGz4yMZ3bJntv
1EThwIOa+Z1+3Za+ZYyO5nz4gNkmiUIKTz+exzmRYmayM+vqenmqhVMjPAnENDlx
mBiCelMlKLiGqZyDX7OI+5a6o0WW5QA4emeXB+NbvmUuA3hIseh9/0su/NTbYNy3
8L0dFyYREL5pz8ahOMGQ7qCfln6XEnErM2SDnOspFDlRMrxUT5ZuNvxRa1A+7p+C
cMLA7ZYNh0p5QILa4daCH3dNhnQ+jhIV/MqhX54zo3we/8Wi7pFZAdlCZ55qeIs3
7HFk1sfFaZBbrQ21JCxlqyD0cilcuixyD6dresj3ViYKZjtKa18c1IY77VEYbEi4
nYmmrtzcOPVKAC47GYvj9M9rVC0SWf5MNidF9bq1sjEZl5qfReLZ/YK6E2dqI2gQ
VE+BCWN3R+JqUd7excEMW31v/pJWCsvn65FiBOMkqY/8WX5WZUnhbAuGBckNKFyc
85ayPWhgRq/hWjmoeKFGJ5b3ik2PqA3jAskKLsU9v1mW3dwJ0LKHPwTSMQZTAtPe
MgKHwvlQOUa+fJS2AC9u9oahOeIK8sNccK2tD8VZnpC/MwbsXjr2q2mo8kn+KYGj
mxH0B/3uIBNWz7BeyOvowEicGndUtR0tz2BQAsWMrsfUxGl9AjfCwZQEEwEKAD4W
IQSRa42Zw46vXorceiqNZgZqLurM2gUCX5LVhgIbAwUJFpsIjwULCQgHAwUVCgkI
CwUWAgMBAAIeAQIXgAAKCRCNZgZqLurM2tlrD/4iB4RnzrzXX7piHhw1kMkQiQf4
3CSmUfBA3hGFshBDFVQzX1b9RVTov2X6DN7UlODst+Bt5Pkp3ujbDCeDpiDA1/lA
NixIz8BuVsWLcFAokHyn70/jUGODeUr2el/e8n1Q+Cgyv5leKDQXSqYqHageqM5U
t3IzpZOTxAlOQCXQgdEpZrFP43AJg5/BKnGkIIQd16Q/EmN/6Jm896dPNuvSk3gj
u8Kzvg3f24Sc9TGbWlvSti+OC8np8bdPPg/GK87DccIxrXTc5wUsKld5yIwV4Bfg
MTBLQGcjIFKfh8BwOHAIYTzTsy+F50WeJ1GCV5vMLQ3LttcfN5/wArH+NfIoeaH7
OQPq1COQt4/i0UoQ8uOCZWEhMGUcQnPw9BBraTVTITD5E5SB1GqD+1RCrJqwfJ2g
9gTjIeb+6wywvl5tUV3kO/DWqzhAJp9HbixtxSFO6Qk3g6PCWe7ZnpRtA3c6/rZ9
L84z7rRlWOOO1K+p7g29vctPaYH4pGChe1FkLtfxkEfudbGslzaEOMtU/X0YpCQQ
62kGbURJ4znJq8GdRXrfrgiKDnAY/H0+awIsmHT36bks9b6wxUM2mPbKBbbtfj3d
c+RkDAKhk5PyPWFL2m+I3vl/SYdQ03C8c5nk3EsrSvBndIkOEEiWJKvvHfBmRyXy
yzsFs+q6McNECp1VTc0oUGF0cmljayBTY2hsZWl6ZXIgPGFkcmVsYW5vc0ByaXNl
dXAubmV0PsLBjgQTAQoAOAIbAwULCQgHAwUVCgkICwUWAgMBAAIeAQIXgBYhBJFr
jZnDjq9eitx6Ko1mBmou6szaBQJpeg31AAoJEI1mBmou6szawXwP/iPv+iH82Txm
rLDlWqVzuK1VbaSUjvfxX3matiAdd1/JxknItoJNTdpvkEiD3xOAEQSDSm0GAPgs
tVPZ8qmKOaAC1xNOEssf2B4doKxcr1T/riGCL1roZFY84w/3IUGv5GYcsfImzSnu
szofCposcV2qwlcw/UB0foJRNjxl6ZX2oliR5GNRdtDuo1ia4Db9dpAJD0KwXaM3
kKb2d1x/DZB1CNBLHtI3aSdlOval0BkucRl5C37SzU+c6QV27v9Mx+Tmj2UPfGKl
3M62WK1wV3ixQd1OR2GfIrTPb3H/Ogneu3gO1RQHUKdj2GQELqS0WDO2zNatS7+m
4bkfbGm9nT7MAqnzLtuWxad0Zi4wm81prD4McQC6QzRFuQip99xlYN+x/+8+wJT8
o0pqNAN2AoT6OYlRdobwIBfxXlS9oypll+/qErplscwbmT7D3NahNgFfGDWRa28H
qfZlVyrdrsetOwR6QrH/ya/83wYL+3N1ufiv1pqn3XY9jDyYrY9iTClz5w30fh9V
jXG19kFhdaGt9CSJynM8BcaSh7sL3eyUinTXvDJ4M+1xKOrnBf2f10tk4hatwO0U
4HuTyERrVvKFkxpZ/93EpYgZ8ViaVYiELuf9HF0rXSxL1z2CadSJ3RlG2AjiL2Nf
qD6kb5ptt5KDW4m1Nn9/r6eWdUTFkL5rwsGUBBMBCgA+AhsDBQsJCAcDBRUKCQgL
BRYCAwEAAh4BAheAFiEEkWuNmcOOr16K3HoqjWYGai7qzNoFAmi9NNwFCSEsBfQA
CgkQjWYGai7qzNrlWBAAgXay0/9yVELlQMMHJR2dTu7fR8Hf+Zcc7p/Oh0YYZXfA
Ew+0LoxixcgZPmHWzl23jw8XpKzhWPwv4LqRUziXQMcCe6oTNQte5pwGNw4HxsO9
0LspCnjKiU8lrKQqJ5hqMgylhDhPfPCxgT63SrV7ysw9hzyNYXB7KRn73lQCjhAs
9JrzYd8dgmi/iMNvq9oolln0q+1ZC+ZnRSxKN/NGX54FS/g3pIQ8SpLe2az11/Z/
MB7jBWTXRc5joRDOqvkV23BGg1TWp3iVuwcLIHpCY8/EGnUJwQ6VpXkGqNs5JQC0
UYGheoub4MTz8vBoki9bBW1ra+9d8hN+nlgh0XnO/aswKKZlvsfnuaOKClR0WcBM
TEk32LOs0Btjabf5P+I61jnVAR/it2k/SsVEUq77Y+aFMQWRY7rpH2rGQtLViscA
rRrOOOUJM88bHhb5Etdv5X4Oy8aLFDlWOxgSG7wTxE/YEVo/CNMiFzdmiKrn4EX9
gvDNqOk70f73uMZIOuYsKdBFrAZ7MS3jVXBezlQ6L61cU2I1WdNyCDHj11QZZpWs
O9nqUM9So/Iy+YErp/4/Lls+5rC8kRON5PbvSUxHB+EbwfKpnAUfGNSb3kSd0WnU
i2My0Iu8wDmFhH+nQoYCKvt1cYTdwuefGRyOa5FMDisXpXcmIS6Irf6cwXaPRNrC
wZQEEwEKAD4CGwMFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AWIQSRa42Zw46vXorc
eiqNZgZqLurM2gUCXiw3dwUJFpsIjwAKCRCNZgZqLurM2hpLD/4qt9HrmkpZUQrX
cd8obQ8TbqR82x4+KuDFR9I5k0YCDiz/pO/s+Mt17mYtxpuIRjgSRcVMzEcwxChp
iIlSJqjt4RHcNEDZ/DXT0IV8tqcVuJYDms3b1aKjZg9HEQJAx5o1GHenG/dH4o1H
W553QJMHgam2FwjcE7uWLEmVtsbn+SHwFARi7v06LwUrWeSzRmRXT+EnS1jjNyZm
B6u9/av+DcH3wnZOnEnTQXVVlIcpuwLRPGWFYNPCLCTfv1+EvjR66OW9sesO9JGu
YLwE998Zris7Z2aNx54ATXFStNXAoqAHGl/SCPnjRUoWAAn3orsUbWTVO957znCP
jEHmO4J5BfcvTeSczN6RQZA7wDqVOegwTGKYXlgYbKa5iXu2GmpDggmpvGQZDCZu
RJQ8mLE9mG4f/B/6SWQw+pWaWSpIlEpNj2ggUTF/yKFYIWGb6Q3oap2F8idSNII4
hyrE0meXExRxxKVTebK4NHTeuZVD7rj7eubQURSNjxWmjGM+rKSXI0DeS6sntqxK
VWnArBRZjWQUi0qiFuI2uRfiu5LrehBVW9It6+MzKhib/jD2n6kE3n4NGiYqw2Sv
IewXq8xGVDWo25s14WRMnZHgalhWzt1LNUA3SMr4t9n6qDVOmnPHVyeGOXLh3Ekx
HeTwTDCXtZfwa8YF4mjGSyxYlscG7cLBlAQTAQoAJwIbAwULCQgHAwUVCgkICwUW
AgMBAAIeAQIXgAUCVxTo0AUJDaKGYQAhCRCNZgZqLurM2hYhBJFrjZnDjq9eitx6
Ko1mBmou6sza+poQAILHN0tydem9f7sYq+wPKs/KeEA8fjndpiEBs4SGEKiHG+os
J+d4a58P8ECdKYDAN9HjV5ytj5ojrWOPXm638YBnt4cS1x2TT7Vn8losSmc1b7wV
G6lY1dBK1U6npIqs+VKDx7syZczHJjBRNDQkZ3Pu/qidXndMijw6iBcqrT1t8Ckw
4EwwjJrjnKTgYjJrZqPCgzSGoImBzfQtsKlMqVX7gQGAlnGlwBhgqEXOemrBsyk2
b6yHvEPuDxP5lmTGnHtBJvvVW0Qh/QwQvInsEb0Mte/l2XyzXChzqBzmhePRpPvB
ECjhiI4U0in7mrsT8OJgr7K8dJZrXDFfp0TmobuFfGuy5rtdL+zZ/bB6MxhjxS80
3beivMHraYoEevGIy3WAHIiSLQIBN9ZfSnQl6e2HtPQVj5oTALrOWkRqGzUUvp9n
jtTdK+U8wFSnO+/sYJtLZw4LjH3PfZg4m6TQF6bDEhjyGWk4Mk8PX78mRBYUL25a
w9nfcp7HYxoMWvR1cS0qU47VITi8ZjMAyOUDgrCNxHaernru1EE+khLFvdm8z3k0
beViLNgf5OPUk7SSvfSeI/37/INdJVWDRgu4K1TPRLVi54YzsDCcNlnPgEOKIK09
a+KkQWtV7DaNwxEaPE194/jt84UchM81RrJZfdxfjz/3rGo0vFwW/pry9uaXwsGU
BBMBCgAnAhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheABQJUMe+7BQkFG/LKACEJ
EI1mBmou6szaFiEEkWuNmcOOr16K3HoqjWYGai7qzNoZqg//XUl9y0hKoM775ktj
0qkN0lDPMGz57i+CvZLUr6IKQB+aUJgcnXrJxkNvc8IdDOuuV/alX57PIgOK5iAK
ZknUsOkqA8x5TdIE/G2hca5GzJlsHhB4A6B+GDc9rS5FBSkDgM25dWcHlEnm6F62
WBgLzPwS9YtvEqcKUwIpdBFJXVdU+YT9aopVgto5juYMJKp3SXxM36Qqn252cDuD
0s/GSw+gWG8Cwih9ikh+ZDkUlPhqzfYCqdo+R0gJq3+L9ksuJ3mHWhzAAxH4oG/U
/tumRf6OzVcO4oNSbkR+ewhfTggr9RA+io3gb/PRRRrnq3KfhVs8mJ+n7b65YtSJ
Ii9aCoY5BS8QGcQ8KEAyns85OOZ0kNcovY4AXlsuCbqcmWrdPC4sffECc29HqTxQ
h+j1IdxKZY7trK58zCcjB+RSFVNDRbbbeEv8PXOBjBLPkdWTb994gcqujr8HvNJL
aYwk5Xwc1Iy/mbNgbnNxRgD/QTt0X223nymOBB+mFQXXmcK0rdIW45hRncGDUkSL
12ciw0qjnomvk4qFG6j1RWY+e/sUiUrkaDx/SPT1oV83IF7OCqm+A6jQivUr/Uy1
3ll3rwlX3TFn7IIPZKv7XY/bYPNC8zgfrFrGUTyXLUia4vAyyItYuHfeQw0qI4lv
1qjt+c3HDbEyJl0AZz9yy+TWxmzCwZQEEwEKACcFAlLYY+gCGwMFCQHhM4AFCwkI
BwMFFQoJCAsFFgIDAQACHgECF4AAIQkQjWYGai7qzNoWIQSRa42Zw46vXorceiqN
ZgZqLurM2kW9D/9DCGN4clnyXlhsIXMYwNb1Jzl5T4RUlpDZCT8dyEQCeTvKjLnS
IIP6x3gXWfSZ3sg+73nP+Hu/m6HCYYOUBmThYFN4NkxTayvCmSglGc2WNrzuBYHQ
NGtIW7P2iPGvnfYfX8UnaP6CYWyGtgytNRCgqaXXnwd/K9d01nTlvATxQ2Hn0WOX
9X7k4xAmmL4RCJNU8afCpOH9fWuiutEhGJgHb8/q5u1CKMH8WByhGxmLa7e7Qu23
Bwhu/vk+VNTvqo5zp4a+Jl+QhIObMRL5iSDFGFyS/vahteX3bge/q2Ac9kzbM6Sk
EOYdhT/g9iQhyS9a1EhZEySZdSVOyZ57pA+YDLU/3hbo6Gm5g/VAAlu1opScc3pD
o+WcYlEzzvY/m4mDhc5uuylzCbcS03jVDRNo+oEb1afXaA2Z+Ug2WlDPpb0aN8kc
k0n4MtN29WfUEq6iZkwoB+Z/WcASI02VtxD1SAe50Kg0ySOHf+5Lyd5mLD6VhlZ+
aBaB6SYVy7nd0YDz1WykH6SSvZxW2XV/yAqW3X7LNSmmKlriVNaqomULW5BxJuMN
6YTdFmmbB0iF0eoiXLGRCBf+4YC2XutNC5trgnZA83xv2tzrOYt54Rv2r3TrTR6e
yKyWMsF3B2yKjvDm5NjXngm/0yItic5fIy7aS0OoGu+Crlcs9uvsL8Ii7c0oUGF0
cmljayBTY2hsZWl6ZXIgPGFkcmVsYW5vc0B3aG9uaXgub3JnPsLBjgQTAQoAOAIb
AwULCQgHAwUVCgkICwUWAgMBAAIeAQIXgBYhBJFrjZnDjq9eitx6Ko1mBmou6sza
BQJpeg31AAoJEI1mBmou6szawsUQAJEYu3wIaRmb74rQWCaypdjyAol5PIEsb/wl
Zl6biPUs+qx46J6wVdxD2mJGQKGKWfv8TKUVLg7rAEZNZxi+vQp+nj9ucLy/A9db
+yvffrniS7Or57Tuk5Zad+0zoGBoB9hoMVRSUrRmDmgPmPhiVqKenO1cRw9JhSFo
ZMc8va7A8pzQ6zyd5bT3bQC6Rjo10jnr2SxGIWLG//2+I4vbmbkEZs+WLMyZa5nX
V0oChuI5Jzs7etpfqyKYOic5k6zBf8cft3v75OmKcIBoOO4vLqjmRx6JtF528ri3
jDCiDSPCm39vvqAc5hqyKBETPo7LZvfiHDLUtPoziL5VrH1haW64v1PDGC8ksAeN
OUWA6Hvds9dtMys7pcLWP2ZhQqNjGFGWqNDTHgn7oijuwCOjtAABJ+OxT6xsRYPI
scbEDoCkM+na31TLijvHlOgooyvYbyt+FmB+9+wtaSStJYVQq7W+lW9O6vdQEyA6
X5w8MccfGpDzsbzwsmTBVSA65eVDhxv380MedOVX+4JEf1b6EXvPdJYhT4nWKt2a
TL1WxFuUi87zoK4fdYuJiTN4+LRyeYhwv0q7bEovOpqP4/2vMGcagYjPgMv/B/9Y
PzXrotWPRPUDD36tybGwWp8BEpb63E4JrGH1boFdA3TKElXQB16++4t6k0CKGD2o
0aZ/kSFfwsGUBBMBCgA+AhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAFiEEkWuN
mcOOr16K3HoqjWYGai7qzNoFAmi9NNwFCSEsBfQACgkQjWYGai7qzNospQ/9HdDh
4scVSa+iNr2UO8/nPMz4Tx5uwZqrfACJwVWkS/Q4qTAjJ8+B1gjxNEQD5N9YuToL
wJEHAQKDw11PD/jMAKd+uD52ehOsc4gJX805glb+uVx6kM/b/X5R6k2QpiG7InCh
RSoVnETO8hdDv2+X4SLGcahTwx3zQOplGsUHM5VLgAkSYdO4mRMcql+nszWX932+
RsqkGjxYgQ6OMm70V8wnFSvdv4Gum7DUa1DwyTVBs+y8l67A2s5hXxKs54n2tzYA
mDQ9fbaDJ8I+j7USASSYK1RKOzp6Ip7x8BwIYdrMYMKZJuJLMT3ypVSCmw0PecAm
11q45ckj5r7dWt8FiQah5ILhd4JwACrw9Fvj+NbYOavBKW0Tm70bo0tlk66UMrKN
PgCz5fxD50ZidK51T408Av6Z0xdoZrml1LrEejcS570TP7a25SgPIwrNf9px7FeW
XA4Ee+JJ6eYmFAIhgfVJD5cHy+29/N3fMpMgNfAHIdmPXoZim2kZPQjVscV3Yo1+
54gNec4R2ZgddlqXuS1oPciXMWEk+urHxSUYCYXlx6V+lymLw2Guj0eNnTO72zL+
aoVWGd5yqhW6a0407j4iIrDyIrYtm8mjuGjvm94sVoh+nUBswZe1JMj0TUzFTSk/
JJ7PZhNz5+EYuEsMmoMaNiclSqNihW2zhNr0HmvCwZQEEwEKAD4WIQSRa42Zw46v
XorceiqNZgZqLurM2gUCX5LVdwIbAwUJFpsIjwULCQgHAwUVCgkICwUWAgMBAAIe
AQIXgAAKCRCNZgZqLurM2juYD/9yVsmRMBsmXnyd6dngvcZpczFbsudl+XGg+Peb
dbfpDxNhRIXjxUGXdO11GNtMZ4QXkGN/AMbcsLfvCuSB/iWIIms7sydVIZfoKdpr
AU5qlhMzNgOA/Dei312zqZIERkHMB4waTfHQYRxHtMn1PwefGWVYxIzipg8R8IPq
3guDt1ihx0cJ0k5t1XR7SbEj2Jl1DXYzedTjDSiubkuSzRBgV3a4Oaawdl3LFrBP
lmS19dAvZ47WbkvD/kmTlOL72zRVRbAR094fO6wmBXXOIl9EbUHb5UftofGhE4HE
S4Fz11cCUxvxHrtWX0q/yaFvrQso5rT9zz2WUbp+b89Vg3TOImliTDBgI0L1wIMd
YCqlyCcBOheyo3JX3JlmGUIODALfxUgXxRqAlkXbWkG1JQXiKMb5sqsLtkDYMRNN
a7tHiaCW3FhVUocmOH6BWorYgmSgVokqQxlIY58cYaRnWFa+Ag/4hBJULaDZNguy
jdpJBy0heHFevefE+Memzr8HVQgXHfTiL+4OI8YENGze9YOihnIeiZMABmyuB+Ab
QLa9idKby601tn70dGSA64HNeYr4eWmJpjkU5CRTXTeOHF/YTTehOCwPej3j1GTV
fjOIk62Pzr6Ceh5YrkiIQ5KirBCUR+Qcuobhb0K+DbQrMim6XXYZxVdMyau/25Gz
ZYtgFs7BTQRS2GY7ARAAwt9MeI3UKfWJGw1R3R2b0CaVpuID34dpBsD+KdQOOYBb
1FcyKQwUJE28x2WfQTg+Y8xJZJQcvnQFaRkHqvIw7JgNy/Ij5qN6GZ4frTqBF1qL
4Ns8jN+SDwAUwKjaX7bRTGqzgrlif8mFy0crS6qVmFYCJMGWsatRfknacwF+WL1+
u5C/REQ67iVMXKeevX8QC0164aaCzCvWkTvl1e3QRO4kY3RgQX2ytm/Tnanb+QwG
fT3idV2SI6erjUxNp+PNYhH42niOioGTGHWo2iWlaOH1SKLzXHaJvJay/Wg4UMUm
EOeInnOz0ULYeLojqtDqpA2zqxlc8AibVLtVwZf4N08h0E3KcQ8zYfOOdL2KaXHA
+pwFgFckM3SRPjQ2B/x8RaZ4vu0t6NAJmq2ydZ1SpEdBAa286ivoRtcG96H49hAz
vVmSn3uMNhUOyGz/TyzK/H2YxjOEsjJGIYsu3FKl/LXcECtkhY1sx0AN++Xyo9Fk
OTMbhTzfJFogvoz5K30vvxO6qPVjIbTIgH7svIijceNdNM0YG/L3LGbHMZl8C/Nt
PmJTfC3Ez6OEqT1MAcVH0l6JO8WdLV1i/53jgLF72+3AWuP5seUh3lWEV3zSRFyU
pqrVaxcoNJmRTEUxXPx6ldgfcTq3f9OAT7FhLiLb6uwG+xrhDzYTf8qchFCd3gUA
EQEAAcLD9QQYAQoAIAIbAhYhBJFrjZnDjq9eitx6Ko1mBmou6szaBQJpeg4uAokJ
EI1mBmou6szawb0gBBkBCgBmBQJS2GY7XxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90
YXRpb25zLm9wZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ2RTk3OUIyOEE2RjM3QzQz
QkUzMEFGQTFDQjhENTBCQjc3QkIzQzQ4AAoJEMuNULt3uzxIOSYQAMClZ1byBDm3
Uw4ljaUZVsjbA2wgoJnS/fMQPSRmAfQHd1CE8bk9ml2oE0t8MIq6QJ8ggiWE/fbN
LYHH6UxqOepF2c1E4hIyFO6Z+E+p1e2n2QI6/X4B9fFcTpoqvXdvXNQ4zEM311FG
qSqJZ0pNo45U9kA3Ck1buB3ovAXcVbFT30q+Hggj/feJeVPsnMTv/pqSyPO5myYi
Dyao2pPKVg7ocgqSssocVqUdaySopWZ0H/RlLf70QSuVQ1YHYBWCfe+TRx1aADSP
7La7ge2wqS3S6h9N6rCzS1rYmU3s0KX4bETGyGCsHsmWAzfwnczsQE4apYclq6GE
IYB9dbifCZSTmf3sPP9sfW4DS/9RaQCViJbV6rB4nXAwNshsNUGSBN7+LBUG3Y+H
XK/ps2+AQs69nYpig9zW+i12WWAlpZwrK7vXtfgRTUv4LPH3AKeIL53icwoSWEwD
6OeweBeNvjssLeq8iXE6204AnP3fYVPwWNNlvkrtkwJTuATKRGTt1SeAKnco+mEo
Up1QNouTb/w31syYDQxB/sZf26Ex/mirOo5t/CM4fJPL4D2APmOzfiUXiFA6QH/E
bB3f6mtZRIF0GXgOubuRI7CRla771Z3Y/wOiw1DD0t+j81LC8CyNNdjOCcMu+oYe
nMsg/bGJ5MuLbiwBhlA7vFcnFelgSKqQ3HMQAJCdS0ZkoI1PFEDuhmK+bLJHPY/Z
ie6sLRhL0TzpTqWZJybOG6O7B7V2T7RdXzR/jLnpjfCMJQGVXnsqXn7j3CjJQvyA
QgkoTC3etRofP9DCLvHcXPxkCuEpQTuh5BO9WiU796Iv7jGhkg7H0ZYM9JQAdfuF
VwownOVXiNF+4jzYW7BFS+/aeU8LL90jV07LHZjzw33qpqyWRTAW0FvRjrCBom/k
bTrMZb8w6OkrWPnyy++nmyIoDiqcFGf6fEd0Mit2kqlaa0iHoOxGxByRj+bp5asd
wBW+WZ9b+LC2Y1Rzp13DxtGVUGRee+YzwZsHas+7bG8p71stqdvQwVUxfrtaCV5O
HCnwqN0at3iU+U2FBe6uq1RPafOrxRWBiKUgJYHlCgNSti5qyN7rWHF0C0IUtSSX
JwPq0ZYuZ0noXq3ttsRaSM4VSP4Jf3V6+sQtrSurDHiVA+wlwpeTMH2jjLxSJE02
0k2Pj5Hm8tqsBowc3YTsWkHZJnxlBLwibt5J+JOy6F+/SZyjugJCD+R8TN5DXOIk
bGoxNzZyP4Tn53TNI/1TT3Zx7JyROo+3E8kSUZBMj0hPggD4TTIQHjZ72ZmZf/dR
ZV0/kgvxUYIiaftNKaLQu+Cn99cIGEPsNuD7dBmoeh2JwSVssfLZz54NYUd770E1
hw+hmoRcoInpxWeP
=ZO9v
-----END PGP PUBLIC KEY BLOCK-----
"""
