#!/bin/bash

set -x

true "Currently running script: $0"

script_help() {
: "
## creates separate build folder
## "$HOMEVAR"/whonix_binary
##
## FLAGS:
## -all
## Build both VBox machines.
##
## -fast
## Build both VBox machines.
## Skips the 20_create-debian-img step.
##
## -tg
## Builds Whonix-Gateway VBox machine.
##
## -tw
## Builds Whonix-Workstation VBox machine.
##
## -tg-fast
## Builds Whonix-Gateway VBox machine.
## Skips the 20_create-debian-img step.
##
## -tw-fast
## Builds Whonix-Workstation VBox machine.
## Skips the 20_create-debian-img step.
##
## -clean
## Deletes both .imgs and VBox vms.
##
## -tg-clean
## Deletes Whonix-Gateway .img and VBox vm.
##
## -tw-clean
## Deletes Whonix-Workstation .img and VBox vm.
##
"
}



error_handler_build-machine() {
: echo "
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
"

chmod +x "$WHONIX_SOURCE_FOLDER"/build-steps/20_create-debian-img

: echo "
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
"

exit 1
}



whonix_build_preparation() {
   export MACHINE="-buildscript"
   export VMNAME="-buildscript"

   cd help-steps

   MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

   source variables
   source pre

   cd ..
}



whonix_build_machine() {
   trap "error_handler_build-machine" ERR INT TERM

   chmod +x "$WHONIX_SOURCE_FOLDER"/build-steps/20_create-debian-img

   if [ "$FAST" = 1 ]; then
      sudo chmod -x "$WHONIX_SOURCE_FOLDER"/build-steps/20_create-debian-img
   fi

   run-parts --verbose --test ./build-steps
   run-parts --verbose --exit-on-error --arg "$MACHINE" ./build-steps

   if [ "$FAST" = 1 ]; then
      sudo chmod +x "$WHONIX_SOURCE_FOLDER"/build-steps/20_create-debian-img
   fi
}



whonix_build_all() {
   trap "error_handler_general" ERR INT TERM
   whonix_build_machine
}



whonix_build_clean() {
   trap "error_handler_general" ERR INT TERM

   ./debug-steps/delete-vbox-vm "$MACHINE"
}



################################################################ 
# -tg                                                          #
################################################################ 
if [ "$1" = "-tg" ]; then
   whonix_build_preparation
   export MACHINE="-tg"
   whonix_build_machine "$MACHINE"
   exit 0
fi

################################################################ 
# -tw                                                          #
################################################################ 
if [[ "$1" = "-tw" ]]; then
   whonix_build_preparation
   export MACHINE="-tw"
   whonix_build_machine "$MACHINE"
   exit 0
fi

################################################################ 
# -all                                                         #
################################################################ 
if [[ "$1" = "-all" ]]; then
   whonix_build_preparation
   export MACHINE="-tg"
   whonix_build_machine "$MACHINE"
   export MACHINE="-tw"
   whonix_build_machine "$MACHINE"
   exit 0
fi

################################################################ 
# -fast                                                        #
################################################################ 
if [[ "$1" = "-fast" ]]; then
   whonix_build_preparation
   export FAST=1
   export MACHINE="-tg"
   whonix_build_machine "$MACHINE"
   export MACHINE="-tw"
   whonix_build_machine "$MACHINE"
   exit 0
fi

################################################################ 
# -tg-fast                                                     #
################################################################ 
if [[ "$1" = "-tg-fast" ]]; then
echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
   whonix_build_preparation
   export FAST=1
echo bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
   export MACHINE="-tg"
   whonix_build_machine "$MACHINE"
   exit 0
fi

################################################################ 
# -tw-fast                                                     #
################################################################ 
if [[ "$1" = "-tw-fast" ]]; then
   whonix_build_preparation
   export FAST=1
   export MACHINE="-tw"
   whonix_build_machine "$MACHINE"
   exit 0
fi

################################################################ 
# -clean                                                       #
################################################################ 
if [[ "$1" = "-clean" ]]; then
   whonix_build_preparation
   export MACHINE="-tg"
   whonix_build_clean "$MACHINE"
   export MACHINE="-tw"
   whonix_build_clean "$MACHINE"
   exit 0
fi

################################################################ 
# -tg-clean                                                    #
################################################################ 
if [[ "$1" = "-tg-clean" ]]; then
   whonix_build_preparation
   export MACHINE="-tg"
   whonix_build_clean "$MACHINE"
   exit 0
fi

################################################################ 
# -tw-clean                                                    #
################################################################ 
if [[ "$1" = "-tw-clean" ]]; then
   whonix_build_preparation
   export MACHINE="-tw"
   whonix_build_clean "$MACHINE"
   exit 0
fi

################################################################ 
# -help                                                        #
################################################################ 
if [[ "$1" = "-help" ]]; then
   script_help
   exit 0
fi

################################################################ 
# no option chosen                                             # 
################################################################ 
if [[ "$1" = "" ]]; then 
echo "
INFO: No option chosen.

Please append -help to find out more.
"
exit 0
fi
