#!/bin/bash

# See LICENSE in root of Whonix source for copyright, license and authors.

script_help() {
: "
# creates separate build folder
# FLAGS:
# -all
# (untested)
# build both Virtual machines
#
# -tg
# (untested)
# Builds Whonix-Gateway VBox machine.
#
# -tw
# (untested)
# Builds Whonix-Workstation VBox machine.
#
# -clean
# (untested / broken?)
# deletes the whole content of the whonix_binary folder
"
}



set -x



build_error_handler() {
   touch /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED
   exit 1
}



USERNAME="user"
WHONIX_SOURCE_FOLDER="/home/$USERNAME/Whonix"



root_check() {
######################################################
# Checking script environment
######################################################
# Check if we are root
if [ "$(id -u)" != "0" ]; then
     echo "ERROR: This must be run as root (sudo)!"
     exit 1
else
     echo "INFO: Script running as root."
fi
}



# If this file was created previously, delete it now.
rm /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED || true



whonix_build_machine() {
      root_check

      trap "build_error_handler" ERR
      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-vboxdelete
      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi

      trap "build_error_handler" ERR
      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-createimg
      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi

      trap "build_error_handler" ERR
      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-copyinto-pre
      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi

      trap "build_error_handler" ERR
      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-chroot
      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi

      trap "build_error_handler" ERR
      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-copyinto-post
      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi

      trap "build_error_handler" ERR
      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-converttovdi
      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi

      trap "build_error_handler" ERR
      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-createvboxvm
      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi

      trap "build_error_handler" ERR
      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-export
      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi

      trap "build_error_handler" ERR
      echo "INFO: No errors."
}



whonix_build_all() {
	root_check

	trap "build_error_handler" ERR
	echo "whonix_Build: Not tested."

	trap "build_error_handler" ERR
	whonix_build_machine

	trap "build_error_handler" ERR
	echo "INFO: No errors."
}



whonix_build_clean() {
	root_check

	trap "build_error_handler" ERR
	"$WHONIX_SOURCE_FOLDER"/whonix_createvm -tg-vboxdelete

	trap "build_error_handler" ERR
	"$WHONIX_SOURCE_FOLDER"/whonix_createvm -tw-vboxdelete

	trap "build_error_handler" ERR
	echo "whonix_Build: Done."
}



################################################################ 
# tg                                                           #
################################################################ 
if [ "$1" = "-tg" ]; then
	MACHINE="g"
	whonix_build_machine
	exit 0
fi

################################################################ 
# tw                                                           #
################################################################ 
if [[ "$1" = "-tw" ]]; then
	MACHINE="w"
	whonix_build_workstation
	exit 0
fi

################################################################ 
# -all                                                         #
################################################################ 
if [[ "$1" = "-all" ]]; then
	MACHINE="g"
	whonix_build_machine
	MACHINE="w"
	whonix_build_machine
	exit 0
fi

################################################################ 
# -clean                                                       #
################################################################ 
if [[ "$1" = "-clean" ]]; then
	whonix_build_clean
	exit 0
fi

################################################################ 
# -help                                                        #
################################################################ 
if [[ "$1" = "-help" ]]; then
script_help
exit 0
fi

################################################################ 
# no option chosen                                             # 
################################################################ 
if [[ "$1" = "" ]]; then 
echo "
INFO: No option chosen.

Please append -help to find out more.
"
exit 0
fi