#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

## Whonix /usr/lib/whonix/dummytor

echo "INFO /usr/lib/whonix/dummytor: Dummy Tor."

exit 0

## End of Whonix /usr/lib/whonix/dummytor
