#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Whonix /usr/lib/whonix/dummytor

## Not using echo, because it conflicts with AppArmor.
#echo "INFO /usr/lib/whonix/dummytor: Dummy Tor."

exit 0

## End of Whonix /usr/lib/whonix/dummytor
