#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

id "clearnet"
if [ ! "$?" = 0 ]; then
   echo 'INFO: Creating user "clearnet"...'
   ## setting password of user clearnet to changeme
   ##
   ## How this password was created:
   ## sudo apt-get install whois
   ## mkpasswd
   ## changeme
   ## Resulted in: aTayYxVyw5kDo
   useradd --create-home --password aTayYxVyw5kDo --shell /bin/bash clearnet
else
   echo 'INFO: Not creating user "clearnet", because it already exists.'
fi

chown --recursive clearnet:clearnet /home/clearnet

