#!/bin/bash

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
else
    echo "INFO: Script running as root."
fi

