#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## This script needs to run before 20_sanity_checks, because debsums would
## otherwise output:
##     perl: warning: Please check that your locale settings:
##             LANGUAGE = "",
##             LC_ALL = (unset),
##             LANG = "en_GB.UTF-8"
##         are supported and installed on your system.
##     perl: warning: Falling back to the standard locale ("C").' = '' ']'
## Which is a confusing warning and considered an error in 20_sanity_checks.

source /usr/share/whonix/postinst.d/pre.bsh

mkdir --parents "/usr/lib/whonix/"

if [ -f "/usr/lib/whonix/updated_locale" ]; then
   exit 0
fi

force_echo "INFO $0: Changing your locale to en_US.UTF-8... Will only do this once."

## Just doing this once, so users who changed from en_US.UTF-8 to something
## else won't always find them having their locale reset to en_US.UTF-8 each
## time there are updated Whonix debian packages.

force_echo "INFO $0: Will run: locale-gen"

locale-gen

force_echo "INFO $0: Will run: update-locale LANG=en_US.UTF-8"

update-locale LANG=en_US.UTF-8

touch "/usr/lib/whonix/updated_locale"

force_echo "INFO $0: Done, changed locale to en_US.UTF-8."
