#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

sync

true 'INFO: Running "dpkg --audit" to check if the system is functional...'
## dpkg --audit does not exit with a non-zero exit code if something is wrong.
## dpkg --audit does not return anything, if everything is fine.
## Therefore we see if dpkg has to say something, and if yes, the system is
## broken and we abort.
dpkg_audit_output="$(dpkg --audit 2>&1)"
if [ ! "$dpkg_audit_output" = "" ]; then
   if [ "$CI" = "true" ]; then
      true "INFO: dpkg_audit_output not empty! Continuing, because CI detected."
   else
      error "dpkg_audit_output not empty!"
   fi
fi

true 'INFO: Running "dpkg --configure -a" to check if the system is functional. Can take a while...'
dpkg --configure -a

sync

true "INFO: Checking if sysctcl -p runs without an error..."
sysctl -p

true 'INFO: Benchmarking "sudo -u root echo "This is a test echo."" using "time"...'
time sudo -u root echo "This is a test echo."

true "INFO: Checking if debsums is installed..."
command -v debsums >/dev/null

true "INFO: Trying to find out if there are packages (or debs) which do not have an MD5 sums file..."

exit_code="0"
debsums_output_1="$(debsums --list-missing 2>&1)" || { exit_code="$?" ; true; };

if [ ! "$exit_code" = "0" ]; then
   error "ERROR: debsums returned a non-zero exit_code: $exit_code!"
fi

if [ "$debsums_output_1" = "" ]; then
   true "INFO: Ok, no packages (or debs) with missing MD5 sums file found."
else
   if [ "$CI" = "true" ]; then
      true "INFO: Packages (or debs) with missing MD5 sums file found! Continuing, because CI detected."
   else
      error "ERROR: Packages (or debs) with missing MD5 sums file found!"
   fi
fi

true "INFO: Trying to find out if there are any packages (or debs) with missing files..."

exit_code="0"
debsums_output_2="$(debsums --silent 2>&1)" || { exit_code="$?" ; true; };

if [ ! "$exit_code" = "0" ]; then
   error "ERROR: debsums returned a non-zero exit_code: $exit_code!"
fi

if [ "$debsums_output_2" = "" ]; then
   true "INFO: Ok, no packages (or debs) with missing files file found."
else
   if [ "$CI" = "true" ]; then
      true "INFO: Packages (or debs) with missing files found! Continuing, because CI detected."
   else
      error "ERROR: Packages (or debs) with missing files found!"
   fi
fi

true "INFO: Listing changed configuration files..."
true "      (Only an information, no check...)"
true "      (Has to be reviewed manually by the builder.)"
true "      (A differencing /etc/resolv.conf.whonix is expected when building \
Virtual Machine images, because the /etc/resolv.conf from the host has been mounted inside the image.)"

exit_code="0"
debsums_output_3="$(debsums --config --silent 2>&1)" || { exit_code="$?" ; true; };

true "INFO: Listed changed configuration files."

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
