#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

sync

true 'INFO: Running "dpkg --configure -a" to check if the system is functional. Can take a while...'
dpkg --configure -a

sync

true "INFO: Checking if sysctcl -p runs without an error..."
sysctl -p

true 'INFO: Benchmarking "echo "This is a test echo.""...'
time sudo -u root echo "This is a test echo."

true "INFO: Checking if debsums is installed..."
command -v debsums >/dev/null

true "INFO: Trying to find out if there are packages (or debs) which do not have an MD5 sums file..."

return_code="0"
debsums_return1="$(debsums --list-missing 2>&1)" || { return_code="$?" ; true; };

if [ ! "$return_code" = "0" ]; then
   error "ERROR: debsums returned a non-zero return_code: $return_code!"
fi

if [ "$debsums_return1" = "" ]; then
   true "INFO: Ok, no packages (or debs) with missing MD5 sums file found."
else
   if [ "$CI" = "true" ]; then
      true "INFO: Packages (or debs) with missing MD5 sums file found! Continuing, because CI detected."
   else
      error "ERROR: Packages (or debs) with missing MD5 sums file found!"
   fi
fi

true "INFO: Trying to find out if there are any packages (or debs) with missing files..."

return_code="0"
debsums_return2="$(debsums --silent 2>&1)" || { return_code="$?" ; true; };

if [ ! "$return_code" = "0" ]; then
   error "ERROR: debsums returned a non-zero return_code: $return_code!"
fi

if [ "$debsums_return2" = "" ]; then
   true "INFO: Ok, no packages (or debs) with missing files file found."
else
   if [ "$CI" = "true" ]; then
      true "INFO: Packages (or debs) with missing files found! Continuing, because CI detected."
   else
      error "ERROR: Packages (or debs) with missing files found!"
   fi
fi

true "INFO: Listing changed configuration files..."
true "      (Only an information, no check...)"
true "      (Has to be reviewed manually by the builder.)"
true "      (A differencing /etc/resolv.conf.whonix is expected when building \
Virtual Machine images, because the /etc/resolv.conf from the host has been mounted inside the image.)"

return_code="0"
debsums_return3="$(debsums --config --silent 2>&1)" || { return_code="$?" ; true; };

true "INFO: Listed changed configuration files."
