#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

sync

true "INFO: Checking if the system is functional and re-reunning apt-get,"
true "      if the script failed before, by running dpkg --configure -a."
true "      Can take a while..."
dpkg --configure -a

sync

true "INFO: Checking if sysctcl -p runs without an error."
sysctl -p

true "INFO: Listing packages (or debs) which don't have an MD5 sums file..."

debsums --list-missing

true "INFO: Listed missing debs."

true "INFO: Listing missing files..."

debsums --silent

true "INFO: Listed missing files."

true "INFO: Listing changed configuration files..."
true "      (Only an information, no check...)"
true "      (Has to be reviewed manually by the builder.)"
true "      (A differencing /etc/resolv.conf.whonix is expected when building \
Virtual Machine images, because the /etc/resolv.conf from the host has been mounted inside the image.)"

debsums --config --silent || true

true "INFO: Listed changed configuration files."
