#!/bin/bash

set -x

error_handler() {
   echo "
#############################################################
## postinst script: ERROR detected. Please report this bug! #
#############################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

## The torproject archive key has been manually downloaded using the key fingerprint from
## https://www.torproject.org/docs/debian.html.en and https://www.torproject.org/docs/signing-keys.html.en
## using gpg:
##    gpg --keyserver keys.gnupg.net --recv <long-key-id>
## Verified using:
##    gpg --list-sigs <long-key-id>
##    gpg --check-sigs <long-key-id>
## And added to Whonix source code using:
##    gpg --export <long-key-id> > /home/user/Whonix/whonix_shared/usr/share/whonix/keys/tpoarchive-keys.d/torprojectarchive.asc
sudo apt-key add /usr/share/whonix/keys/tpoarchive-keys.d/*

## This is a chroot-script and not a postinst.d script,
## because when the user updates, the deb.torproject.org-keyring deb package is already
## installed, which does a better job updating Tor Project's signing key.

