#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

## Removing conflicting software. Should not be installed, but just in case.
## This might be useful for users creating custom builds for example based on
## Ubuntu and for physical isolation users who installed using a standard
## installation medium as well.
apt-get --yes remove --purge \
   popularity-contest \
   canonical-census \
   unity-lens-shopping \
   unity-scope-video-remote \
   unity-scope-musicstores \
   geoclue-ubuntu-geoip \
   geoclue \
   resolvconf \
   openresolv \
   ufw \
   || true

