#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Removing conflicting software. Should not be installed, but just in case.
## This might be useful for users creating custom builds for example based on
## Ubuntu and for physical isolation users who installed using a standard
## installation medium as well.
apt-get --yes remove --purge \
   popularity-contest \
   canonical-census \
   unity-lens-shopping \
   unity-scope-video-remote \
   unity-scope-musicstores \
   geoclue-ubuntu-geoip \
   geoclue \
   resolvconf \
   openresolv \
   ufw \
   || true

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
