#!/bin/bash

## also used by timesync

get_local_whonix_version() {
   trap "error_handler" ERR

   ## fallback
   INSTALLED_WHONIX_VERSION="Could not read Whonix Deb Version File. (Code: 1) Please report this bug!"

   if [ -f "/usr/share/whonix/whonix_gateway" ]; then  
      INSTALLED_WHONIX_VERSION="$(dpkg-query --show --showformat='${Version}' "whonix-gateway-postinst")"
   elif [ -f "/usr/share/whonix/whonix_workstation" ]; then
      INSTALLED_WHONIX_VERSION="$(dpkg-query --show --showformat='${Version}' "whonix-workstation-postinst")"
   fi
   
   ## fallback
   if [ "$INSTALLED_WHONIX_VERSION" = "" ]; then
      INSTALLED_WHONIX_VERSION="Could not read Whonix Deb Version File. (Code: 2) Please report this bug!" 
   fi
   
   ## fallback
   WHONIX_BUILD_VERSION="Could not read Whonix Build Version File. (Code: 1) Please report this bug!"
    
   if [ -f "/usr/share/whonix/build_version" ]; then
      WHONIX_BUILD_VERSION="$(cat "/usr/share/whonix/build_version")"
   else
      ## 97adretemp did not create that file. That feature was not implemented at that time.
      WHONIX_BUILD_VERSION="97adretemp"
      ## This else part will be removed when 97adretemp test is over.
   fi
   
   ## fallback
   if [ "$WHONIX_BUILD_VERSION" = "" ]; then
      WHONIX_BUILD_VERSION="Could not read Whonix Build Version File. (Code: 2) Please report this bug!"   
   fi
}

preparation() {
   trap "error_handler" ERR

   if [ "$SHOW_CLI" = "1" ]; then
      true
   elif [ "$SHOW_X" = "1" ]; then
      true
   else
      if [ -e /var/run/whonix/whonixcheck/""$SCRIPTNAME"_pid" ]; then
         local oldpid="$(cat /var/run/whonix/whonixcheck/""$SCRIPTNAME"_pid")"
         kill -15 "$oldpid" > /dev/null 2>&1 || true         
         kill -9 "$oldpid" > /dev/null 2>&1 || true
      fi   
   
      rm -f /var/run/whonix/whonixcheck/""$SCRIPTNAME"_done"
      touch /var/run/whonix/whonixcheck/""$SCRIPTNAME"_running"
      echo "$BASHPID" > /var/run/whonix/whonixcheck/""$SCRIPTNAME"_pid"
   fi
   
   sync
   
   USERNAME="user"
   WHONIX_HOMEPAGE="https://www.whonix.org"
   VERIFY_TEMPDIR="$(mktemp --directory)"

   ## returns: INSTALLED_WHONIX_VERSION
   get_local_whonix_version

   ## Prepare temporary directory.
   mkdir --parents "$VERIFY_TEMPDIR"
   chmod 700 "$VERIFY_TEMPDIR"
   
   if [ -f "/usr/share/whonix/whonix_gateway" ]; then
      VM="Whonix-Gateway"
      GATEWAY_IP="127.0.0.1"
   elif [ -f "/usr/share/whonix/whonix_workstation" ]; then
      VM="Whonix-Workstation"
      GATEWAY_IP="192.168.0.10"
   else
      VM="whonixcheck script could not determine if this is whonix_gateway or whonix_workstation. Please report this bug."
      GATEWAY_IP="192.168.0.10"
   fi
 
   ## ARCH="x86_64"
   ## ARCH="i686"
   ARCH="$(uname --machine)"
  
   local MSG="INFO: $ARCH detected."
   true "--info" "$MSG" "debug"
   
   for i in /etc/whonix.d/*; do
      if [ -f "$i" ]; then
         ## If the last character is a ~, ignore that file,
         ## because it was created by some editor,
         ## which creates backup files.
         if [ "${i: -1}" = "~" ]; then
            continue
         fi
         source "$i"
      fi
   done   
   
   TIME_START="$(date +%s)"
}
 
