#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_virtualizer() {
   trap "error_handler" ERR

   ## This has a sudoers exception in /etc/sudoers.d/virt-what.
   local result
   result="$(sudo virt-what)"

   if [ "$result" = "" ]; then
      ## Not running in a Virtual Machine (or none detected).
      WHONIXCHECK_NO_VM_DETECTED="1"
      local MSG="Check Virtualizer Result: No Virtualizer detected, probably running on bare metal, continuing."
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
      return 0
   fi

   if [ "$result" = "virtualbox" ]; then
      ## VirtualBox detected.
      WHONIXCHECK_DETECTED_VIRTUALBOX="1"
      local MSG="Check Virtualizer Result: Supported Virtualizer $result detected, continuing."
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
      return 0
   fi

   ## Neither Physical Isolation nor VirtualBox was detected.

   if [ "$WHONIXCHECK_NO_EXIT_ON_UNSUPPORTED_VIRTUALIZER" = "1" ]; then
      WHONIXCHECK_DETECTED_VIRTUALBOX="0"
      local MSG="Check Virtualizer Result: Unsupported Virtualizer $result detected, but WHONIXCHECK_NO_EXIT_ON_UNSUPPORTED_VIRTUALIZER is set, continuing."
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
   else
      WHONIXCHECK_DETECTED_VIRTUALBOX="0"

      if [ "$result" = "vmware" ]; then
         local VMWARE_TEXT="VMware [6] is closed source, therefore security through obscurity [7]."
         local WIKI_LINK="[6] https://en.wikipedia.org/wiki/Security_through_obscurity"
         local VMWARE_LINK="[7] https://www.whonix.org/wiki/VMware"
      else
         local VMWARE_TEXT=""
         local VMWARE_LINK=""
      fi

      local MSG="\
Virutalizer $result unsupported by Whonix developers! Whonixcheck aborted!

Using Virutalizer $result together with Whonix is recommended against, because it is rarely tested. [1] [2] [3] \
It could be made possible, but would require more Whonix contributors.
It may already work, but is highly experimental.

$VMWARE_TEXT

This might endanger your anonymity. Do not proceed unless you know what you are doing.

If you wish to ignore this warning and to continue whonixcheck anyway, you can set
    WHONIXCHECK_NO_EXIT_ON_UNSUPPORTED_VIRTUALIZER=\"1\"
in /etc/whonix.d/30_whonixcheck_default.

Recommended action:
- Shut down.
- Read Whonix documentation [4].
- Use Whonix with either VirtualBox or Physical Isolation [5].

Footnotes:

[1] https://www.whonix.org/wiki/LeakTests
[2] https://www.whonix.org/wiki/Test
[3] https://www.whonix.org/wiki/Protocol-Leak-Protection_and_Fingerprinting-Protection
[4] https://www.whonix.org/wiki/Documentation
[5] https://www.whonix.org/wiki/Physical_Isolation
$VMWARE_LINK
$WIKI_LINK
"

      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   fi
}
