#!/bin/bash

#set -x

## Check if Tor is enabled.
check_tor_enabled_do() {
   trap "error_handler" ERR

   if [ ! -e "/usr/share/whonix/whonix_gateway" ]; then
      TOR_ENABLED=1
      return 0
   fi
   if [ ! -e "/etc/tor/torrc" ]; then
      error "check_tor_enabled: file /etc/tor/torrc does not exist."
      TOR_ENABLED=0
      return 0
   fi
   while read LINE; do
      if [ "$LINE" = "DisableNetwork 1" ]; then     
         TOR_ENABLED=0
         return 0
      fi
   done < "/etc/tor/torrc"   
   TOR_ENABLED=1
   return 0
} 

## Aborting, if whonixsetup was not run, i.e. if
## "DisableNetwork 1" is in commented in /etc/tor/torrc.
check_tor_enabled() {
   trap "error_handler" ERR

   check_tor_enabled_do

   if [ "$TOR_ENABLED" = "0" ]; then
      local MSG="Tor Check Result:
No network. Tor is disabled.

Please close this window and enable Tor!

    Start Menu -> Applications -> System -> First Time Connection Setup

    or in Terminal: sudo whonixsetup"
      $output ${output_opts[@]} --channel "both" --type "warning" --title "$TITLE" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return
   else
      local MSG='Tor Check Result: "DisableNetwork 1" in /etc/tor/torrc commented out, ok.'
      #$output ${output_opts[@]} --channel "both" --type "info" --title "$TITLE" --message "$MSG"
   fi
}

