#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_tor_bootstrap_helper() {
   trap "error_handler" ERR

   ## {{ variables

   local kill_after="5s"
   local timeout_after="10s"
   check_bootstrap_script="/usr/lib/whonix/whonixcheck/help_check_tor_bootstrap.py"

   ## }}

   ## {{ Sometimes it does not work on the first run. Small hack.

   local bootstrap_file="$VERIFY_TEMPDIR/tor_bootstrap_temp"
   rm --force "$bootstrap_file"
   local temp_return
   temp_return="0"
   timeout --kill-after="$kill_after" "$timeout_after" "$check_bootstrap_script" 2>&1 >"$bootstrap_file" &
   lastpid="$!"
   wait "$lastpid" || { temp_return="$?" ; true; }

   if [ -f "$bootstrap_file" ]; then
      local temp_status
      temp_status="$(cat "$bootstrap_file")"
      if [ "$temp_status" = "" ]; then
         temp_status="ERROR: Variable temp_status is empty. Please report this Whonix bug!"
      fi
   else
      temp_status="ERROR: File "$bootstrap_file" does not exist. Please report this Whonix bug!"
   fi

   ## }}

   ## {{ actual check

   if [ "$TOR_BOOTSTRAP_TIME_START" = "" ]; then
      TOR_BOOTSTRAP_TIME_START="$(date +%s)"
   fi
   TOR_BOOTSTRAP_TIME_NOW="$(date +%s)"
   TOR_BOOTSTRAP_TIME_PASSED="$(expr "$TOR_BOOTSTRAP_TIME_NOW" - "$TOR_BOOTSTRAP_TIME_START")" || true

   local bootstrap_file="$VERIFY_TEMPDIR/tor_bootstrap_file"
   rm --force "$bootstrap_file"
   tor_bootstrap_percent="0"
   timeout --kill-after="$kill_after" "$timeout_after" "$check_bootstrap_script" 2>&1 >"$bootstrap_file" &
   lastpid="$!"
   wait "$lastpid" || { tor_bootstrap_percent="$?" ; true; }

   if [ -f "$bootstrap_file" ]; then
      tor_bootstrap_status="$(cat "$bootstrap_file")"
      if [ "$tor_bootstrap_status" = "" ]; then
         tor_bootstrap_status="Variable tor_bootstrap_status is empty."
      fi
   else
      tor_bootstrap_status="ERROR: File $bootstrap_file does not exist. Please report this Whonix bug!"
   fi

   ## }}

   ## `timeout` returns:
   ## - 124 if sigterm was sufficient
   ## - 137 if needed to use kill.
}

check_tor_bootstrap() {
   trap "error_handler" ERR

   ## {{ Small check if one of Tor's SocksPorts is functional.

   local SOCKS_PORT_WHONIXCHECK
   SOCKS_PORT_WHONIXCHECK="9110"

   true "FUNCNAME: CURL: $CURL"

   $CURL \
      --fail \
      $CURL_VERBOSE \
      --max-time 5 \
      --output "$VERIFY_TEMPDIR/socks_port_open_file" \
      "$GATEWAY_IP:$SOCKS_PORT_WHONIXCHECK" \
      &

   ## Example OK:
   ## curl: (22) The requested URL returned error: 501 Tor is not an HTTP Proxy

   ## Example Failure:
   ## curl: (56) Recv failure: Connection reset by peer

   lastpid="$!"
   wait "$lastpid" || { check_socks_port_open_test="$?" ; true; };

   #local curl_status_message="$(/usr/lib/whonix/curl_exit_codes "$check_socks_port_open_test")"

   ## TODO
   if [ "$check_socks_port_open_test" = "22" ]; then
      ## OK.
      true
   elif [ "$check_socks_port_open_test" = "57" ]; then
      ## Failure.
      true
   else
      ## Unexpected error.
      true
   fi

   ## }}

   ## {{ Small check if Control Port Filter Proxy is functional.

   ## Only testing on Whonix-Gateway, because Control Port Filter Proxy only
   ## runs on Whonix-Gateway.
   local i
   i="0"
   if [ "$VM" = "Whonix-Gateway" ]; then
      while [ ! -f "/var/run/controlportfilt/ownrunning" ]; do
         i="$(expr "$i" + "1")" || true
         if [ "$i" -ge "30" ]; then
            break
         fi
         sleep "1" &
         lastpid="$!"
         wait "$lastpid" || true
      done
      if [ ! -f "/var/run/controlportfilt/ownrunning" ]; then
         local MSG="Control Port Filter Proxy Test Result:
File /var/run/controlportfilt/ownrunning does not exist. Please report this Whonix bug!"
         if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
            $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
         fi
         $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
         EXIT_CODE="1"
         cleanup "1"
         return 0
      else
         local MSG="Control Port Filter Proxy Test Result: OK"
      fi
   fi

   ## }}

   ## sets: check_bootstrap_script
   ## sets: lastpid
   ## sets: check_tor_bootstrap_helper
   ## sets: TOR_BOOTSTRAP_TIME_START
   ## sets: TOR_BOOTSTRAP_TIME_NOW
   ## sets: TOR_BOOTSTRAP_TIME_PASSED
   ## sets: tor_bootstrap_percent
   ## sets: tor_bootstrap_status
   check_tor_bootstrap_helper

   local MSG="tor_bootstrap_percent: $tor_bootstrap_percent"
   local MSG="tor_bootstrap_status: $tor_bootstrap_status"

   if [ "$tor_bootstrap_percent" = "255" ] || [ "$tor_bootstrap_percent" = "124" ] || [ "$tor_bootstrap_percent" = "137" ]; then
      if [ "$VM" = "Whonix-Gateway" ]; then
         local MSG="Tor Bootstrap Result:
Tor's Control Port could not be reached. (Code: "$tor_bootstrap_percent")
(tor_bootstrap_status: $tor_bootstrap_status)
(check_socks_port_open_test: $check_socks_port_open_test)
Please report this Whonix bug!"
      elif [ "$VM" = "Whonix-Workstation" ]; then
         local MSG="Tor Bootstrap Result:
Tor's Control Port could not be reached. (Code: "$tor_bootstrap_percent")
(tor_bootstrap_status: $tor_bootstrap_status)
(check_socks_port_open_test: $check_socks_port_open_test)
Did you start Whonix-Gateway beforehand?
Please run whonixcheck on Whonix-Gateway.
Then restart whonixcheck on Whonix-Workstation"
      else
         local MSG="$FUNCNAME: This is neither Whonix-Gateway nor Whonix-Workstation. Please report this Whonix bug!"
      fi
      if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
         $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
      fi
      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   fi

   if [ "$tor_bootstrap_percent" -gt "100" ] || [ "$tor_bootstrap_percent" -lt "0" ]; then
      local MSG="Tor Bootstrap Result:
"$check_bootstrap_script" ERROR ($tor_bootstrap_percent).
(tor_bootstrap_status: $tor_bootstrap_status)
(check_socks_port_open_test: $check_socks_port_open_test)
Please report this Whonix bug!"
      if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
         $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
      fi
      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   fi

   ## For testing.
   #if [ "$TOR_BOOTSTRAP_TIME_PASSED" -lt "10" ]; then
      #tor_bootstrap_percent="$(expr "5" + "${#RANDOM}")"
   #fi

   if [ "$tor_bootstrap_percent" = "100" ]; then
      local MSG="Tor Bootstrap Result: Connected to Tor."
      if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
         $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
      fi
      if [ "$DAEMON" = "1" ]; then
         ## Let's not show a success message every time whonixcheck
         ## successfully finished the Tor bootstrap test.
         return 0
      fi
      $output ${output_opts[@]} --passivepopupqueuex --typex "info" --titlecli "$TITLE" --message "$MSG" --done
      ## Only attempt to close the progress bar if one was started.
      ## Otherwise this might conflict with the progress bar in 25_autostart.
      $output ${output_opts[@]} --waitmessagecli --typecli "info" --titlex "$TITLE" --message "$MSG" --done
      return 0
   fi

   wait_max="60"

   if [ "$TOR_BOOTSTRAP_TIME_PASSED" -gt "1" ]; then
      if [ ! "$started_tor_bootstrap_progress_bar" = "1" ]; then
         if [ "$DAEMON" = "1" ]; then
            ## Daemon mode. Not creating a progress bar.
            true
         else
            ## Not running in daemon mode.
            started_tor_bootstrap_progress_bar="1"
            ## Waited for more than 5 seconds.
            local tmp
            tmp="$(mktemp)"
            local progressbaridx
            progressbaridx="${tmp##*.}"
            local MSG="Tor Bootstrap Test: Checking Tor's Bootstrap Status... (Will take up to $wait_max seconds.)"
            $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressbarx --titlex "$TITLE" --message "$MSG" --done
         fi
      fi
   fi

   if [ "$TOR_BOOTSTRAP_TIME_PASSED" -lt "$wait_max" ]; then
      if [ "$tor_bootstrap_percent" -lt "100" ]; then
         if [ "$PROGRESS" = "" ]; then
            PROGRESS="5"
         fi
         PROGRESS="$(expr "$PROGRESS" + "1")" || true

         if [ "$TOR_BOOTSTRAP_PERCENT_OLD" = "" ]; then
            TOR_BOOTSTRAP_PERCENT_OLD="$tor_bootstrap_percent"
         fi

         if [ "$TOR_BOOTSTRAP_PERCENT_OLD" = "$tor_bootstrap_percent" ]; then
            ## no progress has been made
            local MSG="Tor Bootstrap Result: Bootstrapping for $TOR_BOOTSTRAP_TIME_PASSED seconds. $tor_bootstrap_percent % done. Tor reports: $tor_bootstrap_status"
         else
            ## progress has been made
            local MSG="Tor Bootstrap Result: Bootstrapping $TOR_BOOTSTRAP_TIME_PASSED seconds. Progress has been made. $tor_bootstrap_percent % done. Tor reports: $tor_bootstrap_status"
         fi

         TOR_BOOTSTRAP_PERCENT_OLD="$tor_bootstrap_percent"

         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG" --done
         ## Only attempt to close the progress bar if one was started.
         ## Otherwise this might conflict with the progress bar in 25_autostart.
         if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
            $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "$PROGRESS"
         fi

         sleep "2" &
         lastpid="$!"
         wait "$lastpid" || true

         check_tor_bootstrap
         return 0
      fi
   fi

   if [ "$VM" = "Whonix-Gateway" ]; then

      local MSG="\
Tor Bootstrap Result:
Whonixcheck gave up waiting after $TOR_BOOTSTRAP_TIME_PASSED seconds.
Bootstrapping $tor_bootstrap_percent % done.
Tor reports: $tor_bootstrap_status

Possible issues:
- Is the host's internet connection working?
- Whonix-Gateway will need a few moments for bootstrapping the Tor network.
- Do you live in a censored area?

Recommendations:

1)
Shut down Whonix and try to get the Tor Browser Bundle from https://www.torproject.org working on your host. If you can not get the Tor Browser Bundle to work, you will most certainly not get Whonix to work either.

The Tor Browser Bundle is great for testing if you live in a censored area. If you need bridges for the Tor Browser Bundle, you will need them for Whonix as well.

2)
Try again: Start menu -> Applications -> System -> Whonix Check
           or in Terminal: whonixcheck
           or in Terminal with debugging: bash -x whonixcheck --verbose

3)
Use arm, connection page two, to see if Tor is connected:
   Start menu -> Applications -> System -> Arm
   or in Terminal: armwrapper"

   elif [ "$VM" = "Whonix-Workstation" ]; then

      local MSG="\
Tor Bootstrap Result:
Whonixcheck gave up waiting after $TOR_BOOTSTRAP_TIME_PASSED seconds.
Bootstrapping $tor_bootstrap_percent % done.
Tor reports: $tor_bootstrap_status.

Possible issues:
- Is the host's internet connection working?
- Whonix-Gateway will need a few moments for bootstrapping the Tor network.
- Did you start Whonix-Gateway beforehand?

Recommendations:

1)
Try again: Start menu -> Applications -> System -> Whonix Check
           or in Terminal: whonixcheck
           or in Terminal with debugging: bash -x whonixcheck --verbose

2)
Run whonixcheck on Whonix-Gateway as well."

   else

      local MSG="$FUNCNAME: This is neither Whonix-Gateway nor Whonix-Workstation. Please report this Whonix bug!"

   fi

   if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
      $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
   fi
   $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
   $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
   EXIT_CODE="1"
   cleanup "1"
   return 0
}
