#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

#set -x

check_tor_pid_do() {
   trap "error_handler" ERR

   ## Fallback.
   tor_pid_return_code="1"

   ## Only check on Whonix-Gateway.
   if [ ! -e "/usr/share/whonix/whonix_gateway" ]; then
      tor_pid_message="Not running on Whonix-Gateway."
      tor_pid_return_code="0"
      return 0
   fi

   if [ ! -f "/var/run/tor/tor.pid" ]; then
      tor_pid_message="Pid file /var/run/tor/tor.pid does not exist."
      tor_pid_return_code="1"
      return 0
   fi

   local pid="$(cat "/var/run/tor/tor.pid")"

   if [ "$pid" = "" ]; then
      tor_pid_message="Pid file /var/run/tor/tor.pid is empty."
      tor_pid_return_code="1"
      return 0
   fi

   local ps_return="0"
   ps -p "$pid" >/dev/null 2>/dev/null || { local ps_return="$?" ; true; };

   if [ ! "$ps_return" = "0" ]; then
      tor_pid_message="Pid $pid is not running."
      tor_pid_return_code="1"
      return 0
   fi

   tor_pid_message="Pid $pid running."
   tor_pid_return_code="0"
   return 0
}

check_tor_pid() {
   trap "error_handler" ERR

   ## returns: tor_pid_return_code, tor_verify_config_return_msg
   check_tor_pid_do

   if [ ! "$tor_pid_return_code" = "0" ]; then
      local MSG="Tor Pid Check Result:
Tor not running. (tor_pid_message: $tor_pid_message)

You have to fix this error, before you can use Tor.

Please restart Tor after fixing this error.

    Start Menu -> Applications -> System -> Restart Tor
    or in Terminal: sudo service tor restart

Restart whonixcheck after fixing this error.

    Start Menu -> Applications -> System -> Whonix Check
    or in Terminal: whonixcheck
"
      $output ${output_opts[@]} --channel "both" --type "error" --title "$TITLE" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   else
      local MSG="Tor Pid Check Result: $tor_pid_message Ok."
   fi
}
