#!/bin/bash

check_whonixcheck_lastrun() {
   trap "error_handler" ERR

   ## One hour has 3600 seconds.
   ## A day has 86400 seconds.
   local MAX="86400"
   
   ## Using "/var/lib/whonix/whonixcheck/"$SCRIPTNAME"_lastrun", because
   ## /var/run/ gets cleared on boot.
   
   if [ -f "/var/lib/whonix/whonixcheck/"$SCRIPTNAME"_lastrun" ]; then
      local i="0"
      while read LINE; do
         let i "i=i+1" ||  true
         #echo "$i: $LINE"
         if [ "$i" = "1" ]; then
            local LASTRUN="$LINE"
         fi
      done < "/var/lib/whonix/whonixcheck/"$SCRIPTNAME"_lastrun"
   else
      ## the whonixcheck_completed function does almost the same
      local LASTRUN="$MAX"
   fi

   local CURRENTTIME="$(date +%s)"

   let DIFFERENCE="$CURRENTTIME"-"$LASTRUN" || true

   #echo "whonixcheck checks completed $DIFFERENCE seconds ago."

   ## If difference is less than or equal to one day.
   #echo "DIFFERENCE: $DIFFERENCE MAX: $MAX"

   if [ "$DIFFERENCE" -le "$MAX" ]; then
      RECENTLY_RUN="1"
   else
      RECENTLY_RUN="0"
   fi
}

whonixcheck_completed() {
   trap "error_handler" ERR

   local LASTRUN="$(date +%s)"
   echo "$LASTRUN" | sudo -u user tee "/var/lib/whonix/whonixcheck/"$SCRIPTNAME"_lastrun" > /dev/null
}

