#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

welcome() {
   trap "error_handler" ERR

   local MSG="$NOTIFY_MSG"

   $output ${output_opts[@]} --channel "echo" --type "info" --title "$TITLE" --message "$MSG" --waitmessagecli
   $output ${output_opts[@]} --channel "x" --type "info" --title "$TITLE" --message "$MSG" --waitmessagex
   
   if [ "$DAEMON" = "1" ]; then
      ## Daemon mode.
      
      ## No progress meter, if timesync was run by daemon.
      if [ "$IDENTIFIER" = "timesync" ]; then 
         true
      else
         $output ${output_opts[@]} --progressbar --title "$TITLE" --message "$MSG" --parentpid "$$" &      
      fi
   elif [ "$AUTOSTARTED" = "1" ]; then
      ## Autostart.
      
      ## Not required to start a progress bar or to show a waiting message, because
      ## /etc/profile.d/40_whonixcheck.sh and /etc/xdg/autostart/whonixcheck.desktop
      ## will keep care of this.
      true
   else
      ## Manual run.
      true
      
      $output ${output_opts[@]} --progressbar --title "$TITLE" --message "$MSG" --parentpid "$$" &
   fi
}

