#!/bin/bash

## This script gets sourced by:
## - /usr/bin/whonixcheck
## - /usr/bin/timesync

disclaimer() {
   trap "error_handler" ERR

   ## Not adding disclaimer here, because the kdialog info message would contain it,
   ## which would be too much.
   if [ "$SCRIPTNAME" = "timesync" ]; then
      if [ "$AUTOSTARTED" = "1" ]; then
         return 0
      fi
   fi

   local MSG="Whonix is produced independently of, with no guarantee from, The Tor Project.
Whonix is experimental software. Do not rely on it for strong anonymity.
$WHONIX_HOMEPAGE"

   $output ${output_opts[@]} --channel "both" --type "info" --title "$TITLE" --message "$MSG"
}

