#!/bin/bash

## This script gets sourced by:
## - /usr/bin/whonixcheck
## - /usr/bin/timesync

disclaimer() {
   trap "error_handler" ERR

   if [ "$SCRIPTNAME" = "timesync" ]; then
      if [ "$AUTOSTARTED" = "1" ]; then
         return 0
      fi
   fi

   local MSG="Whonix is produced independently from the Tor (r) anonymity software and carries no guarantee from The Tor Project about quality, suitability or anything else.
Whonix is experimental software by means of concept and design. Do not rely on it for strong anonymity.
$WHONIX_HOMEPAGE"

   output "--info" "$MSG" "both"
}

