#!/bin/bash

check_stream_isolation() {
   trap "error_handler" ERR

   ## Check if curl failed.
   if [ ! "$CHECK_TOR_RESULT" = "0" ]; then
      local MSG="TransPort test failed! Can not test stream isolation."
      output "--error" "$MSG" "both"
      return 0
   fi

   ## Lets compare TransPort with SocksPort.
   if [ "$IP_TRANS_PORT" = "$IP_SOCKS_PORT" ]; then
      local MSG="TransPort and SocksPort have the same IP. This is sometimes normal."
      output "--info" "$MSG" "both"
   else
      if [ "$NOT_USING_TOR" = "1" ]; then
         local MSG="TransPort and SocksPort IPs differ, but Tor not detected! This is normal only if you're using a VPN behind Tor or specifically configured Whonix this way."
         output "--info" "$MSG" "both"
      else
         local MSG="Stream isolation is functional."
         output "--info" "$MSG" "both"
      fi
   fi
}

