#!/bin/bash

check_stream_isolation() {
   ## Check if curl failed.
   if [ "$NETWORK_DOWN" = "1" ]; then
      local MSG="TransPort Test: Failed! Can not test stream isolation!"
      output "--error" "ERROR" "$MSG" "both"
      return
   fi

   ## Lets compare TransPort with SocksPort.
   if [ "$IP_TRANS_PORT" = "$IP_SOCKS_PORT" ]; then
      local MSG="IP of Tor's TransPort and IP of Tor's SocksPort are equal. This is sometimes normal."
      output "--info" "Info" "$MSG" "both"
   else
      if [ "$NOT_USING_TOR" = "1" ]; then
         local MSG="IP of Tor's TransPort and IP of Tor's SocksPort differ, but Tor not detected!!!"
         output "--info" "Info" "$MSG" "both"
      else
         local MSG="Stream isolation appears to be functional. IP of Tor's TransPort and IP of Tor's SocksPort differ."
         output "--info" "Info" "$MSG" "both"
      fi
   fi
}

