#!/bin/bash

download_important_blog() {
   trap "error_handler" ERR

   local SOCKS_PORT_WHONIX_NEWS="9114"

   local DOWNLOAD_IMPORTANTBLOG_SUCCESS="1"
   local MSG="Downloading Whonix Important Blog..."
   output "--info" "Info" "$MSG" "echo"

   rm -f /home/user/.rawdog/importantblog.html

   uwt -t 5 -i "$GATEWAY_IP" -p "$SOCKS_PORT_WHONIX_NEWS"\
   $RAWDOG --config ~/.rawdog/importantblog.conf $WHONIXCHECK_RAWDOG_VERBOSE --update --write || DOWNLOAD_IMPORTANTBLOG_SUCCESS="0"

   if [ "$DOWNLOAD_IMPORTANTBLOG_SUCCESS" = "0" ]; then
      local MSG="Could not download Whonix Important Blog."
      output "--error" "ERROR" "$MSG" "both"
      return
   fi

   local MSG="Successfully downloaded Whonix Important Blog."
   output "--info" "Info" "$MSG" "both"
}

download_feature_blog() {
   trap "error_handler" ERR

   local SOCKS_PORT_WHONIX_NEWS="9114"

   local DOWNLOAD_FEATUREBLOG_SUCCESS="1"
   local MSG="Downloading Whonix Feature Blog..."
   output "--info" "Info" "$MSG" "echo"

   rm -f /home/user/.rawdog/featureblog.html

   uwt -t 5 -i "$GATEWAY_IP" -p "$SOCKS_PORT_WHONIX_NEWS"\
   $RAWDOG --config ~/.rawdog/featureblog.conf $WHONIXCHECK_RAWDOG_VERBOSE --update --write || DOWNLOAD_FEATUREBLOG_SUCCESS="0"

   if [ "$DOWNLOAD_FEATUREBLOG_SUCCESS" = "0" ]; then
      local MSG="Could not download Whonix Feature Blog."      
      output "--error" "ERROR" "$MSG" "both"
      return
   fi

   local MSG="Successfully downloaded Whonix Feature Blog."
   output "--info" "Info" "$MSG" "both"
}

