#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

check_torbrowser() {
   trap "error_handler" ERR

   ## Check if TB_LANG exists and is not empty.
   if [[ "$TB_LANG" && "${TB_LANG}" ]]; then
      MSG="Tor Browser Update Check: Tor Browser language variable is set to $TB_LANG."
   else
      MSG="Tor Browser Update Check: Tor Browser language set to default en-US."
      TB_LANG="en-US"
   fi
   #echo "$MSG"

   CHECK_TORBROWSER_RESULT="0"
   local MSG="Tor Browser Update Check: Checking version..."
   $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"

   local SOCKS_PORT_WHONIXCHECK="9110"

   ## This variable gets used by tbbversion.
   RecommendedTBBVersions="$VERIFY_TEMPDIR/RecommendedTBBVersions"

   ## Getting latest version number
   $CURL \
      --fail \
      $CURL_VERBOSE \
      --socks5-hostname socks5h://"$GATEWAY_IP":"$SOCKS_PORT_WHONIXCHECK"/ \
      --tlsv1 \
      --proto =https \
      --max-time 180 \
      --output "$RecommendedTBBVersions" \
      https://check.torproject.org/RecommendedTBBVersions \
      &

   lastpid="$!"
   wait "$lastpid" || { CHECK_TORBROWSER_RESULT="$?" ; true; }

   local curl_status_message="$(/usr/lib/whonix/curl_return_codes "$CHECK_TORBROWSER_RESULT")"

   if [ ! "$CHECK_TORBROWSER_RESULT" = "0" ]; then
      local MSG="Tor Browser Update Check Result: Tor Browser Update check failed. (curl return code: $curl_status_message) Could not download: https://check.torproject.org/RecommendedTBBVersions. Try:
    Start menu -> Applications -> System -> Tor Browser Updater"
      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
      return 0
   fi

   ## returns: TBBVERSION
   tbbversion

   ## Getting currently installed version number
   local temp="/home/$USERNAME/tor-browser_$TB_LANG/Docs/version"
   TBBINSTALLEDVERSION=""
   if [ -f "$temp" ]; then
      TBBINSTALLEDVERSION="$(head -1 "$temp")" || true
   fi

   if [ "$TBBINSTALLEDVERSION" != "" ]; then
      true "Successfully detected Tor Browser version. TB_LANG: $TB_LANG"
   else
      TBBINSTALLEDVERSION="UNKNOWN"
      local MSG="Tor Browser Update Check Result: Could not determine currently installed Tor Browser version. \
This could be either because none is installed or because the version format changed. Try:
    Start menu -> Applications -> System -> Tor Browser Updater"
      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
      return 0
   fi

   ## Append to MSG if Tor Browser is current or not.
   if [ "$TBBINSTALLEDVERSION" = "$TBBVERSION" ]; then
      ## It is up to date...
      local MSG="Tor Browser Update Check Result: Up to date."
      $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
   else
      ## Outdated...
      local MSG="Tor Browser Update Check Result: Installed Tor Browser version: $TBBINSTALLEDVERSION. Latest Tor Browser version: $TBBVERSION. Please run:
    Start menu -> Applications -> System -> Tor Browser Updater"
      $output ${output_opts[@]} --messagex --typex "warning" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "warning" --titlecli "$TITLE" --message "$MSG"
   fi
}
