#!/bin/bash

check_torbrowser() {
   trap "error_handler" ERR

   ## Check if TB_LANG exists and is not empty.
   if [[ "$TB_LANG" && "${TB_LANG}" ]]; then
      MSG="Tor Browser language variable is set to "$TB_LANG"."
   else
      MSG="Tor Browser language set to default en-US."
      TB_LANG="en-US"
   fi
   #echo "$MSG"

   GET_VERSION="1"
   local MSG="Checking Tor Browser version..."
   output "--info" "Info" "$MSG" "echo"

   ## Getting latest version number
   $CURL $WHONIXCHECK_CURL_VERBOSE --socks5-hostname socks5h://"$GATEWAY_IP":"$SOCKS_PORT_WHONIXCHECK"/ --tlsv1 --proto =https --max-time 300 --output RecommendedTBBVersions https://check.torproject.org/RecommendedTBBVersions || GET_VERSION="0"

   if [ "$GET_VERSION" = "0" ]; then
      local MSG="Tor Browser Update check failed. Could now download: https://check.torproject.org/RecommendedTBBVersions
Try: Start menu -> Applications -> System -> Tor Browser Updater"
      output "--error" "ERROR" "$MSG" "both"
      return
   fi

   tbbversion

   ## Getting currently installed version number
   TBBINSTALLEDVERSION="$(head -1 /home/"$USERNAME"/tor-browser_"$TB_LANG"/Docs/version)" || true

   if [ "$TBBINSTALLEDVERSION" != "" ]; then
      #echo "Successfully detected TorBrowser version. TB_LANG: $TB_LANG"
      true
   else
      TBBINSTALLEDVERSION="UNKNOWN"
      local MSG="Could not determine currently installed Tor Browser version.\
This could be either because none is installed or because the version format changed.

Try: Start menu -> Applications -> System -> Tor Browser Updater"
      output "--error" "ERROR" "$MSG" "both"
      return
   fi

   ## Append to MSG if Tor Browser is current or not.
   if [ "$TBBINSTALLEDVERSION" = "$TBBVERSION" ]; then
      ## It is up to date...
      local MSG="Installed Tor Browser version $TBBINSTALLEDVERSION is up to date."
      output "--info" "Info" "$MSG" "both"
   else
      ## Outdated...
      local MSG="\
Installed Tor Browser version: $TBBINSTALLEDVERSION. Latest Tor Browser version: $TBBVERSION.
Please run: Start menu -> Applications -> System -> Tor Browser Updater"
      output "--error" "WARNING" "$MSG" "both"
   fi
}

