#!/bin/bash

donate() {
   trap "error_handler" ERR

   ## Do not ask for donations if a bug occurred. More important things have to be sorted out.  
   if [ "$BUG" = "1" ]; then
      return
   fi
   
   ## Only for whonixcheck, not for timesync.
   if [ "$SCRIPTNAME" = "whonixcheck" ]; then
      ## Do not ask for donations if the user has something important to do.  
      if [ "$ZENITY_TYPE" = "--info" ]; then
         local BITCOIN_ADDRESS="1JgzCCSox56Sh4NnQJqRiwoxKi8oVSZBEd"  
         local MSG="Please support the development of Whonix, donate Bitcoin to:
$BITCOIN_ADDRESS"
         $output ${output_opts[@]} --channel "both" --type "info" --title "$TITLE" --message "$MSG"
      fi
   fi
}

