#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

donate() {
   trap "error_handler" ERR

   ## Do not ask for donations if a bug occurred. More important things have to be sorted out.
   if [ "$BUG" = "1" ]; then
      return
   fi

   ## Only for whonixcheck, not for timesync.
   if [ "$SCRIPTNAME" = "whonixcheck" ]; then
      if [ -f "/var/run/msgcollector/"$IDENTIFIER"_type" ]; then
         TYPE="$(cat "/var/run/msgcollector/"$IDENTIFIER"_type")"
         ## Do not ask for donations if the user has something important to do.
         if [ "$TYPE" = "info" ]; then
            local BITCOIN_ADDRESS="1JgzCCSox56Sh4NnQJqRiwoxKi8oVSZBEd"
            local MSG="Please consider making a small reoccurring donation. See:
https://www.whonix.org/wiki/Donate"
            $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
         fi
      fi
   fi
}
