#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

ex_funct() {
   trap "error_handler" ERR

   local pid

   ## This will include the pgrep child process itself.
   local pgrep_result="$(pgrep --parent "$$")"

   ## Debugging.
   ## Won't show the pgrep process itself, since that necessarily terminated already at this point.
   local ps_p_result="$(ps -p $pgrep_result)"

   for pid in $pgrep_result; do
      ## >/dev/null 2>/dev/null to prevent seeing error due to race conditions (process in meanwhile already terminated) and
      ## due to trying to kill the pgrep process which was already terminated.
      kill -sigterm "$pid" >/dev/null 2>/dev/null || true
   done

   local i=0

   ## Give remaining processes up to 5 seconds after sending signal sigterm (above) before killing them sending signal sigkill.
   while true; do
      i="$(expr $i + 1)"
      local pgrep_result="$(pgrep --parent "$$")"

      ## Debugging.
      local ps_p_result="$(ps -p $pgrep_result)"

      ## Create a local variable j, which holds how many pids are in pgrep_result.
      local j=0
      for pid in $pgrep_result; do
         local j="$(expr "$j" + 1)"
      done

      ## If there is only one pid in pgrep_result, it will be pgrep itself,
      ## which necessarily already terminated at this point.
      if [ "$j" = "1" ]; then
         break
      fi
      if [[ "$i" < "5" ]]; then
         sleep 1 &
         wait "$!"
         continue
      fi

      for pid in $pgrep_result; do
         ## >/dev/null 2>/dev/null to prevent seeing error due to race conditions (process in meanwhile already terminated) and
         ## due to trying to kill the pgrep process which was already terminated.
         kill -sigkill "$pid" >/dev/null 2>/dev/null || true
      done

   done

   rm --force "/var/run/whonix/whonixcheck/${IDENTIFIER}_running"
   rm --force "/var/run/whonix/whonixcheck/${IDENTIFIER}_waiting"
   #rm --force "/var/run/whonix/whonixcheck/${IDENTIFIER}_pid"

   ## Check if $output command has been already defined. This is not the case,
   ## when the script is terminated very early.
   if [ "$(command -v "$output" >/dev/null)" ]; then
      $output ${output_opts[@]} --progress "100"
   fi
   exit 0
}

trap_sigterm() {
   trap "error_handler" ERR

   echo "$SCRIPTNAME: SIGTERM received. Exiting."
   ex_funct
}

trap "trap_sigterm" SIGTERM

trap_sigint() {
   trap "error_handler" ERR

   echo "$SCRIPTNAME: SIGINT received. Exiting."
   ex_funct
}

trap "trap_sigint" SIGINT

cleanup() {
   trap "error_handler" ERR

   true "cleanup function..."

   $output ${output_opts[@]} --progress "100"

   rm --force "/var/run/whonix/whonixcheck/${IDENTIFIER}_running"
   rm --force "/var/run/whonix/whonixcheck/${IDENTIFIER}_waiting"
   #rm --force "/var/run/whonix/whonixcheck/${IDENTIFIER}_pid"

   sudo -u user touch "/var/run/whonix/whonixcheck/${IDENTIFIER}_done"

   sync

   ## Close pipe, which was opened for zenity.
   #exec 3>&- || true

   if [ "$DAEMON" = "1" ]; then
      ## Daemon mode.

      ## & so the daemon will continue to run even when the windows will not be closed.
      $output ${output_opts[@]} --showx &
      $output ${output_opts[@]} --showcli &
   elif [ "$AUTOSTARTED" = "1" ]; then
      ## Autostart.

      ## Not required to dispatch output, because
      ## /etc/profile.d/40_whonixcheck.sh and /etc/xdg/autostart/whonixcheck.desktop
      ## will keep care of this.
      true
   else
      ## Manual run.
      true

      $output ${output_opts[@]} --showx --forceactive

      ## Not required, because we are using --instantecho.
      #$output ${output_opts[@]} --showcli
   fi

   cd ..

   ## default exit code
   if [ "$EXIT_CODE" = "" ]; then
      EXIT_CODE="0"
   fi

   if [ "$1" = "1" ]; then
      true "END"
      exit "$EXIT_CODE"
   fi
}
