#!/bin/bash

ex_funct() {
   rm --force "/var/run/whonix/whonixcheck/"$IDENTIFIER"_running"
   rm --force "/var/run/whonix/whonixcheck/"$IDENTIFIER"_waiting"
   rm --force "/var/run/whonix/whonixcheck/"$IDENTIFIER"_pid"

   $output ${output_opts[@]} --progress "100"
}

trap_sigterm() {
   ex_funct
   
   echo "$SCRIPTNAME: SIGTERM received. Exiting."
   exit 0
}

trap "trap_sigterm" SIGTERM

trap_sigint() {
   ex_funct

   echo "$SCRIPTNAME: SIGINT received. Exiting."
   exit 0
}

trap "trap_sigint" SIGINT

cleanup() {
   trap "error_handler" ERR

   true "cleanup function..."

   $output ${output_opts[@]} --progress "100"
 
   rm --force "/var/run/whonix/whonixcheck/"$IDENTIFIER"_running"
   rm --force "/var/run/whonix/whonixcheck/"$IDENTIFIER"_waiting"
   rm --force "/var/run/whonix/whonixcheck/"$IDENTIFIER"_pid"
   
   sudo -u user touch "/var/run/whonix/whonixcheck/"$IDENTIFIER"_done"
  
   sync
   
   ## Close pipe, which was opened for zenity.
   #exec 3>&- || true

   if [ "$AUTOSTARTED" = "1" ]; then
      true
   else
      true
      ## Manual run.
      
      $output ${output_opts[@]} --showx

      ## Not required, because we are using --instantecho.
      #$output ${output_opts[@]} --showcli
   fi
   
   cd ..
   #if [ -d "$VERIFY_TEMPDIR" ]; then
      #rm -r "$VERIFY_TEMPDIR"
   #fi
  
   ## default exit code
   if [ "$EXIT_CODE" = "" ]; then
      EXIT_CODE="0"
   fi

   if [ "$1" = "1" ]; then
      true "END"
      exit "$EXIT_CODE"
   fi
}
