#!/bin/bash

## Whonix /usr/lib/whonix/whonixcheck/apt-get-update

## Required to run apt-get update as user (non-root).
## Required for whonixcheck function check_operating_system.
## Exception to run /usr/bin/apt-get-update as user
## is defined in /etc/sudoers.

apt-get update

exit "$?"

# End of Whonix /usr/lib/whonix/whonixcheck/apt-get-update

