#!/bin/bash

error_handler() {
   local return_code="$?"
   BUG="1"
  
   local MSG="\
###############################################################################
## $SCRIPTNAME script bug.
## No panic. Nothing is broken. Just some rare condition has been hit.
## Try again later. There is likely a solution for this problem.
## Please see Whonix News, Whonix Blog and Whonix User Help Forum.
## Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
## return_code: $return_code
##
## Experts only:
## bash -x $SCRIPTNAME --verbose
## for verbose output. Clean the output and
## submit to Whonix developers.
###############################################################################\
"
   $output ${output_opts[@]} --channel "both" --type "error" --title "$TITLE" --message "$MSG" --instanttty
} 
