#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012, 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

help_cli() {
   trap "error_handler" ERR

   echo "$SCRIPTNAME by Whonix
$WHONIX_HOMEPAGE

See:
man $SCRIPTNAME"
} 

