#!/bin/bash

error_handler() {
   BUG="1"
   show_output
  
   local MSG="\
###############################################################################
## $SCRIPTNAME script bug.
## No panic. Nothing is broken. Just some rare condition has been hit.
## Try again later. There is likely a solution for this problem.
## Please see Whonix News, Whonix Blog and Whonix User Help Forum.
## Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
##
## Experts only:
## bash -x $SCRIPTNAME --verbose
## for verbose output. Clean the output and
## submit to Whonix developers.
###############################################################################\
"
   output "--error" "$MSG" "both"
} 


