#!/bin/bash

phrase_cmd_options() {
   trap "error_handler" ERR

   ## If whonixcheck is run without command line arguments,
   ## $1 will not exist.

   ## defaults
   ##
   ## not being autostarted is the default
   WHONIXCHECK_AUTOSTARTED="0"

   ## adding --silent to curl to surpress output
   WHONIXCHECK_CURL_VERBOSE="--silent"

   ## not adding any verbosity options to rawdog
   WHONIXCHECK_RAWDOG_VERBOSE=""

   ## if started with -v switch for verbose output
   if [ "$1" = "-v" ]; then
      set -x
      WHONIXCHECK_CURL_VERBOSE=""
      WHONIXCHECK_RAWDOG_VERBOSE="--verbose"
      WHONIXCHECK_VERBOSE="1"
      echo "Verbose output..."
      echo "Script running as $(whoami)"
   fi

   ## if started with -help switch for help
   if [ "$1" = "-help" ]; then
      whonixcheck_help
      exit 0
   fi

   ## if started with -autostart switch when run by
   ## kde autostart or /etc/profile.d/whonixcheck.sh
   if [ "$1" = "-autostart" ]; then
      WHONIXCHECK_AUTOSTARTED="1"
   fi

   ## if started with -cron switch when run by cron
   if [ "$1" = "-cron" ]; then
      WHONIXCHECK_AUTOSTARTED="1"
      WHONIXCHECK_RUN_BY_CRON="1"
   fi
   
   if [ "$WHONIXCHECK_RUN_BY_CRON" = 1 ]; then
      echo "WHONIXCHECK_RUN_BY_CRON=1, setting DISPLAY to: :0"
      DISPLAY=":0"
   fi
} 

