#!/bin/bash

phrase_cmd_options() {
   trap "error_handler" ERR

   ## If whonixcheck is run without command line arguments,
   ## $1 will not exist.

   ## defaults
   ##
   ## not being autostarted is the default
   WHONIXCHECK_AUTOSTARTED="0"
   ##
   ## adding --silent to curl to surpress output
   WHONIXCHECK_CURL_VERBOSE="--silent"
   ##
   ## not adding any verbosity options to rawdog
   WHONIXCHECK_RAWDOG_VERBOSE=""   
   
   ## Thanks to:
   ## http://mywiki.wooledge.org/BashFAQ/035

   while :
   do
       case $1 in
           -h | --help | -\?)
               whonixcheck_help
               exit 0
               ;;               
           -v | --verbose)
               echo "$SCRIPTNAME verbose output..."
               echo "Script running as $(whoami)"
               set -x
               WHONIXCHECK_CURL_VERBOSE=""
               WHONIXCHECK_RAWDOG_VERBOSE="--verbose"
               WHONIXCHECK_VERBOSE="1"
               shift
               ;;
           -a | --autostart)
               WHONIXCHECK_AUTOSTARTED="1"
               shift
               ;;               
           -c | --cron)
               WHONIXCHECK_AUTOSTARTED="1"
               WHONIXCHECK_RUN_BY_CRON="1"
               echo "WHONIXCHECK_RUN_BY_CRON=1, setting DISPLAY to: :0"
               DISPLAY=":0"
               shift
               ;;                  
           --)
               shift
               break
               ;;
           -*)
               echo "$SCRIPTNAME unknown option: $1" >&2
               exit 1
               ;;
           *)
               break
               ;;
       esac
   done   

   ## If there are input files (for example) that follow the options, they
   ## will remain in the "$@" positional parameters.   
} 

