#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

if [ "$BARE_METAL" = "1" ] || [ "$CI" = "true" ]; then
   ## Working around: "sudo: unable to resolve host host"
   my_host_name="$(cat "/etc/hostname")"
   echo "INFO $0: Running \"hostname $my_host_name\"."
   hostname "$my_host_name"
else
  echo "INFO $0: Skipping, because BARE_METAL is not set to 1, ok."
fi

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
