#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Check if user "user" already exist.

ret=0
id user || { ret=$? ; true; };

if [ ! "$ret" = 0 ]; then
   echo 'INFO: Creating user "user"...'
   ## setting password of user user to changeme
   ##
   ## How this password was created:
   ## sudo apt-get install whois
   ## mkpasswd
   ## changeme
   ## Resulted in: aTayYxVyw5kDo
   useradd --password aTayYxVyw5kDo --user-group --create-home --shell /bin/bash user

   chown --recursive user:user /home/user
else
   echo 'Not creating user "user", because it user already exists.'
fi

usermod --append --groups adm,cdrom,audio,dip,sudo,plugdev user || true

## Debugging CI.
if [ "$CI" = "true" ]; then
   ls -la "/etc/resolv.conf"
   cat "/etc/resolv.conf"
   ls -la "/etc/hostname"
   cat "/etc/hostname"
   ls -la "/etc/hosts"
   cat "/etc/hosts"
   hostname
   hostname --all-fqdns
   hostname --long

   ## Sanity test.
   sudo -u user echo "INFO $0: Test echo as user."
fi
