#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

if [ -f "/usr/share/whonix/build_timestamp" ]; then
   exit 0
fi

BOOT_TIMESTAMP="$(date +%s)"

echo "$BOOT_TIMESTAMP" > /usr/share/whonix/build_timestamp

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
