#!/bin/bash

source /usr/share/whonix/postinst.d/pre.bsh

if [ -f "/usr/share/whonix/build_timestamp" ]; then
   exit 0
fi

BOOT_TIMESTAMP="$(date +%s)"

echo "$BOOT_TIMESTAMP" > /usr/share/whonix/build_timestamp

