#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Have we already done this? Check if lockfile exists.
if [ ! -f "/var/lib/whonix/do_once/remove_apper_desktop_icon" ]; then

   ## Required for Whonix Build Version 7, because we no longer install
   ## Apper by default.
   if [ -f "/home/user/Desktop/apper.desktop" ]; then
      ## || true in case it's not a symlink for some strange reason.
      unlink /home/user/Desktop/apper.desktop || true
   fi

   ## Create lockfile.
   mkdir --parents "/var/lib/whonix/do_once"
   touch "/var/lib/whonix/do_once/remove_apper_desktop_icon"
fi

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
