#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/lib/whonix/confirm_open 90
update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /usr/lib/whonix/confirm_open 90

## If one wanted to remove this, use this:
#update-alternatives --remove x-www-browser /usr/lib/whonix/confirm_open
#update-alternatives --remove gnome-www-browser /usr/lib/whonix/confirm_open
