#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/lib/whonix/confirm_open 90
update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /usr/lib/whonix/confirm_open 90

## If one wanted to remove this, use this:
#update-alternatives --remove x-www-browser /usr/lib/whonix/confirm_open
#update-alternatives --remove gnome-www-browser /usr/lib/whonix/confirm_open

## Let /usr/bin/whonix-torbrowser link to /usr/bin/torbrowser.
## Override with || true, so we do not need a separate file for
## Whonix-Workstation, because there is no /usr/bin/torbrowser file on
## Whonix-Gateway.
ln -s /usr/bin/torbrowser /usr/bin/whonix-torbrowser || true

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
