#!/bin/bash

if [ "$WHONIX_DEB_DEBUG" = "1" ]; then
   set -x
fi

error_handler() {
   echo "
#############################################################
## postinst script: ERROR detected. Please report this bug! #
#############################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

## || true to support re-running the script

## Get ride of old symlink.
unlink /etc/dpkg/origins/default || true

ln -s /etc/dpkg/origins/whonix /etc/dpkg/origins/default || true
 
