#!/bin/bash

source /usr/share/whonix/postinst.d/pre.bsh

## Deactivating kmix autostart. Workaround to fix Klipper (and others?) autostart.
## Working around bug http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=630617 by using
## workaround http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=630617#79
dpkg-divert --add --rename --divert /usr/share/autostart/kmix_autostart.desktop.real /usr/share/autostart/kmix_autostart.desktop

#dpkg-divert --list

