#!/bin/bash

source /usr/share/whonix/postinst.d/pre.bsh

## || true to support re-running the script

## Get rid of old symlink.
unlink /etc/dpkg/origins/default || true

ln -s /etc/dpkg/origins/whonix /etc/dpkg/origins/default || true
 
