#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## KDM (Whonix default login manager) sysvinit autostart gets disabled, because
## in /etc/profile.d/ we start RAM Adjusted Desktop Loader which decides
## whether to autostart kdm based on total amount of RAM, default and user
## settings or not.
if [ -x /usr/lib/whonix/display-manager-dpkg-post-invoke ]; then
   /usr/lib/whonix/display-manager-dpkg-post-invoke
fi
