#!/bin/bash

if [ "$WHONIX_DEB_DEBUG" = "1" ]; then
   set -x
fi

error_handler() {
   echo "
#############################################################
## postinst script: ERROR detected. Please report this bug! #
#############################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

##################
## kgpg settings #
##################

sudo -u user kwriteconfig --file kgpgrc \
             --group "General Options" \
             --key "First run" \
             --type bool \
             false

#sudo -u user kwriteconfig --file kgpgrc \
#             --group "Servers" \
#             --key "Server_List" \
#             --type string \
#             hkp://2eghzlv2wwcq7u7y.onion,hkp://keys.gnupg.net,hkp://pgp.dtype.org,hkp://search.keyserver.net,hkp://subkeys.pgp.net,hkp://wwwkeys.pgp.net,hkp://wwwkeys.pgp.net,hkp://wwwkeys.us.pgp.net

sudo -u user kwriteconfig --file kgpgrc \
             --group "TipOfDay" \
             --key "RunOnStart" \
             --type bool \
             false

temp='$HOME/.gnupg/gpg.conf'

sudo -u user kwriteconfig --file kgpgrc \
             --group "GPG Settings" \
             --key gpg_config_path \
             --type string \
             $temp

###################
## kgpg tray icon #
###################

sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
             --group Containments --group 1 --group Applets --group 6 --group Configuration \
             --key 'alwaysShown' \
             --type string \
             KGpg

#################
## Double Click #
#################

sudo -u user kwriteconfig --file kdeglobals \
             --group KDE \
             --key SingleClick \
             --type bool \
             false

#############################
## plasma-desktop-appletsrc #
#############################

## TODO: KDE

## Could be used to disable the clock. Would it be safe?
#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#            --group Containments --group 1 --group Applets --group 7 \
#             --key plugin \
#             --type string \
#            ""

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key dateStyle \
#             --type string \
#            0

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key defaultTimezone \
#             --type string \
#            UTC

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key showSeconds \
#             --type bool \
#            true

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key showTimezone \
#             --type bool \
#            true

#kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key timeZones \
#             --type string \
#            UTC

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key timezone \
#             --type string \
#            UTC

#######
# END #
#######

## Only for developing/testing.
#sudo -u user kquitapp plasma-desktop
#sudo -u user sleep 1
#sudo -u user plasma-desktop 

