#!/bin/bash

source /usr/share/whonix/postinst.d/pre.bsh

## knetattach is part of the kdebase-runtime debian package
## I am not aware of any reviews of this application with
## respect to Tor. The start menu entry gets hidden.
dpkg-divert --add --rename --divert /usr/share/applications/kde4/knetattach.desktop.real /usr/share/applications/kde4/knetattach.desktop

#dpkg-divert --list

