#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## {{ Get rid of old scripts.

rm --force /etc/profile.d/30_timesync
rm --force /etc/profile.d/40_whonixcheck
rm --force /etc/profile.d/80_desktop.sh

## }}

## {{ First Run Initializer

## First Run Initializer re-creates files which have been previously removed to
## during the build process (for the verifiable builds feature). Running it on
## older systems would only lead to a useless reboot. Not a critical issue, but
## should be prevented to avoid fingerprinting Whonix users at ISP level.
## (Because Tor is already running on legacy versions.)

skip_first_run_initializer="0"

if [ ! -f "/usr/share/whonix/build_version" ]; then
   ## Earlier versions than 137adretemp had no build_version file.
   skip_first_run_initializer="1"
else
   build_version="$(cat "/usr/share/whonix/build_version")"
fi

if [ "$build_version" = "137adretemp" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "6" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "6.1" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "6.2" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "7" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "7.3.3" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "7.3.7" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "7.3.8" ]; then
   skip_first_run_initializer="1"
fi

if [ "$skip_first_run_initializer" = "1" ]; then
   done_file="/home/user/.whonix/first_run_initializer.done"
   legacy_file="/home/user/.whonix/first_run_initializer.legacy"

   sudo -u user mkdir --parents "/home/user/.whonix"
   sudo -u user touch "$done_file"
   sudo -u user touch "$legacy_file"
fi

## }}
