#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## {{ Get rid of old scripts.

rm --force /etc/profile.d/30_timesync.sh
rm --force /etc/profile.d/40_whonixcheck.sh
rm --force /etc/profile.d/80_desktop.sh

## }}

## {{ First Run Initializer

## First Run Initializer re-creates files which have been previously removed to
## during the build process (for the verifiable builds feature). Running it on
## older systems would only lead to a useless reboot. Not a critical issue, but
## should be prevented to avoid fingerprinting Whonix users at ISP level.
## (Because Tor is already running on legacy versions.)

## Fallback.
skip_first_run_initializer="0"

## We can not do the following, because the /usr/share/whonix/build_version by
## gets created by a chroot-post.d after this postinst.d script runs, which is
## too late. This will result in users of 137adretemp and earlier build version
## in suffering from a useless reboot. Since there are probably very few such
## users, this is a compromise we can make.
#build_version="$(cat "/usr/share/whonix/build_version")"

if [ ! -f "/usr/share/whonix/build_version" ]; then
   ## - Earlier versions than 137adretemp had no build_version file.
   ## - This is also the case when building Whonix from source code.
   skip_first_run_initializer="1"
else
   ## - This is the case when upgrading Whonix from source code.
   build_version="$(cat "/usr/share/whonix/build_version")"
fi

if [ "$build_version" = "137adretemp" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "6" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "6.1" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "6.2" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "7" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "7.3.3" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "7.3.7" ]; then
   skip_first_run_initializer="1"
fi

if [ "$build_version" = "7.3.8" ]; then
   skip_first_run_initializer="1"
fi

if [ "$skip_first_run_initializer" = "1" ]; then
   ## Legacy version detected. Creating status files that will make first run
   ## initializer skip running.

   done_file="/home/user/.whonix/first_run_initializer.done"
   legacy_file="/home/user/.whonix/first_run_initializer.legacy"

   sudo -u user mkdir --parents "/home/user/.whonix"
   sudo -u user touch "$done_file"
   sudo -u user touch "$legacy_file"
fi

## }}
