#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Just for users' convenience.
## It reduces the required steps for setting up a shared folder.
## Also see:
## https://www.whonix.org/wiki/VirtualBox_Guest_Additions

mkdir --parents /mnt/shared
chmod 777 /mnt/shared
addgroup vboxsf || true
addgroup user vboxsf

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
