#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Ensure timezone is UTC.
ln -sf /usr/share/zoneinfo/UTC /etc/localtime

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
