#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Remove symlink, if any.
unlink /etc/localtime || true

## Ensure timezone is UTC.
cp --recursive --preserve /usr/share/zoneinfo/UTC /etc/localtime
