#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

unlink /usr/bin/apt-get || true
unlink /usr/bin/curl || true
unlink /usr/bin/git || true
unlink /usr/bin/gpg || true
unlink /usr/bin/mixmaster-update || true
unlink /usr/bin/rawdog || true
unlink /usr/bin/ssh || true
unlink /usr/bin/wget || true
unlink /usr/bin/aptitude || true

true "INFO: Diverting some /usr/bin/<uwt-wrapped-applications> to /usr/bin/<uwt-wrapped-applications>.real..."

dpkg-divert --rename --remove /usr/bin/apt-get || true
dpkg-divert --add --rename --divert /usr/bin/apt-get.real /usr/bin/apt-get

dpkg-divert --rename --remove /usr/bin/curl || true
dpkg-divert --add --rename --divert /usr/bin/curl.real /usr/bin/curl

dpkg-divert --rename --remove /usr/bin/git || true
dpkg-divert --add --rename --divert /usr/bin/git.real /usr/bin/git

dpkg-divert --rename --remove /usr/bin/gpg || true
dpkg-divert --add --rename --divert /usr/bin/gpg.real /usr/bin/gpg

dpkg-divert --rename --remove /usr/bin/mixmaster-update || true
dpkg-divert --add --rename --divert /usr/bin/mixmaster-update.real /usr/bin/mixmaster-update

dpkg-divert --rename --remove /usr/bin/rawdog || true
dpkg-divert --add --rename --divert /usr/bin/rawdog.real /usr/bin/rawdog

dpkg-divert --rename --remove /usr/bin/ssh || true
dpkg-divert --add --rename --divert /usr/bin/ssh.real /usr/bin/ssh

dpkg-divert --rename --remove /usr/bin/wget || true
dpkg-divert --add --rename --divert /usr/bin/wget.real /usr/bin/wget

dpkg-divert --rename --remove /usr/bin/aptitude || true
dpkg-divert --add --rename --divert /usr/bin/aptitude.real /usr/bin/aptitude

true "INFO: Diverted some /usr/bin/<uwt-wrapped-applications> to /usr/bin/<uwt-wrapped-applications>.real."

true "INFO: Linking uwt wrappers to /usr/lib/whonix/uwtwrapper master script..."

ln -s /usr/lib/whonix/uwtwrapper /usr/bin/apt-get
ln -s /usr/lib/whonix/uwtwrapper /usr/bin/curl
ln -s /usr/lib/whonix/uwtwrapper /usr/bin/git
ln -s /usr/lib/whonix/uwtwrapper /usr/bin/gpg
ln -s /usr/lib/whonix/uwtwrapper /usr/bin/mixmaster-update
ln -s /usr/lib/whonix/uwtwrapper /usr/bin/rawdog
ln -s /usr/lib/whonix/uwtwrapper /usr/bin/ssh
ln -s /usr/lib/whonix/uwtwrapper /usr/bin/wget
ln -s /usr/lib/whonix/uwtwrapper /usr/bin/aptitude

true "INFO: Linked uwt wrappers to /usr/lib/whonix/uwtwrapper master script."
