#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Sanity test.
command -v readlink

## Debugging.
command -v gpg || true
command -v gpg.real || true
ls -la /usr/bin/gpg || true
ls -la /usr/bin/gpg.real || true
readlink /usr/bin/gpg || true
readlink /usr/bin/gpg.real || true

## The DPKG_MAINTSCRIPT_PACKAGE hack is required, because in earlier versions
## the *-postinst packages created the dpkg diversions. Since the *-postinst
## packages have been merged into the *-files packages, we need this hack to
## support legacy versions. This is required because dpkg-divert does not let
## packages remove dpkg diversions created by other packages.
DPKG_MAINTSCRIPT_PACKAGE_BACKUP="$DPKG_MAINTSCRIPT_PACKAGE"

true "INFO: Diverting some /usr/bin/<uwt-wrapped-applications> to /usr/bin/<uwt-wrapped-applications>.real..."
true "INFO: Linking uwt wrappers to /usr/lib/whonix/uwtwrapper master script..."

file_list="
/usr/bin/apt-get
/usr/bin/curl
/usr/bin/git
/usr/bin/gpg
/usr/bin/mixmaster-update
/usr/bin/rawdog
/usr/bin/ssh
/usr/bin/wget
/usr/bin/aptitude
"

for file_name in $file_list; do
   ## The following step is required so we can remove the dpkg diversion.
   ## (Legacy)
   if [ "$(readlink "$file_name")" = "/usr/lib/whonix/uwtwrapper" ]; then
      unlink "$file_name"
   fi

   unset DPKG_MAINTSCRIPT_PACKAGE
   ## Remove old dpkg diversion. (Which is eventually still owned by the
   ## whonix-gateway/workstation-postinst package.)
   dpkg-divert --rename --remove "$file_name" || true
   export DPKG_MAINTSCRIPT_PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE_BACKUP"

   ## Add diversion.
   dpkg-divert --add --rename --divert "$file_name.real" "$file_name"

   ## Link original name to uwtwrapper.
   ln -s "/usr/lib/whonix/uwtwrapper" "$file_name" || true
done
unset file_name
unset file_list

true "INFO: Diverted some /usr/bin/<uwt-wrapped-applications> to /usr/bin/<uwt-wrapped-applications>.real."
true "INFO: Linked uwt wrappers to /usr/lib/whonix/uwtwrapper master script."

## Debugging.
command -v gpg || true
command -v gpg.real || true
ls -la /usr/bin/gpg || true
ls -la /usr/bin/gpg.real || true
readlink /usr/bin/gpg || true
readlink /usr/bin/gpg.real || true
