#!/bin/bash

source /usr/share/whonix/postinst.d/pre.bsh

sudo -u user mkdir --parents /var/lib/whonix/whonixcheck/

sudo -u user mkdir --parents /var/run/whonix/whonixcheck/

sudo -u rawdog mkdir --parents /home/rawdog/.rawdog/
