#!/bin/bash

source /usr/share/whonix/postinst.d/pre.bsh

mkdir -p /var/lib/whonix/whonixcheck/

chmod g+w /var/lib/whonix/whonixcheck/
chmod o+w /var/lib/whonix/whonixcheck/

mkdir -p /var/run/whonix/whonixcheck/

chmod g+w /var/run/whonix/whonixcheck/
chmod o+w /var/run/whonix/whonixcheck/

mkdir -p /home/rawdog/.rawdog/

chmod g+w /home/rawdog/.rawdog/
chmod o+w /home/rawdog/.rawdog/

