#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

/usr/bin/whonix_repository

