#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Debugging.
true "UWT_DEV_PASSTHROUGH: $UWT_DEV_PASSTHROUGH"

if [ "$WHONIX_APT_REPOSITORY_DISTRUST_ENV" = "0" ]; then
   ## This is not the case by default.
   ## We are no longer enabling Whonix's APT Repository by default, neither for
   ## redistributable builds not for builds from source code. The
   ## whonix_repository tool gets auto started once Whonix starts so the user
   ## can choose there.
   echo "INFO $0: WHONIX_APT_REPOSITORY_DISTRIBUTION_ENV is set to 0, enabling Whonix APT Repository.."
   bash -x /usr/bin/whonix_repository --enable
   exit 0
fi

## Just honor existing /etc/whonix.d and /root/.whonix.d config folders.
## Default Whonix APT Repository related configs have only comments. If neither
## WHONIX_APT_REPOSITORY_DISTRUST_ENV nor WHONIX_APT_REPOSITORY_DISTRUST_CONFIG
## are set to 0, then the whonix_repository tool will revoke all keys in
## /usr/share/whonix/keys/whonix-keys.d/ and in
## /usr/share/whonix/keys/whonix-keys-revoked.d/ (if there are any) and delete
## /etc/apt/sources.list.d/whonix.list (if it exists).
bash -x /usr/bin/whonix_repository --just

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
