#!/bin/bash

## Whonix /etc/cron.hourly/30_timesync

set -x

## Debugging:
#echo "htpdate cron.hourly pre: date: $(date)" >> /home/user/timesynclog

## & did not work on Debian.
exec /usr/local/bin/timesync_hourly

## Debugging:
#echo "htpdate cron.hourly post: date: $(date)" >> /home/user/timesynclog

exit 0

## End of Whonix /etc/cron.hourly/30_timesync

