#!/bin/bash

## Whonix /etc/cron.hourly/htpdate

set -x

## Debugging:
#echo "htpdate cron.hourly: date: `date`" >> /home/user/delayed

## & did not work on Debian.
exec /usr/local/bin/htpdate_hourly

exit 0

## End of Whonix /etc/cron.hourly/htpdate

