#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_kvmclock() {
   trap "error_handler" ERR

   if [ ! -f "/sys/devices/system/clocksource/clocksource0/current_clocksource" ]; then
      local MSG="KVMClock Result: \
/sys/devices/system/clocksource/clocksource0/current_clocksource does not exist, ok."
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
      return 0
   fi

   local current_clocksource
   current_clocksource="$(cat "/sys/devices/system/clocksource/clocksource0/current_clocksource")"

   if [ ! "$current_clocksource" = "kvm-clock" ]; then
      local MSG="KVMClock Result: \
/sys/devices/system/clocksource/clocksource0/current_clocksource exist, is \
$current_clocksource, not kvm-clock, ok."
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
      return 0
   fi

   if [ "$WHONIXCHECK_NO_EXIT_ON_KVMCLOCK_DETECTION" = "1" ]; then
      local MSG="KVMClock Test Result: KVMClock detected, but WHONIXCHECK_NO_EXIT_ON_KVMCLOCK_DETECTION is set, continuing."
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
   else
      local MSG="\
KVMClock Test Result:

KVMClock detected! This is unsupported by Whonix developers! Whonixcheck aborted!

Using KVM together with Whonix is recommended against, because KVMClock conflicts with Whonix's TimeSync design [1].

You probably did not follow Whonix's KVM instructions. [2]

This might endanger your anonymity. Do not proceed unless you know what you are doing.

If you wish to ignore this warning and to continue whonixcheck anyway, you can set
    WHONIXCHECK_NO_EXIT_ON_KVMCLOCK_DETECTION=\"1\"
in /etc/whonix.d/30_whonixcheck_default.

Recommended action:
- Shut down.
- Read Whonix documentation. [3]
- Follow Whonix's KVM instructions. [2]
- Or use Whonix with VirtualBOx.
- Or use Whonix with Physical Isolation. [4]

[1] https://www.whonix.org/wiki/Dev/TimeSync
[2] https://www.whonix.org/wiki/KVM
[3] https://www.whonix.org
[4] https://www.whonix.org/wiki/Physical_Isolation
"

      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   fi
}
