#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

## Check if Tor is enabled.
check_tor_enabled_do() {
   trap "error_handler" ERR

   ## Skip this test, if not running on Whonix-Gateway.
   if [ ! -e "/usr/share/whonix/whonix_gateway" ]; then
      TOR_ENABLED="1"
      return 0
   fi

   if [ ! -e "/etc/tor/torrc" ]; then
      error "check_tor_enabled: file /etc/tor/torrc does not exist."
      TOR_ENABLED="0"
      return 0
   fi

   local line

   ## Parse /etc/tor/torrc.
   while read line; do
      if [ "$line" = "DisableNetwork 0" ]; then
         TOR_ENABLED="1"
         return 0
      fi
   done < "/etc/tor/torrc"
   unset line

   ## Parse /usr/share/tor/tor-service-defaults-torrc.
   while read line; do
      if [ "$line" = "DisableNetwork 0" ]; then
         TOR_ENABLED="1"
         return 0
      fi
   done < "/usr/share/tor/tor-service-defaults-torrc"
   unset line

   ## Fallback.
   TOR_ENABLED="0"
   return 0
}

check_tor_enabled() {
   trap "error_handler" ERR

   ## sets: TOR_ENABLED
   check_tor_enabled_do

   if [ "$TOR_ENABLED" = "0" ]; then
      ## When Tor is not yet enabled, i.e. if "DisableNetwork 1" is in
      ## commented /etc/tor/torrc and/or
      ## /usr/share/tor/tor-service-defaults-torrc and whonxicheck is
      ## manually started, show the following message and exit.
      ## Otherwise, if whonixcheck is automatically started just be quit and
      ## exit.

      local MSG="Tor Check Result:
No network. Tor is disabled.

Please close this window and enable Tor!

    Start Menu -> Applications -> System -> Connection Wizard (Whonix)

    or in Terminal: sudo whonixsetup"

      if [ "$manualrun" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "warning" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "warning" --titlecli "$TITLE" --message "$MSG"
      fi

      EXIT_CODE="1"
      cleanup "1"
      return 0
   else
      if [ -e "/usr/share/whonix/whonix_gateway" ]; then
         local MSG='Tor Check Result: "DisableNetwork 1" in /etc/tor/torrc commented out, ok.'
         if [ "$verbose" = "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
         fi
      else
         local MSG='Tor Check Result: Not running on Whonix-Gateway, ok.'
         if [ "$verbose" = "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
         fi
      fi
   fi
}
