#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_whonix_apt_repository() {
   trap "error_handler" ERR

   local temp_x_tool="Start menu -> Applications -> System -> Whonix Repository"
   local temp_cli_tool="sudo whonix_repository"

   local temp_base_msg_enabled="Whonix APT Repository: Enabled.
When the Whonix team releases $whonix_codename_uppercase updates, \
they will be AUTOMATICALLY installed (when you run apt-get dist-upgrade) \
along with updated packages from the Debian team. Please \
read https://whonix.org/wiki/Trust to understand the risk. \
If you want to change this, use:"

   local temp_base_msg_disabled="Whonix APT Repository: Disabled.
When the Whonix team releases an update, it will be NOT be installed. \
Please read https://whonix.org/wiki/Trust to understand the risk. \
You will still be notified when updated Whonix packages are released by \
whonixcheck's Whonix News. You are free to manually update from source code. \
If you want to change this, use:"

   if [ -f "/etc/apt/sources.list.d/whonix.list" ]; then
      local MSG="$temp_base_msg_enabled
    $temp_x_tool"
   else
      local MSG="$temp_base_msg_disabled
    $temp_x_tool"
   fi

   $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"

   if [ -f "/etc/apt/sources.list.d/whonix.list" ]; then
      local MSG="$temp_base_msg_enabled
    $temp_cli_tool"
   else
      local MSG="$temp_base_msg_disabled
    $temp_cli_tool"
   fi

   $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
}
