#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

parse_cmd_options() {
   trap "error_handler" ERR

   ## If whonixcheck is run without command line arguments,
   ## $1 will not exist.

   ## defaults
   ##
   ## not being autostarted is the default
   AUTOSTARTED="0"
   ##
   ## adding --silent to curl to surpress output
   CURL_VERBOSE="--silent"
   ##

   ## Thanks to:
   ## http://mywiki.wooledge.org/BashFAQ/035

   while :
   do
       case $1 in
           -h | --help | -\?)
               help_cli
               EXIT_CODE="0"
               cleanup
               return 0
               ;;
           -v | --verbose)
               echo "$SCRIPTNAME verbose output..."
               echo "Script running as $(whoami)"
               verbose="1"
               shift
               ;;
           -e | --debug)
               echo "$SCRIPTNAME debug output..."
               echo "Script running as $(whoami)"
               set -x
               CURL_VERBOSE=""
               shift
               ;;
           -d | --daemon)
               DAEMON="1"
               shift
               ;;
           -a | --autostart)
               AUTOSTARTED="1"
               shift
               ;;
           -n | --nosleep)
               NOSLEEP="1"
               shift
               ;;
           --sleepseconds)
               SLEEP_SECONDS="$2"
               shift 2
               ;;
           -l | --nochecklastrun)
               NOCHECKLASTRUN="1"
               shift
               ;;
           -f | --function)
               FUNCTION="$2"
               shift 2
               ;;
           -f | --mode)
               MODE="$2"
               shift 2
               ;;
           -m | --minimal)
               MINIMAL="1"
               shift
               ;;
           --)
               shift
               break
               ;;
           -*)
               echo "$SCRIPTNAME unknown option: $1" >&2
               EXIT_CODE="1"
               cleanup "1"
               return 0
               ;;
           *)
               break
               ;;
       esac
   done

   ## If there are input files (for example) that follow the options, they
   ## will remain in the "$@" positional parameters.
}
