#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.
## This script is to be executed on the host and builds the derivative-maker-docker image.

set -x
set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

MYDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )"

cd -- "$MYDIR"

sudo -- docker build -t derivative-maker/derivative-maker-docker:latest .
