#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## This script is executed from within the container with the purpose of verifying
## a chosen or the latest available tag, before initiating the build process.
##
## GIT=true - run 'git pull'

set -x
set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

SOURCE_DIR="${HOME}/derivative-maker"
BINARY_DIR="${HOME}/derivative-binary"
LOG_DIR="${BINARY_DIR}/logs"
BUILD_LOG="${LOG_DIR}/build.log"
GIT_LOG="${LOG_DIR}/git.log"
## TODO: refactoring, avoid code duplication
## Move '/usr/bin/dm-git-tag-checkout-latest' from 'developer-meta-files'
## to 'help-steps' folder instead, improve?

mkdir --parents -- "${BINARY_DIR}" "${LOG_DIR}"

chown --recursive -- "${USER}:${USER}" "${LOG_DIR}"

cd -- "${SOURCE_DIR}"

git fetch --tags --depth=1

[ -n "${TAG}" ] || export TAG="$(git describe --tags -- "$(git rev-list --tags --max-count=1)")"

{
  [ -z "${GIT}" ] || git pull
  git checkout --recurse-submodules "${TAG}"
  [ "$TAG" = "master" ] || git describe
  git status
} 2>&1 | tee -a -- "${GIT_LOG}"

"$@" 2>&1 | tee -a -- "${BUILD_LOG}"
