#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## This script is executed on the host with the purpose of setting up
## required volume directories and executing the docker run command with any given arguments.

set -x
set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

HOST_USER="$(id -u)"
DOCKER_USER="user"
COMMAND="./derivative-maker"
SOURCE_VOLUME="$(dirname -- "$PWD")"
BINARY_VOLUME="$HOME/binary_mnt"
CACHER_VOLUME="$HOME/approx_cache_mnt"
IMG="derivative-maker/derivative-maker-docker"

declare {GIT,TAG}=""
declare -a -- VOLUMES=(
"${CACHER_VOLUME}" "101:102" "770"
"${BINARY_VOLUME}" "${HOST_USER}:${HOST_USER}" "770"
)

volume_check() {
  if [ -d "${1}" ] ; then
    return 0
  fi
  mkdir --parents -- "${1}"
  sleep -- ".1"
  sudo -- chown --recursive -- "${2}" "${1}"
  sudo -- chmod --recursive -- "${3}" "${1}"
}

## Thanks to:
## http://mywiki.wooledge.org/BashFAQ/035

while true; do
  case "$1" in
    -t|--tag)
      TAG="${2}"
      shift 2
      ;;
    -b|--build-step)
      COMMAND="build-steps.d/${2}"
      shift 2
      ;;
    -c|--custom)
      COMMAND="${2}"
      shift 2
      ;;
    -g|--git)
      GIT="1"
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      break
      ;;
  esac
done

while [ "${#VOLUMES[@]}" -gt "0" ]; do
  volume_check ${VOLUMES[@]:0:3}
  VOLUMES=("${VOLUMES[@]:3:3}")
done

sudo --non-interactive -- modprobe -a loop dm_mod

sudo \
  --non-interactive \
  -- \
    docker \
      run \
      --name derivative-maker-docker \
      --interactive \
      --tty \
      --rm \
      --privileged \
      --env "TAG=${TAG}" \
      --env "GIT=${GIT}" \
      --env 'flavor_meta_packages_to_install=' \
      --env 'install_package_list=' \
      --env 'DERIVATIVE_APT_REPOSITORY_OPTS=' \
      --volume "${SOURCE_VOLUME}:/home/${DOCKER_USER}/derivative-maker" \
      --volume "${BINARY_VOLUME}:/home/${DOCKER_USER}/derivative-binary" \
      --volume "${CACHER_VOLUME}:/var/cache/approx-derivative-maker" \
      "${IMG}" \
        sudo \
          --non-interactive \
          --preserve-env \
          -u "${DOCKER_USER}" \
          -- \
            "/usr/bin/derivative-maker-docker-start" "${COMMAND}" "${@}"
