#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

for i in $(find "./old"); do

   if [ -d "$i" ]; then
      continue
   fi

   echo "debfiff... $i"
   
   debdiff "$i" ./new/"$(basename "$i")"   
  
   #sleep 10

done

