#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

change_partition_uuid() {
   trap "error_handler_unmount" ERR INT TERM

   sync

   if [ "$BARE_METAL" = "1" ]; then
      true "${cyan}INFO${reset}: Changing of partition uuid not implemented for bare metal."
   else
      ./mount-img
      ## Change partition uuid.
      true "${cyan}INFO${reset}: Changing of partition uuid..."
      tune2fs /dev/mapper/loop0p1 -U 26ada0c0-1165-4098-884d-aafd2220c2c6
      true "${cyan}INFO${reset}: Changed of partition uuid."
      sync
      ./unmount-img
   fi

   sync
}

change_partition_uuid

