#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

change_partition_uuid() {
   trap "error_handler_unmount" ERR INT TERM

   sync

   if [ "$BARE_METAL" = "1" ]; then
      true "${cyan}INFO: Changing of partition uuid not implemented for bare metal.${reset}"
   else
      ./mount-img
      ## Change partition uuid.
      true "${cyan}INFO: Changing of partition uuid...${reset}"
      tune2fs /dev/mapper/loop0p1 -U 26ada0c0-1165-4098-884d-aafd2220c2c6
      true "${cyan}INFO: Changed of partition uuid.${reset}"
      sync
      ./unmount-img
   fi

   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
change_partition_uuid

