#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

prepare-build-machine() {
   trap "error_handler_general" ERR INT TERM

   ## If whonix_build is run with -fast switch.
   if [ "$FAST" = "1" ]; then
      echo "prepare-build-machine: run with -fast switch. Skipping prepare-build-machine step."
      exit 0
   fi

   ## Always keep old configuration file. Do not prompt to install new config files.
   echo '
      Dpkg::Options {
         "--force-confold";
      }
   ' > /etc/apt/apt.conf.d/99whonix-build-confold

   ## Update package lists and upgrade.
   apt-get update
   apt-get --yes dist-upgrade

   ## Install build dependencies.
   apt-get install --yes virtualbox qemu apt-cacher-ng grml-debootstrap parted kpartx debootstrap mksh dialog git sudo rsync

   ## Add user to sudo group.
   addgroup "$USERNAME" sudo

   ## If you build inside Whonix-Workstation, disable the apt-get uwt wrapper.
   ## || true in case not building inside Whonix
   chmod -x /usr/local/bin/apt-get || true

   ## Using an apt cache to speed up downloading
   ## If you want to build multiple times (for debugging etc.),
   ## it makes sense to install a local apt proxy on your build machine.
   ## That safes download time and traffic.
   ##
   ## Minor: If you build Whonix on Whonix, apt-cacher-ng will go through Tor's TransPort.
   ##
   ## Thanks to source:
   ##    https://linuxexpresso.wordpress.com/2011/02/13/howto-apt-cacher-ng-on-ubuntu/
   ## It would be possible to download without an apt-cacher...
   ## But why? If you do not want to use it, comment out the following line and
   ## change the mirror settings in grml configuration file.
   echo 'Acquire::http { Proxy "http://127.0.0.1:3142"; };' > /etc/apt/apt.conf.d/99whonix-build-apt-cacher-ng

   ## Restart apt-cacher-ng.
   ## Should not be required, but it was for me.
   service apt-cacher-ng restart

   ## Test apt-cacher-ng is working.
   /usr/bin/apt-get update

   ##Should there ever be a problem with apt-cacher-ng (package verification failure) (rare cases), use this.
   #sudo apt-get update
   #sudo apt-get autoremove
   #sudo apt-get dist-upgrade
   #sudo apt-get clean
   #sudo apt-get autoclean
} 

prepare-build-machine

