#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

copy_into_shared() {
   trap "error_handler_unmount" ERR INT TERM
   
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-shared_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-shared-common_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-shared-desktop_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-shared-desktop-kde_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/

   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-shared-common_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-shared-kde-accessibility_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/

   ## Too big.
   #cp "$WHONIX_SOURCE_PARENTDIR"/whonix-shared-desktop-langpack-kde_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
}

copy_into_gateway() {
   trap "error_handler_unmount" ERR INT TERM

   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-gateway_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-gateway-common_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/               
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-gateway-postinst_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/ 
}

copy_into_workstation() {
   trap "error_handler_unmount" ERR INT TERM

   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-workstation_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-workstation-common_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-workstation-postinst_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-workstation-langpack-common_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-workstation-default-applications_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/            
   cp "$WHONIX_SOURCE_PARENTDIR"/whonix-workstation-extra-applications_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
   
   ## DummyTor
   cp "$WHONIX_SOURCE_PARENTDIR"/tor_"$VERSION"_all.deb "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/
}

copy_into_packages() {
   trap "error_handler_unmount" ERR INT TERM

   ./mount-img

   mkdir --parent "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"/

   if [ "$MACHINE" = "-tg" ] || [ "$MACHINE" = "-tg-bare-metal" ]; then
      copy_into_gateway
      copy_into_shared
   elif [ "$MACHINE" = "-tw" ] || [ "$MACHINE" = "-tw-bare-metal" ]; then
      copy_into_shared
      copy_into_workstation
   else
      bug "ERROR: MACHINE is $MACHINE - neither -tg nor -tw"
   fi

   ./unmount-img
}

copy_into_packages

