#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

install-meta-packages() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   sync

   ./mount-img
   ./prevent-daemons-from-starting
   ./chroot-img

   sync

   ## Just for testing.
   $CHROOT update-grub -v
   $CHROOT sync
   sync
   
   ## Enable apt-cacher-ng.
   export http_proxy="http://127.0.0.1:3142"

   mkdir --parents "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"
   mkdir --parents "$CHROOT_FOLDER"/"$EMPTY_DIR"
   mount --bind "$WHONIX_APT_REPOSITORY_FOLDER" "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"
  
   echo "deb file:$DEB_INSTALL_FOLDER/ stable main" > "$WHONIX_SOURCES_LIST_TEMP_BUILD_FULL"
   
   sync
   
   $CHROOT sudo apt-get update \
                   -o Dir::Etc::sourcelist="$WHONIX_SOURCES_LIST_TEMP_BUILD_BASE" \
                   -o Dir::Etc::sourceparts="$EMPTY_DIR" \
                   -o APT::Get::List-Cleanup="0"

   $CHROOT apt-get --yes install whonix-shared

   $CHROOT apt-get --yes install whonix-shared-desktop
   
   $CHROOT apt-get --yes install whonix-shared-desktop-kde

   $CHROOT apt-get --yes install whonix-shared-kde-accessibility   
      
   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then 
      $CHROOT apt-get --yes install whonix-gateway
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      $CHROOT apt-get --yes install whonix-workstation
      
      $CHROOT apt-get --yes install whonix-workstation-default-applications
   else
      bug "ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!"
   fi
   
   $CHROOT rm --force "$WHONIX_SOURCES_LIST_TEMP_BUILD_FULL"
   
   $CHROOT apt-get update \
              --no-download \
              --list-cleanup
   
   $CHROOT sync
   sync

   umount "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"
   
   sync
   
   ## Disable apt-cacher-ng.
   export unset http_proxy   

   ./unchroot-img
   ./unprevent-daemons-from-starting   
   ./unmount-img

   sync
}

install-meta-packages

 
