#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

backup-img-after-meta-package-install() {
   trap "error_handler_general" ERR INT TERM

   cp "$WHONIX_BINARY"/"$VMNAME".img "$WHONIX_BINARY"/"$VMNAME"-backup-after-meta-package-install.img
   chown --recursive "$USERNAME":"$USERNAME" "$WHONIX_BINARY"/
}

backup-img-after-meta-package-install

