#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

run-chroot-scripts() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   sync

   ./mount-img   
   ./prevent-daemons-from-starting   
   ./chroot-img

   sync

   ## Just for testing.
   $CHROOT update-grub -v
   $CHROOT sync
   sync

   ## We need to copy the pre chroot scripts manually into the image,
   ## because the *-common packages are not yet installed at this point.
   
   ## Delete eventually already existing folder to support re-running the script.
   rm --recursive --force "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/
   
   mkdir --parents "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/
   
   cp \
     "$WHONIX_SOURCE_FOLDER"/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/* \
     "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/
     
   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then   
      cp \
        "$WHONIX_SOURCE_FOLDER"/whonix_gateway/usr/share/whonix/chroot-scripts-pre.d/* \
        "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/ 
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then   
      cp \
        "$WHONIX_SOURCE_FOLDER"/whonix_workstation/usr/share/whonix/chroot-scripts-pre.d/* \
        "$CHROOT_FOLDER"/var/lib/whonix/initial-chroot-scripts-pre.d/
   else
      bug "ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!"
   fi
   
   ## Check which chroot scripts we got.
   $CHROOT run-parts --verbose --test "/var/lib/whonix/initial-chroot-scripts-pre.d"

   ## Run the chroot scripts.
   ## (Which got copied into the image by copyinto.)
   $CHROOT run-parts --verbose --exit-on-error "/var/lib/whonix/initial-chroot-scripts-pre.d"

   sync

   ./unchroot-img   
   ./unprevent-daemons-from-starting    
   ./unmount-img

   sync
}

run-chroot-scripts

