#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

install-common-packages() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   sync

   ./mount-img   
   ./prevent-daemons-from-starting   
   ./chroot-img

   sync

   ## Just for testing.
   $CHROOT update-grub -v
   $CHROOT sync
   sync
   
   ## Enable apt-cacher-ng.
   export http_proxy="http://127.0.0.1:3142"
  
   $CHROOT gdebi --non-interactive "$DEB_INSTALL_FOLDER"/whonix-shared-common_"$VERSION"_all.deb
   
   sync
   
   if [ "$MACHINE" = "-tg" ] || [ "$MACHINE" = "-tg-bare-metal" ]; then 
      $CHROOT gdebi --non-interactive "$DEB_INSTALL_FOLDER"/whonix-gateway-common_"$VERSION"_all.deb
   elif [ "$MACHINE" = "-tw" ] || [ "$MACHINE" = "-tw-bare-metal" ]; then
      $CHROOT gdebi --non-interactive "$DEB_INSTALL_FOLDER"/whonix-workstation-common_"$VERSION"_all.deb
      
      ## DummyTor
      $CHROOT gdebi --non-interactive "$DEB_INSTALL_FOLDER"/tor_"$VERSION"_all.deb
   else
      bug "ERROR: MACHINE is $MACHINE - neither -tg nor -tg-bare-metal nor -tw nor tw-bare-metal"
   fi   
   
   sync
   
   ## Disable apt-cacher-ng.
   export unset http_proxy

   ./unchroot-img
   ./unprevent-daemons-from-starting   
   ./unmount-img

   sync
}

install-common-packages

 
