#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

install-common-packages() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   sync

   ./mount-img   
   ./prevent-daemons-from-starting   
   
   ## Deactivate mounting of /etc/resolv.conf inside chroot,
   ## because /etc/resolv.conf from whonix_gateway/whonix_workstation folder
   ## is going to be installed.
   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"
   
   ./chroot-img
   
   export unset WHONIX_CHROOT_MOUNT_RESOLV_CONF

   sync

   ## Just for testing.
   $CHROOT update-grub -v
   $CHROOT sync
   sync
   
   ## Enable apt-cacher-ng.
   export http_proxy="http://127.0.0.1:3142"
   
   mkdir --parents "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"
   mkdir --parents "$CHROOT_FOLDER"/"$EMPTY_DIR"   
   mount --bind "$WHONIX_APT_REPOSITORY_FOLDER" "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"

   local TEMP="$CHROOT_FOLDER"/etc/apt/sources.list.d/whonix_temp_initialdeb.list

   echo "deb file:$DEB_INSTALL_FOLDER/ stable main" > "$TEMP"   
   
   $CHROOT sudo apt-get update \
                   -o Dir::Etc::sourcelist="$TEMP" \
                   -o Dir::Etc::sourceparts="-" \
                   -o APT::Get::List-Cleanup="0"   
   
   sync

   $CHROOT apt-get --yes install whonix-shared-common 
   
   if [ "$MACHINE" = "-tg" ] || [ "$MACHINE" = "-tg-bare-metal" ]; then
      $CHROOT apt-get --yes install whonix-gateway-common
   elif [ "$MACHINE" = "-tw" ] || [ "$MACHINE" = "-tw-bare-metal" ]; then
      $CHROOT apt-get --yes install whonix-workstation-common
      
      ## DummyTor
      $CHROOT apt-get --yes install tor
   else
      bug "ERROR: MACHINE is $MACHINE - neither -tg nor -tg-bare-metal nor -tw nor tw-bare-metal"
   fi   

   $CHROOT rm --force "$TEMP"
   
   $CHROOT apt-get update \
              --no-download \
              --list-cleanup
   
   $CHROOT sync
   sync

   umount "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"
   
   ## Disable apt-cacher-ng.
   export unset http_proxy

   ./unchroot-img
   ./unprevent-daemons-from-starting   
   ./unmount-img

   sync
}

install-common-packages

 
