#!/bin/bash

set -x

true "Currently running script: $0"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

install-files-packages() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM
   
   if [ ! -f "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done ]; then
      error "${red}${bold}$0 ERROR: "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done does not exist. Most likely build-steps/1200_create-debian-packages has not been run yet.${reset}"
   fi   

   sync

   ./mount-img   
   ./prevent-daemons-from-starting   
   
   ## Deactivate mounting of /etc/resolv.conf inside chroot,
   ## because /etc/resolv.conf from whonix_gateway/whonix_workstation folder
   ## is going to be installed.
   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"
   
   ./chroot-img
   
   export unset WHONIX_CHROOT_MOUNT_RESOLV_CONF

   sync

   ## Just for testing.
   $CHROOT update-grub -v
   $CHROOT sync
   sync
   
   ## Enable apt-cacher-ng.
   export http_proxy="http://127.0.0.1:3142"
   
   mkdir --parents "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"
   mkdir --parents "$CHROOT_FOLDER"/"$EMPTY_DIR"   
   mount --bind "$WHONIX_APT_REPOSITORY_FOLDER" "$WHONIX_INITIAL_DEB_INSTALL_FOLDER"

   cp "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/pubring.gpg "$CHROOT_FOLDER"/etc/apt/trusted.gpg.d/whonix-temporary-local-apt-repository.gpg
   
   echo "deb file:"$DEB_INSTALL_FOLDER"/ local main" > "$WHONIX_SOURCES_LIST_TEMP_BUILD_FULL"
   
   $CHROOT apt-get update \
                   -o Dir::Etc::sourcelist="$WHONIX_SOURCES_LIST_TEMP_BUILD_BASE" \
                   -o Dir::Etc::sourceparts="$EMPTY_DIR" \
                   -o APT::Get::List-Cleanup="0"   
   
   sync

   $CHROOT apt-get --yes install whonix-shared-files 
   
   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      $CHROOT apt-get --yes install whonix-gateway-files
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      $CHROOT apt-get --yes install whonix-workstation-files
      
      ## DummyTor
      $CHROOT apt-get --yes install tor
   else
      bug "${red}${bold}ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!${reset}"
   fi   

   rm --force "$WHONIX_SOURCES_LIST_TEMP_BUILD_FULL"

   $CHROOT apt-get update \
              --no-download \
              --list-cleanup
   
   $CHROOT sync
   sync
   
   ## Disable apt-cacher-ng.
   export unset http_proxy

   ./unchroot-img
   ./unprevent-daemons-from-starting   
   ./unmount-img

   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
install-files-packages

 
