#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

convert_img-to_vdi() {
   trap "error_handler_general" ERR INT TERM

   sudo -u "$USERNAME" \
      mkdir --parents ""$HOMEVAR"/VirtualBox VMs/""$VMNAME"
   
   sudo -u "$USERNAME" \
      VBoxManage convertfromraw "$WHONIX_BINARY"/"$VMNAME".img ""$HOMEVAR"/VirtualBox VMs/""$VMNAME"/"$VMNAME".vdi
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping $0, because BARE_METAL is set to 1.${reset}"
else
   true "${bold}INFO: Currently running script: $0${reset}"
   convert_img-to_vdi
fi


