#!/bin/bash

set -x

true "$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/variables
source "$MYDIR"/pre

copy_img() {
   ## error_handler_general

   cp /home/user/whonix_binary/"$VMNAME".img /home/"$USERNAME"/whonix_binary/"$VMNAME"_copy.img
} 

