#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

copy_img() {
   trap "error_handler_general" ERR INT TERM

   cp /home/"$USERNAME"/whonix_binary/"$VMNAME".img /home/"$USERNAME"/whonix_binary/"$VMNAME"_copy.img
   chown --recursive user:user /home/"$USERNAME"/whonix_binary/
}

copy_img

