#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

copy_img() {
   trap "error_handler_general" ERR INT TERM

   cp "$WHONIX_BINARY"/"$VMNAME".img "$WHONIX_BINARY"/"$VMNAME"_copy.img
   chown --recursive "$USERNAME":"$USERNAME" "$WHONIX_BINARY"/
}

copy_img

