#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

export-vbox-vm() {
   trap "error_handler_general" ERR INT TERM

   ## Not yet using: --producturl
   
   sudo -u "$USERNAME" \
      VBoxManage export "$VMNAME" \
         --manifest \
         --vsys "0" \
         --product "$VMNAME" \
         --vendor "Whonix" \
         --vendorurl "http://whonix.sourceforge.net" \
         --version "$VERSION" \
         --output "$WHONIX_BINARY"/"$VMNAME".ova
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO${reset}: Skipping $0, because BARE_METAL is set to 1."
else
   export-vbox-vm
fi

