#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

export-vbox-vm() {
   trap "error_handler_general" ERR INT TERM

   sudo -u "$USERNAME" VBoxManage export "$VMNAME" --output "$WHONIX_BINARY"/"$VMNAME".ova
}

export-vbox-vm

