#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

trap "error_handler_general" ERR INT TERM

error_handler_copy-into-img() {
: echo "
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
"

   ./unmount-img

: echo "
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
"

   exit 1
}

copy_into_vm_image_whonix_gateway() {
   trap "error_handler_copy-into-img" ERR INT TERM

   copy_backup_shared
   copy_into_shared

   copy_backup_gateway
   copy_into_gateway

   ## Ensure changes get written before unmounting.
   sync
}

copy_into_vm_image_whonix_workstation() {
   trap "error_handler_copy-into-img" ERR INT TERM

   copy_backup_shared
   copy_into_shared

   copy_backup_workstation
   copy_into_workstation

   ## Ensure changes get written before unmounting.
   sync
}

copy_backup_shared() {
   trap "error_handler_copy-into-img" ERR INT TERM

   ## Better no backup of localtime.
   #cp --no-clobber "$CHROOT_FOLDER"/etc/localtime "$CHROOT_FOLDER"/etc/localtime.backup

   ## Better no backup of dbusmachineid.
   #cp --no-clobber "$CHROOT_FOLDER"/var/lib/dbus/machine-id "$CHROOT_FOLDER"/var/lib/dbus/machine-id.backup

   touch "$CHROOT_FOLDER"/etc/motd
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/motd "$CHROOT_FOLDER"/etc/motd.backup || true

   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/apt/sources.list "$CHROOT_FOLDER"/etc/apt/sources.list.backup
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/hosts "$CHROOT_FOLDER"/etc/hosts.backup || true
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/issue "$CHROOT_FOLDER"/etc/issue.backup || true
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/inittab "$CHROOT_FOLDER"/etc/inittab.backup || true
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/network/interfaces "$CHROOT_FOLDER"/etc/network/interfaces.backup
}

copy_into_shared() {
   trap "error_handler_copy-into-img" ERR INT TERM

   ## /etc/motd
   ## rm to get ride of the symlink, in case there is any.
   ## http://wiki.debian.org/motd
   rm "$CHROOT_FOLDER"/etc/motd || true

   ## delete default symlink to "$CHROOT_FOLDER"/etc/dpkg/origins/debian
   rm "$CHROOT_FOLDER"/etc/dpkg/origins/default || true

   ## copy skel to user home
   cp --recursive --preserve "$CHROOT_FOLDER"/etc/skel/. "$CHROOT_FOLDER"/home/user

   ## Ensure timezone is UTC.
   ## Remove symlink, if any.
   unlink "$CHROOT_FOLDER"/etc/localtime || true
   cp --recursive --preserve "$CHROOT_FOLDER"/usr/share/zoneinfo/UTC "$CHROOT_FOLDER"/etc/localtime

   ## Copy
   rsync --verbose --perms --recursive --checksum "$WHONIX_SOURCE_FOLDER"/whonix_shared/ "$CHROOT_FOLDER"/

   ## /etc/dpkg/origins/default
   ## symlink is created by /home/user/Whonix/whonix_shared/usr/share/whonix/chroot-scripts/70_symlinks

   ## Permissions for /home/user get fixed by int_copy_gateway or int_copy_workstation.
}

copy_backup_gateway() {
   trap "error_handler_copy-into-img" ERR INT TERM

   ## Backup torrc inside VM before replacing it with Whonix version.
   cp --no-clobber "$CHROOT_FOLDER"/etc/tor/torrc "$CHROOT_FOLDER"/etc/tor/torrc.backup
}

copy_into_gateway() {
   trap "error_handler_copy-into-img" ERR INT TERM

   ## copy skel to clearnet home
   cp --recursive --preserve "$CHROOT_FOLDER"/etc/skel/. "$CHROOT_FOLDER"/home/clearnet

   ## copy skel to user home is done in int_copy_shared

   ## Copy
   rsync --verbose --perms --recursive --checksum "$WHONIX_SOURCE_FOLDER"/whonix_gateway/ "$CHROOT_FOLDER"/

   
   trap "" ERR INT TERM
   id "clearnet"
   if [ ! "$?" = 0 ]; then
      trap "error_handler_copy-into-img" ERR INT TERM

      ## This is required for chown --recursive clearnet:clearnet...
      
      echo 'INFO: Creating user "clearnet"...'
      ## setting password of user clearnet to changeme
      ##
      ## How this password was created:
      ## sudo apt-get install whois
      ## mkpasswd
      ## changeme
      ## Resulted in: aTayYxVyw5kDo
      ##
      useradd --create-home --password aTayYxVyw5kDo --user-group --shell /bin/bash clearnet
   else
      trap "error_handler_copy-into-img" ERR INT TERM
      echo 'INFO: Not creating user "clearnet", because it already exists.'
   fi

   trap "error_handler_copy-into-img" ERR INT TERM

   ## Fix /home/clearnet permissions.
   chown --recursive clearnet:clearnet "$CHROOT_FOLDER"/home/clearnet

   ## Fix /home/user permissions.
   chown --recursive user:user "$CHROOT_FOLDER"/home/user
}

copy_backup_workstation() {
   trap "error_handler_copy-into-img" ERR INT TERM

   ## /etc/polipo/config
   ## not installing polipo by default
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/whonix_workstation/etc/polipo/config "$CHROOT_FOLDER"/etc/polipo/config.backup || true

   ## /etc/kde4/kdm/kdmrc
   ## Overriding with true because its only for kde autologin for the case kde does not get installed in custom builds.
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/kde4/kdm/kdmrc "$CHROOT_FOLDER"/etc/kde4/kdm/kdmrc.backup || true
}

copy_into_workstation() {
   trap "error_handler_copy-into-img" ERR INT TERM

   ## /etc/resolv.conf
   ## We do not need chattr +i for Whonix-W resolv.conf, because
   ## DHCP is never used and resolvconf was uninstalled.

   ## /home/user/Desktop symlinks get created by
   ## /home/user/Whonix/whonix_workstation/usr/share/whonix/chroot-scripts/70_desktop-icons

   ## copy skel to user home is done in int_copy_shared

   ## Copy
   rsync --verbose --perms --recursive --checksum "$WHONIX_SOURCE_FOLDER"/whonix_workstation/ "$CHROOT_FOLDER"/

   ## Fix permissions for /home/user/.
   mkdir --parents "$CHROOT_FOLDER"/home/user/
   chown --recursive user:user "$CHROOT_FOLDER"/home/user/
}

./mount-img

if [ "$MACHINE" = "-tg" ] || [ "$MACHINE" = "-tg-bare-metal" ]; then
   copy_into_vm_image_whonix_gateway
elif [ "$MACHINE" = "-tw" ] || [ "$MACHINE" = "-tw-bare-metal" ]; then
   copy_into_vm_image_whonix_workstation
else
   bug "ERROR: MACHINE is $MACHINE - neither -tg nor -tw"
fi

./unmount-img

