#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

convert_img-to_vdi() {
   trap "error_handler_general" ERR INT TERM

   sudo -u "$USERNAME" mkdir --parents ""$HOMEVAR"/VirtualBox VMs/""$VMNAME"
   sudo -u "$USERNAME" VBoxManage convertfromraw "$HOMEVAR"/whonix_binary/"$VMNAME"_copy.img ""$HOMEVAR"/VirtualBox VMs/""$VMNAME"/"$VMNAME".vdi
}

convert_img-to_vdi


