#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

## Create folder.
mkdir --parents /usr/local/share/whonix/sources/

cd /usr/local/share/whonix/sources/

apt-get --config-file /usr/local/share/whonix/apt.conf update

for i in `/usr/local/share/whonix/damngpl --source /var/lib/dpkg/status`; do
   apt-get --config-file /usr/local/share/whonix/apt.conf --download-only source $i;
done

 
