#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012, 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

ret=0
id "clearnet" || { ret=$? ; true; };

if [ ! "$ret" = 0 ]; then
   echo 'INFO: Creating user "clearnet"...'
   ## setting password of user clearnet to changeme
   ##
   ## How this password was created:
   ## sudo apt-get install whois
   ## mkpasswd
   ## changeme
   ## Resulted in: aTayYxVyw5kDo
   useradd --create-home --password aTayYxVyw5kDo --user-group --shell /bin/bash clearnet
else
   echo 'INFO: Not creating user "clearnet", because it already exists.'
fi


