#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

touch /var/log/controlportfilt.log

chown --recursive debian-tor:debian-tor /var/log/controlportfilt.log
