#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

## NOTE:
## /usr/share/whonix/postinst.d/70_legacy prevents this script from getting run
## on older versions not supporting the verifiable builds feature.

first_run_initializer_exit_code="0"

error_handler() {
   true "ERROR: exited with non-zero exit code: $?"
   first_run_initializer_exit_code="1"
}

trap "error_handler" ERR

true "INFO: Running Whonix First Run Initializer..."

if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
else
    true "INFO: Script running as root."
fi

export DEBIAN_FRONTEND="noninteractive"

## {{{ /var/lib/whonix/initial-packages

## Using a simpler method to install initial packages.
## Leaving dependency resolution to dpkg.
##
## Modifications comment:
## It has a little disadvantage, it may re-install packages, which have been
## uninstalled by advanced users between running chroot-post.d scripts and
## finalizing/importing the image. It should not hinder creation modifications
## of Whonix, because in the cleanup chroot-post.d script, we do not download
## packages (for later re-installation at this point), which are not installed
## at that point.

## Debugging.
ls -la /var/lib/dpkg/lock || true
ps aux | grep dpkg || true

true "\
INFO: Running dpkg --install /var/lib/whonix/initial-packages/* for the first time...
      The errors:
      - update-xmlcatalog: error: root catalog /etc/xml/catalog not found
      - update-xmlcatalog: error: package catalog /etc/xml/docbook-xml.xml not found
      are expected and can be ignored. When running dpkg for the second time, they will be gone."
dpkg --install "/var/lib/whonix/initial-packages/"* || true
true "INFO: Done running dpkg for the first time."

## Debugging.
ls -la /var/lib/dpkg/lock
ps aux | grep dpkg || true

## This may not be necessary.
## Re-running the same command, so we can see in the log, if it runs without
## any warnings the second time.
true "Running dpkg --install /var/lib/whonix/initial-packages/* for the \
second and final time..."
dpkg --install "/var/lib/whonix/initial-packages/"*
true "INFO: Done running dpkg for the second and final time."

## }}}

## non-deterministic [14]
## /etc/init.d/.depend.boot
## /etc/init.d/.depend.start
## /etc/init.d/.depend.stop
if [ -x /sbin/insserv ]; then
   /sbin/insserv --showall
   /sbin/insserv --verbose
fi

## non-deterministic [17]
## /etc/apt/trustdb.gpg
## Thanks to:
## https://unix.stackexchange.com/questions/110500/how-to-regenerate-etc-apt-trustdb-gpg-on-debian
## This is no longer required for Debian Jessie?
apt-key update

dpkg --configure -a

true "INFO: End of First Run Initializer."

exit "$first_run_initializer_exit_code"
