#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## dummytor

unlink /usr/bin/tor || true
unlink /usr/sbin/tor || true

dpkg-divert --rename --remove /usr/sbin/tor || true
dpkg-divert --add --rename --divert /usr/sbin/tor.real /usr/sbin/tor

dpkg-divert --rename --remove /usr/bin/tor || true
dpkg-divert --add --rename --divert /usr/bin/tor.real /usr/bin/tor

ln -s /usr/lib/whonix/dummytor /usr/bin/tor
ln -s /usr/lib/whonix/dummytor /usr/sbin/tor
