#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

sudo -u user mkdir --parents /home/user/Desktop/

## Adding konsole icon on Desktop.
sudo -u user ln -s /usr/share/applications/kde4/konsole.desktop /home/user/Desktop/ || true

## Adding kgpg icon on Desktop.
sudo -u user ln -s /usr/share/applications/kde4/kgpg.desktop /home/user/Desktop/ || true

## Adding synaptic icon on Desktop.
#sudo -u user ln -s /usr/share/applications/synaptic-kde.desktop /home/user/Desktop/ || true

## Adding Apper icon on Desktop.
sudo -u user ln -s /usr/share/applications/kde4/apper.desktop /home/user/Desktop/ || true

## Adding xchat icon on Desktop.
## Symlink xchat starter to Desktop.
## Override with true in case xchat gets removed from package selection.
sudo -u user ln -s /usr/share/applications/xchat.desktop /home/user/Desktop/ || true

## symlink .desktop files to Desktop folder

sudo -u user ln -s /usr/share/applications/whonix/whonix-contribute.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-mailinglist.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-torbrowser.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-torbrowser_update.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-documentation.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-forum.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-tbrecommend.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-donate.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-timesync.desktop /home/user/Desktop || true

sudo -u user ln -s /usr/share/applications/whonix/whonix-whonixcheck.desktop /home/user/Desktop || true

#sudo -u user ln -s /usr/share/applications/whonix/whonix-featureblog.desktop /home/user/Desktop || true

#sudo -u user ln -s /usr/share/applications/whonix/whonix-importantblog.desktop /home/user/Desktop || true
