#!/bin/bash

set -x

error_handler() {
   echo "
#############################################################
## postinst script: ERROR detected. Please report this bug! #
#############################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

if [ -e /home/user/.gnupg/gpg.conf ]; then
   true "INFO: Skipping $own_filename, not replacing /home/user/.gnupg/gpg.conf, because it already exists."
   exit 0
fi

sudo -u user cp /usr/share/whonix/home/.gnupg/gpg.conf /home/user/.gnupg/gpg.conf


