#!/bin/bash

source /usr/share/whonix/postinst.d/pre.bsh

if [ -e /home/user/.gnupg/gpg.conf ]; then
   true "INFO: Skipping $own_filename, not replacing /home/user/.gnupg/gpg.conf, because it already exists."
   exit 0
fi

sudo -u user mkdir /home/user/.gnupg
sudo -u user chmod --recursive 700 /home/user/.gnupg

sudo -u user cp /usr/share/whonix/home/.gnupg/gpg.conf /home/user/.gnupg/gpg.conf

## sanity test
sudo -u user gpg --gpgconf-test

