#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

if [ -e /home/user/.Mix/mix.cfg ]; then
   true "INFO: Skipping $own_filename, not replacing /home/user/.Mix/mix.cfg, because it already exists."
   exit 0
fi

sudo -u user mkdir /home/user/.Mix/

sudo -u user cp /usr/share/whonix/home/.Mix/mix.cfg /home/user/.Mix/mix.cfg

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
