#!/bin/bash

set -x

error_handler() {
   echo "
#############################################################
## postinst script: ERROR detected. Please report this bug! #
#############################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

## TorChat does not get installed by default.
## Just for easier user instructions the required file gets copied 

if [ -e /home/user/.torchat/torchat.ini ]; then
   true "INFO: Skipping $own_filename, because /home/user/.torchat/torchat.ini already exists."
   exit 0
fi

sudo -u user mkdir /home/user/.torchat

sudo -u user cp /usr/share/whonix/home/.torchat/torchat.ini /home/user/.torchat/torchat.ini

