#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## TorChat does not get installed by default.
## Just for easier user instructions the required file gets copied

if [ -e /home/user/.torchat/torchat.ini ]; then
   true "INFO: Skipping $own_filename, because /home/user/.torchat/torchat.ini already exists."
   exit 0
fi

sudo -u user mkdir /home/user/.torchat

sudo -u user cp /usr/share/whonix/home/.torchat/torchat.ini /home/user/.torchat/torchat.ini

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
