#!/bin/bash

if [ "$WHONIX_DEB_DEBUG" = "1" ]; then
   set -x
fi

error_handler() {
   echo "
#############################################################
## postinst script: ERROR detected. Please report this bug! #
## scriptname: $0
## BASH_COMMAND: $BASH_COMMAND
#############################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

## Not overwriting the users XChat data folder,
## important once this may be run as postinst script.
if [ -d /home/user/.xchat2 ]; then
   true "INFO: Skipping $own_filename, because /home/user/.xchat2 already exists."
   exit 0
fi

## Ok, this script runs for the very first time. The users XChat data
## folder does not exist yet. Therefore it's safe to create it.

## Using xchat-reset to copy privacy hardened configuration files from
## /usr/share/whonix/home/.xchat2/* to /home/user/.xchat2/.
xchat-reset

## Disable plugins to reduce attack surface.
## User documentation contains how to re-enable these plugins.

dpkg-divert --add --rename --divert /usr/lib/xchat/plugins/python.so.real /usr/lib/xchat/plugins/python.so

dpkg-divert --add --rename --divert /usr/lib/xchat/plugins/tcl.so.real /usr/lib/xchat/plugins/tcl.so

## For custom builds perhaps keep perl.so for SASL.
dpkg-divert --add --rename --divert /usr/lib/xchat/plugins/perl.so.real /usr/lib/xchat/plugins/perl.so

#dpkg-divert --list

