#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Not overwriting the user's XChat data folder,
## important once this may be run as postinst script.
if [ -d /home/user/.xchat2 ]; then
   true "INFO: Skipping $own_filename, because /home/user/.xchat2 already exists."
   exit 0
fi

## Ok, this script runs for the very first time. The user's XChat data
## folder does not exist yet. Therefore it's safe to create it.

## Using xchat-reset to copy privacy hardened configuration files from
## /usr/share/whonix/home/.xchat2/* to /home/user/.xchat2/.
xchat-reset

## Disable plugins to reduce attack surface.
## User documentation contains how to re-enable these plugins.

## The DPKG_MAINTSCRIPT_PACKAGE related hack is documented in the 70_uwt
## postinst.d script.
DPKG_MAINTSCRIPT_PACKAGE_BACKUP="$DPKG_MAINTSCRIPT_PACKAGE"

unset DPKG_MAINTSCRIPT_PACKAGE
dpkg-divert --rename --remove /usr/lib/xchat/plugins/python.so || true
export DPKG_MAINTSCRIPT_PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE_BACKUP"

dpkg-divert --add --rename --divert /usr/lib/xchat/plugins/python.so.real /usr/lib/xchat/plugins/python.so

unset DPKG_MAINTSCRIPT_PACKAGE
dpkg-divert --rename --remove /usr/lib/xchat/plugins/tcl.so || true
export DPKG_MAINTSCRIPT_PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE_BACKUP"

dpkg-divert --add --rename --divert /usr/lib/xchat/plugins/tcl.so.real /usr/lib/xchat/plugins/tcl.so

## For custom builds perhaps keep perl.so for SASL.
unset DPKG_MAINTSCRIPT_PACKAGE
dpkg-divert --rename --remove /usr/lib/xchat/plugins/perl.so || true
export DPKG_MAINTSCRIPT_PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE_BACKUP"

dpkg-divert --add --rename --divert /usr/lib/xchat/plugins/perl.so.real /usr/lib/xchat/plugins/perl.so

#dpkg-divert --list

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
