#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

## KDM (Whonix default login manager) sysvinit autostart gets disabled, because
## in /etc/profile.d/20_desktop.sh we implement out own way to decide whether to
## autostart kdm based on total amount of RAM, default and user settings.

update-rc.d kdm remove
