#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t error_handler_unchroot_unprevent_unmount)" = "function" ]; then
   ## Function error_handler_unchroot_unprevent_unmount exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "error_handler_unchroot_unprevent_unmount" ERR
else
   ## Function error_handler_unchroot_unprevent_unmount does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Enable apt-cacher-ng proxy.
export http_proxy="http://127.0.0.1:3142"

mkdir --parents "$EMPTY_DIR"

## Debugging.
true "UWT_DEV_PASSTHROUGH: $UWT_DEV_PASSTHROUGH"

## Debugging.
export UWT_VERBOSE=1
true "UWT_VERBOSE: UWT_VERBOSE"

## Debugging.
which torsocks
which uwt

## Update torproject repository upstream package lists, so latest version of Tor, torsocks and obfsproxy gets known.
apt-get \
   $apt_timeout_opts \
   -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/torproject.list" \
   -o Dir::Etc::sourceparts="$EMPTY_DIR" \
   -o APT::Get::List-Cleanup="0" \
   update

## Disable apt-cacher-ng proxy.
unset http_proxy

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
