#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   echo "
#############################################################
## chroot script: ERROR detected. Please report this bug!   #
## scriptname: $0
## BASH_COMMAND: $BASH_COMMAND
#############################################################
"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t error_handler_unchroot_unprevent_unmount)" = "function" ]; then
   ## Function error_handler_unchroot_unprevent_unmount exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "error_handler_unchroot_unprevent_unmount" ERR
else
   ## Function error_handler_unchroot_unprevent_unmount does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

sudo -u user cp /usr/share/whonix/home/.bashrc /home/user/.bashrc

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
