#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

echo "INFO: Logging WHONIX_BUILD_WHONIX_VERSION_NEW $WHONIX_BUILD_WHONIX_VERSION_NEW to /usr/share/whonix/build_version..."

## Support re-running the script.
rm --force "/usr/share/whonix/build_version"

## Debugging.
touch "/usr/share/whonix/build_version"

## Logging.
echo "$WHONIX_BUILD_WHONIX_VERSION_NEW" > "/usr/share/whonix/build_version"

## Debugging.
cat "/usr/share/whonix/build_version"
