#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t error_handler_unchroot_unprevent_unmount)" = "function" ]; then
   ## Function error_handler_unchroot_unprevent_unmount exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "error_handler_unchroot_unprevent_unmount" ERR
else
   ## Function error_handler_unchroot_unprevent_unmount does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Info.
echo "INFO: Logging whonix_build_whonix_version_new $whonix_build_whonix_version_new to /usr/share/whonix/build_version..."

## Sanity test.
if [ "$whonix_build_whonix_version_new" = "" ]; then
   echo "ERROR: whonix_build_whonix_version_new is empty! Please report this bug!"
   exit 1
fi

## Support re-running the script.
rm --force "/usr/share/whonix/build_version"

## Debugging.
touch "/usr/share/whonix/build_version"

## Logging.
echo "$whonix_build_whonix_version_new" > "/usr/share/whonix/build_version"

## Debugging.
cat "/usr/share/whonix/build_version"

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
