#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

## Enable apt-cacher-ng proxy.
export http_proxy="http://127.0.0.1:3142"

## Installing torsocks from Torprojects repository,
## in case that is more current than the Debian repository.
## Override with || true in case Torprojects repository does include torsocks.
apt-get \
   $apt_timeout_opts \
   --yes \
   -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/torproject.list" \
   -o Dir::Etc::sourceparts="$EMPTY_DIR" \
   install torsocks \
   || true

## Disable apt-cacher-ng proxy.
unset http_proxy
