#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

ARCH="$(uname --machine)"
true "${cyan}$0 INFO: Architecture $ARCH detected.${reset}"
true "${cyan}INFO: WHONIX_TARGET_ARCH set to: $WHONIX_TARGET_ARCH${reset}"

if [ "$BARE_METAL" = "1" ]; then
   ## See chroot-post script 71_install_686_pae_kernel for a comment why.
   true "$0 INFO: Skipping installation of a kernel, because BARE_METAL is set to $BARE_METAL, ok."
   exit 0
fi

if [ "$CI" = "true" ]; then
   true "$0 INFO: Skipping, because CI detected."
   exit 0
fi

## Enable apt-cacher-ng proxy.
export http_proxy="http://127.0.0.1:3142"

## This is a chroot-script and not a postinst.d script. Once it's installed on the user's
## system, apt-get will keep care of upgrading it. The user is free to uninstall it.
## (In case the user uses the 486 kernel or something entirely different.)

## Install 686 pae kernel.
apt-get $apt_sourcelist_empty $apt_sourceparts $apt_timeout_opts $apt_verify_opts --yes install linux-image-amd64 linux-headers-amd64

## Disable apt-cacher-ng proxy.
unset http_proxy

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
