#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

true "INFO: Running \"vrms\", as a sanity test, to check if packages from the contrib or non-free APT repository have been accidentally installed."
## For visible output, debugging.
vrms

## For machine readable output, taking action depending on.
vrms_result="$(vrms --quiet)"

if [ "$vrms_result" = "" ]; then
   true "INFO $0: No non-free or contrib packages detected."
else
   if [ "$CI" = "true" ]; then
      true "INFO $0: Non-free or contrib packages detected. Continuing, because CI detected."
   else
      error "ERROR $0: Non-free or contrib packages detected! See above!"
   fi
fi
