#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

echo "INFO: Cleaning up..."

## Kill dhclient3 to prevent rewrite of /var/lib/dhcp/*.
killall dhclient3 || true
## There are .leases.
rm /var/lib/dhcp/*.leases || true
## And there are .lease.
rm /var/lib/dhcp/*.lease || true
## We are best of deleting the whole folder.
rm -r /var/lib/dhcp/* || true

## Cleanup.
apt-get --yes autoremove --purge || true
apt-get --yes clean || true

## No longer deleting /var/lib/tor. We install but forbid to run software such as Tor we install.
## Therefore /var/lib/tor should be empty.
## Ensure to delete /var/lib/tor. It contains sensitive stuff like the Tor consensus and the Tor entry guards.
## rm -r /var/lib/tor/* || true

## Delete logs and other stuff.
rm -r /tmp/* || true
rm /var/log/installer/* || true
rm -r /var/cache/apt/* || true
rm -r /var/lib/apt/lists/* || true
rm -r /var/log/installer || true
rm /var/lib/dpkg/*-old || true
rm /var/cache/debconf/*-old || true
## Erase rotated logs (usually wont appear unless you left your VM running for several days).
rm /var/log/*.[0-9] || true
rm /var/log/*.[0-9].gz || true

## Truncate all log files, keeping user group and perms.
find /var/log -type f -exec cp /dev/null {} \;

## This will not work in chroot.
## Take care of development leaks and make resulting ova image smaller.
## Since VBox export works below the FS level it will keep deleted files (and the ova will stay large). 
## This also ensure that possible leaks we deleted before are really deleted.
#echo "INFO: Wiping free space. This can take a while."
## TODO CHROOT #dd if=/dev/zero of=/zerofile bs=1024 || true

## Flush the zero-file to disk before removing it.
sync

## Delete the zero-file.
rm /zerofile || true

## Flush again after rm.
sync

## Delete bash history.
rm /home/"$USERNAME"/.bash_history || true
history -c || true

sync
 
