#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

## backup
mkdir --parents /var/lib/whonix/grub-backup

if [ "$CI" = "true" ]; then
   true "INFO $0: Skipping, because CI detected."
else
   cp /boot/grub/grub.cfg /var/lib/whonix/grub-backup/grub.cfg.whonix-chroot-post2

   ## Update grub, so changes in /etc/default/grub will take effect.
   update-grub
fi
