#!/bin/bash

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

## backup
cp /boot/grub/grub.cfg /boot/grub/grub.cfg.whonix-chroot-post2

## Update grub, so changes in /etc/default/grub will take effect.
update-grub

