#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t error_handler_unchroot_unprevent_unmount)" = "function" ]; then
   ## Function error_handler_unchroot_unprevent_unmount exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "error_handler_unchroot_unprevent_unmount" ERR
else
   ## Function error_handler_unchroot_unprevent_unmount does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## just another backup
mkdir --parents /var/lib/whonix/grub-backup

if [ "$CI" = "true" ]; then
   true "INFO $0: Skipping, because CI detected."
else
   ## Non-deterministic on Debian Wheezy. Should work on Debian Jessie.
   #cp /boot/grub/grub.cfg /var/lib/whonix/grub-backup/grub.cfg.whonix-chroot-post3
   true
fi

## Installation of 486 kernel (in chroot-scripts-post.d 70_install_486_kernel)
## might have run update-grub (as part of its postinst script) and
## the 85_update_grub chroot-scripts-post.d script runs update-grub to let changes in
## /etc/default/grub take effect.
## grub has a bug to mess up /boot/grub/grub.cfg when run inside chroot
## (which will get fixed in grub 2.something).
## Therefore we have to fix it here.

if [ "$BARE_METAL" = "1" ]; then
   true "INFO $0: Fixing /boot/grub/grub.cfg is not required for bare metal builds (BARE_METAL is set to 1), skipping."
else
   if [ "$CI" = "true" ]; then
      true "INFO $0: Skipping, because CI detected."
   else
      true "INFO $0: Fixing /boot/grub/grub.cfg to work around a bug in grub when run inside chroot..."

      ## For the following two lines, credit goes to grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
      ## It's taken from usr/sbin/grml-debootstrap, from grml-debootstrap package, which is licensed GPL v2+.
      sed -i "s;set root=.*;set root='(hd0,msdos1)';" /boot/grub/grub.cfg
      sed -i "s;root=[^ ]\+;root=/dev/sda1;" /boot/grub/grub.cfg

      true "INFO $0: Fixed /boot/grub/grub.cfg."
   fi
fi

## just another backup
mkdir --parents /var/lib/whonix/grub-backup

if [ "$CI" = "true" ]; then
   true "INFO $0: Skipping, because CI detected."
else
   cp /boot/grub/grub.cfg /var/lib/whonix/grub-backup/grub.cfg.whonix-chroot-post4
fi

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
