#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

echo "
######################################################
# checks
######################################################
"

echo "Checking if the system is functional and continuing apt-get if the script failed before,"
echo "by running dpkg --configure -a. Can take a while."
dpkg --configure -a

echo "Checking if sysctcl -p runs without an error."
sysctl -p

