#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

echo "
## GRUB_CMDLINE_LINUX_DEFAULT="" has been appended to /etc/default/grub
## for more verbose output while booting, to show the system does not hang.
## We need to run update-grub2 to activate the change.
## Bug: It does not work inside chroot.
## TODO CHROOT: update-grub2
"

