#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

echo "Creating the htp user..."
adduser --system --quiet --group --no-create-home htp || :

echo "Adding htpdate init script..."
update-rc.d htpdate defaults
 
