#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

ARCH="$(uname --machine)"

true "INFO: Architecture $ARCH detected."

if [ ! "$ARCH" = "i686" ]; then
   true "INFO: Architecture $ARCH is not i686, not installing linux-image-486."
   true "      (This is because, trying to install linux-image-486 on x86_64 would fail."
   exit 0
fi

## Updating package lists.
apt-get --config-file /usr/local/share/whonix/apt.conf update

## Installing extra kernel for compatibility with older non-pae systems.
## Documented in FAQ.
apt-get --yes --config-file /usr/local/share/whonix/apt.conf install linux-image-486

