#!/bin/bash

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

ARCH="$(uname --machine)"

true "INFO: Architecture $ARCH detected."

if [ ! "$ARCH" = "i686" ]; then
   true "INFO: Architecture $ARCH is not i686, not installing linux-image-486."
   true "      (This is because, trying to install linux-image-486 on x86_64 would fail."
   exit 0
fi

## Installing extra kernel for compatibility with older non-pae systems.
## Documented in FAQ.
apt-get --yes --config-file /usr/local/share/whonix/apt.conf install linux-image-486

## This is a chroot-script and not a postinst.d script, because the linux-image-486
## gets only installed for compatibility reasons. Once its installed on the users
## system, apt-get will keep care of upgrading it. The user is free to uninstall it.

