#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

###########
# damngpl #
###########

## Create folder.
mkdir -p /usr/local/share/whonix/
mkdir -p /usr/local/share/whonix/gpl/

## Outputs format "package=1:1.0-1"
/usr/local/share/whonix/damngpl --source > /usr/local/share/whonix/gpl/damngpl_source

## Outputs format "package_1.0-1"
/usr/local/share/whonix/damngpl --dget > /usr/local/share/whonix/gpl/damngpl_dget

## Outputs snapshot.debian.net deb-src lines
/usr/local/share/whonix/damngpl --snapshot > /usr/local/share/whonix/gpl/damngpl_snapshot

####################
# download sources #
####################

## Create folder.
mkdir -p /usr/local/share/whonix/
mkdir -p /usr/local/share/whonix/sources/

cd /usr/local/share/whonix/sources/

apt-get --config-file /usr/local/share/whonix/apt.conf update

for i in `/usr/local/share/whonix/damngpl -s /var/lib/dpkg/status`; do
   apt-get --config-file /usr/local/share/whonix/apt.conf --download-only source $i;
done

