#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM


## update-command-not-found internally uses curl.
## The curl uwt wrapper does not yet work inside
## chroot, because on Whonix-Workstation,
## Whonix-Gateway may not be running yet and on
## Whonix-Gateway, Tor will not be running yet.
## Therefore temporarily disable the curl uwt
## wrapper.
chmod -x /usr/local/bin/curl

## Just for convenience so the user will not be
## promoted "Please update-command-not-found.".
update-command-not-found

## Re-enable the curl uwt wrapper.
chmod +x /usr/local/bin/curl

