#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

cd help-steps

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

source variables

version="$whonix_build_closest_git_tag"

mkdir --parents "$WHONIX_BINARY"

cd "/mnt/shared/"

cp "sha512sum" "$WHONIX_BINARY/"
sync

cp "sha1sum" "$WHONIX_BINARY/"
sync

cp "Whonix-Gateway-"$version".ova" "$WHONIX_BINARY/"
cp "Whonix-Gateway-"$version".qcow2" "$WHONIX_BINARY/"
sync

cp "Whonix-Workstation-"$version".ova" "$WHONIX_BINARY/"
cp "Whonix-Workstation-"$version".qcow2" "$WHONIX_BINARY/"
sync
