#!/bin/bash

set -x

error_handler() {
   echo "FAILED!"
   exit 1
} 

trap "error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

cd help-steps

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

source variables

## hardcoded
version="118adretemp"

cd "$WHONIX_BINARY"

## Create sha512sum sum to ensure copying was done without bit flip.
sha512sum *.ova > sha512sum

## Debugging.
cat sha512sum

## Create sha1sum to compare with sourceforge.
sha1sum *.ova > sha1sum

## Debugging.
cat sha1sum

cp "sha512sum" "/mnt/shared/"

cp "sha1sum" "/mnt/shared/"

cp "Whonix-Gateway-"$version".ova" "/mnt/shared/"

cp "Whonix-Workstation-"$version".ova" "/mnt/shared/"
