#!/bin/bash

## Thanks to:
## https://github.com/moba/createtortorrents/blob/master/createtorrents.sh 

#TRACKERS="udp://tracker.openbittorrent.com:80/announce,udp://tracker.publicbt.com:80/announce,http://tracker.openbittorrent.com:80/announce,http://tracker.publicbt.com:80/announce,udp://tracker.ccc.de/announce"

TRACKERS="http://announce.torrentsmd.com:6969/announce"

#Not well supported by BitTorrent clients.
#mktorrent \
#   --verbose \
#   --announce="$TRACKERS" \
#   --web-seed http://178.18.17.174:8008/Whonix-Workstation-0.5.6.ova \
#   --web-seed http://178.18.17.174:8008/Whonx-Gateway-0.5.6.ova \
#   ~/0.5.6
   
mktorrent 
   --verbose \
   --announce="$TRACKERS" \
   --web-seed http://178.18.17.174:8008/Whonix-Gateway-0.5.6.ova \
   ~/0.5.6/Whonix-Gateway.ova 

mktorrent \
   --verbose \
   --announce="$TRACKERS" \
   --web-seed http://178.18.17.174:8008/Whonix-Workstation-0.5.6.ova \
   ~/0.5.6/Whonix-Workstation.ova

