#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

## Thanks to:
## https://github.com/moba/createtortorrents/blob/master/createtorrents.sh

#TRACKERS="udp://tracker.openbittorrent.com:80/announce,udp://tracker.publicbt.com:80/announce,http://tracker.openbittorrent.com:80/announce,http://tracker.publicbt.com:80/announce,udp://tracker.ccc.de/announce"

TRACKERS="http://announce.torrentsmd.com:6969/announce"

## Not well supported by BitTorrent clients.
## Multi file webseeds do not work
##     https://trac.transmissionbt.com/ticket/4437
## (fixed upstream, but takes a while to propagate to Debian stable)
#mktorrent \
#   --verbose \
#   --announce="$TRACKERS" \
#   --web-seed "http://webseed.whonix.org.8008.nyud.net/Whonix-Gateway-0.5.6.ova" \
#   --web-seed "http://webseed.whonix.org.8008.nyud.net/Whonix-Workstation-0.5.6.ova" \
#   ~/0.5.6

mktorrent \
   --verbose \
   --announce="$TRACKERS" \
   --web-seed "http://webseed.whonix.org.8008.nyud.net/Whonix-Gateway-0.5.6.ova" \
   ~/0.5.6/Whonix-Gateway.ova

mktorrent \
   --verbose \
   --announce="$TRACKERS" \
   --web-seed "http://webseed.whonix.org.8008.nyud.net/Whonix-Workstation-0.5.6.ova" \
   ~/0.5.6/Whonix-Workstation.ova

## echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org:8008/Whonix-Gateway-0.5.6.ova");' "$2")"
## echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org:8008/Whonix-Workstation-0.5.6.ova");' "$2")"

## echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org.8008.nyud.net/Whonix-Gateway-0.5.6.ova");' "$2")"
## echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org.8008.nyud.net/Whonix-Workstation-0.5.6.ova");' "$2")"
