#!/bin/bash

set -x

error_handler() {
   echo "FAILED!"
   exit 1
} 

trap "error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

## provides VERSION variable
source help-steps/version

mkdir --parents "../whonix_binary"

cp "./release/README" "../whonix_binary/"
rm --force "../whonix_binary/README.asc"

gpg --clearsign "../whonix_binary/README"

cat "../whonix_binary/README.asc"

gpg --verify "../whonix_binary/README.asc"

sleep 10

rsync --partial --progress --verbose --rsh ssh "../whonix_binary/README.asc" adrelanos,whonix@frs.sourceforge.net:/home/frs/project/whonix/whonix-"$VERSION"/README
