#!/bin/bash

set -x

error_handler() {
   echo "FAILED!"
   exit 1
} 

trap "error_handler" ERR INT TERM

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

## provides VERSION variable
source help-steps/version

mkdir --parents "../whonix_binary"

## Reading ./release/whonix_news, substitute the $VERSION variable in ./release/whonix_news
## with the actual VERSION and storing it as ../whonix_binary/whonix_news.
##
## Thanks to:
## http://superuser.com/questions/235738/how-do-i-substitute-environment-variables-when-i-ouput-a-file

eval echo "\"$(cat <<EOF_$RANDOM
$(<"./release/whonix_news")
EOF_$RANDOM
)\"" > "../whonix_binary/whonix_news"

cat "../whonix_binary/whonix_news"

rm --force "../whonix_binary/whonix_news.asc"

gpg --clearsign "../whonix_binary/whonix_news"

cat "../whonix_binary/whonix_news.asc"

gpg --verify "../whonix_binary/whonix_news.asc"

rsync --partial --progress --verbose --rsh ssh "../whonix_binary/whonix_news.asc" adrelanos,whonix@frs.sourceforge.net:/home/frs/project/whonix/news/

