#!/bin/bash

set -x

error_handler() {
   echo "FAILED!"
   exit 1
} 

trap "error_handler" ERR

export MACHINE="-internal"
export VMNAME="-internal"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

cd help-steps

source variables

mkdir --parents "$WHONIX_BINARY"

cp ""$WHONIX_SOURCE_FOLDER"/release/README" ""$WHONIX_BINARY"/"
rm --force ""$WHONIX_BINARY"/README.asc"

gpg --clearsign ""$WHONIX_BINARY"/README"

cat ""$WHONIX_BINARY"/README.asc"

gpg --verify ""$WHONIX_BINARY"/README.asc"

sleep 10

rsync --partial --progress --verbose --rsh ssh ""$WHONIX_BINARY"/README.asc" adrelanos,whonix@frs.sourceforge.net:/home/frs/project/whonix/whonix-"$VERSION"/README
