#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

## Whonix News v3
## A tarball on
## http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news_v3/whonix_news.tar.gz/download
## and a detached armored OpenPGP signature on
## http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news_v3/whonix_news.tar.gz.asc/download

set -x

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

cd help-steps

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

source variables

mkdir --parents "$WHONIX_BINARY"/news_v3

## Reading ./release/whonix_news, substitute the $WHONIX_BUILD_WHONIX_VERSION variable in ./release/whonix_news
## with the actual WHONIX_BUILD_WHONIX_VERSION and storing it as ../whonix_binary/whonix_news.
##
## Thanks to:
## http://superuser.com/questions/235738/how-do-i-substitute-environment-variables-when-i-ouput-a-file

for i in "$WHONIX_SOURCE_FOLDER"/release/news/*; do
   if [ -f "$i" ]; then
      ## If the last character is a ~, ignore that file,
      ## because it was created by some editor,
      ## which creates backup files.
      if [ "${i: -1}" = "~" ]; then
         continue
      fi
   fi

   filename="$(basename "$i")"

   cp "$i" "$WHONIX_BINARY"/news_v3/"$filename"
   sync

   ## Debugging.
   cat "$WHONIX_BINARY"/news_v3/"$filename"

done

rm --force "$WHONIX_BINARY"/news_v3/.directory
rm --force "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz
rm --force "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz.asc
sync

tar -zcvpf "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz -C "$WHONIX_BINARY"/news_v3 .
sync

gpg --detach-sign --armor --yes "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz
sync
gpg --verify "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz.asc

true "INFO $0: Please press any key to continue with --dry-run."

read temp

true "INFO $0: Running with --dry-run..."
rsync \
   --dry-run \
   --partial \
   --progress \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz.asc \
   "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz \
   adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news_v3/

true "INFO $0: Please press any key to continue to upload."

read temp

true "INFO $0: Uploading..."
rsync \
   --partial \
   --progress \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz.asc \
   "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz \
   adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news_v3/
