#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012, 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "FAILED!"
   exit 1
} 

trap "error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

cd help-steps

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

source variables

mkdir --parents ""$WHONIX_BINARY""

## Reading ./release/whonix_news, substitute the $WHONIX_BUILD_WHONIX_VERSION variable in ./release/whonix_news
## with the actual WHONIX_BUILD_WHONIX_VERSION and storing it as ../whonix_binary/whonix_news.
##
## Thanks to:
## http://superuser.com/questions/235738/how-do-i-substitute-environment-variables-when-i-ouput-a-file

eval echo "\"$(cat <<EOF_$RANDOM
$(<""$WHONIX_SOURCE_FOLDER"/release/whonix_news")
EOF_$RANDOM
)\"" > ""$WHONIX_BINARY"/whonix_news"

cat ""$WHONIX_BINARY"/whonix_news"

rm --force ""$WHONIX_BINARY"/whonix_news.asc"

gpg --clearsign ""$WHONIX_BINARY"/whonix_news"

cat ""$WHONIX_BINARY"/whonix_news.asc"

gpg --verify ""$WHONIX_BINARY"/whonix_news.asc"

sleep 10

rsync \
   --partial \
   --progress \
   --verbose \
   --rsh ssh \
   ""$WHONIX_BINARY"/whonix_news.asc" \
   adrelanos,whonix@frs.sourceforge.net:/home/frs/project/whonix/news/

