#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

## NOTE:
## /usr/share/whonix/postinst.d/70_legacy prevents this script from getting run
## on older versions not supporting the verifiable builds feature.

maybe_run() {
   if [ ! -x "$1" ]; then
      true "$1 does not exist. Either the package is not installed, that script does not provide that script or else..."
      return 0
   fi
   $1 $2
}

if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
else
    true "INFO: Script running as root."
fi

## non-deterministic [1]
## /var/cache/fontconfig folder
## does not exist /var/lib/dpkg/info/fontconfig-config.preinst install
maybe_run /var/lib/dpkg/info/fontconfig-config.preinst install
maybe_run /var/lib/dpkg/info/fontconfig.postinst configure

## non-deterministic [2]
## /var/cache/ldconfig/aux-cache file
for script in /var/lib/dpkg/info/libc6*.preinst; do
   maybe_run $script install
done
unset script
for script in /var/lib/dpkg/info/libc6*.postinst; do
   maybe_run $script configure
done
unset script

## non-deterministic [3]
## /var/cache/man folder
maybe_run /var/lib/dpkg/info/man-db.preinst install
maybe_run /var/lib/dpkg/info/man-db.postinst configure

## non-deterministic [4]
## /var/lib/xml-core folder
## /etc/xml/catalog
## /etc/xml/catalog.old
## /etc/xml/xml-core.xml
## /etc/xml/xml-core.xml.old
maybe_run /var/lib/dpkg/info/xml-core.preinst install
maybe_run /var/lib/dpkg/info/xml-core.postinst configure

## non-deterministic [6]
## /var/lib/sgml-base/supercatalog
## /var/lib/sgml-base/supercatalog.old
maybe_run /var/lib/dpkg/info/sgml-base.preinst install
maybe_run /var/lib/dpkg/info/sgml-base.postinst configure

## non-deterministic [5]
## /etc/xml/sgml-data
## /etc/xml/sgml-data.old
maybe_run /var/lib/dpkg/info/sgml-data.preinst install
maybe_run /var/lib/dpkg/info/sgml-data.postinst configure

## non-deterministic [7]
## /etc/xml/docbook-xml.xml
## /etc/xml/docbook-xml.xml.old
maybe_run /var/lib/dpkg/info/docbook-xml.preinst install
maybe_run /var/lib/dpkg/info/docbook-xml.postinst configure

## non-deterministic [14]
## /etc/xml/docbook-xsl.xml
## /var/lib/xml-core/docbook-xsl
maybe_run /var/lib/dpkg/info/docbook-xsl.preinst install
maybe_run /var/lib/dpkg/info/docbook-xsl.postinst configure

## non-deterministic [8]
## /usr/share/info/dir file
maybe_run /var/lib/dpkg/info/install-info.preinst install
maybe_run /var/lib/dpkg/info/install-info.postinst configure

## non-deterministic [9]
## /usr/lib/*/gdk-pixbuf*/*/loaders.cache file
## ex: /usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
for script in /var/lib/dpkg/info/libgdk-pixbuf*.postinst; do
   maybe_run $script configure
done
unset script

## non-deterministic [10]
## /usr/lib/i386-linux-gnu/gio/modules/giomodule.cache
for script in /var/lib/dpkg/info/libglib*.postinst; do
   maybe_run $script configure
done
unset script

## non-deterministic [11]
## /usr/lib/i386-linux-gnu/*/*/immodules.cache
## /usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules.cache
## /usr/lib/i386-linux-gnu/gtk-3.0/3.0.0/immodules.cache
for script in /var/lib/dpkg/info/libgtk*.preinst; do
   maybe_run $script install
done
unset script
for script in /var/lib/dpkg/info/libgtk*.postinst; do
   maybe_run $script configure
done
unset script

## non-deterministic [12]
## some /usr/lib/pymodules/python2.7/**/__init__.pyc
## does not exist: /var/lib/dpkg/info/python-support.prerm remove
maybe_run /var/lib/dpkg/info/python-support.preinst install
maybe_run /var/lib/dpkg/info/python-support.postinst configure

## non-deterministic [13]
## /var/lib/gconf/defaults/%gconf-tree.xml
maybe_run /var/lib/dpkg/info/gconf2-common.preinst install
maybe_run /var/lib/dpkg/info/gconf2-common.postinst configure

## non-deterministic [14]
## /etc/init.d/.depend.boot
## /etc/init.d/.depend.start
## /etc/init.d/.depend.stop
maybe_run /sbin/insserv --showall
maybe_run /sbin/insserv --verbose

## non-deterministic [15]
## /var/lib/urandom/random-seed

## non-deterministic [16]
## /etc/blkid.tab
maybe_run /var/lib/dpkg/info/linux-base.preinst install
maybe_run /var/lib/dpkg/info/linux-base.postinst configure

## non-deterministic [17]
## /etc/apt/trustdb.gpg
## Thanks to:
## https://unix.stackexchange.com/questions/110500/how-to-regenerate-etc-apt-trustdb-gpg-on-debian
## This is no longer required for Debian Jessie?
apt-key update

dpkg --configure -a

## exit 0 would not be required, but that makes it easier to check the last
## command in the log using a script.
exit 0
