#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

mkdir --parents ~/.whonix/
log_file=~/.whonix/first_run_initializer.log
start_file=~/.whonix/first_run_initializer.start
done_file=~/.whonix/first_run_initializer.done

if [ -f "$done_file" ]; then
   exit 0
fi

touch "$start_file"
sync

echo "[INFO] [Whonix First Run Initializer]: Preparing Whonix... Will reboot when finished..."

## The sleep is just in for the look an feel.
sleep 10 &
sleeppid="$!"

## There is an /etc/sudoers.d exception.
sudo /usr/lib/whonix/first_run_initializer >"$log_file" 2>"$log_file"
sync

touch "$done_file"
sync

wait "$sleeppid"

echo "[INFO] [Whonix First Run Initializer]: Done. Rebooting..."

## The sleep is just in for the look an feel.
sleep 10 &
sleeppid="$!"
wait "$sleeppid"

## Workaround for CI compatibility.
if [ "$CI" = "true" ]; then
   ## Do not try to reboot Travis CI!
   ## Otherwise you'll run into...
   ## "I'm sorry but there was an error with the connection to the VM.
   ## Your job will be requeued shortly."
   echo "[INFO] [Whonix First Run Initializer]: CI detected. Skipping reboot."
else
   ## There is an /etc/sudoers.d exception.
   sudo /sbin/reboot
fi

## The sleep is just in for the look an feel.
sleep 60 &
sleeppid="$!"
wait "$sleeppid"

echo "[ERROR] [Whonix First Run Initializer]: Rebooting not done after 60 seconds. Please report this Whonix bug!"

## Sleep, so this message has a chance of being read.
sleep 10 &
sleeppid="$!"
wait "$sleeppid"

exit 0
