#!/bin/bash

#set -x

SCRIPTNAME="$(basename $0)"
IDENTIFIER="timesync"

source /usr/lib/whonix/whonixcheck/10_preparation
source /usr/lib/whonix/whonixcheck/17_check_tor_enabled

error_handler() {
   local return_code="$?"
   BUG="1"

   local MSG="\
BASH_COMMAND: $BASH_COMMAND
return_code: $return_code
"

   ## TODO: log.
}

sdwdate_prerequisite() {
   trap "error_handler" ERR

   if [ -f "/usr/share/whonix/whonix_gateway" ]; then
      VM="Whonix-Gateway"
   elif [ -f "/usr/share/whonix/whonix_workstation" ]; then
      VM="Whonix-Workstation"
   else
      VM="whonixcheck script could not determine if this is whonix_gateway or whonix_workstation. Please report this bug."
   fi   

   ## Sets: TOR_ENABLED
   check_tor_enabled_do ## 17_check_tor_enabled

   if [ "$TOR_ENABLED" = "1" ]; then
      ## Ok.
      true
   else
      echo "Tor is disabled. Please enable Tor using whonixsetup. \
Start Menu -> Applications -> System -> First Time Connection Setup or in Terminal: sudo whonixsetup"
      
      ## Exit 2, so sdwdate will wait until this has been fixed.
      exit "2"
   fi

   ## Sometimes it does not work on the first run. Small hack.
   /usr/lib/whonix/whonixcheck/help_check_tor_bootstrap.py >/dev/null || true   

   tor_bootstrap_status="$(/usr/lib/whonix/whonixcheck/help_check_tor_bootstrap.py)" || { tor_bootstrap_percent="$?" ; true; }

   local MSG="Tor is not yet fully bootstrapped. $tor_bootstrap_percent % done. Tor reports: $tor_bootstrap_status"

   if [ "$tor_bootstrap_percent" = "254" ]; then
      local MSG="Tor Bootstrap Result: \
/usr/lib/whonix/whonixcheck/help_check_tor_bootstrap.py ERROR ($tor_bootstrap_percent). Please report this bug!"
   fi

   if [ "$tor_bootstrap_percent" = "255" ]; then
      if [ "$VM" = "Whonix-Gateway" ]; then
         local MSG="Tor Bootstrap Result: \
Tor's Control Port could not be reached. \
Please report this bug!"
      elif [ "$VM" = "Whonix-Workstation" ]; then
         local MSG="Tor Bootstrap Result: \
Tor's Control Port could not be reached. \
Did you start Whonix-Gateway beforehand? \
Please run whonixcheck on Whonix-Gateway."
      else
         local MSG="$FUNCNAME: This is neither Whonix-Gateway nor Whonix-Workstation. Please report this bug!"
      fi
   fi
   
   if [ "$tor_bootstrap_percent" = "100" ]; then
      ## Ok.
      ## Exit 0, so sdwdate will continue.
      exit "0"
   else
      ## Echo message, so sdwdate can integrate it into its log.
      echo "$MSG"
      
      ## Exit 2, so sdwdate will wait until this has been fixed.
      exit "2"
   fi
}

sdwdate_prerequisite ${1+"$@"}

