#!/bin/bash

#set -x

SCRIPTNAME="$(basename $0)"
IDENTIFIER="timesync"

source /usr/lib/whonix/whonixcheck/10_preparation
source /usr/lib/whonix/whonixcheck/17_check_tor_enabled

error_handler() {
   local return_code="$?"
   BUG="1"

   local MSG="\
BASH_COMMAND: $BASH_COMMAND
return_code: $return_code
"

   ## TODO: log.
}

timesync_main() {
   trap "error_handler" ERR

   ## Sets: TOR_ENABLED
   check_tor_enabled_do ## 17_check_tor_enabled

   if [ "$TOR_ENABLED" = "1" ]; then
      ## Ok.
      true
   else
      ## Exit 2, so sdwdate will wait until this has been fixed.
      exit "2"
   fi

   ## Sometimes it does not work on the first run. Small hack.
   /usr/lib/whonix/whonixcheck/help_check_tor_bootstrap.py >/dev/null || true   

   tor_bootstrap_status="$(/usr/lib/whonix/whonixcheck/help_check_tor_bootstrap.py)" || { tor_bootstrap_percent="$?" ; true; }

   if [ "$tor_bootstrap_percent" = "100" ]; then
      ## Ok.
      ## Exit 0, so sdwdate will continue.
      exit "0"
   else
      ## Tor not yet bootstrapped.

      ## TODO: Log $tor_bootstrap_status.
      
      ## Exit 2, so sdwdate will wait until this has been fixed.
      exit "2"
   fi
}

timesync_main ${1+"$@"}

