#!/bin/bash

## Whonix /usr/lib/whonix/timesync_hourly

## Useful for testing:
## run-parts /etc/cron.hourly/
## pgrep timesync_hourly

set -x

## anacron runs this script every hour.
## Not exactly at hour:00:00, but somewhat predictable.
## We add a random delay before we run htpdate again,
## to prevent issuing leaving a clear network fingerprint.
## (Not always exactly at xx:yy:zz sending a request.)

## Create a random number between 0 and 3600.
##
## Thanks to
## http://linux.byexamples.com/archives/128/generating-random-numbers/
##
## One hour has 3600 seconds.
DELAY="$(( 100+($(od -An -N2 -i /dev/random) )%(3600-0+1) ))"

## Debugging:
#DELAY="30"
#SCRIPTNAME="$(basename $0)"
#echo "$SCRIPTNAME: date: $(date) | Sleeping for $DELAY seconds..." >> /home/user/timesynclog
#chown user:user /home/user/timesynclog

sleep "$DELAY"

## Debugging:
#echo "$SCRIPTNAME: date: $(date) | Restarting htpdate..." >> /home/user/timesynclog
#chown user:user /home/user/timesynclog

## Debugging:
#sudo -u user /usr/bin/timesync --autostart --cron >> /home/user/timesynclog
#chown user:user /home/user/timesynclog

sudo -u user /usr/bin/timesync --autostart --cron

## Debugging:
#echo "$SCRIPTNAME: date: $(date) | Htpdate restarted. Sleeping for 60 seconds..." >> /home/user/timesynclog
#chown user:user /home/user/timesynclog
##
#sleep 60
##
#echo "$SCRIPTNAME: date: $(date) | Htpdate restarted. Clock should now be changed." >> /home/user/timesynclog
#chown user:user /home/user/timesynclog

exit 0

## End of Whonix /usr/lib/whonix/timesync_hourly
