#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

mkdir -p /var/run/whonixcheck/
chown --recursive user:user /var/run/whonixcheck/
chmod --recursive o+w /var/run/whonixcheck/
chmod --recursive g+w /var/run/whonixcheck/

## Does not work: /usr/sbin/VBoxService --disable-timesync || true

echo "\
INFO: Whonix /usr/lib/whonix/timesync_init_d
      Running: service virtualbox-guest-utils stop 2>/dev/null || true
      Only in case guest additions are installed.
      Should only deactivate time sync.
      Bug report:
  https://www.virtualbox.org/ticket/10828
      Details:
  https://www.whonix.org/wiki/Dev/TimeSync"

## Ubuntu:
service vboxadd-service stop 2>/dev/null || true

## Debian
service virtualbox-guest-utils stop 2>/dev/null || true
