#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

mkdir -p /var/run/whonix/whonixcheck/
chown --recursive user:user /var/run/whonix/whonixcheck/
chmod --recursive o+w /var/run/whonix/whonixcheck/
chmod --recursive g+w /var/run/whonix/whonixcheck/
