#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

## Whonix /usr/lib/whonix/whonixcheck_profile_d

## This script gets run by the /etc/profile.d/30_timesync.sh hook.

## Please see /usr/lib/whonix/ram_adjusted_desktop_starter for a comment why
## we are using this file instead of directly implementing this functionality
## into /etc/profile.d/ folder.

#set -x

## The delay is just for the look and feel.
/usr/lib/whonix/delay sudo -u user /usr/lib/whonix/doutput --identifier whonixcheck --icon /usr/share/whonix/icons/whonix.ico --showcli

## End of /usr/lib/whonix/whonixcheck_profile_d
