#!/bin/bash

#set -x

sudo -u user /usr/bin/whonixcheck --autostart >/dev/null 2>/dev/null || true
sleep 3600 &
wait "$!"

while true; do

   sudo -u user /usr/bin/whonixcheck --autostart --daemon >/dev/null 2>/dev/null || true
   sleep 3600 &
   wait "$!"

done
