#!/bin/bash

#set -x

sudo -u user /usr/bin/whonixcheck --autostart || true
sleep 3600 &
wait "$!"

while true; do

   sudo -u user /usr/bin/whonixcheck --autostart --daemon || true
   sleep 3600 &
   wait "$!"

done
