#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012, 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

#set -x

sudo -u user /usr/bin/whonixcheck --autostart >/dev/null 2>/dev/null || true
sleep 3600 &
wait "$!"

while true; do

   sudo -u user /usr/bin/whonixcheck --autostart --daemon >/dev/null 2>/dev/null || true
   sleep 3600 &
   wait "$!"

done
