#!/bin/bash

# Internally used by whonix_gateway and whonix_workstation.

# This script is required to work arround the following upstream bug:
# - https://code.google.com/p/torsocks/issues/detail?id=3
# - https://trac.torproject.org/projects/tor/ticket/6155

# Debugging.
set -x



patch_torsocks() {
# TODO: Do we really need to keep the source folder?
# If yes, we would have to move it tor /home/$USERNAME/.torsocks-1.2.
# But what if the script gets executed again? Than we would have to delete
# the .torsocks-1.2 folder before. That may have unexpected side effects,
# if someone was really working on the source and everything where gone.
#
# If someone wants to issue sudo make uninstall, source can be downloaded
# again.
#
# If there are no objections, lets remove this todo.

# Will break if torsocks gets updated.
# Run as root, since vm script also runs as root.

echo "
########################
# Get torsocks source
########################
"

# Get into temp folder.
cd /tmp

# Download torsocks source code.
echo "INFO: Trying to download torsocks source code..."
sudo -u $USERNAME apt-get source torsocks

# Get into torsocks source code folder.
cd /tmp/torsocks-1.2

# Check if we could cd into the torsocks source code folder.
# cd will return 0 if it was possible to get into that directory.
if  [ "$?" != "0" ]; then
   # Inform about failure.
   echo "ERROR: Could not cd into torsocks-1.2 folder. torsocks got probable updated and torsocks_patch() is no longer necessary."
   # Restore working folder.
   cd /home/$USERNAME
   # Exit this function.
   return
fi

echo "INFO: Successfully joint the torsocks source code folder."

echo "
########################
# ./configure torsocks
########################
"

sudo -u $USERNAME ./configure

echo "
########################
# patching torsocks
########################
"

sudo -u $USERNAME patch -p1 < /usr/share/Whonix/torsocks_patch

echo "
########################
# make torsocks
########################
"

sudo -u user make

echo "
########################
# make install torsocks
########################
"

# Install as root.
make install

# Leave that folder.
cd /home/$USERNAME

# Temporary files will be delted by the slim_down function. 
}