#!/bin/bash

# Internally used by whonix_gateway and whonix_workstation scripts.

set -x

whonix_create_swap_file() {
trap "error_handler" ERR INT TERM

echo "
######################################################
# create_swap_file
######################################################
"

# Source: http://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/

echo "Checking if something accessing /swapfile1."
local result="`lsof | grep /swapfile1`" || true
echo "$result" || true

echo "Delete /swapfile1 if it already exists. Only in case re-running the script."
rm /swapfile1 || true

# Creating 512 MB swap file.
echo "INFO: Creating /swapfile1... This may take a while..."
dd if=/dev/zero of=/swapfile1 bs=1024 count=524288
echo "INFO: Created /swapfile1."

# Format swapfile.
mkswap /swapfile1 --uuid 0615ba72-85b0-4183-8d54-300bb0d2e491

# Set permissions.
chown root:root /swapfile1

# Set permissions.
chmod 0600 /swapfile1

# Should be probable omitted. No need. Will be restarted so or so.
# swapon /swapfile1
}