#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR

## Create folder.
mkdir --parents /usr/share/whonix/sources/

cd /usr/share/whonix/sources/

## Enable apt-cacher-ng proxy.
export http_proxy="http://127.0.0.1:3142"   

apt-get update

for i in $(/usr/share/whonix/damngpl --source /var/lib/dpkg/status); do
   apt-get --download-only source $i;
done
 
## Disable apt-cacher-ng proxy.
export unset http_proxy

