#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

true "Adding bootclockrandomization init script..."
update-rc.d bootclockrandomization defaults
 
