#!/bin/bash

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

cd /usr/local/share/whonix/dummytor/
equivs-build tor

dpkg -i tor_1.0_all.deb

echo "tor hold" | dpkg --set-selections

 
