#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

cd /usr/local/share/whonix/dummytor/
equivs-build tor

dpkg -i tor_1.0_all.deb

echo "tor hold" | dpkg --set-selections

 
