#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

## Building in the clear and behind a transparent Tor proxy is supported.
## In case we are not behind a Whonix-Gateway with dedicated ports for
## Tor Browser download, use TransPort or clear download instead of SocksPort.
sudo -u user /usr/local/bin/torbrowser -dev-build-passthrough ## Depends on working internet connection. 

