#!/bin/bash

set -x

error_handler() {
   echo "
###################################
## chroot script: ERROR detected. #
###################################
"

   exit 1
} 

trap "error_handler" ERR INT TERM

## 1) Prepare directory for the disabled plugins.
mkdir -p /usr/lib/xchat/plugins.disabled/

## Disable unnecessary plugins (keep perl for sasl).
#mv /usr/lib/xchat/plugins/{python.*,tcl.*} /usr/lib/xchat/plugins.disabled/ || true

## 2) Move all plugins to plugins.disabled.
mv /usr/lib/xchat/plugins/* /usr/lib/xchat/plugins.disabled/ || true

