#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

if [ -f "/usr/share/whonix/whonix_gateway" ]; then
   VM="Whonix-Gateway"
elif [ -f "/usr/share/whonix/whonix_workstation" ]; then
   VM="Whonix-Workstation"
else
   VM="could not determine if this is whonix_gateway or whonix_workstation. Please report this Whonix bug."
fi

if [ "$VM" = "Whonix-Gateway" ]; then
   TITLE="whonixsetup - Connection Wizard and Whonix Repository Wizard ($VM)"
elif [ "$VM" = "Whonix-Workstation" ]; then
   TITLE="whonixsetup - Whonix Repository Wizard ($VM)"
else
   TITLE="whonixsetup - $VM"
fi

MSG="
Welcome to Whonix!

The programs included with Whonix are free software. The distribution terms for each program are described in /usr/share/doc/*/copyright.

Whonix comes with ABSOLUTELY NO WARRANTY and is a derivative of Debian GNU/Linux. It is produced independently of, with no guarantee from, The Tor Project.

Whonix is experimental. Do not rely on it for strong anonymity.
"

dialog --title "$TITLE" --yes-label "Start" --no-label "Exit" --yesno "$MSG" 640 480

ret="$?"

if [ "$ret" = "1" ]; then
   true "INFO: Ok, exit 1, so whonixsetup will end."
fi

exit "$ret"
