#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Debugging
#set -x

set -o pipefail

error_handler() {
   local MSG="\
###########################################################
## Something went wrong. Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
###########################################################\
"
   echo "$MSG"
   exit 1
}

trap "error_handler" ERR

source /usr/lib/whonix/whonixcheck/10_preparation
get_local_whonix_version

MENU_TITLE="whonixsetup - Connection Wizard ($whonix_deb_package_version)"

MENU_TEXT="Before we let Tor connect, we need to know about your Internet connection.

Which of the following applies to you?

(Please scroll down using the arrow keys.)"

exec 3>&1

trap "" ERR

_return=$(\
   dialog \
      --title "$MENU_TITLE" \
      --menu "$MENU_TEXT" \
         100 120 20 \
         "1" "I'm ready to enable Tor." \
         "2" "I want to disable Tor." \
         "3" "Tor is censored or dangerous in my area." \
         "4" "I use proxy or firewall settings to connect to the internet." \
         2>&1 1>&3)

EXITCODE="$?"

trap "error_handler" ERR

exec 3>&-;

exit "$_return"
