#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

run_sdwdate() {
   trap "error_handler" ERR

   let "PROGRESS=$PROGRESS+5" || true
   ## The 5% indicate, that the check has begun.
   $output ${output_opts[@]} --progressbaridx "$progressbaridx_main" --progressx "$PROGRESS"

   if [ "$AUTOSTARTED" = "1" ]; then
      true "$SCRIPTNAME run_sdwdate: not restarting sdwdate in this case, \
because the /etc/init.d/sdwdate init script already started sdwdate."
   else
      ## When manually run...
      if [ "$VERBOSE" = "1" ]; then
         sudo /etc/init.d/sdwdate restartnd &
      else
         sudo service sdwdate restartnd
      fi
   fi

   let "PROGRESS=$PROGRESS+1" || true
   $output ${output_opts[@]} --progressbaridx "$progressbaridx_main" --progressx "$PROGRESS"
}
