#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

run_sdwdate() {
   trap "error_handler" ERR

   let "PROGRESS=$PROGRESS+5" || true
   ## The 5% indicate, that the check has begun.
   $output ${output_opts[@]} --progressbaridx "$progressbaridx_main" --progressx "$PROGRESS"

   if [ "$AUTOSTARTED" = "1" ]; then
      true "$SCRIPTNAME run_sdwdate: not restarting sdwdate in this case, \
because the /etc/init.d/sdwdate init should have already started sdwdate (unless /etc/init.d/sdwdate has been set -x).."
   else
      ## When manually run...
      if [ ! -x "/etc/init.d/sdwdate" ]; then
         local MSG='/etc/init.d/sdwdate not executable.

Most likely you removed the executable bit from /etc/init.d/sdwdate using "sudo chmod -x /etc/init.d/sdwdate"

To undo this, type in terminal:
sudo chmod +x /etc/init.d/sdwdate'
         $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
         return 0
      else
         if [ "$VERBOSE" = "1" ]; then
            sudo /etc/init.d/sdwdate restartnd &
         else
            sudo service sdwdate restartnd
         fi
      fi
   fi

   PROGRESS="$(( $PROGRESS + 1 ))"
   $output ${output_opts[@]} --progressbaridx "$progressbaridx_main" --progressx "$PROGRESS"
}
