#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

MSG="
Welcome to Whonix!

The programs included with Whonix are free software. The distribution terms for each program are described in /usr/share/doc/*/copyright.

Whonix comes with ABSOLUTELY NO WARRANTY and is a derivative of Debian GNU/Linux. It is produced independently of, with no guarantee from, The Tor Project.

Whonix is experimental. Do not rely on it for strong anonymity.
"

TITLE="Connection Wizard"

dialog --title "$TITLE" --yes-label "OK" --no-label "Cancel" --yesno "$MSG" 640 480

ret="$?"

if [ "$ret" = "1" ]; then
   true "INFO: Ok, exit 1, so whonixsetup will end."
fi

exit "$ret"
