#!/bin/bash

MSG="
Welcome to Whonix!
https://www.whonix.org

The programs included with Whonix are free software. The distribution 
terms for each program are described in /usr/share/doc/*/copyright.

Whonix comes with ABSOLUTELY NO WARRANTY, and is a derivative of 
Debian GNU/Linux. It is produced independently of, with no guarantee 
from, The Tor Project.

The concept and design of Whonix is experimental. 
Do not rely on it for strong anonymity.
"

TITLE="Welcome / Disclaimer"

dialog --title "$TITLE" --yesno "$MSG" 640 480

exit $?
