#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

MSG='
(You can scroll down using the arrow key).

You must edit /etc/tor/torrc so that Tor can navigate through your firewall or proxy. Comments and examples in that file will guide you through the process.

Press enter to close this message, then cancel the connection wizard via the main menu. Open /etc/tor/torrc and find the appropriate section. After you have finished editing, restart the First Time Connection Wizard.

You can open /etc/tor/torrc in the terminal:
    sudo nano /etc/tor/torrc

Or on the desktop:
    Start Menu -> Applications -> /etc/tor/torrc
'

TITLE="I use proxy or firewall settings to connect to the internet."

dialog --title "$TITLE" --msgbox "$MSG" 640 480

exit 0
