#!/bin/bash

set -x

error_handler() {
   local MSG="\
###########################################################
## Something went wrong. Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
###########################################################\
"
   echo "$MSG"
   exit 1
} 

trap "error_handler" ERR

## root check
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
fi

MSG='
Tor tries to prevent attackers from learning what destination websites you connect to. However, by default, it does not prevent somebody watching your Internet traffic from learning that you are using Tor. If this matters to you, you can reduce this risk by configuring Tor to use a Tor bridge relay rather than connecting directly to the public Tor network. Ultimately the best protection is a social approach: the more Tor users there are near you and the more diverse their interests, the less dangerous it will be that you are one of them. Convince other people to use Tor, too!

(Technically speaking, whonixsetup activates Tor by commenting out "DisableNetwork 1" in /etc/tor/torrc.)

Enable Tor and connect to the public Tor network?
'

TITLE="Connect to the public Tor network."

returncode=0
dialog --title "$TITLE" --yesno "$MSG" 640 480 || { returncode=$? ; true; };

if [ ! "$returncode" = "0" ]; then
   ## Back to main menu.
   exit 0
fi

## Check if Tor was already enabled.
## This is to prevent getting ed from failing.
while read LINE; do
   if [ "$LINE" = '#DisableNetwork 1' ]; then
      dialog --title "Success!" --msgbox '"DisableNetwork 1" was already commented out in /etc/tor/torrc.
So Tor should now be activated.

whonixsetup really only activates Tor by commenting out "DisableNetwork 1" in /etc/tor/torrc.
Running it multiple times in a row archives nothing.
In case of network problems, this is probably not the cause.
You can confirm that by manually checking if "DisableNetwork 1" has been out commented in /etc/tor/torrc.
' 640 480
   fi
done < "/etc/tor/torrc"

## Comment out DisableNetwork 1 in /etc/tor/torrc
returncode=0
ed -s /etc/tor/torrc <<< $',s/DisableNetwork 1/#DisableNetwork 1/g\nw' || { returncode=$? ; true; };

## Ensure changes get written to the disk right now.
sync

if [ ! "$returncode" = "0" ]; then
   TITLE="Info..."

   MSG="
Could not comment out \"DisableNetwork 1\" in /etc/tor/torrc.
Maybe you commented out or completely removed \"DisableNetwork 1\" in
/etc/tor/torrc already? This is not necessarily a problem.
   
Will try to reload Tor now and check its status afterward...
"
else
   TITLE="Info..."

   MSG="
Tor in /etc/tor/torrc has been activated.

Will try to reload Tor now and check its status afterward...
"
fi

dialog --title "$TITLE" --msgbox "$MSG" 640 480

returncode=0
service tor status || { returncode=$? ; true; };
sync
sleep 1

if [ ! "$returncode" = "0" ]; then
   returncode=0
   service tor start || { returncode=$? ; true; };
   sync
   sleep 1
else
   returncode=0
   service tor reload || { returncode=$? ; true; };
   sync
   sleep 1
fi

returncode=0
service tor status || { returncode=$? ; true; };
sync
sleep 1

if [ ! "$returncode" = "0" ]; then
   ## Working around a bug in Tor.
   ## Reloading Tor did not work. Starting it.
   returncode=0
   service tor start || { returncode=$? ; true; };
   sync
   sleep 1
fi

## Working around another bug in Tor.
## When starting Tor fails, it does not return a non-zero return code.
returncode=0
service tor status || { returncode=$? ; true; };
sync
sleep 1

if [ ! "$returncode" = "0" ]; then

   TITLE="Error!"

   MSG="
sudo service tor status
returned exit code $returncode, which means, that there is something wrong
with your /etc/tor/torrc. Tor will NOT work.

This problem is most likely not caused by whonixsetup.

This is most likely a problem with your /etc/tor/torrc.
Please fix your /etc/tor/torrc.

You can open /etc/tor/torrc for example using the nano editor.

    sudo nano /etc/tor/torrc

Or, if you are using a graphical Whonix-Gateway.    
    
    Start Menu -> Applications -> /etc/tor/torrc

Running,

   sudo service tor restart

might be of assistance finding out, what the problem is.
"

   dialog --title "$TITLE" --msgbox "$MSG" 640 480

   exit 1

fi

TITLE="Success!"

MSG="
sudo service tor status
returned $returncode, which means, that reloading Tor worked.
Tor should work now.

This only means, that Tor is configured now and will try to connect.

Checking, if your host internet connection is functional and/or if Tor can
reach the Tor network has not been implemented yet into whonixsetup.

Running,

    whonixcheck

might be of assistance.
"

dialog --title "$TITLE" --msgbox "$MSG" 640 480

exit 1

