#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   local MSG="\
###########################################################
## Something went wrong. Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
###########################################################\
"
   echo "$MSG"
   exit 1
}

trap "error_handler" ERR

## root check
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
fi

MSG='
Tor tries to prevent attackers from learning what websites you connect to. However, by default, it does not hide the fact that you are using Tor. If this matters, you can reduce this risk by configuring Tor to use a Tor bridge relay rather than connecting directly to the public Tor network. Ultimately, the best protection is a social approach: the more Tor users there are near you and the more diverse their interests, the safer it will be to use it. Convince other people to use Tor, too!

Note: whonixsetup activates Tor by in commenting "DisableNetwork 0" in /etc/tor/torrc.

Enable Tor and connect to the Tor network?
'

TITLE="Connect to the Tor network."

returncode=0
dialog --title "$TITLE" --yesno "$MSG" 640 480 || { returncode=$? ; true; };

if [ ! "$returncode" = "0" ]; then
   ## Back to main menu.
   exit 0
fi

## Check if Tor was already enabled.
## This is to prevent getting ed from failing.
already_commented_in="0"
while read LINE; do
   if [ "$LINE" = 'DisableNetwork 0' ]; then
      already_commented_in="1"
      returncode=0
      dialog --title "Success!" --yes-label "OK" --no-label "Exit" --yesno '"DisableNetwork 0" was already in commented in /etc/tor/torrc. Tor should be activated.

Note: whonixsetup activates Tor by in commenting "DisableNetwork 0" in /etc/tor/torrc. There is no need to run it multiple times, and it probably not the cause of network problems. You can manually check if "DisableNetwork 0" is in commented in /etc/tor/torrc.

Will try to reload Tor now and check its status afterward...
' 640 480 || { returncode=$? ; true; };

      if [ ! "$returncode" = "0" ]; then
         ## User pressed Exit button.
         true "INFO: Ok, exit 1, so whonixsetup will end."
         exit 1
      fi

      break
   fi
done < "/etc/tor/torrc"

if [ "$already_commented_in" = "0" ]; then
   ## Comment in DisableNetwork 0 in /etc/tor/torrc.
   returncode=0
   ed -s /etc/tor/torrc <<< $',s/\#DisableNetwork 0/DisableNetwork 0/g\nw' || { returncode=$? ; true; };

   ## Ensure changes get written to the disk right now.
   sync

   if [ ! "$returncode" = "0" ]; then
      TITLE="Info:"

      MSG="
Could not comment in \"DisableNetwork 0\" in /etc/tor/torrc. Have you commented in or completely removed \"DisableNetwork 0\" in /etc/tor/torrc? This is not necessarily a problem.

Will try to reload Tor now and check its status afterward...
"

   else
      TITLE="Info:"

      MSG="
Tor has been activated in /etc/tor/torrc.

Will try to reload Tor now and check its status afterward...
"
   fi

   returncode=0
   dialog --title "$TITLE" --yes-label "OK" --no-label "Exit" --yesno "$MSG" 640 480 || { returncode=$? ; true; };

   if [ ! "$returncode" = "0" ]; then
      ## User pressed Exit button.
      true "INFO: Ok, exit 1, so whonixsetup will end."
      exit 1
   fi
fi

returncode=0
service tor status || { returncode=$? ; true; };
sync
sleep 1

if [ ! "$returncode" = "0" ]; then
   returncode=0
   service tor start || { returncode=$? ; true; };
   sync
   sleep 1
else
   returncode=0
   service tor reload || { returncode=$? ; true; };
   sync
   sleep 1
fi

returncode=0
service tor status || { returncode=$? ; true; };
sync
sleep 1

if [ ! "$returncode" = "0" ]; then
   ## Working around a bug in Tor.
   ## Reloading Tor did not work. Starting it.
   returncode=0
   service tor start || { returncode=$? ; true; };
   sync
   sleep 1
fi

## Working around another bug in Tor.
## When starting Tor fails, it does not return a non-zero return code.
returncode=0
service tor status || { returncode=$? ; true; };
sync
sleep 1

if [ ! "$returncode" = "0" ]; then

   TITLE="Error!"

   MSG="
sudo service tor status
returned exit code $returncode. There is something wrong with your /etc/tor/torrc. Tor will NOT work. This is most likely a problem with your /etc/tor/torrc (and not whonixsetup). Please fix your /etc/tor/torrc.

You can open /etc/tor/torrc in the terminal:

    sudo nano /etc/tor/torrc

Or, if you are using a graphical Whonix-Gateway:

    Start Menu -> Applications -> /etc/tor/torrc

Running:

   sudo service tor restart

might help with troubleshootingt .
"

   dialog --title "$TITLE" --msgbox "$MSG" 640 480

   true "INFO: Ok, exit 1, so whonixsetup will end."
   exit 1

fi

TITLE="Success!"

MSG="
Tor was successfully reloaded.

Press Enter to run whonixcheck and exit.
"

returncode=0
dialog --title "$TITLE" --yes-label "OK" --no-label "Exit" --yesno "$MSG" 640 480 || { returncode=$? ; true; };

if [ ! "$returncode" = "0" ]; then
   ## User pressed Exit button.
   true "INFO: Ok, exit 1, so whonixsetup will end."
   exit 1
fi

true "INFO: Opening timesync progress bar..."
## (Developer comment: When modifying the next line, also consider modifying /etc/sdwdate.d/30_sdwdate_default.)
## ">/dev/null 2>/dev/null" to hide `echo`s, because `sdw_pre` will use `doutput` which will use `write` to write to tty1.
/usr/lib/whonix/sdw_pre --autostart >/dev/null 2>/dev/null & disown
## Wait. Only for the look and feel. Prevent mixing up timesync message with whonixcheck.
sleep 5 &
wait "$!"
true "INFO: Opened timesync progress bar."
true "INFO: (This is only of interest when Tor was still disabled while Whonix was booted.)"

true "INFO: Will now start whonixcheck for your convenience..."

## || true, so in case whonixcheck returns a non-zero exit code, it won't be
## interpreted as an error in whonixsetup.
sudo -u user whonixcheck || true

true "INFO: End of whonixcheck. You can always start whonixcheck again, by starting:
            whonixcheck"

true "INFO: Ok, exit 1, so whonixsetup will end."
exit 1
