#!/bin/bash

set -x
set -e

sudo systemctl stop approx-derivative-maker.socket

sudo mkdir --parents /var/cache/approx-derivative-maker

sudo find /var/cache/approx-derivative-maker -mindepth 1 -print0 | xargs -0 sudo safe-rm --verbose -r -f

sudo chown --recursive approx:approx /var/cache/approx-derivative-maker

sudo systemctl restart approx-derivative-maker.socket
