#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler_chroot-img() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

chroot-img() {
   trap "error_handler_chroot-img" ERR INT TERM

   sync

   if [ "$BARE_METAL" = "1" ]; then
      true
   else

      #########
      ## /dev #
      #########

      ## We need /dev for create_swap_file
      ##  "dd if=/dev/zero of=/swapfile1 bs=1024 count=524288"
      mount --bind /dev "$CHROOT_FOLDER"/dev

      ##########
      ## /proc #
      ##########

      mount --bind /proc "$CHROOT_FOLDER"/proc

      #########
      ## /sys #
      #########

      #mount --bind /sys "$CHROOT_FOLDER"/sys
   fi

   #####################
   ## /etc/resolv.conf #
   #####################

   ## /etc/resolv.conf controversy:
   ## When we are inside chroot, we need a functional /etc/resolv.conf,
   ## otherwise DNS lookups and subsequently apt-get and curl would be defunct.
   ## On the other hand, we do not want to copy /etc/resolv.conf from the
   ## build machine into chroot, to prevent leaking personal data into chroot.
   ## Therefore we use /etc/resolv.conf from the host inside chroot,
   ## without ever writing it. (Mounting)

   ## We need two commands to remount an existing file as read only.
   ## Thanks to: https://lwn.net/Articles/281157/

   if [ "$WHONIX_CHROOT_MOUNT_RESOLV_CONF" = "0" ]; then
      true "${cyan}INFO $0: Not mounting /etc/resolv.conf inside chroot, because WHONIX_CHROOT_MOUNT_RESOLV_CONF is 0.${reset}"
   else
      if [ "$BARE_METAL" = "1" ]; then
         true "${cyan}INFO $0: using .backup files as /etc/resolv.conf etc.${reset}"
         mount --bind /etc/resolv.conf.backup "$CHROOT_FOLDER"/etc/resolv.conf
         mount --bind /etc/hosts.backup "$CHROOT_FOLDER"/etc/hosts
         mount --bind /etc/hostname.backup "$CHROOT_FOLDER"/etc/hostname
         mount --bind /etc/network/interfaces.backup "$CHROOT_FOLDER"/etc/network/interfaces
      else
         mount --bind /etc/resolv.conf "$CHROOT_FOLDER"/etc/resolv.conf
      fi
   fi

   ## Remount as read only...
   ## Does not work on Debian Wheezy.
   ## Not required anymore. We are not starting any services, DHCP or
   ## networking inside the chroot, so the file should remain untouched.
   #mount -o remount,ro,noload "$CHROOT_FOLDER"/etc/resolv.conf

   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
chroot-img
true "${bold}INFO: End of: $0 No error detected.${reset}"
