#!/bin/bash

## Copyright (C) 2019 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x

set -e

true "$0: start"

## Debugging.
true "$0: $(whoami)" || true
ls -la || true

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## travis.debian.net does not pass the CI environment variable to docker.
## build script reads CI variable.
if echo "$PWD" | grep -q travis ; then
   true "INFO: travis detected, ok."
elif [ ! "$CI" = "true" ]; then
   true "ERROR: You probably do not want to run this outside of a CI."
   exit 1
fi

sudo --non-interactive apt-get update

sudo --non-interactive apt-get --yes --no-install-recommends install git time tor torsocks

sudo --non-interactive systemctl status tor || true
sudo --non-interactive systemctl status tor@default || true

pushd /tmp

## Test if git cloning from gitlab over Tor (using torsocks) is functional.
## Useful to have this test fail in case there are generally gitlab
## connectivity issues or blocking of Tor users.

## --branch 15.0.1.7.2-stable
## Can be any tag.

## --shallow-submodules
## Speed up download. Save traffic. Repositories binaries-freedom and
## monero-gui is too large which lead to failed git clone.

time \
   torsocks \
      git \
         clone \
         --depth=1 \
         --branch 15.0.1.7.2-stable \
         --jobs=100 \
         --recurse-submodules \
         --shallow-submodules \
         https://gitlab.com/whonix/Whonix.git

popd

true "$0 INFO: OK. End."
