#!/bin/bash

## Copyright (C) 2019 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

true "$0: start"

## Debugging.
true "$0: $(whoami)" || true
true "$0: $(pwd)" || true
ls -la || true

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## travis.debian.net does not pass the CI environment variable to docker.
## build script reads CI variable.
if echo "$PWD" | grep -q travis ; then
   true "INFO: travis detected, ok."
elif [ ! "$CI" = "true" ]; then
   true "ERROR: You probably do not want to run this outside of a CI \
environment, because it uses virsh to undefine virtual machines."
   exit 1
fi

apt-get update

### XXX: duplicated from apt-get-noninteractive
## XXX: not using POLICYRCD
#[ -n "$POLICYRCD" ] || POLICYRCD="/usr/share/usability-misc/policy-rc.d"
[ -n "$DEBIAN_FRONTEND" ] || DEBIAN_FRONTEND="noninteractive"
[ -n "$DEBIAN_PRIORITY" ] || DEBIAN_PRIORITY="critical"
[ -n "$DEBCONF_NOWARNINGS" ] || DEBCONF_NOWARNINGS="yes"
[ -n "$APT_LISTCHANGES_FRONTEND" ] || APT_LISTCHANGES_FRONTEND="text"
export POLICYRCD DEBIAN_FRONTEND DEBIAN_PRIORITY DEBCONF_NOWARNINGS APT_LISTCHANGES_FRONTEND

## Sanity tests.
apt-get --yes dist-upgrade
dpkg --configure -a

apt-get --yes --no-install-recommends install sudo git time curl apt-cacher-ng lsb-release fakeroot dpkg-dev

user_name=user
user_to_be_created=user

adduser --no-create-home --disabled-login --gecos "" "$user_to_be_created"

addgroup --system console

adduser "$user_name" sudo
adduser "$user_name" console

## https://unix.stackexchange.com/questions/18796/how-to-apply-changes-of-newly-added-user-groups-without-needing-to-reboot
gpasswd -a "$user_name" sudo
gpasswd -a "$user_name" console

## Debugging.
id "$user_name"

## https://askubuntu.com/questions/250720/is-it-necessary-to-reboot-after-changing-group-membership
su --login "$user_name"

## Debugging.
id "$user_name"

echo "
Defaults !requiretty
user ALL=(ALL) NOPASSWD: ALL
" > /etc/sudoers.d/allow-all-sudo-on-ci

cat /etc/sudoers.d/allow-all-sudo-on-ci

chown --recursive "$user_name:$user_name" /home/travis

sudo --non-interactive -u "$user_name" /bin/bash - << EOF

set -x
set -e

id "$user_name"

sudo --non-interactive -E ./build-steps.d/1100_sanity-tests --internalrun --build --target root --allow-untagged true --allow-uncommitted true
sudo --non-interactive -E ./build-steps.d/1120_prepare-build-machine --internalrun --build --target root
sudo --non-interactive -E ./build-steps.d/1130_cowbuilder-setup --internalrun --build --target root
sudo --non-interactive -E ./build-steps.d/1200_create-debian-packages --internalrun --build --target root

EOF

## XXX
#make_cross_build_platform_list="armel armhf i386 amd64 arm64"

true "$0 INFO: OK. End."
