#!/bin/bash

## Copyright (C) 2019 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

true "$0: start"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## travis.debian.net does not pass the CI environment variable to docker.
## build script reads CI variable.
if echo "$PWD" | grep -q travis ; then
   true "INFO: travis detected, ok."
elif [ ! "$CI" = "true" ]; then
   true "ERROR: You probably do not want to run this outside of a CI \
environment, because it uses virsh to undefine virtual machines."
   exit 1
fi

export CI=true

apt-get update

## Sanity tests.
apt-get --yes dist-upgrade
dpkg --configure -a

apt-get --yes install sudo virt-what lintian mmdebstrap

codename="buster-developers" \
   ./packages/usability-misc/usr/bin/whonix-repo-add

user_name=user
user_to_be_created=user

adduser --no-create-home --disabled-login --gecos "" "$user_to_be_created"

addgroup --system console

adduser "$user_name" sudo
adduser "$user_name" console

apt-get update

## Sanity tests.
apt-get --yes dist-upgrade
dpkg --configure -a

## whonix-legacy: Prevent debconf questions by firmware packages.
## usability-misc: apt-get-noninteractive
apt-get --yes install whonix-legacy usability-misc

apt-get-noninteractive --yes install whonix-host-xfce-kvm-nonfreedom

## The environment variables are not set here.
#true "$0: TRAVIS_DEBIAN_BUILD_DIR: $TRAVIS_DEBIAN_BUILD_DIR"
#true "$0: TRAVIS_DEBIAN_TARGET_DIR: $TRAVIS_DEBIAN_TARGET_DIR"

true "$0 INFO: OK. End."
