#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

WHONIX_BUILD_PARSED="1"
ROOT_CHECK="0"
VMNAME="internalrun"

source pre
source variables

cleanup_files() {
   trap "error_handler_general" ERR INT TERM

   shopt -s nullglob
   shopt -s dotglob

   rm --force "$WHONIX_SOURCE_FOLDER/packages/"*".dsc"
   rm --force "$WHONIX_SOURCE_FOLDER/packages/"*".changes"
   rm --force "$WHONIX_SOURCE_FOLDER/packages/"*".tar.gz"
   rm --force "$WHONIX_SOURCE_FOLDER/packages/"*".build"
   rm --force "$WHONIX_SOURCE_FOLDER/packages/"*".deb"

   local list
   list="$(echo "$WHONIX_SOURCE_FOLDER/packages/"* | sort)"
   for item in $list; do
      if [ ! -d "$item" ]; then
         true "INFO: Not a folder: $item"
         continue
      fi
      cd "$item"
      ./clean
   done

}

true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
cleanup_files
benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE No error detected. (benchmark: $benchmark_took_time)${reset}"
