#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

WHONIX_BUILD_PARSED="1"
ROOT_CHECK="0"
VMNAME="internalrun"

source pre
source variables

cleanup_files() {
   trap "error_handler_general" ERR INT TERM

   set +x

   local result="$(gawk '/^Package\:[[:space:]]*.*$$/ { match($$0, /^Package:[[:space:]]*(.*)$$/, m); print m[1]"*.deb" }' "$WHONIX_SOURCE_FOLDER/debian/control")"

   for dp in $result; do
      local cmd="rm --force $WHONIX_SOURCE_FOLDER/../$dp"
      echo "$cmd"
      $cmd
   done

   local cmd="rm --force $WHONIX_SOURCE_FOLDER/../$(gawk '/^Source\:[[:space:]]+.*$$/ { match($$0, /^Source:[[:space:]]+(.*)$$/, m); print m[1]"*.dsc" }' "$WHONIX_SOURCE_FOLDER/debian/control")"
   echo "$cmd"
   $cmd

   local cmd="rm --force $WHONIX_SOURCE_FOLDER/../$(gawk '/^Source\:[[:space:]]+.*$$/ { match($$0, /^Source:[[:space:]]+(.*)$$/, m); print m[1]"*.changes" }' "$WHONIX_SOURCE_FOLDER/debian/control")"
   echo "$cmd"
   $cmd

   local cmd="rm --force $WHONIX_SOURCE_FOLDER/../$(gawk '/^Source\:[[:space:]]+.*$$/ { match($$0, /^Source:[[:space:]]+(.*)$$/, m); print m[1]"*.tar.*" }' "$WHONIX_SOURCE_FOLDER/debian/control")"
   echo "$cmd"
   $cmd

   local cmd="rm --force $WHONIX_SOURCE_FOLDER/../$(gawk '/^Source\:[[:space:]]+.*$$/ { match($$0, /^Source:[[:space:]]+(.*)$$/, m); print m[1]"*.build" }' "$WHONIX_SOURCE_FOLDER/debian/control")"
   echo "$cmd"
   $cmd

   local cmd="rm --force $WHONIX_SOURCE_FOLDER/debian/changelog"
   echo "$cmd"
   $cmd

   local cmd="fakeroot "$WHONIX_SOURCE_FOLDER/debian/rules" clean"
   echo "$cmd"
   $cmd

   set -x
}

true "${bold}INFO: Currently running script: $0${reset}"
cleanup_files
true "${bold}INFO: End of: $0 No error detected.${reset}"
