#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR/pre"
source "$MYDIR/colors"
source "$MYDIR/variables"

root_check

create_local_temp_apt_repo() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   local gpg_temp_homedir
   gpg_temp_homedir="$($CHROOT mktemp --directory)"

   ## Apt signing key.
   sudo -u "$user_name" gpg \
      --no-options \
      --no-default-keyring \
      --homedir "$WHONIX_LOCAL_SIGNING_KEY_FOLDER" \
      --export "$DEBEMAIL" \
         | \
            gpg \
               --no-options \
               --no-default-keyring \
               --homedir "$CHROOT_FOLDER/$gpg_temp_homedir" \
               --keyring "$CHROOT_FOLDER/etc/apt/trusted.gpg.d/whonix-temporary-local-apt-repository.gpg" \
               --import

   ## For debugging.
   gpg \
      --no-options \
      --no-default-keyring \
      --homedir "$WHONIX_LOCAL_SIGNING_KEY_FOLDER" \
      --keyring "$CHROOT_FOLDER/etc/apt/trusted.gpg.d/whonix-temporary-local-apt-repository.gpg" \
      --keyid-format "0xlong" \
      --fingerprint

   ## DEB_INSTALL_FOLDER Example:
   ## /mnt/initialdeb

   ## WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER Example:
   ## /var/lib/whonix/sources_temp_list.d

   ## EMPTY_DIR Example:
   ## "/tmp/empty"

   ## WHONIX_APT_REPOSITORY_FOLDER Example:
   ## /home/user/whonix_binary/aptrepo_local

   mkdir --parents "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER"
   mkdir --parents "$CHROOT_FOLDER/$EMPTY_DIR"
   mkdir --parents "$CHROOT_FOLDER/$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER"

   ## Mount our local apt repository inside the image (or machine).
   mount --bind "$WHONIX_APT_REPOSITORY_FOLDER" "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER"

   ## Create a sources.list file for our local apt repository.
   echo "deb file:$DEB_INSTALL_FOLDER/ $WHONIX_BUILD_APT_CODENAME main" > "$CHROOT_FOLDER/$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER/whonix_temp_initialdeb.list"

   ## Copy which (frozen) sources.list will be used for building Whonix into the image (or machine).
   if [ "$whonix_build_no_upstream_sources_list" = "1" ]; then
      true "${cyan}INFO $BASH_SOURCE: Not copying "$whonix_build_sources_list" to "$CHROOT_FOLDER/$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER/build_sources.list", \
because whonix_build_no_upstream_sources_list is set to 1.${reset}"
   else
      cp "$whonix_build_sources_list" "$CHROOT_FOLDER/$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER/build_sources.list"
   fi

   sync

   ## For debugging / Info.
   ls -la "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER"
   ls -la "$CHROOT_FOLDER/$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER"
   if [ "$whonix_build_no_upstream_sources_list" = "1" ]; then
      true
   else
      cat "$CHROOT_FOLDER/$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER/build_sources.list"
   fi
   cat "$CHROOT_FOLDER/$WHONIX_SOURCES_LIST_TEMP_BUILD_FOLDER/whonix_temp_initialdeb.list"
}

true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
create_local_temp_apt_repo
benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE ${1+"$@"} | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
