#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## Copyright (C) 2018 Algernon
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR/pre"
source "$MYDIR/colors"
source "$MYDIR/variables"

main() {
   root_check

   ## DEB_INSTALL_FOLDER Example:
   ## /mnt/initialdeb

   ## dist_sources_list_templ_build_folder Example:
   ## /var/lib/whonix/sources_temp_list.d

   ## EMPTY_DIR Example:
   ## "/tmp/empty"

   ## dist_apt_repository_folder Example:
   ## /home/user/whonix_binary/aptrepo_local

   mkdir --parents "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER"
   mkdir --parents "$CHROOT_FOLDER/$EMPTY_DIR"
   mkdir --parents "$CHROOT_FOLDER/$dist_sources_list_templ_build_folder"

   ## sets: dist_apt_repository_folder
   set_whonix_build_reprepro_folder_options

   if [ "$build_remote_derivative_pkgs" = "true" ]; then
      cp "$source_code_folder_dist/packages/usability-misc/usr/bin/repo-add-dist" "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER/repo-add-dist"

      ## creates $dist_sources_list_temp_initial_deb_sources_list
      $CHROOT bash -x "$DEB_INSTALL_FOLDER/repo-add-dist"
   else
      ## Mount our local apt repository inside the image (or machine).
      mount --bind "$dist_apt_repository_folder" "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER"

      ## Create a sources.list file for our local apt repository.
      echo "deb [trusted=yes] file:$DEB_INSTALL_FOLDER/ $dist_build_apt_codename main contrib non-free" > "$dist_sources_list_temp_initial_deb_sources_list"
   fi

   ## For debugging / Info.
   cat "$dist_sources_list_temp_initial_deb_sources_list"

   ## Copy which (frozen) sources.list will be used for building Whonix into the image (or machine).
   cp "$whonix_build_sources_list_primary" "$CHROOT_FOLDER/$dist_sources_list_templ_build_folder/build_sources.list"

   ## For debugging / Info.
   cat "$CHROOT_FOLDER/$dist_sources_list_templ_build_folder/build_sources.list"

   sync

   ## For debugging / Info.
   ls -la "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER"
   ls -la "$CHROOT_FOLDER/$dist_sources_list_templ_build_folder"
}

main "$@"
