#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR/pre"
source "$MYDIR/colors"
source "$MYDIR/variables"

delete_vm() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   ## Turning off the VM without saving.
   sudo -u "$user_name" VBoxManage controlvm "$VMNAME" poweroff || true
   sync

   ## Delete old Whonix-Gateway.
   sudo -u "$user_name" VBoxManage unregistervm "$VMNAME" --delete || true
   sync

   ## The "VBoxManage unregistervm  --delete" does not do its job,
   ## we have to manually delete the VM folder.
   if [ -d "$HOMEVAR/VirtualBox VMs/$VMNAME" ]; then
      rm -r "$HOMEVAR/VirtualBox VMs/$VMNAME"
   fi
   sync

   ## Delete old ova.
   if [ -e "$binary_image_ova" ]; then
      rm "$binary_image_ova"
   fi
   sync
}

true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
delete_vm
benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE ${1+"$@"} | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
