#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR/pre"
source "$MYDIR/colors"
source "$MYDIR/variables"

main() {
   ## Turning off the VM without saving.
   sudo $SUDO_OPTS VBoxManage controlvm "$VMNAME" poweroff || true
   sync

   ## Delete old Whonix-Gateway.
   sudo $SUDO_OPTS VBoxManage unregistervm "$VMNAME" --delete || true
   sync

   ## The "VBoxManage unregistervm  --delete" does not do its job,
   ## we have to manually delete the VM folder.
   if [ -d "$HOMEVAR/VirtualBox VMs/$VMNAME" ]; then
      rm -r "$HOMEVAR/VirtualBox VMs/$VMNAME"
   fi
   sync

   ## Delete old ova.
   if [ -e "$binary_image_ova" ]; then
      rm "$binary_image_ova"
   fi
   sync
}

main "$@"
