#!/bin/bash

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

dist_build_one_parsed="1"
VMNAME="internalrun"

source pre
source colors
source variables

main() {
   true "gpg_bin: $gpg_bin"
   true "dist_build_sign_local_repository: $dist_build_sign_local_repository"
   true "dist_local_signing_key_folder: $dist_local_signing_key_folder"
   true "dist_build_reprepro_signing_options: $dist_build_reprepro_signing_options"
   true "make_use_debsign: $make_use_debsign"

   echo "test" | tee "$binary_build_folder_dist/test_sign_file" >/dev/null
   chown "$user_name:$user_name" "$binary_build_folder_dist/test_sign_file"

   $gpg_bin --detach-sign --armor --yes --output "$binary_build_folder_dist/test_sign_file.asc" "$binary_build_folder_dist/test_sign_file"
   $gpg_bin --verify "$binary_build_folder_dist/test_sign_file.asc" "$binary_build_folder_dist/test_sign_file"

   rm "$binary_build_folder_dist/test_sign_file"
   rm "$binary_build_folder_dist/test_sign_file.asc"
}

main "$@"
