#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

whonix_build_one_parsed="1"
VMNAME="internalrun"

source pre
source colors
source variables

main() {
   echo "test" > "$WHONIX_BINARY/test_sign_file"
   $gpg_bin --detach-sign --armor --yes --output "$WHONIX_BINARY/test_sign_file.asc" "$WHONIX_BINARY/test_sign_file"
   $gpg_bin --verify "$WHONIX_BINARY/test_sign_file.asc" "$WHONIX_BINARY/test_sign_file"
   rm "$WHONIX_BINARY/test_sign_file"
   rm "$WHONIX_BINARY/test_sign_file.asc"
}

main "$@"
