#!/bin/bash

set -x
set -e

rm -r -f ~/live-build-test
mkdir ~/live-build-test
cd ~/live-build-test

##     --chroot-filesystem ext4 \ - issue?

lb config \
    --distribution "bookworm" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --source false \
    --zsync false

echo "task-lxde-desktop firefox-esr" | tee ./config/package-lists/my.list.chroot >/dev/null

lb config --dump
lb config --validate

lb build

true "END"
