#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

dist_build_one_parsed="1"
VMNAME="internalrun"

source pre
source colors
source variables

main() {
   cd live-build

   $SUDO_TO_ROOT cp --no-clobber --verbose /usr/sbin/debootstrap /usr/sbin/debootstrap-backup
   ## live-build: support configuration of debootstrap binary
   ## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031929
   $SUDO_TO_ROOT cp --verbose "$dist_source_help_steps_folder/pbuilder-debootstrap-command-filter" /usr/sbin/debootstrap

   ## The word 'chroot' is set in live-build 'lb'.
   ## It is the folder name where live-build expects "$DEBOOTSTRAP" to bootstrap Debian to.
   dist_grml_mount_point="chroot"

   ## 'lb build' internally runs 'debootstrap'.

   $SUDO_TO_ROOT \
      $LIVEBUILD_PREFIX \
      dist_build_multiarch_package_item="$dist_build_target_arch" \
      dist_grml_mount_point="$dist_grml_mount_point" \
      lb build

   CHROOT_FOLDER="$source_code_folder_dist/live-boot/chroot"
   #CHROOT_FOLDER="$binary_build_folder_dist/live-boot/chroot"

   ## XXX: Duplicate code in help-steps/chroot-raw
   ## Delete extraneous, duplicate /etc/apt/sources.list.d/0000debian_stable_current_clearnet.list by mmdebstrap.
   if test -f "$CHROOT_FOLDER/$dist_mmdebstrap_build_sources_list_primary" ; then
      if diff "$dist_build_sources_list_primary" "$CHROOT_FOLDER/$dist_mmdebstrap_build_sources_list_primary" ; then
         true "INFO: Host $dist_build_sources_list_primary matches chroot $CHROOT_FOLDER/$dist_mmdebstrap_build_sources_list_primary, deleting, ok."
         $SUDO_TO_ROOT rm --verbose "$CHROOT_FOLDER/$dist_mmdebstrap_build_sources_list_primary"
      else
         error "ERROR: Host $dist_build_sources_list_primary does not match chroot $CHROOT_FOLDER/$dist_mmdebstrap_build_sources_list_primary"
      fi
   else
      true "INFO: chroot $CHROOT_FOLDER/$dist_mmdebstrap_build_sources_list_primary, does not exist, ok."
   fi

   true
}

main "$@"
