#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

main() {
   mkdir --parents "$binary_build_folder_live_build"
   cd "$binary_build_folder_live_build"

   ## folder derivative-maker/live-build can be re-created using:
   ## 1. lb config
   ## 2. help-steps/live-config

   ## TODO: research
   #--apt-indices false
   #--apt-options OPTION|"OPTIONS"
   #--backports true|false
   #--bootappend-live PARAMETER|"PARAMETERS"
   #--checksums md5|sha1|sha224|sha256|sha384|sha512|none
   ## calamares
   #--debian-installer cdrom|netinst|netboot|businesscard|live|none
   ## --freedom true|false
   #--firmware-binary true|false
   #--firmware-chroot true|false
   ## fasttrack?
   #--keyring-packages PACKAGE|"PACKAGES"
   #--cache-stages "bootstrap rootfs"

   ## TODO: apt --error-on=any
   ## TODO: mmdebstrap
   ## TODO: onion

   ## TODO: lb config --clean

   ## TODO:
   ## --architecture ARCHITECTURE
   ## --distribution CODENAME
   ## --hdd-label LABEL
   ## --hdd-size SIZE
   ## --image-name NAME
   ## --iso-application NAME
   ## --iso-publisher NAME
   ## --iso-volume NAME
   ## --source

   ## TODO: live
   ## --initramfs none|live-boot
   ## --system live
   ## --chroot-filesystem ext4
   ## --binary-image hdd
   ## --bootloaders grub-efi

   ## TODO: kernel headers
   ## --linux-packages PACKAGE|"PACKAGES"

   ## '--variant=required' is only supported by 'mmdebstrap'. It might not be supported by 'debootstrap'.

   ## --cache-packages false
   ## mmdebstrap: fix debootstrap, live-boot compatibility / support --download-only, --foreign, --second-stage, --no-check-gpg
   ## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031932

   ## TODO
   ## --apt-ftp-proxy "${REPO_PROXY}"
   ## --apt-http-proxy "${REPO_PROXY}"

   lb config \
      --distribution "$dist_build_apt_stable_release" \
      --mirror-binary "$dist_build_apt_sources_mirror" \
      --mirror-binary-security "$dist_build_apt_sources_security_mirror" \
      --mirror-bootstrap "$dist_build_apt_sources_mirror" \
      --mirror-chroot "$dist_build_apt_sources_mirror" \
      --mirror-chroot-security "$dist_build_apt_sources_security_mirror" \
      --mirror-debian-installer "$dist_build_apt_sources_mirror" \
      --parent-mirror-binary "$dist_build_apt_sources_mirror" \
      --parent-mirror-binary-security "$dist_build_apt_sources_security_mirror" \
      --parent-mirror-bootstrap "$dist_build_apt_sources_mirror" \
      --parent-mirror-chroot "$dist_build_apt_sources_mirror" \
      --parent-mirror-chroot-security "$dist_build_apt_sources_security_mirror" \
      --parent-mirror-debian-installer "$dist_build_apt_sources_mirror" \
      --cache-packages false \
      --apt-recommends false \
      --apt-source-archives false \
      --archive-areas "main contrib non-free non-free-firmware" \
      --binary-filesystem ext4 \
      --chroot-filesystem ext4 \
      --binary-image iso-hybrid \
      --debootstrap-options "--variant=minbase" \
      --source false \
      --system normal

   ## Running 'lb config' should not result in any further changes.
   #lb config

   lb config --dump

   lb config --validate
}

main "$@"
