#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

main() {
   cd live-build

   $SUDO_TO_ROOT cp --no-clobber --verbose /usr/sbin/debootstrap /usr/sbin/debootstrap-backup
   ## live-build: support configuration of debootstrap binary
   ## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031929
   ## Functional.
   #$SUDO_TO_ROOT cp --verbose "$dist_source_help_steps_folder/pbuilder-debootstrap-command-filter" /usr/sbin/debootstrap
   ## Test.
   if test -h /usr/sbin/debootstrap ; then
      $SUDO_TO_ROOT unlink /usr/sbin/debootstrap
   fi
   $SUDO_TO_ROOT ln -s "$dist_source_help_steps_folder/pbuilder-debootstrap-command-filter" /usr/sbin/debootstrap
   ## Debugging.
   ls -la /usr/sbin/debootstrap

   ## The word 'chroot' is set in live-build 'lb'.
   ## It is the folder name where live-build expects "$DEBOOTSTRAP" to bootstrap Debian to.
   dist_grml_mount_point="chroot"

   ## 'lb build' internally runs 'debootstrap'.

   ## Create the ISO chroot and initial ISO.
   ## Slightly wasteful because in the overnext step the ISO will be deleted
   ## but the ISO chroot will be kept.
   $SUDO_TO_ROOT \
      $LIVEBUILD_PREFIX \
      dist_build_multiarch_package_item="$dist_build_target_arch" \
      dist_grml_mount_point="$dist_grml_mount_point" \
      lb build

   ## Delete the ISO but keep the ISO chroot.
   $SUDO_TO_ROOT \
      $LIVEBUILD_PREFIX \
      dist_build_multiarch_package_item="$dist_build_target_arch" \
      dist_grml_mount_point="$dist_grml_mount_point" \
      lb clean --binary

   ## TODO: run other derivative-maker build steps

   ## Remaster the ISO.
   ## This does not re-create the ISO chroot thanks to live-build's stage files.
   $SUDO_TO_ROOT \
      $LIVEBUILD_PREFIX \
      dist_build_multiarch_package_item="$dist_build_target_arch" \
      dist_grml_mount_point="$dist_grml_mount_point" \
      lb build

   true
}

main "$@"
