#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "${bold}${red}$0 ERROR:${reset} BASH_COMMAND: $BASH_COMMAND"
   exit 1
}

trap "error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

cd help-steps

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"

export ROOT_CHECK="0"
export VMNAME="internalrun"

source pre
source variables

make_debian_upstream_tarball() {
   trap "error_handler_general" ERR INT TERM

   ## The -n switch for gzip is required to produce a reproducible tarball.

   sudo -E -u "$USERNAME" \
      faketime -f "2013-08-15 11:02:35" \
         git archive \
            --format=tar HEAD \
            | gzip -n > "$WHONIX_SOURCE_PARENTDIR/whonix_${whonix_build_closest_git_tag}.orig.tar.gz"

   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
make_debian_upstream_tarball
true "${bold}INFO: End of: $0 No error detected.${reset}"
