#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "${bold}${red}$0 ERROR:${reset} BASH_COMMAND: $BASH_COMMAND"
   exit 1
}

trap "error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

cd help-steps

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"

export ROOT_CHECK="0"
export VMNAME="internalrun"

source pre
source variables

make_debian_upstream_tarball() {
   trap "error_handler_general" ERR INT TERM

   sudo -E -u user \
      git archive \
         --format=tar HEAD \
         | gzip > "$WHONIX_SOURCE_PARENTDIR"/whonix_"$whonix_build_whonix_version_new".orig.tar.gz

   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
make_debian_upstream_tarball
true "${bold}INFO: End of: $0 No error detected.${reset}"
