#!/bin/bash

set -x

true "$0"

error_handler_mount-img() {
: echo "
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
"

#"$MYDIR"/unchroot-img
"$MYDIR"/unmount-img-force
#"$MYDIR"/unmount-vdi-force

: echo "
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
"

exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/variables
source "$MYDIR"/pre

mount_img() {
   trap "error_handler_mount-img" ERR INT TERM

   sync
   
   kpartx -av /home/"$USERNAME"/whonix_binary/"$VMNAME"_copy.img
   sync
   
   mkdir --parents "$CHROOT_FOLDER"
   sync
   
   mount /dev/mapper/loop0p1 "$CHROOT_FOLDER"
   sync
} 

mount_img

