#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler_mount-img() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

mount_img() {
   trap "error_handler_mount-img" ERR INT TERM

   local raw_file="$WHONIX_BINARY/$VMNAME.img"
   mkdir --parents "$CHROOT_FOLDER"
   sync

   guestmount -o allow_other -a "$raw_file" -m /dev/sda1 "$CHROOT_FOLDER"
   sync
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping script, because BARE_METAL=1: $0${reset}"
   exit 0
else
   true "${bold}INFO: Currently running script: $0 ${1+"$@"}${reset}"
   mount_img
   benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
fi
