#!/bin/bash

set -x

if [ "$BARE_METAL" = "1" ]; then
   true "Skipping script, because BARE_METAL=1: $0"
   exit 0
else
   true "Currently running script: $0"
fi

error_handler_mount-img() {
: echo "
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
"
exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/variables
source "$MYDIR"/pre

mount_img() {
   trap "error_handler_mount-img" ERR INT TERM

   sync
   
   kpartx -av "$WHONIX_BINARY"/"$VMNAME".img
   sync
   
   mkdir --parents "$CHROOT_FOLDER"
   sync
   
   mount /dev/mapper/loop0p1 "$CHROOT_FOLDER"
   sync
} 

mount_img

