#!/bin/bash

## Copyright (C) 2017 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## This script fixes the interaction between multiple tools.
##
## - `cowbuilder` hardcodes setting '--buildplace'.
##
## - `pbuilder` sets by default '--force-check-gpg'.
##   (This could also be sorted in `dist_build_pbuilder_config_file`.)
## - `pbuilder` `/usr/lib/pbuilder/pbuilder-createbuildenv` hardcodes calling `${DEBOOTSTRAP}`.
##
## - `mmdebstrap` does not support '--force-check-gpg'.
## - `mmdebstrap` requires the parameters in a certain order.

set -x
set -e

true "${bold}INFO: Currently running $0.${reset}"

args_original="$@"

## Example $@ when called by cowbuilder:
## --arch=amd64 --include=apt --variant=buildd --force-check-gpg bullseye /var/cache/pbuilder/base.cow_amd64 http://HTTPS///deb.debian.org/debian

## Debugging.
true "BUILDPLACE: $BUILDPLACE"
true "dist_grml_mount_point: $dist_grml_mount_point"
true "http_proxy: $http_proxy"
true "REPO_PROXY: ${REPO_PROXY}"
true "APTGETOPT: $APTGETOPT"
true "dist_build_target_arch: $dist_build_target_arch"
true "dist_build_apt_stable_release: $dist_build_apt_stable_release"
true "dist_build_apt_sources_mirror: $dist_build_apt_sources_mirror"
true "dist_aptgetopt_file: $dist_aptgetopt_file"
cat "$dist_aptgetopt_file"
true "dist_build_sources_list_primary: $dist_build_sources_list_primary"
cat "$dist_build_sources_list_primary"

## args_filtered is currently not required. Just keeping it for debugging
## purposes in applications such as grml-debootstrap, cowbuilder or pbuilder in
## the future set additional arguments.

args_filtered="$args_original"

true "INFO: filter out default mirror by cowbuilder or pbuilder (if we were not using --mirror)"
args_filtered="${args_filtered//"http://ftp.us.debian.org/debian"}"
args_filtered="${args_filtered//"https://ftp.us.debian.org/debian"}"

true "INFO: filter out default mirror by grml-debootstrap"
args_filtered="${args_filtered//"http://httpredir.debian.org/debian"}"
args_filtered="${args_filtered//"https://httpredir.debian.org/debian"}"
args_filtered="${args_filtered//"http://deb.debian.org/debian"}"
args_filtered="${args_filtered//"https://deb.debian.org/debian"}"

true "INFO: filter out --mirror"
args_filtered="${args_filtered//"$dist_build_apt_sources_mirror"}"

true "INFO: filter out variable BUILDPLACE (set by pbuilder) because we need to adjust the order of arguments"
args_filtered="${args_filtered//"$BUILDPLACE"}"

true "INFO: filter out --force-check-gpg (set by cowbuilder or pbuilder) since mmdebstrap does this by default and therefore does not support that command"
args_filtered="${args_filtered//"--force-check-gpg"}"

true "INFO: filter out --verbose (set by grml-debootstrap) since we add it by ourselves."
args_filtered="${args_filtered//"--verbose"}"

true "INFO: filter out --include=apt (set by cowbuilder or pbuilder) since we will use our own --include switch."
args_filtered="${args_filtered//"--include=apt"}"

true "INFO: Default to default --variant. Decide which packages are to be installed using --include."
args_filtered="${args_filtered//"--variant=buildd"}"

true "INFO: filter out '--arch amd64' since we will use our own."
args_filtered="${args_filtered//"--arch $dist_build_target_arch"}"
true "INFO: filter out '--arch=amd64' since we will use our own."
args_filtered="${args_filtered//"--arch=$dist_build_target_arch"}"

true "INFO: filter out suite since we will use our own."
args_filtered="${args_filtered//"$dist_build_apt_stable_release"}"

true "INFO: filter out --include (that grml-debootstrap sets) since we will use our own."
args_filtered="${args_filtered//"--include"}"

true "INFO: filter out sources list file (that grml-debootstrap sets) since we will use our own."
args_filtered="${args_filtered//"$dist_build_sources_list_primary"}"

true "INFO: filter out dist_build_apt_sources_mirror (that pbuilder sets) since we will use our own."
args_filtered="${args_filtered//"$dist_build_apt_sources_mirror"}"

true "INFO: filter out extraneous white spaces."
args_filtered="${args_filtered//" "}"

true "FINAL args_filtered: $args_filtered"
## example args_filtered:
## /mnt/debootstrap.15557

## mmdebstrap needs 3 positional arguments.
## suite buildplace path-to-sources-list
## For example when using grml-debootstrap:
## bullseye /mnt/debootstrap.15557 /home/user/derivative-maker/build_sources/debian_stable_current_clearnet.list
## For example when using cowbuilder:
## bullseye /var/cache/pbuilder/base.cow_amd64 /home/user/derivative-maker/build_sources/debian_stable_current_clearnet.list

if [ "$BUILDPLACE" = "" ]; then
   ## For grml-debootstrap.

   true "$0: Variable BUILDPLACE is unset."
   true "$0: This means this script was probably called by grml-debootstrap."
   true "$0: Setting BUILDPLACE to: $dist_grml_mount_point"
   BUILDPLACE="$dist_grml_mount_point"

   include_opt="--include=eatmydata,apt-transport-tor,gpg,gpg-agent,fasttrack-archive-keyring"

   ## example:
   ## /home/user/derivative_dot/derivative-maker/help-steps/mmdebstrap --verbose --debug --format directory --variant=required --architectures=amd64 --aptopt=/home/user/derivative-binary/aptgetopt.conf --include=eatmydata,apt-transport-tor,gpg,gpg-agent,fasttrack-archive-keyring bullseye /mnt/debootstrap.33132 /home/user/derivative-maker/build_sources/debian_stable_current_clearnet.list
else
   ## For cowbuilder.

   true "$0: Variable BUILDPLACE is set."
   true "$0: This means this script was probably called by called by pbuilder which was called by cowbuilder."

   ## build dependencies
   include_opt="--include=apt,sudo,devscripts,debhelper,strip-nondeterminism,fakeroot,apt-transport-tor,eatmydata,aptitude,cowdancer,fasttrack-archive-keyring"

   ## example:
   ## /home/user/derivative-maker/help-steps/mmdebstrap --verbose --debug --format directory --variant=required --architectures=amd64 --aptopt=/home/user/derivative-binary/aptgetopt.conf --include=apt,sudo,devscripts,debhelper,strip-nondeterminism,fakeroot,apt-transport-tor,eatmydata,aptitude,cowdancer,fasttrack-archive-keyring bullseye /var/cache/pbuilder/base.cow_amd64 /home/user/derivative-maker/build_sources/debian_stable_current_clearnet.list
fi

## Sanity tests.
[ -n "$dist_build_apt_stable_release" ] || error "dist_build_apt_stable_release is unset!"
[ -n "$BUILDPLACE" ] || error "BUILDPLACE is unset!"
[ -n "$dist_build_sources_list_primary" ] || error "dist_build_sources_list_primary is unset!"

"$dist_source_help_steps_folder/mmdebstrap" \
   --verbose \
   --debug \
   --format directory \
   --variant=required \
   --architectures="$dist_build_multiarch_package_item" \
   --aptopt="$dist_aptgetopt_file" \
   $include_opt \
   "$dist_build_apt_stable_release" \
   "$BUILDPLACE" \
   "$dist_build_sources_list_primary"

true "${bold}INFO: End of script $0.${reset}"
