#!/bin/bash

## Copyright (C) 2017 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## This script fixes the interaction between multiple tools.
##
## - `cowbuilder` hardcodes setting '--buildplace'.
##
## - `pbuilder` sets by default '--force-check-gpg'.
##   (This could also be sorted in `dist_build_pbuilder_config_file`.)
## - `pbuilder` `/usr/lib/pbuilder/pbuilder-createbuildenv` hardcodes calling `${DEBOOTSTRAP}`.
##
## - `mmdebstrap` does not support '--force-check-gpg'.
## - `mmdebstrap` requires the parameters in a certain order.

set -x
set -e

true "${bold}INFO: Currently running $0.${reset}"

args="$@"

## Example $@ when called by cowbuilder:
## --arch=amd64 --include=apt --variant=buildd --force-check-gpg bullseye /var/cache/pbuilder/base.cow_amd64 http://HTTPS///deb.debian.org/debian

## Debugging.
true "BUILDPLACE: $BUILDPLACE"
true "dist_build_sources_list_primary: $dist_build_sources_list_primary"
true "http_proxy: $http_proxy"
true "REPO_PROXY: ${REPO_PROXY}"
true "APTGETOPT: $APTGETOPT"
true "dist_build_target_arch: $dist_build_target_arch"

## filter out default mirror by cowbuilder or pbuilder (if we were not using --mirror)
args="${args//"http://ftp.us.debian.org/debian"}"
args="${args//"https://ftp.us.debian.org/debian"}"

## filter out default mirror by grml-debootstrap
args="${args//"http://httpredir.debian.org/debian"}"
args="${args//"https://httpredir.debian.org/debian"}"
args="${args//"http://deb.debian.org/debian"}"
args="${args//"https://deb.debian.org/debian"}"

## filter out --mirror
args="${args//"$dist_build_apt_sources_mirror"}"

## filter out variable BUILDPLACE (set by pbuilder) because we need to adjust the order of arguments
args="${args//"$BUILDPLACE"}"

## filter out --force-check-gpg (set by cowbuilder or pbuilder) since mmdebstrap does this by default and therefore does not support that command
args="${args//"--force-check-gpg"}"

## filter out --verbose (set by grml-debootstrap) since we add it by ourselves.
args="${args//"--verbose"}"

## filter out --include=apt (set by cowbuilder or pbuilder) since we will use our own --include switch.
args="${args//"--include=apt"}"

## Default to default --variant. Decide which packages are to be installed using --include.
args="${args//"--variant=buildd"}"

## filter out --arch=amd64 since we will use our own.
args="${args//"--arch=$dist_build_target_arch"}"

## example args:
## bullseye

true "args: $args"

true "dist_aptgetopt_file: $dist_aptgetopt_file"
true "Now running: cat \$dist_aptgetopt_file"
cat "$dist_aptgetopt_file"

true "dist_build_sources_list_primary: $dist_build_sources_list_primary"
cat "$dist_build_sources_list_primary"

true "BUILDPLACE: $BUILDPLACE"

## mmdebstrap needs 3 positional arguments.
## suite buildplace path-to-sources-list
## For example when using grml-debootstrap:
## bullseye /mnt/debootstrap.15557 /home/user/derivative-maker/build_sources/debian_stable_current_clearnet.list
## For example when using cowbuilder:
## bullseye /var/cache/pbuilder/base.cow_amd64 /home/user/derivative-maker/build_sources/debian_stable_current_clearnet.list

if [ "$BUILDPLACE" = "" ]; then
   true "$0: Variable BUILDPLACE is unset."
   true "$0: This means this script was probably called by grml-debootstrap."

   "$dist_source_help_steps_folder/mmdebstrap" \
      --verbose \
      --debug \
      --format directory \
      --variant=required \
      --architectures="$dist_build_multiarch_package_item" \
      --aptopt="$dist_aptgetopt_file" \
      $args

   ## example:
   ## mmdebstrap --verbose --debug --architectures=amd64 --aptopt=/home/user/derivative-binary/aptgetopt.conf --arch amd64 --include=eatmydata,apt-transport-tor,gnupg2 bullseye /mnt/debootstrap.15557 /home/user/derivative-maker/build_sources/debian_stable_current_clearnet.list
else
   true "$0: Variable BUILDPLACE is set."
   true "$0: This means this script was probably called by called by pbuilder which was called by cowbuilder."

   ## build dependencies
   include_opt="--include=apt,sudo,devscripts,debhelper,strip-nondeterminism,fakeroot,apt-transport-tor,eatmydata,aptitude,cowdancer,fasttrack-archive-keyring"

   "$dist_source_help_steps_folder/mmdebstrap" \
      --verbose \
      --debug \
      --format directory \
      --variant=required \
      --architectures="$dist_build_multiarch_package_item" \
      --aptopt="$dist_aptgetopt_file" \
      $include_opt \
      $args \
      "$BUILDPLACE" \
      "$dist_build_sources_list_primary"

   ## example:
   ## /home/user/derivative-maker/help-steps/mmdebstrap --verbose --debug --format directory --variant=required --architectures=amd64 --aptopt=/home/user/derivative-binary/aptgetopt.conf --include=apt,sudo,devscripts,debhelper,strip-nondeterminism,fakeroot,apt-transport-tor,eatmydata,aptitude,cowdancer,fasttrack-archive-keyring --arch=amd64 bullseye /var/cache/pbuilder/base.cow_amd64 /home/user/derivative-maker/build_sources/debian_stable_current_clearnet.list
fi

true "${bold}INFO: End of script $0.${reset}"
