#!/bin/bash

## Copyright (C) 2017 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## This script gets executed by 'build-steps.d/*_cowbuilder-setup'.
## Install VirtualBox inside the chroot using 'dist-installer-cli'.
## Useful for running 'vboxmanage' inside a clean 'cowbuilder' chroot.

set -x
set -e

true "${bold}INFO: Currently running cowbuilder VirtualBox chroot script.${reset}"

set -o pipefail
#set -o nounset

## /usr/share/doc/pbuilder/examples/D10tmp
[ -n "$TMP" -a ! -d "$TMP" ] && mkdir -p "$TMP" || true
[ -n "$TMPDIR" -a ! -d "$TMPDIR" ] && mkdir -p "$TMPDIR" || true
## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=725434;msg=45
chmod 1777 "$TMP" || true
chmod 1777 "$TMPDIR" || true

#declare -p | awk '{print $3}' | sort

## Debugging.
cat "/home/$user_name/pbuilder_config_file"

source "/home/$user_name/pbuilder_config_file"

## XXX
user_name="dm-vbox-temp"

## virtualbox-installer / dist-installer-cli refuses to run as 'root'.
## Hence run virtualbox-installer / dist-installer-cli under account 'dm-vbox-temp'.

## TODO: remove
#adduser --quiet --group --system --home "/home/$user_name" "$user_name"
#usermod -d "/home/$user_name" "$user_name"

chown --recursive -- "$user_name" "/home/$user_name"

adduser "$user_name" sudo
printf "%s\n" "$user_name ALL=(ALL:ALL) NOPASSWD:ALL" | SUDO_EDITOR="" VISUAL="" EDITOR=tee visudo -f "/etc/sudoers.d/${user_name}_nopassword" >/dev/null

## {{ code duplication
##    - prepare-build-machine
##    - pbuilder-chroot-script-virtualbox
adduser --system --group --home "$HOMEVAR_VBOX_TEMP" -- "$user_name"
mkdir --parents -- "$HOMEVAR_VBOX_TEMP"
chown --recursive -- "$user_name:$user_name" "$HOMEVAR_VBOX_TEMP"
## Debugging.
groups -- "$user_name" || true
ls -la -- "$HOMEVAR_VBOX_TEMP"
## Sanity test.
test -d "/"
ls -la -- "$HOMEVAR_VBOX_TEMP"
## }}

## Debugging.
## sudo test.
sudo --non-interactive test -d /usr

## Debugging.
sudo --non-interactive -u "$user_name" -- test -x /usr/bin/dist-installer-cli-standalone
sudo --non-interactive -u "$user_name" -- ls -la /usr/bin/dist-installer-cli-standalone

printf '%s\n' "APTGETOPT_SERIALIZED:"
printf '%s\n' "--------------------"
printf '%s\n' "$APTGETOPT_SERIALIZED"
printf '%s\n' "--------------------"

## Not yet needed but useful as a sanity test.
mapfile -t APTGETOPT <<< "$APTGETOPT_SERIALIZED"
printf "%s\n" "APTGETOPT: ${APTGETOPT[@]}"

## NOTE: Code duplication in build-step prepare-build-machine
## NOTE: Code duplication in help-step pbuilder-chroot-script-virtualbox
dist_installer_cli_arguments=()
dist_installer_cli_arguments+=("--non-interactive")
dist_installer_cli_arguments+=("--virtualbox-only")
dist_installer_cli_arguments+=("--log-level=debug")
## Speed up the build? Not possible.
## `apt-get update` is actually needed to fetch
## VirtualBox from Debian 'unstable' repository.
## Option '--noupdate' should is not safe here, because if the installer adds a repository,
## then running 'apt update' is crucial for APT to learn about the new packages.
#dist_installer_cli_arguments+=("--noupdate")
##
## Run virtualbox-installer with '--noupgrade' because the system has been updated earlier.
## This is to avoid a race condition where an update is made available shortly after
## to avoid breaking the build.
dist_installer_cli_arguments+=("--noupgrade")
dist_installer_cli_arguments+=("--ci")
## Redundant.
dist_installer_cli_arguments+=("--no-boot")
## Redundant.
dist_installer_cli_arguments+=("--no-import")
## NOTE: End code duplication.

success="true"
## virtualbox-installer / dist-installer-cli
if ! sudo --non-interactive -u "$user_name" APTGETOPT_SERIALIZED="$APTGETOPT_SERIALIZED" bash -x /usr/bin/dist-installer-cli-standalone "${dist_installer_cli_arguments[@]}" ; then
  success=false
fi

#last_run_integer="$(printf '%s ' "/home/$user_name/dist-installer-cli-download/logs/"/* | awk '{print NF}')"

## Debugging.
ls -la -- "/home/$user_name/dist-installer-cli-download" || true
#ls -la -- "/home/$user_name/dist-installer-cli-download/logs" || true
#ls -la -- "/home/$user_name/dist-installer-cli-download/logs/$last_run_integer" || true

## No longer required because running 'dist-installer-cli-standalone' using 'bash -x'.
#cat -- "/home/$user_name/dist-installer-cli-download/logs/$last_run_integer/debug.log"
#cat -- "/home/$user_name/dist-installer-cli-download/logs/$last_run_integer/user.log"

true "INFO: dist-installer-cli-standalone success: $success"
if [ "$success" = "false" ];then
  error "VirtualBox installer failed inside cowbuilder chroot."
fi

## Check if VirtualBox really got installed.
command -v vboxmanage >/dev/null

rm -f -- "/etc/sudoers.d/${user_name}_nopassword"

true "${bold}INFO: End of script cowbuilder VirtualBox chroot script.${reset}"
