#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ ! "$whonix_build_no_unset_xtrace" ]; then
   set +x
fi
#set -x
set -e
set -o pipefail
set -o errtrace
shopt -s extdebug

function_trace_function() {
   true "INFO: BEGIN: $FUNCNAME"
   if [ -o xtrace ]; then
      set +x
      local xtrace_reenable="true"
   fi
   local frame temp one two
   frame="0"
   while caller >/dev/null 2>&1 $frame; do
      temp="$(caller $frame)" || true
      read one two _ <<< "$temp"
      if [ "$function_trace_result" = "" ] ; then
         function_trace_result="$two (line number: $one)"
      else
         function_trace_result="$function_trace_result
$two (line number: $one)"
      fi
      frame="$(( $frame + 1 ))" || true
   done
   function_trace_result="$(echo "$function_trace_result" | tac)" || true
   if [ "$xtrace_reenable" = "true" ]; then
      set -x
   fi
   true "INFO: END  : $FUNCNAME"
}

## {{{ process_backtrace_function - GPL v2.0 (only)

process_backtrace_function() {
   ## function    : process_backtrace_function
   ## Copyright   : Gian Paolo Ghilardi
   ## LICENSE     : GPL v2.0 (only)
   ## Source      : http://stackoverflow.com/a/1438241/2605155
   ## Modification: Patrick Schleizer
   true "INFO: BEGIN: $FUNCNAME"
   if [ -o xtrace ]; then
      set +x
      local xtrace_reenable="true"
   fi
   local TRACE CP CMDLINE PP
   TRACE=""
   CP="$$" ## PID of the script itself [1]
   while true ## safe because "all starts with init..."
   do
           CMDLINE="$(cat /proc/$CP/cmdline | tr '\000' ' ')" || true
           PP="$(grep PPid /proc/$CP/status | awk '{ print $2; }')" || true ## [2]
           TRACE="$TRACE : $CMDLINE\n"
           if [ "$CP" = "1" ]; then # we reach 'init' [PID 1] => backtrace end
                   break
           fi
           CP="$PP"
   done
   process_backtrace_result="$(echo -en "$TRACE" | tac | grep -n ":")" || true ## using tac to "print in reverse" [3]
   if [ "$xtrace_reenable" = "true" ]; then
      set -x
   fi
   true "INFO: END  : $FUNCNAME"
}

## }}} process_backtrace_function - GPL v2.0 (only)

errorhandlershell() {
   true "${cyan}${bold}INFO: Opening interactive shell...${reset}"
   true "${cyan}${bold}INFO: When you have finished, please enter \"exit 0\" to \
continue (Recommended against!) or \"exit 1\" to cleanup and exit. (Recommended.)${reset}"
   interactive_chroot_shell_bash_exit_code="0"
   $CHROOT /bin/bash || { interactive_chroot_shell_bash_exit_code="${PIPESTATUS[0]}" ; true; };
   if [ "$interactive_chroot_shell_bash_exit_code" = "0" ]; then
      true "${cyan}${bold}INFO: Interactive shell termited with \
exit code $interactive_chroot_shell_bash_exit_code, will ignore this error and continue...${reset}"
      ignore_error="true"
   else
      true "${cyan}${bold}INFO: Interactive shell termited with \
exit code $interactive_chroot_shell_bash_exit_code, cleanup and exit as requested...${reset}"
      ignore_error="false"
   fi
}

errorhandlerretry() {
   if [ ! "$whonix_build_dispatch_before_retry" = "" ]; then
      true "${cyan}${bold}INFO: dispatch before retry (--retry-before)...: $whonix_build_dispatch_before_retry ${reset}"
      whonix_build_dispatch_before_retry_exit_code="0"
      eval $whonix_build_dispatch_before_retry || { whonix_build_dispatch_before_retry_exit_code="$?" ; true; };
      if [ "$whonix_build_dispatch_before_retry_exit_code" = "0" ]; then
         true "${cyan}${bold}INFO: dispatch before retry (--retry-after) exit code was 0, ok. ${reset}"
      else
         true "${red}${bold}INFO: dispatch before retry (--retry-before) non-zero exit code: $whonix_build_dispatch_before_retry_exit_code ${reset}"
      fi
   else
      true "INFO: Skipping whonix_build_dispatch_before_retry (--retry-before), because empty, ok."
   fi

   true "${cyan}${bold}INFO: Retrying last_failed_bash_command...: $last_failed_bash_command ${reset}"
   retry_last_failed_bash_command_exit_code="0"
   eval $last_failed_bash_command || { retry_last_failed_bash_command_exit_code="$?" ; true; };
   if [ "$retry_last_failed_bash_command_exit_code" = "0" ]; then
      true "${cyan}${bold}INFO: Retry succeeded. exit code of last_failed_bash_command: $retry_last_failed_bash_command_exit_code ${reset}"
      unset whonix_build_auto_retry_counter
   else
      true "${red}${bold}INFO: Retry failed. exit code of last_failed_bash_command: $retry_last_failed_bash_command_exit_code ${reset}"
      last_failed_exit_code="$retry_last_failed_bash_command_exit_code"
      last_failed_bash_command="$last_failed_bash_command"
   fi

   if [ ! "$whonix_build_dispatch_after_retry" = "" ]; then
      true "${cyan}${bold}INFO: dispatch after retry (--retry-after)...: $whonix_build_dispatch_after_retry ${reset}"
      whonix_build_dispatch_after_retry_exit_code="0"
      eval $whonix_build_dispatch_after_retry || { whonix_build_dispatch_after_retry_exit_code="$?" ; true; };
      if [ "$whonix_build_dispatch_after_retry_exit_code" = "0" ]; then
         true "${cyan}${bold}INFO: dispatch after retry (--retry-after) exit code was 0, ok. ${reset}"
      else
         true "${red}${bold}INFO: dispatch after retry (--retry-after) non-zero exit code: $whonix_build_dispatch_after_retry_exit_code ${reset}"
      fi
   else
      true "INFO: Skipping whonix_build_dispatch_after_retry (--retry-after), because empty, ok."
   fi

   if [ "$retry_last_failed_bash_command_exit_code" = "0" ]; then
      return 0
   else
      errorhandlerprocessshared "NONE (called by $FUNCNAME)"
   fi
}

errorhandlerprocessshared() {
   last_script="$0"
   ## $1 contains trap signal type.
   trap_signal_type_last="$1"
   whonix_build_error_counter="$(( $whonix_build_error_counter + 1 ))"
   benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
   process_backtrace_function ## sets process_backtrace_result
   function_trace_function ## sets function_trace_result
   true "
############################################################
${red}${bold}ERROR in ${under}$last_script${eunder} detected!${reset}
(whonix_build_error_counter: $whonix_build_error_counter)
(benchmark: $benchmark_took_time)
${red}${bold}trap_signal_type_last${reset}: $trap_signal_type_last
${red}${bold}process_backtrace_result${reset}:
$process_backtrace_result
${red}${bold}function_trace_result${reset}:
$function_trace_result
${red}${bold}last_failed_bash_command${reset}: $last_failed_bash_command
${red}${bold}last_failed_exit_code${reset}: $last_failed_exit_code
${red}${bold}ERROR in ${under}$last_script${eunder} detected!${reset}
############################################################
"

   if [ "$trap_signal_type_last" = "ERR" ]; then
      true "INFO: Signal trap ERR, considering auto retry..."
      if [ ! "$whonix_build_auto_retry" = "0" ]; then
         if [ "$whonix_build_auto_retry_counter" = "" ]; then
            whonix_build_auto_retry_counter="1"
         fi
         [ -n "$whonix_build_auto_retry" ] || whonix_build_auto_retry="1"
         [ -n "$whonix_build_wait_auto_retry" ] || whonix_build_wait_auto_retry="5"
         if [ "$whonix_build_auto_retry_counter" -gt "$whonix_build_auto_retry" ]; then
            true "${cyan}${bold}INFO: Auto retried (--retry-max) already $whonix_build_auto_retry times. No more auto retry. ${reset}"
         else
            true "${cyan}${bold}INFO: Auto retry attempt number: $whonix_build_auto_retry_counter. Max retry attempts: $whonix_build_auto_retry (--retry-max). Auto retry... ${reset}"
            whonix_build_auto_retry_counter="$(( $whonix_build_auto_retry_counter + 1 ))"
            if [ ! "$whonix_build_wait_auto_retry" = "0" ]; then
               true "${cyan}${bold}INFO: Waiting (--retry-wait) $whonix_build_wait_auto_retry seconds before auto retry... ${reset}"
               sleep "$whonix_build_wait_auto_retry" &
            fi
            wait "$!"
            ignore_error="true"
            error_handler_do_retry="true"
            errorhandlerretry
            return 0
         fi
      else
         true "INFO: whonix_build_auto_retry set to $whonix_build_auto_retry (--retry-max). No auto retry."
      fi
   else
      true "INFO: No auto retry for non ERR signal type: $trap_signal_type_last"
   fi
   unset whonix_build_auto_retry_counter

   if [ ! "$trap_signal_type_last" = "ERR" ]; then
      ## TODO: Would otherwise "double" the error handlers.
      true "INFO: Aborting because of non ERR signal type: $trap_signal_type_last"
      return 0
   fi

   true "INFO: whonix_build_non_interactive: $whonix_build_non_interactive | CI: $CI"
   if [ "$whonix_build_non_interactive" = "true" ] || [ "$CI" = "true" ]; then
      true "INFO: using non-interactive error handler."
   else
      if [ -t "0" ]; then
         true "INFO: stdin connected to terminal, using interactive error handler."
         read -p "\
${red}${bold}ERROR in $0 detected!
Please have a look above (the block within ###...), note the command that failed, last_failed_exit_code and its output (further above).
- Please enter c and press enter to ignore the error and continue building. (Recommended against!)
- Please press r and enter to retry.
- Please press s and enter to open an chroot interactive shell.
- Please press enter to cleanup and exit. ${reset}" answer
      else
         true "INFO: stdin not connected to terminal, using non-interactive error handler."
      fi
   fi
   ignore_error=""
   error_handler_do_retry=""
   if [ "$answer" = "continue" ] || [ "$answer" = "c" ]; then
      ignore_error="true"
      interactive_chroot_shell="false"
   elif [ "$answer" = "s" ] || [ "$answer" = "shell" ]; then
      interactive_chroot_shell="true"
      errorhandlershell
   elif [ "$answer" = "r" ] || [ "$answer" = "retry" ]; then
      ignore_error="true"
      error_handler_do_retry="true"
      errorhandlerretry
   else
      ignore_error="false"
      interactive_chroot_shell="false"
   fi
}

if [ "$whonix_build_error_counter" = "" ]; then
   whonix_build_error_counter="0"
fi

errorhandlermaybeexit() {
   if [ "$error_handler_do_retry" = "true" ]; then
      true "INFO ($FUNCNAME): auto retry succeeded. Will not exit. Continue."
      return 0
   fi
   if [ "$ignore_error" = "true" ]; then
      abort_or_continue="Continue"
   else
      abort_or_continue="Aborted"
      ## Removing temporary debian testing (jessie) repository.
      rm --force "/etc/apt/sources.list.d/whonix_temp.list"
      ## Remove lockfile for whonixcheck.
      rm --force "/var/run/package_manager_lock"
      rm --force "$WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN"
      rm --force "$WHONIX_BUILD_APT_GET_GPGV_LOG"
   fi
   if [ "$ignore_error" = "true" ]; then
      true "INFO: whonix_build_non_interactive: $whonix_build_non_interactive | CI: $CI"
      if [ "$whonix_build_non_interactive" = "true" ] || [ "$CI" = "true" ]; then
         true "INFO: using non-interactive error handler."
      else
         true "${red}${bold}You have chosen to ignore this error. Your build may be unstable!
This is recommended against unless you know what you are doing. Do not report
bugs, that are a result of this! Please press enter to continue. ${reset}"
      fi
   else
      if [ "$trap_signal_type_last" = "INT" ]; then
         true "${red}${bold}INFO: Now exiting from $last_script (because error was detected, see above) with code 130 because signal sigint received..${reset}"
         exit 130 ## ctrl + c
      fi
      if [ "$trap_signal_type_last" = "TERM" ]; then
         true "${red}${bold}INFO: Now exiting from $last_script (because error was detected, see above) with code 143 because signal sigterm received.${reset}"
         exit 143
      fi
      true "${red}${bold}INFO: Now exiting from $last_script (because error was detected, see above) with code 1.${reset}"
      exit 1
   fi
}

errorhandlergeneral() {
   last_failed_exit_code="$?"
   last_failed_bash_command="$BASH_COMMAND"
   true "INFO: Middle of function $FUNCNAME of $0."
   ## $1 contains trap signal type.
   errorhandlerprocessshared "$1"
   errorhandlermaybeexit "$1"
   true "INFO: End of function $FUNCNAME of $0."
}

errorhandlerunchrootunpreventunmount() {
   last_failed_exit_code="$?"
   last_failed_bash_command="$BASH_COMMAND"
   ## $1 contains trap signal type.
   errorhandlerprocessshared "$1"
   if [ "$ignore_error" = "false" ]; then
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/remove-local-temp-apt-repo
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-raw
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-raw
   fi
   errorhandlermaybeexit "$1"
}

errorhandlerunmount() {
   last_failed_exit_code="$?"
   last_failed_bash_command="$BASH_COMMAND"
   ## $1 contains trap signal type.
   errorhandlerprocessshared "$1"
   if [ "$ignore_error" = "false" ]; then
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-raw
   fi
   errorhandlermaybeexit "$1"
}

## Thanks to:
## camh
## http://stackoverflow.com/a/2183063/2605155
errorhandlersetup() {
   local handler signal
   ## $1 contains the name of the error handler function.
   handler="$1" ; shift
   for signal ; do
       trap "$handler $signal" "$signal"
   done
}

errorhandlersetup "errorhandlergeneral" ERR INT TERM
set +e

export -f errorhandlershell
export -f errorhandlerretry
export -f errorhandlerprocessshared
export -f errorhandlermaybeexit
export -f errorhandlergeneral
export -f errorhandlerunchrootunpreventunmount
export -f errorhandlerunmount
export -f errorhandlersetup

errorhandlersetup "errorhandlergeneral" ERR INT TERM

bash -n "$BASH_SOURCE"

maybe_set_plus_x() {
   if [ "$MINUS_X_SET" = "1" ]; then
      set +x
   fi
}

## Thanks to  perreal for the convertsecs function.
## http://stackoverflow.com/a/12199798
convertsecs() {
   local h m s
   ((h="${1}/3600")) || true
   ((m="(${1}%3600)/60")) || true
   ((s="${1}%60")) || true
   printf "%02d:%02d:%02d\n" "$h" "$m" "$s" || true
}

export -f convertsecs

benchmark_time_start() {
   export benchmark_time_start="$(date +%s)" || true
}

benchmarktimeend() {
   benchmarktimeend="$(date +%s)" || true
   benchmark_took_seconds="$(( $benchmarktimeend - $benchmark_time_start ))" || true
   benchmark_took_time="$(convertsecs "$benchmark_took_seconds")" || true
}

export -f benchmarktimeend

## start benchmarktimeend
benchmark_time_start

root_check() {
   if [ "$(id -u)" != "0" ]; then
       echo "${red}${bold}ERROR: This must be run as root (sudo)!${reset}"
       exit 1
   else
       true "INFO: Script running as root."
   fi
}

lower_priorities() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   ## Lower IO priority.
   ionice -c3 -p$$

   ## Debugging.
   ionice >/dev/null

   ## Lower CPU priority.
   renice +19 -p $$ >/dev/null

   ## Debugging.
   nice >/dev/null

   export whonix_build_already_lowered_priorities="true"
}

if [ ! "$whonix_build_already_lowered_priorities" = "true" ]; then
   lower_priorities
fi

aptcachemaybeenable() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   if [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
      ## Someone updating Whonix-Gateway from source code.

      ## apt-cacher-ng will not work on Whonix-Gateway, because Whonix-Gateway
      ## does not have TransPort / DnsPort by default.
      echo 'INFO: Not setting http_proxy, because Whonix-Gateway detected, ok.'
      true
   else
      if [ "$http_proxy" = "" ]; then
         ## Enable apt-cacher-ng.
         echo 'INFO: Setting, export http_proxy="http://127.0.0.1:3142"'
         export http_proxy="http://127.0.0.1:3142"
      else
         echo "INFO: Leaving custom variable http_proxy $http_proxy as is."
      fi
   fi
}

export -f aptcachemaybeenable

apt_cache_disable() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   unset http_proxy
}

export -f apt_cache_disable

## {{ apt_get_gpgv

aptgetgpgvcreatetmp() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   ## workaround for
   ##     apt: Provide meaningful exit codes for gpg failures
   ##     https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745735
   ## W: A error occurred during the signature verification.
   ## To catch situations such as:
   ##     The repository is not updated and the previous index files will be used.
   ##     GPG error: http://deb.torproject.org stable Release: The following signatures were invalid: KEYEXPIRED 1409325681 KEYEXPIRED 1409325681 KEYEXPIRED 1409325681 KEYEXPIRED 1409325681
   ## That apt-repository would otherwise be silently ignored without error notification.

   if [ "$WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN" = "" ]; then
      error "Variable WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN is empty!"
   fi

   apt_get_gpgv_opts+=" -o Dir::Bin::gpg=$WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN "
   export apt_get_gpgv_opts

   rm --force "$WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN"
   touch "$WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN"

   if [ "$WHONIX_BUILD_APT_GET_GPGV_LOG" = "" ]; then
      error "Variable WHONIX_BUILD_APT_GET_GPGV_LOG is empty!"
   fi

   rm --force "$WHONIX_BUILD_APT_GET_GPGV_LOG"
   touch "$WHONIX_BUILD_APT_GET_GPGV_LOG"

   ## apt-get calls gpgv (this gpgv wrapper) with --status-fd 3. We redirect
   ## a copy of file descriptor 3 to the log.
   ## Variable WHONIX_BUILD_APT_GET_GPGV_LOG gets set and exported in help-steps/variables.
   echo '#!/bin/bash
gpgv ${1+"$@"} 3> >(tee --append "$WHONIX_BUILD_APT_GET_GPGV_LOG" >&3)
echo "-----" >> "$WHONIX_BUILD_APT_GET_GPGV_LOG"' | tee "$WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN" >/dev/null

   chmod +x "$WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN"
}

export -f aptgetgpgvcreatetmp

aptgetgpgvparsetmp() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   local gpg_log
   gpg_log="$(cat "$WHONIX_BUILD_APT_GET_GPGV_LOG")" || true
   if [ "$gpg_log" = "" ]; then
      true "${red}${bold}ERROR: variable gpg_log is empty!${reset}"
      error "See above!"
      return 0
   fi

   local aptgetgpgvgrepbadsigpattern
   aptgetgpgvgrepbadsigpattern="BADSIG\|EXPSIG\|EXPKEYSIG\|REVKEYSIG\|ERRSIG"

   if echo "$gpg_log" | grep -i -q "$aptgetgpgvgrepbadsigpattern" ; then
      true "${red}${bold}ERROR: ${red}${bold}apt-get: error occurred during the signature verification!${reset}"
      error "See above!"
      return 0
   fi
}

export -f aptgetgpgvparsetmp

aptgetgpgvdeletetmp() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM
   rm --force "$WHONIX_BUILD_APT_GET_GPGV_TEMP_BIN"
   rm --force "$WHONIX_BUILD_APT_GET_GPGV_LOG"
}

export -f aptgetgpgvdeletetmp

## Prevent the log from needlessly filling up.
rm --force "$WHONIX_BUILD_APT_GET_GPGV_LOG"

## }} apt_get_gpgv

#echo "${bold}Currently running script: $BASH_SOURCE${reset}"

set -x
