#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

error_handler_prevent_daemons_from_starting() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

prevent_daemons_from_starting() {
   trap "error_handler_prevent_daemons_from_starting" ERR INT TERM

   sync
   
   echo "chroot-img: copy policy-rc.d into /usr/sbin/ to prevent daemons from starting."
   
   cp --preserve --verbose "$WHONIX_SOURCE_FOLDER"/whonix_shared/usr/share/whonix/policy-rc.d "$CHROOT_FOLDER"/usr/sbin/policy-rc.d
   
   sync
}

true "${bold}INFO: Currently running script: $0${reset}"
prevent_daemons_from_starting

