#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

error_handler_prevent_daemons_from_starting() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $BASH_SOURCE: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR/pre"
source "$MYDIR/colors"
source "$MYDIR/variables"

root_check

prevent_daemons_from_starting() {
   trap "error_handler_prevent_daemons_from_starting" ERR INT TERM

   sync

   echo "$FUNCNAME: copy policy-rc.d into /usr/sbin/ to prevent daemons from starting."

   cp --preserve --verbose "$WHONIX_SOURCE_HELP_STEPS_FOLDER/policy-rc.d" "$CHROOT_FOLDER"/usr/sbin/policy-rc.d

   sync
}

true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
prevent_daemons_from_starting
benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE ${1+"$@"} | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
