#!/bin/bash

set -x

error_handler_prevent_daemons_from_starting() {
: echo "
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
"
exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/variables
source "$MYDIR"/pre

prevent_daemons_from_starting() {
   trap "error_handler_prevent_daemons_from_starting" ERR INT TERM

   sync
   
   echo "chroot-img: copy policy-rc.d into /usr/sbin/ to prevent daemons from starting."
   
   cp --preserve --verbose "$WHONIX_SOURCE_FOLDER"/whonix_shared/usr/share/whonix/policy-rc.d "$CHROOT_FOLDER"/usr/sbin/policy-rc.d
   
   sync
}

prevent_daemons_from_starting

