#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## Copyright (C) 2018 Algernon
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR/pre"
source "$MYDIR/colors"
source "$MYDIR/variables"

main() {
   root_check

   rm --force "$dist_sources_list_temp_initial_deb_sources_list"
   rm --force "$CHROOT_FOLDER/$dist_sources_list_temp_build_folder/build_sources.list"
   rm --force "$CHROOT_FOLDER/$dist_sources_list_temp_build_folder/qubes-builder.list"

   ## Exists only when using:
   ## build_remote_derivative_pkgs=true / --remote-derivative-packages true
   if [ ! "$apt_target_key_derivative" = "" ]; then
      rm --force "$CHROOT_FOLDER/$apt_target_key_derivative"
   fi

   ## "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER" gets unmounted in help-steps/unchroot script.
}

main "$@"
