#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

remove_local_temp_apt_repo() {
   trap "error_handler_general" ERR INT TERM   

   rm --force "$CHROOT_FOLDER"/etc/apt/trusted.gpg.d/whonix-temporary-local-apt-repository.gpg
   rm --force "$WHONIX_SOURCES_LIST_TEMP_BUILD_FULL"   
} 

remove_local_temp_apt_repo
