#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

dist_build_internal_run="true"

source pre
source colors
source variables

main() {
   true "gpg_bin: $gpg_bin"
   true "dist_local_signing_key_folder: $dist_local_signing_key_folder"
   true "dist_build_reprepro_signing_options: $dist_build_reprepro_signing_options"
   true "make_use_debsign: $make_use_debsign"

   ## Debugging. Was functional. No longer required.
   ## Omitted for simplicity since it requires local keystore folder '~/.gnupg'.
#    $gpg_bin \
#       --keyid-format 0xlong \
#       --fingerprint \
#       --list-secret-keys \
#       "$DEBEMAIL"
#    $gpg_bin \
#       --with-colons \
#       --keyid-format 0xlong \
#       --fingerprint \
#       --list-secret-keys \
#       "$DEBEMAIL"
#    $gpg_bin \
#       --with-colons \
#       --keyid-format 0xlong \
#       --fingerprint \
#       --list-secret-keys \
#       "$DEBEMAIL" \
#       | awk -F: '$1 == "pub" {print $2}'

   ## TODO: When extending 'buildconfig.d/30_signing_key.conf' variable 'derivative_signing_public_key_list' or
   ##       variable 'derivative_signing_key_fingerprint_group_list' we might need to stop at first success but make sure there
   ##       was at least one successful test.
   for key_index in "${!derivative_signing_public_key_list[@]}"; do
      readarray -t derivative_signing_key_fingerprint_list <<< "${derivative_signing_key_fingerprint_group_list[key_index]}"
      derivative_signing_public_key_item="${derivative_signing_public_key_list[key_index]}"

      for derivative_signing_key_fingerprint_item in "${derivative_signing_key_fingerprint_list[@]}"; do
         printf '%s\n' "test" | tee -- "$binary_build_folder_dist/test_sign_file" >/dev/null
         safe-rm --force -- "$binary_build_folder_dist/test_sign_file.asc"
         chown -- "$user_name:$user_name" "$binary_build_folder_dist/test_sign_file"

         test -r "${derivative_signing_public_key_item}"

         sq inspect -- "${derivative_signing_public_key_item}" &>/dev/null
         sq cert lint --cert-file "${derivative_signing_public_key_item}" &>/dev/null

         #$gpg_bin --keyid-format 0xlong --detach-sign --armor --yes --output "$binary_build_folder_dist/test_sign_file.asc" "$binary_build_folder_dist/test_sign_file"
         ## Not possible to use 'sqop' (stateless). derivative_signing_public_key_item is only the public key. Not the private key.
         #sqop sign "${derivative_signing_public_key_item}" < "$binary_build_folder_dist/test_sign_file" > "$binary_build_folder_dist/test_sign_file.asc"
         ## 'sqop' (stateless) cannot be used. 'sq' (keystore) must be used for 'split-gpg-2' compatibility.
         sq sign --signature-notation testvar testcontent --signer "$derivative_signing_key_fingerprint_item" --signature-file="$binary_build_folder_dist/test_sign_file.asc" -- "$binary_build_folder_dist/test_sign_file"

         ## Functional but omitted since it requires local keystore folder '~/.gnupg'.
         #$gpg_bin --keyid-format 0xlong --verify "$binary_build_folder_dist/test_sign_file.asc" "$binary_build_folder_dist/test_sign_file"
         sq verify --signer-file="${derivative_signing_public_key_item}" --signature-file="$binary_build_folder_dist/test_sign_file.asc" -- "$binary_build_folder_dist/test_sign_file"
         sqop verify "$binary_build_folder_dist/test_sign_file.asc" -- "${derivative_signing_public_key_item}" < "$binary_build_folder_dist/test_sign_file"

         ## gpgv:   error: Key resource "/home/user/.gnupg/trustedkeys.kbx" does not exist
         #$gpgv_bin "$binary_build_folder_dist/test_sign_file.asc" "$binary_build_folder_dist/test_sign_file"

         safe-rm -- "$binary_build_folder_dist/test_sign_file"
         safe-rm -- "$binary_build_folder_dist/test_sign_file.asc"
      done
   done

   ## TODO: stub
   test -d ~/.signify
}

main "$@"
