#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler_unchroot-img() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

do_unchroot() {
   trap "error_handler_unchroot-img" ERR INT TERM

   sync || true

   if [ "$BARE_METAL" = "1" ]; then
      true
   else
      #umount "$CHROOT_FOLDER"/dev/pts || true
      umount "$CHROOT_FOLDER"/dev || true
      umount "$CHROOT_FOLDER"/proc || true
      #umount "$CHROOT_FOLDER"/sys || true
   fi

   umount "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER" || true

   ## Also possibly unmount .backup file for bare metal builds.
   umount "$CHROOT_FOLDER"/etc/resolv.conf || true
   umount "$CHROOT_FOLDER"/etc/hosts || true
   umount "$CHROOT_FOLDER"/etc/hostname || true
   umount "$CHROOT_FOLDER"/etc/network/interfaces || true

   sync || true
}

true "${bold}INFO: Currently running script: $0 ${1+"$@"}${reset}"
do_unchroot
benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
