#!/bin/bash

set -x

if [ "$BARE_METAL" = "1" ]; then
   true "Skipping script, because BARE_METAL=1: $0"
   exit 0
else
   true "Currently running script: $0"
fi

error_handler_unchroot-img() {
: echo "
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
"
exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

do_unchroot() {
   trap "error_handler_unchroot-img" ERR INT TERM
   
   sync || true

   #umount "$CHROOT_FOLDER"/dev/pts || true
   umount "$CHROOT_FOLDER"/dev || true
   umount "$CHROOT_FOLDER"/proc || true
   #umount "$CHROOT_FOLDER"/sys || true
   umount "$CHROOT_FOLDER"/etc/resolv.conf || true
   umount "$WHONIX_INITIAL_DEB_INSTALL_FOLDER" || true
   
   rm --force "$CHROOT_FOLDER"/etc/apt/trusted.gpg.d/whonix-temporary-local-apt-repository.gpg

   sync || true
}

do_unchroot

