#!/bin/bash

set -x

if [ "$BARE_METAL" = "1" ]; then
   true "Skipping script, because BARE_METAL=1: $0"
   exit 0
else
   true "Currently running script: $0"
fi

error_handler_unmount-img-force() {
: echo "
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
#!!! ERROR in `caller` !!!#
"
exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/variables
source "$MYDIR"/pre

unmount_img_force() {
   trap "error_handler_unmount-img-force" ERR INT TERM

   sync || true
   
   "$MYDIR"/unchroot-img || true

   ## Will be called if there is an error.
   ## || true to avoid more errors and to ensure
   ## clean unmount.

   sync || true

   umount "$CHROOT_FOLDER" || true
   sync || true

   ## Delete temporary folder.
   ## It did not contain anything. It was only a mount point.
   rm -r "$CHROOT_FOLDER" || true
   sync || true
} 

unmount_img_force

