#!/bin/bash

set -x

if [ "$BARE_METAL" = "1" ]; then
   true "Skipping script, because BARE_METAL=1: $0"
   exit 0
else
   true "Currently running script: $0"
fi

error_handler_unmount-img() {
: echo "
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
"
exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

unmount_img() {
   trap "error_handler_unmount-img" ERR INT TERM

   sync
   
   umount "$CHROOT_FOLDER"
   sync
   
   kpartx -d "$WHONIX_BINARY"/"$VMNAME".img
   sync

   # Delete temporary folder.
   # It did not contain anything. It was only a mount point.
   rm -r "$CHROOT_FOLDER"
   sync
} 

unmount_img

