#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler_unmount-raw-force() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $BASH_SOURCE: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

unmount_raw_force() {
   trap "error_handler_unmount-raw-force" ERR INT TERM

   if [ "$mount_folder" = "" ]; then
      true
   else
      ## hack for help-steps/analyze-image
      CHROOT_FOLDER="$mount_folder"
   fi

   sync || true

   "$MYDIR"/unprevent-daemons-from-starting || true
   "$MYDIR"/unchroot-raw || true

   ## Will be called if there is an error.
   ## || true to avoid more errors and to ensure
   ## clean unmount.

   sync || true

   ## Sleep to work around some obscure bug.
   ## http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734794
   sleep 2 &
   wait "$!" || true
   sync || true

   umount "$CHROOT_FOLDER" || true
   sync || true

   ## Sleep to work around some obscure bug.
   ## http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734794
   sleep 2 &
   wait "$!" || true
   sync  || true

   ## Debugging.
   losetup --all || true
   sync || true

   kpartx -d -s -v "$binary_image_raw" || true
   sync || true

   ## Debugging.
   losetup --all || true
   sync || true

   ## Delete temporary folder.
   ## It did not contain anything. It was only a mount point.
   rm -r "$CHROOT_FOLDER" || true
   sync || true
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping script, because BARE_METAL=1: $BASH_SOURCE${reset}"
   exit 0
else
   true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
   unmount_raw_force
   benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}INFO: End of: $BASH_SOURCE ${1+"$@"} No error detected. (benchmark: $benchmark_took_time)${reset}"
fi
