#!/bin/bash

set -x

if [ "$BARE_METAL" = "1" ]; then
   true "Skipping script, because BARE_METAL=1: $0"
   exit 0
else
   true "Currently running script: $0"
fi

error_handler_unmount-vdi() {
: echo "
${red}${bold}ERROR${reset} in $(caller)
${red}${bold}ERROR${reset} in $(caller)
${red}${bold}ERROR${reset} in $(caller)
"
exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

unmount_vdi() {
   trap "error_handler_unmount-vdi" ERR INT TERM

   ## Called after copying into vm.
   ## Should not throw any errors.

   sync

   ## Shutdown the ndb.
   qemu-nbd -d /dev/nbd0
   sync

   ## In the end unmount.
   umount "$CHROOT_FOLDER"
   sync

   ## Delete temporary folder.
   ## It did not contain anything. It was only a mount point.
   rm -r "$CHROOT_FOLDER"
   sync
}

unmount_vdi

