#!/bin/bash

set -x

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/variables
source "$MYDIR"/pre

unprevent_daemons_from_starting() {
   sync || true

   rm --verbose --force "$CHROOT_FOLDER"/usr/sbin/policy-rc.d || true
   sync || true
}

unprevent_daemons_from_starting


