#!/bin/bash

# This file is part of Whonix
# Copyright (C) 2012, 2013 adrelanos <adrelanos at riseup dot net>
# See the file COPYING for copying conditions.

set -x

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre
source "$MYDIR"/variables

unprevent_daemons_from_starting() {
   sync || true

   rm --verbose --force "$CHROOT_FOLDER"/usr/sbin/policy-rc.d || true
   sync || true
}

true "${bold}INFO: Currently running script: $0${reset}"
unprevent_daemons_from_starting


