#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR/pre"
source "$MYDIR/colors"
source "$MYDIR/variables"

root_check

unprevent_daemons_from_starting() {
   sync || true

   rm --verbose --force "$CHROOT_FOLDER"/usr/sbin/policy-rc.d || true
   sync || true
}

true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
unprevent_daemons_from_starting
benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE ${1+"$@"} | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
