#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

error_handler_build-machine() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $BASH_SOURCE: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

source ./help-steps/pre
source ./help-steps/colors

root_check

export WHONIX_BUILD_ONE_SCRIPT_STARTED="1"

whonix_build_preparation() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   cd help-steps

   source parse-cmd
   whonix_build_one_parse_cmd ${1+"$@"}
   export whonix_build_one_parsed="1"

   source pre

   cd ..
}

whonix_build_machine() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   run-parts --verbose --test ./build-steps.d
   run-parts --verbose --exit-on-error ./build-steps.d
}

whonix_build_clean() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   local cleaned_up
   ## Fallback
   cleaned_up="false"

   if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
      cleaned_up="true"
      ./help-steps/delete-vbox-vm
   fi
   if [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
      cleaned_up="true"
      ./help-steps/delete-qcow
   fi
   if [ "$ANON_BUILD_INSTALL_TO_ROOT" = "1" ]; then
      error "${red}${bold}For --flavor root builds, --clean is not implemented.${reset}"
   fi

   if [ "$cleaned_up" = "false" ]; then
      parse_cmd_target_error
   fi
}

whonix_build_preparation ${1+"$@"}

if [ "$WHONIX_BUILD_CLEAN" = "1" ]; then
   whonix_build_clean
elif [ "$WHONIX_BUILD_BUILD" = "1" ]; then
   whonix_build_machine
else
   true "${bold}${red}ERROR $BASH_SOURCE: You must either use --build or --clean. ${reset}"
   exit 1
fi

benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}${green}INFO: End of: $BASH_SOURCE ${1+"$@"} | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
