#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

MSG="
Tunnel Tor through proxy
(user -> proxy -> Tor)

(You can scroll down using the arrow key.)

On Whonix-Gateway:

   sudo nano /etc/tor/torrc

Or, if you are using a graphical Whonix-Gateway.

    Start Menu -> Applications -> /etc/tor/torrc

Depending on your proxy configuration, add the settings you'll need to your /etc/tor/torrc. For more information on these settings, have a look in the Tor manual and read the FAQ.

HTTPProxy host[:port]
HTTPProxyAuthenticator username:password
HTTPSProxy host[:port]
HTTPSProxyAuthenticator username:password

Socks4Proxy host[:port]

Socks5Proxy host[:port]
Socks5ProxyUsername username
Socks5ProxyPassword password

FascistFirewall 0|1

ReachableAddresses ADDR[/MASK][:PORT]...
ReachableDirAddresses ADDR[/MASK][:PORT]...
ReachableORAddresses ADDR[/MASK][:PORT]...

FAQ:
https://trac.torproject.org/projects/tor/wiki/doc/TorFAQ#MyInternetconnectionrequiresanHTTPorSOCKSproxy.

Tor Manual:
https://www.torproject.org/docs/tor-manual.html.en

Whonix documentation online:
(could me more up to date)
https://www.whonix.org/wiki/Tunnel_Tor_through_proxy_or_VPN_or_SSH
"

TITLE="whonixsetup - I need a proxy to access the Internet."

dialog --title "$TITLE" --msgbox "$MSG" 640 480

exit 0
