#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   local MSG="\
###########################################################
## Something went wrong. Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
###########################################################\
"
   echo "$MSG"
   exit 1
}

trap "error_handler" ERR

## root check
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
fi

stop_tor() {
      exit_code="0"
      service tor status || { exit_code="$?"; true; };
      sync
      sleep 1

      if [ "$exit_code" = "0" ]; then
         dialog --title "whonixsetup - Info" --msgbox 'The Tor process is still running. Stopping it now...' 640 480

         exit_code="0"
         service tor stop || { exit_code="$?"; true; };
         sync
         sleep 1

         dialog --title "whonixsetup - Info" --msgbox 'Stopped the Tor process.' 640 480
      else
         dialog --title "whonixsetup - Info" --msgbox 'The Tor process was already stopped.' 640 480
      fi
}

MSG="
Do you want to disable Tor networking?
"

TITLE="whonixsetup - Disable Tor Networking"

exit_code="0"
dialog --title "$TITLE" --yesno "$MSG" 640 480 || { exit_code="$?"; true; };

if [ ! "$exit_code" = "0" ]; then
   ## Back to main menu.
   whonixsetup
   exit 0
fi

## Check if Tor networking was already disabled.
## This is to prevent getting a /etc/tor/torrc
## with ####DisableNetwork 0 if the user chooses
## this option multiple times.
while read LINE; do
   if [ "$LINE" = "#DisableNetwork 0" ]; then
      dialog --title "Success!" --msgbox '"DisableNetwork 0" was already commented in /etc/tor/torrc

Tor networking should already be disabled, and there is no need to disable it multiple times.
' 640 480

      dialog --title "whonixsetup - Info" --msgbox 'Checking if the Tor process is still running and stopping it if necessary...' 640 480

      stop_tor
      true "INFO: Ok, exit 1, so whonixsetup will end."
      ## Signal for whonixsetup to break the while loop.
      exit 1
   fi
done < "/etc/tor/torrc"

dialog --title "Info" --msgbox 'Trying to disable Tor networking...

Note: This will comment out "DisableNetwork 0" in /etc/tor/torrc
' 640 480

## Comment out DisableNetwork 0 in /etc/tor/torrc.
exit_code="0"
ed -s /etc/tor/torrc <<< $',s/DisableNetwork 0/#DisableNetwork 0/g\nw' || { exit_code="$?"; true; };

## Ensure changes get written to the disk right now.
sync

if [ "$exit_code" = "0" ]; then
   stop_tor
   true "INFO: Ok, exit 1, so whonixsetup will end."
   ## Signal for whonixsetup to break the while loop.
   exit 1

   dialog --title "whonixsetup - Success!" --msgbox 'Tor networking has been disabled.

Note: whonixsetup disables Tor networking by commenting "DisableNetwork 0" in /etc/tor/torrc
' 640 480
else
   dialog --title "whonixsetup - ERROR!" --msgbox 'Tor networking could not be disabled. Please report this bug!

Note: whonixsetup tried to disable Tor networking by commenting "DisableNetwork 0" in /etc/tor/torrc but was unable to.
' 640 480

   dialog --title "whonixsetup - WARNING" --msgbox 'Trying to stop the Tor process...

Warning: Since Tor networking could not be disabled in /etc/tor/torrc, Tor will reconnect the next time you reboot or restart Tor. You can try to manually comment "DisableNetwork 0" in /etc/tor/torrc and run "sudo service tor stop" to ensure that Tor will not start.
' 640 480

   stop_tor
   true "INFO: Ok, exit 1, so whonixsetup will end."
   ## Signal for whonixsetup to break the while loop.
   exit 1
fi
