#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

MSG="
You can always enter whonixsetup again, by starting: sudo whonixsetup
"

TITLE="whonixsetup - Cancel."

dialog --title "$TITLE" --msgbox "$MSG" 640 480

true "INFO: Ok, exit 1, so whonixsetup will end."
## Signal for whonixsetup to break the while loop.
exit 1
