#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

MSG='
(You can scroll down using the arrow key).

You must manually edit /etc/tor/torrc for Tor to navigate through your firewall or proxy.

Press Enter to close this message, then select Exit. After you have finished editing, run whonixsetup again.

You can open /etc/tor/torrc in the terminal:
    sudo nano /etc/tor/torrc

Or on the desktop:
    Start Menu -> Applications -> /etc/tor/torrc
'

TITLE="whonixsetup - I use proxy or firewall settings to connect to the internet."

dialog --title "$TITLE" --msgbox "$MSG" 640 480

exit 0
