## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Variables for key handling and verification

## 'sq-git'
## https://sequoia-pgp.gitlab.io/sequoia-git/
## https://sequoia-pgp.gitlab.io/sequoia-git/user-manual/
## https://sequoia-pgp.gitlab.io/sequoia-git/man/sq-git.1.html
## https://fosdem.org/2026/schedule/event/KFSUCW-sequoia-git/

## 'sq-git log' root of trust ('--trust-root')
sq_git_trust_root="HEAD"

## path to 'sq-git log' policy file ('--policy-file')
## https://sequoia-pgp.gitlab.io/sequoia-git/specification/#name-policy
sq_git_policy_file=./openpgp-policy.toml
