#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Variables for key handling and verification

## 'sq-git'
## https://sequoia-pgp.gitlab.io/sequoia-git/
## https://sequoia-pgp.gitlab.io/sequoia-git/user-manual/
## https://sequoia-pgp.gitlab.io/sequoia-git/man/sq-git.1.html
## https://fosdem.org/2026/schedule/event/KFSUCW-sequoia-git/

## 'sq-git log' root of trust ('--trust-root')
## Default to:
## - for user custom builds: HEAD
## - redistributable builds: See 'help-steps/variables'.
##   (when using setting variable 'dist_build_redistributable=true')
#sq_git_trust_root="HEAD"

## path to 'sq-git log' policy file ('--policy-file')
## https://sequoia-pgp.gitlab.io/sequoia-git/specification/#name-policy
## Defaults to: ${source_code_folder_dist}/openpgp-policy.toml
#sq_git_policy_file=~/buildconfig.d/openpgp-policy.toml

## Future development idea:
## Different 'openpgp-policy.toml' default paths.
##
##   Priority  | Location
## 1 (lowest)  | ${source_code_folder_dist}/openpgp-policy.toml
## 2 (higher)  | /etc/buildconfig.d/openpgp-policy.toml
## 3 (highest) | ~/buildconfig.d/openpgp-policy.toml

#set -x
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
