#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Variables for key handling and verification

## 'sq-git'
## https://sequoia-pgp.gitlab.io/sequoia-git/
## https://sequoia-pgp.gitlab.io/sequoia-git/user-manual/
## https://sequoia-pgp.gitlab.io/sequoia-git/man/sq-git.1.html
## https://fosdem.org/2026/schedule/event/KFSUCW-sequoia-git/

## 'sq-git log' root of trust ('--trust-root')
##
## One option might be
## using the git commit ID where derivative-maker 'openpgp-policy.toml' file
## was first introduced.
## sq_git_trust_root="93d79d25ad28539a0fea503fcf9ea9f12b683d72"
##
## 'HEAD' might be non-ideal? It's functional with git shallow clone.
[[ -v sq_git_trust_root ]] || sq_git_trust_root="HEAD"

## path to 'sq-git log' policy file ('--policy-file')
## https://sequoia-pgp.gitlab.io/sequoia-git/specification/#name-policy
[[ -v sq_git_policy_file ]] || sq_git_policy_file="${source_code_folder_dist}/openpgp-policy.toml"

## Future development idea:
## Different 'openpgp-policy.toml' default paths.
##
##   Priority  | Location
## 1 (lowest)  | ${source_code_folder_dist}/openpgp-policy.toml
## 2 (higher)  | /etc/buildconfig.d/openpgp-policy.toml
## 3 (highest) | ~/buildconfig.d/openpgp-policy.toml
