#!/bin/bash

## crontab by Whonix

## REVIEW!

set -x

## Adds whonixcheck script. Also note the following link when
## you are about to add graphical applications to cron.
## http://promberger.info/linux/2009/01/02/running-x-apps-like-zenity-from-crontab-solving-cannot-open-display-problem/

## Add crontab.
## cron.daily will run as root, but the script will be executed as user.
## Otherwise wget would run as root.

## Debugging:
## echo "whonixcheck cron.daily: date: `date`" >> /home/user/delayed

sudo -u user /usr/local/bin/whonixcheck_daily

## End of Whonix /etc/cron.daily/whonixcheck.
