#!/bin/bash

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source variables
source pre

error_handler_interactive-chroot-img-shell() {
   trap "error_handler_interactive-img" ERR INT TERM

   echo "Exited (1) interactive shell."
   sync
}

error_handler_interactive-chroot-img() {
   echo "
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
"

   ./unchroot-img
   ./unmount-img
   
   echo "
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
#!!! ERROR in $(caller) !!!#
"

   exit 1
}

interactive-chroot-img() {
   trap "error_handler_interactive-chroot-img" ERR INT TERM

   ./mount-img
   ./chroot-img

   sync

   ## Just for testing.
   chroot "$CHROOT_FOLDER" dir
   chroot "$CHROOT_FOLDER" ls -l "/usr/bin/"
   chroot "$CHROOT_FOLDER" mount
   chroot "$CHROOT_FOLDER" update-grub -v
   sync

   ## Info.
   echo "Entering interactive shell..."
   echo "Recommendation: check /home/user if you are really inside the image and not on your host system."
   echo "When you are done, do not forget to leave the shell using: exit 0"

   ## Run interactive shell.
   trap "error_handler_interactive-chroot-img-shell" ERR INT TERM
   chroot "$CHROOT_FOLDER" "/bin/bash"

   echo "Exited (0) interactive shell."

   ./unchroot-img
   ./unmount-img

   sync
}

interactive-chroot-img

