#!/bin/bash

set -x

error_handler() {
   echo "
#############################################################
## postinst script: ERROR detected. Please report this bug! #
#############################################################
"

   exit 1
} 

trap "error_handler" ERR

own_filename="$(basename $0)"
case $skip_scripts in
   *$own_filename*) true "INFO: Skipping $own_filename, because skip_scripts includes it."
                    exit 0
                    ;;
esac

trap "" ERR
id "clearnet"
if [ ! "$?" = 0 ]; then
   trap "error_handler" ERR
   echo 'INFO: Creating user "clearnet"...'
   ## setting password of user clearnet to changeme
   ##
   ## How this password was created:
   ## sudo apt-get install whois
   ## mkpasswd
   ## changeme
   ## Resulted in: aTayYxVyw5kDo
   useradd --create-home --password aTayYxVyw5kDo --shell /bin/bash clearnet
else
   trap "error_handler" ERR
   echo 'INFO: Not creating user "clearnet", because it already exists.'
fi

trap "error_handler" ERR

chown --recursive clearnet:clearnet /home/clearnet

